### ISSUE TITLE
Reparse opened files even with trackDependency=0

### ISSUE THREAD

**Issue by sergei-dyshel** [MaskRay/ccls#105]
I'm using `ccls.index.trackDependency=0` which is very handy as it prevents entire db reindex on changing some central header file. However this does have some negative side-effect: if there is some diagnostic in source file (say, source/header function signature mismatch) which is fixed by changing the header file, it won't be updated until I change the source as well or trigger its reparse in some other way.

I think it makes sense to introduce some new value for `trackDependency' which would mean "reparse any dependent **open** files". For the sake of diagnostics alone we may reparse open but hidden editors only when they become visible but I'm not sure this is possible with LSP (differentiation between hidden and visible editors).

**Comment by MaskRay** [comment]
indexer, diag (diagnostics), comp (completion) are different threads. `DiagnosticMain` is not affected by `ccls.index.*`. It builds preamble (longest preprocessor token prefix (`#include` `#define` ...)) when the document is saved. Consider this scenario:

* `a.cc` has diagnostics because of `a.h`
* `a.h` is fixed
* `a.cc`'s preamble is not rebuilt until `a.cc` is saved

In your case, you just need to save `a.cc` (update its modification time).

**Comment by sergei-dyshel** [comment]
I just want the process to be automatic, i.e. whenever header file is saved, rebuild preamble for dependent file (only those open in the editor). Otherwise I have to remember to manually trigger saving source file. 

Don't you think such functionality will be useful?

**Comment by MaskRay** [comment]
If the scenario I described the preamble is stale (`clang::PrecompiledPreamble::CanReuse` should return false)

I did not say I do not want precise diagnostics but I need to balance various trade-offs, find an appropriate point to rebuild preamble, and think of an appropriate initialization option.

You may use
`CINDEXTEST_EDITING=1 c-index-test -code-completion-at=a.cc:10:13 a.cc`
to have a feeling what code completion feels like w/ w/o preamble.

`CINDEXTEST_EDITING=1` repeats completion 5 times. It is significantly faster than 5 `c-index-test` invocations.

**Comment by MaskRay** [comment]
Fixed in HEAD.

    DiagnosticMain: trigger building stale preamble
    
    WorkingFiles::files : vector -> unordered_map

We need a `PreambleCallbacks` to collect included files and their timestamps. In `DiagnosticMain`, we check if the preamble is stale, if true, cancel the diagnostic task and send a preamble building task to the "comp-preload" thread.

**Comment by sergei-dyshel** [comment]
Thanks! If I understand correctly, diagnostics now will be automatically updated on dependency changes too?

**Comment by MaskRay** [comment]
> diagnostics now will be automatically updated on dependency changes too?

Yes. The dependency information is collected from a previous preamble (`using IncludeStructure = std::map<std::string, int64_t>;`).
