### ISSUE TITLE
Enum member collapsing in documentSymbol

### ISSUE THREAD

**Issue by isundaylee** [MaskRay/ccls#108]
With the following code

```cpp
enum class Test {
   A, B, C
};
```

`documentSymbol` method returns 4 entries for `Test`, `A`, `B`, and `C`. I think it makes more sense to return a single entry for `Test` with `children` being entries for `A`, `B`, and `C`. Just wondering if this is a known issue? 

Thanks! :)

**Comment by isundaylee** [comment]
I did a little digging, and it seems like in `indexer.cc`, where the enum constants are indexed, `getDeclContext()` returns a `clang::TranslationUnitDecl` as these constants' declaration context. Any idea why this is the case? Shouldn't a `clang::EnumDecl` be returned as their declaration context instead?

**Comment by isundaylee** [comment]
So the `getRedeclContext()` issue only applies to `enum`. For `enum class`, the only change needed to get the enum constants collapsed under the enum is (https://github.com/isundaylee/ccls/commit/ef33222c091631dee94e7a7f5a16a285bbdf44ff). But obviously I don't know the project enough to know if that change might break something else haha.

**Comment by MaskRay** [comment]
Pushed a commit to fix scoped enumeration... I also want `$ccls/member` on unscoped enumeration `enum E { A };` to list `A` but there can be complexity when it is a nested type in a template.

**Comment by isundaylee** [comment]
Yeah that makes sense. Thanks for the fix! Can confirm here that scoped enums now work as expected.
