### ISSUE TITLE
Support for compile_flags.txt?

### ISSUE THREAD

**Issue by oblitum** [MaskRay/ccls#110]
I've just learned of the project and couldn't find whether it supports `compile_flags.txt` [like `clangd` does](https://clang.llvm.org/docs/JSONCompilationDatabase.html#alternatives).

**Comment by MaskRay** [comment]
ccls does not read `compile_flags.txt` (`clang::tooling::FixedCompilationDatabase`).

It reads `.ccls` or `compile_commands.json` https://github.com/MaskRay/ccls/wiki/Getting-started#project-setup

**Comment by oblitum** [comment]
I know, I just asked out of conformance with clang tools. I'll close it as it seems there's no interest(?).

**Comment by MaskRay** [comment]
It is more than "there's no interest" :)

`compile_flags.txt` was added last November (D39799). It uses `clang-tool` as the compiler driver. I feel it might be better to give the user more control. You can change the compiler driver to `clang-cl` or `aarch64-linux-gnu-clang++` `clang++`, and see what happens.

`%cpp ` `%c ` are useful for language specific options.

```cpp
FixedCompilationDatabase::
FixedCompilationDatabase(Twine Directory, ArrayRef<std::string> CommandLine) {
  std::vector<std::string> ToolCommandLine(1, "clang-tool");
  ToolCommandLine.insert(ToolCommandLine.end(),
                         CommandLine.begin(), CommandLine.end());
  CompileCommands.emplace_back(Directory, StringRef(),
                               std::move(ToolCommandLine),
                               StringRef());
}
```

**Comment by oblitum** [comment]
@MaskRay can you help me on how should I put this `compile_flags.txt` in `.ccls` format?

```
-Wall
-Wextra
-pedantic
-std=c++17
-stdlib=libc++
-isystem /usr/local/include
-isystem /usr/lib/clang/7.0.0/include
-isystem /usr/include
-isystem /usr/include/c++/v1
```

I've always used this with YouCompleteMe and clangd, they work fine, but it seems I'm having trouble with the `-isystem` flags with `ccls` due to whitespace. Note that I've always had to be explicit about system include paths because libclang in general don't do (at least didn't) it by default.

**Comment by MaskRay** [comment]
```
-isystem
/usr/local/include
```

**Comment by oblitum** [comment]
@MaskRay I have indeed tried that before too, but then indexing didn't work quite right, I've checked the log and it was indexing much less files in `/usr` than if I use `-I/usr/local/include`. Due to that, for example, I was about to complete `cout`  from `std::` but `std::cout.` came empty, while it's not when I use `-I/usr/local/include`.

**Comment by MaskRay** [comment]
Sorry I didn't read your comment carefully. The `.ccls` format:

```
clang++
-Wall
-Wextra
-pedantic
-std=c++17
-stdlib=libc++
-isystem/usr/local/include
-isystem/usr/lib/clang/7.0.0/include
-isystem/usr/include
-isystem/usr/include/c++/v1
```

**Comment by oblitum** [comment]
is it right without the `%` before `clang++`? Will try it here.

**Comment by MaskRay** [comment]
Read wiki. I use `%clang` to mean either `clang` or `clang++`

**Comment by oblitum** [comment]
> But I'd say `/usr/lib/clang/7.0.0/include` `/usr/include/c++/v1` `/usr/lib/clang/7.0.0/include` are really redundant.

I do that because I'm used to specify include locations when using libclang tools, the reason is here: https://github.com/Valloric/YouCompleteMe/issues/303#issuecomment-17702994. Libclang may have changed that behavior already, I don't know, and ccls may act completely different than that?

I think I will just remove them anyway.

But still, I found it strange that with these flags, completion and indexing doesn't work right, try completing `std::cout.<something>`, it doesn't work, but `std::<something>` does.

**Comment by oblitum** [comment]
Thanks for the help. Sadly, no vim or neovim general LSP implementation is doing signatureHelp right. There's one libclang plugin that [heard my suggestion and implemented it OK](https://github.com/hukeyue/vim-clangd/issues/13):

![](https://camo.githubusercontent.com/3c3b8a37455fff555353e0921c11c2e88b79d9db/687474703a2f2f692e696d6775722e636f6d2f79536b4135724a2e676966)

Sadly it's clang specific, and currently I can't even build it.

**Comment by MaskRay** [comment]
I am unclear about the history as I started hacking clang last December.

ccls invokes `clang::createInvocationFromCommandLine`
cquery calls some libclang API like `clang_indexSourceFileFullArgv`
`ycmd/cpp/ycm/ClangCompleter/TranslationUnit.cpp` invokes `clang_codeCompleteAt` which calls `clang::ASTUnit::CodeComplete` with some pre-created `CompilerInvocation` created by `clang::createInvocationFromCommandLine`

`clang::createInvocationFromCommandLine` runs clangDriver to get system search directories. `-isystem/usr/include` is mostly redundant (it still has some effect: it changes the search order as you can bserve in the output of `clang -E -v -xc++ /dev/null`, but `-externc-isystem/usr/include` should probably be a total redundancy)

**Comment by oblitum** [comment]
This should have changed at some point I think. I'm an oldie on clang but has been some time I don't touch the codebase to know when that changed. I've implemented [this](http://nosubstance.me/articles/2015-01-29-better-completion-for-cpp/) and committed to clang, which today is used by `signatureHelp` implementers, at least the ones that do it.

**Comment by MaskRay** [comment]
Thank you for rC26670 and its friends!

So it seems you may have landed it without a review? I think no one is focusing on libclang now and lots of contribution may go through a really long process...

My clang journey started with D41575, when I was still hacking on cquery.

**Comment by oblitum** [comment]
No no, there was a review for sure: https://reviews.llvm.org/D6880.

**Comment by oblitum** [comment]
I know, there's much stuff in any codebase that's not pretty, and anything clang is no exception :)

**Comment by MaskRay** [comment]
For `clang::CodeCompleteConsumer::ProcessOverloadCandidates`, I forgot to mention that the author of irony-mode contributed cquery 391 

The implementation is a bit different now in ccls and the optional argument part is split into a separate initialization option:

`completion.detailedLabel`
`completion.duplicateOptional`
