### ISSUE TITLE
ccls finds headers but not symbols in the headers

### ISSUE THREAD

**Issue by adzenith** [MaskRay/ccls#120]
So far ccls seems great - unlike cquery it doesn't cause my editor to hang on startup, it seems like it has a lot of cool features, and I'm excited to work with it.

I am seeing a problem, though. ccls appears to have found all of my headers - none of them have underlines showing that they can't be found, and in the log I see that all the search paths seems to be correct. However, any symbol that is not declared in the current file can't be found. This seems to happen for all files in my project, and it doesn't matter if the header is a project header or a system header.
![example](https://user-images.githubusercontent.com/614934/48420052-7d7ec180-e727-11e8-94db-daf914f3b644.png)

I've looked through the wiki and I'm not sure what my problem could be. I'm using version 1111.
Thanks!

**Comment by MaskRay** [comment]
vector shouls be found in system C++ search paths. Can you check out wiki/FAQ and see if -resource-dir= is correct?

**Comment by adzenith** [comment]
I changed my cache format to JSON and took a look.
```
$ /usr/bin/clang++ -print-resource-dir
/usr/lib/llvm-6.0/lib/clang/6.0.1
$ ls $(/usr/bin/clang++ -print-resource-dir)/include/stddef.h
/usr/lib/llvm-6.0/lib/clang/6.0.1/include/stddef.h
$ grep resource foo@bar@file.json
$
```
It looks like `-resource-dir` isn't set at all in the json file.

Regardless, ccls isn't complaining about not finding the header - it's complaining about not finding the symbol. Is that a notable distinction in this case?

**Comment by MaskRay** [comment]
Sorry that piece of information is outdated. When compiling ccls, `-DDEFAULT_RESOURCE_DIRECTORY=/usr/lib/llvm-6.0/lib/clang/6.0.1` is passed by the cmake build system. When indexing a project,

```
// clang_tu.cc
std::unique_ptr<CompilerInvocation>
BuildCompilerInvocation(std::vector<const char *> args,
                        IntrusiveRefCntPtr<llvm::vfs::FileSystem> VFS) {
  std::string save = "-resource-dir=" + g_config->clang.resourceDir; //////// DDEFAULT_RESOURCE_DIRECTORY
  args.push_back(save.c_str());
  IntrusiveRefCntPtr<DiagnosticsEngine> Diags(
      CompilerInstance::createDiagnostics(new DiagnosticOptions));
  std::unique_ptr<CompilerInvocation> CI =
      createInvocationFromCommandLine(args, Diags, VFS);
```

What `createInvocationFromCommandLine` does should be very similar to `c-index-test -index-file a.cc [options] -resource-dir=/usr/lib/llvm-6.0/lib/clang/6.0.1`

**Comment by adzenith** [comment]
ccls.log says at the top:
`Using -resource-dir=/ccls/Release/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04/lib/clang/7.0.0`
which, if true, means it's using a different version than what I'm expecting. Perhaps I will try again to compile with system Clang.

**Comment by adzenith** [comment]
I fixed this by rebuilding ccls against my system Clang. Thanks for the help!
Maybe could ccls make it more obvious when i can't find the resource dir? I saw the mention of the resource dir in the FAQ, but I didn't think that was my problem because it looked like ccls could find the headers correctly.

**Comment by MaskRay** [comment]
The macro `DEFAULT_RESOURCE_DIRECTORY` is computed from `Clang_RESOURCE_DIR` where the latter is the output of `clang -print-resource-dir` (`cmake/FindClang.cmake`). Do you know why it had the weird value `/ccls/Release/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04/lib/clang/7.0.0` ?

I have no idea how to make it (when `-resource-dir` is incorrect) obvious and I tend to avoid such dirty check. Since there is a command option option `-index`. The wiki can be probably improved to teach users to check `ccls -index [some simple file with #include stddef.h]`

**Comment by adzenith** [comment]
That value was correct based on how I built it - I built it in a Docker container so `ccls` was checked out in `/`, and I just let it download Clang on its own. I just didn't think I needed the repo anymore after I built it - but it turns out `ccls` still looks for Clang there.
