### ISSUE TITLE
Add status tables to relevant docs

### ISSUE THREAD

**Issue by jwatt** [MaskRay/ccls#123]
Something like the [clangd status section](https://clang.llvm.org/extra/clangd.html#current-status) would be very helpful. Not only for the status of ccls, but also a status table for each editor stating which features UI has been implemented for.

Background: I would like to know whether call hierarchy UI has been implemented for vim or vscode. The project I'm interested in potentially using ccls for is very large, and having to set up ccls and test it in each editor just to figure out if a feature is supported is a pain.

**Comment by MaskRay** [comment]
I have my own idea to implement this: https://github.com/MaskRay/ccls/wiki/Status-table

**Comment by jwatt** [comment]
Thank you!

**Comment by juergenhoetzel** [comment]
> I have my own idea to implement this: https://github.com/MaskRay/ccls/wiki/Client-feature-table

It seems that this link is broken
