### ISSUE TITLE
Completion inserts placeholders as text for function arguments

### ISSUE THREAD

**Issue by iensen** [MaskRay/ccls#124]
When I try to use auto-completion on a function call, say f(a), I see the following text inserted:
f(${1:int a)$0.

Is there any way to disable the completion of arguments, or make it more intelligent somehow?
Or maybe there is a simple way to get emacs navigate through the placeholders?

Emacs version is 25.1.1, ccls version is the one from this commit:
commit ee39ada4f01ccc8839b02499527770ec71cc1d8e
Date:   Sun Oct 28 21:39:17 2018 -0700

Config for company:
```
(use-package company
   :diminish ""
       :bind (:map company-active-map
                   ("C-j" . company-select-next)
                   ("<backtab>" . company-complete-common-or-cycle)
                   ("C-k" . company-select-previous))
       :custom
       (company-idle-delay 0.3)
       :config
       (global-company-mode))

(push 'company-lsp company-backends)

(setq company-transformers nil company-lsp-async t company-lsp-cache-candidates nil)
 (setq ccls-extra-init-params '(:completion (:detailedLabel t)))
```
I will be glad to provide more info if needed.

**Comment by BooAA** [comment]
Do you have yasnippet installed?  This is a snippet feature provided by language server. Try enable yas-minor-mode for C/C++-mode and the result should be more intelligent.

**Comment by MaskRay** [comment]
Thanks to BooAA for the help!

See https://github.com/MaskRay/emacs-ccls/issues/15

If you don't like snippets: https://github.com/MaskRay/ccls/wiki/Initialization-options#clientsnippetsupport

`:detailedLabel t` is the default: https://github.com/MaskRay/ccls/wiki/Initialization-options#completiondetailedlabel

**Comment by iensen** [comment]
Thank you very much! Adding yasnippet helped, it now works very well, just as I expected.
