### ISSUE TITLE
Can't complete any C++ system headers and only some C system headers but jumping to their definition works

### ISSUE THREAD

**Issue by bfrg** [MaskRay/ccls#125]
I'm on Gentoo Linux using `ccls` through [vim-lsp](https://github.com/prabirshrestha/vim-lsp). Further system info see below.

### Issues

`ccls` doesn't find any C++ system headers and only a few C system headers:
![screenshot-2018-11-19_205850](https://user-images.githubusercontent.com/6266600/48736981-17c19680-ec4d-11e8-8425-840128d2b346.png)

Completion of `std::vector` doesn't work:
![screenshot-2018-11-19_210105](https://user-images.githubusercontent.com/6266600/48736234-011a4000-ec4b-11e8-82cc-7acabf528fa8.png)

But completing a `std::vector` method or nested type works:
![screenshot-2018-11-19_223733](https://user-images.githubusercontent.com/6266600/48736639-1e9bd980-ec4c-11e8-9d50-679ba2867d44.png)

Completing the methods of a `std::vector` instance works, too:
![screenshot-2018-11-19_210007](https://user-images.githubusercontent.com/6266600/48736152-c3b5b280-ec4a-11e8-817f-15616f5485b5.png)

Jumping to the definition of `std::vector` (or any of its methods) works, too:
![screenshot-2018-11-19_210335](https://user-images.githubusercontent.com/6266600/48736276-2149ff00-ec4b-11e8-9b09-009911f66c48.png)

### System info

This is how I built `ccls`:
```bash
$ mkdir build && cd build
$ cmake .. -DSYSTEM_CLANG=on -DCMAKE_PREFIX_PATH=/usr/lib/llvm/7 -DLLVM_ENABLE_RTTI=on
$ make -j4
```
My system include directories (output of `clang -E -v -xc++ /dev/null`):
```
/usr/include/c++/v1
/usr/lib64/llvm/7/bin/../../../../lib/clang/7.0.0/include
/usr/include
```
```
$ clang++ -print-resource-dir
/usr/lib64/llvm/7/bin/../../../../lib/clang/7.0.0
```

This issue is similar to #37.

**Comment by MaskRay** [comment]
From your `clang -E -v -xc++ /dev/null` output, `/usr/include/c++/v1` indicates your clang uses libc++ for its `-stdlib=platform`. Are you using [default-libcxx](https://packages.gentoo.org/useflags/default-libcxx)?

Can you try this `.ccls` configuration:

```
clang++
-stdlib=libstdc++
```

**Comment by bfrg** [comment]
Yes, I do have the `default-libcxx` USE flag enabled and `ccls` jumps to the correct `std::vector` definition (see last screenshot).

### libstdc++
I've added the `-stdlib=libstdc++` option and completion works better now, but it still won't list all system include headers.

### libc++
Running `c-index-test` (cursor at `#include <s▎`, see first screenshot):
```
c-index-test -code-completion-at=main.cpp:3:12 -stdlib=libc++ main.cpp -ccc-install-dir /usr/lib64/llvm/7/bin -resource-dir /usr/lib/clang/7.0.0
```
outputs:
```
Completion contexts:
Unknown
Any type
Any value
Objective-C object value
Objective-C selector value
C++ class type value
Dot member access
Arrow member access
Objective-C property access
Enum tag
Union tag
Struct tag
Class name
Namespace or namespace alias
Nested name specifier
Objective-C interface
Objective-C protocol
Objective-C category
Objective-C instance method
Objective-C class method
Objective-C selector name
Macro name
Natural language
```

**Comment by MaskRay** [comment]
You may use strace/sysdig to dump LSP requests/responses
https://github.com/MaskRay/ccls/wiki/Debugging#dump-lsp-requestsresponses

**Comment by bfrg** [comment]
I've tried it with VS Code using your ccls extension and everything works fine. So it's definitively the language server client that I'm using ([vim-lsp](https://github.com/prabirshrestha/vim-lsp)).

Thank you for your help!

**Comment by avnotaklu** [comment]
I had gcc 12 installed but did not have libstdc++ for it.
I worked after installing it using
`sudo apt install libstdc++-12-dev`
