### ISSUE TITLE
Error: cannot find interface declaration for 'NSObject'.

### ISSUE THREAD

**Issue by shoorlyne** [MaskRay/ccls#126]
I have an Objective-C snippet which looks like this:

```
#import <Foundation/Foundation.h>

@interface HelloWorld : NSObject
- (void) hello;
@end

@implementation HelloWorld
- (void) hello {
    NSLog(@"Hello Objective-C!");
}
@end

int main(void) {
    HelloWorld *hw = [[HelloWorld alloc] init];
    [hw hello];
    [hw release];
}
```

Things like completion work -- ccls is able to complete the `hello` method for `hw` object. However, it's unable to find interface declaration for 'NSObject'. Kindly check this out please:

<img width="433" alt="screen shot 2018-11-20 at 8 13 44 am" src="https://user-images.githubusercontent.com/20250340/48743127-ae697400-ec9c-11e8-91a1-1c8af97f7c39.png">

The error that shows up when I hover over the NSObject class in the above image is:

`Error: cannot find interface declaration for 'NSObject', superclass of 'HelloWorld'.`

I use .ccls for this project, which looks like:

```
%clang
%c -std=gnu11
%cpp -std=gnu++14
-pthread

# Includes
-I/usr/include/GNUstep
# -I space_is_not_allowed
```

My OS is Ubuntu 16.04, GNUStep has been set up, and header files are under `/usr/include/GNUstep`.

One thing I do notice is that no setting specific to Objective-C is present in .ccls. Is that what's causing the issue? If so, how do I set it up?

Thanks!

**Comment by MaskRay** [comment]
No. The wiki merely gives an example how to use `%c` directives. clang defaults to `-std=gnu11` for C and `-std=gnu++14` for C++. You don't really need them.

**Comment by shoorlyne** [comment]
Tried it just now. Still seeing the issue.

**Comment by Riatre** [comment]
I just tried and found that in my case, this is because clang cannot find objc/objc.h. Adding `-isystem/usr/lib/gcc/x86_64-linux-gnu/8/include/` to .ccls helped.

(You may need to change the above path if you're using a different version of gobjc)

**Comment by shoorlyne** [comment]
@Riatre, `/usr/lib/gcc/x86_64-linux-gnu/8/include/` is present on my Ubuntu 16.04, but there is no `objc/objc.h`.

Do I need to install additional packages? I have installed these:
`apt-get install -y gnustep gnustep-devel gobjc`

**Comment by Riatre** [comment]
As I said, you have to change the path if you're using a different version of gobjc.

On Ubuntu 16.04, the gobjc installed by `apt-get install -y gobjc` is likely gobjc-5, according to https://packages.ubuntu.com/en/xenial/amd64/libobjc-5-dev/filelist the path should be /usr/lib/gcc/x86_64-linux-gnu/**5**/include/

**Comment by shoorlyne** [comment]
Confirmed working. @MaskRay & @Riatre, thanks a bunch for your help!
