### ISSUE TITLE
-32002: snippet.m is being indexed

### ISSUE THREAD

**Issue by shoorlyne** [MaskRay/ccls#129]
I am able to get ccls up and working with completion and diagnostics for Objective-C.

Now I am running into another issue while trying hover info. The code snippet looks like below:

<img width="418" alt="screen shot 2018-11-22 at 10 53 03 am" src="https://user-images.githubusercontent.com/20250340/48878995-eca19780-ee44-11e8-9ea6-383ffa20b620.png">

Whenever I hover over NSLog function in the snippet, ccls returns:

{"jsonrpc":"2.0","id":91,"error":{"code":-32002,"message":"/home/snippet.m is being indexed"}}

And therefore, no hover popover appears.

**Comment by MaskRay** [comment]
You need to make sure this file has finished parsing, otherwise "... is being indexed" is reported

**Comment by shoorlyne** [comment]
Right -- but the whole snippet is 17 lines of code, and I retry minutes after the first error, this still happens.

So I guess there are 2 possiblities:
1 the "xxxx.m is being indexed" message is a manifestation of a different issue, in which case, the message is misleading;
2 the snippet is indeed being indexed; however, this would indicate a performance issue in indexing, since one would not normally it would take minutes to index such a simple file. In fact, the "indexing" is still going on at the moment after 10 minutes.

**Comment by MaskRay** [comment]
The error message is misleading. I think this file just fails to parse. You may find more logs if you run ccls with `ccls -log-file=/tmp/ccls.log`

**Comment by MaskRay** [comment]
> It turns out, snippet.m being empty is the culprit.

Fixed in HEAD.

`indexer.cc`:
```cpp
-  void initialize(ASTContext &Ctx) override { this->Ctx = param.Ctx = &Ctx; }
+  void initialize(ASTContext &Ctx) override {
+    this->Ctx = param.Ctx = &Ctx;
+    SourceManager &SM = Ctx.getSourceManager();
+    (void)param.ConsumeFile(*SM.getFileEntryForID(SM.getMainFileID()));
+  }
```

> Once that file is stuffed some valid code, hover info works.

You should have told me this when reporting the issue :) I've added a section to http://go/gh/MaskRay/ccls/wiki/FAQ#hover
