### ISSUE TITLE
Reply with an error for invalid/unsupported initialize request

### ISSUE THREAD

**Issue by krzyzanowskim** [MaskRay/ccls#131]
I've noticed that when ccls can't understand InitializationRequest, or there are some missing properties that ccls assume to be sent, there is nothing in the response. It's completely muted. That makes hard to reason what is going on. I guess server should respond with an error for a initialization that is completely unsupported by the server.

eg. If `rootUri` of the workspace is missing, the server ignores the request.

**Comment by MaskRay** [comment]
Which language client do you observe does not send `rootUri` in the `initialize` request? ccls does not support `rootPath`

```typescript
	/**
	 * The rootPath of the workspace. Is null
	 * if no folder is open.
	 *
	 * @deprecated in favour of rootUri.
	 */
	rootPath?: string | null;
```

**Comment by krzyzanowskim** [comment]
> ccls does not support rootPath

that's fine, I don't use it.

> Is workspaceFolders specified by the client?

no

My point being that if for some reason, `initialize` is failing, this should be somehow notified to the client. Specifically, it is possible to send `initialize` that is not expected, hence no responce, and later send other requests. If initialize failed, I think it should respond with an error. Specification describe it in this way:

> The initialize request is sent as the first request from the client to the server. If the server receives a request or notification before the initialize request it should act as follows:
For a request the response should be an error with code: -32002. The message can be picked by the server.

> Until the server has responded to the initialize request with an InitializeResult, the client must not send any additional requests or notifications to the server. **In addition the server is not allowed to send any requests or notifications to the client until it has responded with an InitializeResult**

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/pull/133
