### ISSUE TITLE
Include incorrectly recognized as link.

### ISSUE THREAD

**Issue by shoorlyne** [MaskRay/ccls#132]
A C++ include in code is incorrectly recognized as a link, and it offers "click to follow link" option on hover. See below:

<img width="206" alt="screen shot 2018-11-23 at 10 43 09 pm" src="https://user-images.githubusercontent.com/20250340/48949081-b9a8f200-ef71-11e8-9963-9ab719935009.png">

This should be disabled -- an include is not a link.

**Comment by MaskRay** [comment]
This is called `textDocument/documentLink`. The hyper link can be limited to the filename only `<iostream>` but that would require some tokenization work, so I simply mark the whole line as a link.

```cpp
// messages/textDocument_document.cc
namespace {
struct DocumentLink {
  lsRange range;
  DocumentUri target;
};
MAKE_REFLECT_STRUCT(DocumentLink, range, target);
} // namespace

void MessageHandler::textDocument_documentLink(TextDocumentParam &param,
                                               ReplyOnce &reply) {
  QueryFile *file = FindFile(reply, param.textDocument.uri.GetPath());
  if (!file)
    return;

  std::vector<DocumentLink> result;
  for (const IndexInclude &include : file->def->includes)
    result.push_back({lsRange{{include.line, 0}, {include.line + 1, 0}},
                      DocumentUri::FromPath(include.resolved_path)});
  reply(result);
} // namespace ccls
```

**Comment by MaskRay** [comment]
Fixed by https://github.com/MaskRay/ccls/pull/135

It looks like:
```
#include <iostream>
          ~~~~~~~~
```

But for the first file opened in the project, it does not have `DocumentLink` information as the server hasn't loaded the index yet.

**Comment by shoorlyne** [comment]
Surely this looks better.
