### ISSUE TITLE
win7下vscode使用ccls出错

### ISSUE THREAD

**Issue by maosuyun2009** [MaskRay/ccls#134]
在win7下编译了ccls，但是通过vscode index的过程中直接报错如下：
[Error - 11:57:58 AM] Request textDocument/documentSymbol failed.
  Message: unable to find E:/Nuvoton/T123_TZ/include/uart0_user.h
  Code: -32603 
[Error - 11:57:58 AM] Request textDocument/documentLink failed.
  Message: unable to find E:/Nuvoton/T123_TZ/include/uart0_user.h
  Code: -32603 
LLVM ERROR: out of memory

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
LLVM ERROR: out of memory

**Comment by MaskRay** [comment]
> LLVM ERROR: out of memory

Is it an issue of your llvm library? I've seen similar issues before. It can be caused by version mismatch.
