### ISSUE TITLE
Support for cross- or non-standard compilers?

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#138]
I use my own build of GCC to compile for my code.  I use CMake and I have it generate `compile_commands.json` so ccls knows the complete command line.  However, all the system C runtime and compiler header files are installed at a separate location and the local build of GCC knows where to find them.  The compiler doesn't use any of the system libc headers or system compiler headers at all, ever.

Unfortunately ccls doesn't seem to understand this; after running if I look at the `.ccls-cache/@@work@src` directory for the system and compiler headers, they are all from the clang instance that ccls was built with and the system's /usr/include.  I know for sure that those were not the C / C++ headers that my code is compiled with.

I'm not sure how ccls attempts to locate header files to index: I hoped it would ask the compiler itself where to look, either by parsing post-processed code or by getting the compiler to print the set of include paths it will use when searching for headers.  Using these options ccls would locate the correct headers to index.  However neither of those seem to be used.

Any thoughts?

**Comment by MaskRay** [comment]
> I use my own build of GCC to compile for my code. ... However, all the system C runtime and compiler header files are installed at a separate location and the local build of GCC knows where to find them

The gcc you use has a unconventional sysroot and system search paths

> Unfortunately ccls doesn't seem to understand this; after running if I look at the .ccls-cache/@@work@src directory for the system and compiler headers, they are all from the clang instance that ccls was built with and the system's /usr/include. 

Right. ccls just calls `clang::createInvocationFromCommandLine` to infer system search paths (e.g. /usr/include). The underneath mechanism is similar to that of clang -v -E -x c++ /dev/null

```cpp
std::unique_ptr<CompilerInvocation> clang::createInvocationFromCommandLine(
...
  // clangDriver which detects system search paths
  driver::Driver TheDriver(Args[0], llvm::sys::getDefaultTargetTriple(),
                           *Diags, VFS);
...
  // Similar as clang -cc1
  if (!CompilerInvocation::CreateFromArgs(...)
```

You need to figure out your search paths in your GCC installation directory, but I think you still need `-isystem/usr/include` as these system headers are not shipped with GCC.

**Comment by madscientist** [comment]
If I didn't need to support Visual Studio and Xcode project files, I probably would just use a straightforward makefile system... I've definitely banged my head for hours against things in cmake that I could have written in 10 minutes in a makefile :).

> The gcc you use has a unconventional sysroot and system search paths.

Yes, definitely.  In fact I have a wrapper script I invoke, that sets up all the sysroot etc. arguments.  That's why I was hoping ccls would query the actual compiler somehow (e.g. by running `<compiler> -v -E -xc++` or whatever--may have to be customized for different compilers although that works with both GCC and clang) rather than using predefined values.  It seems that by relying on `clang::createInvocationFromCommandLine` it limits, somewhat, the ability of ccls to understand alternate compilers and their locations.

The issue I was hitting is that by using `compile_commands.json` I don't have the ability to manipulate the directories.  It's also quite inconvenient, in our environment, to try to "post process" the .json file generated by cmake. Also, our compiler and alternate sysroot are completely relocatable (you can copy the entire thing somewhere else and it works fine--in fact the compiler and sysroots are checked into a separate Git repository and cloned "somewhere" on the user's system) so I can't check in a pre-defined set of ccls flags: they need to be generated specifically for a given system.  And finally, the invocation of ccls to do the indexing is sort of "hidden" because it's being used with Emacs and company mode.  I'll look into seeing how to pass through options there.

I feel personally that to get the most accurate indexing with the least amount of effort from the user (and the fewest PEBCAK issues filed :) ) it would be great for ccls to query the compiler for include directories.  I realize that's much more effort than simply asking the clang library for a set of directories.  I don't know what your thoughts are on this.

Also it would be great if ccls could accept configuration in more flexible ways than just the command line (I'm afraid it wasn't exactly clear to me from the initialization option wiki page, whether that was already true or not): for example, from an environment variable or a `~/.cclsconfig` file or something like that, in addition to directly on the command line (which may be difficult to configure behind front-ends).  Perhaps that deserves a different issue.

Thanks for your reply!

**Comment by cmm** [comment]
One potential problem with the "query the damn compiler for its default include path" is that bundled includes may in theory contain arbitrary compiler-specific magic that can give clang severe indigestion, if the compiler in question is not clang (admittedly gcc is fine in my experience, but perhaps I've just had good luck with gcc/clang version combinations).

**Comment by MaskRay** [comment]
You may try specifying `--gcc-toolchain=` to your GCC installation directory, e.g. if you have `/Driver/Inputs/mips_img_v2_tree/lib/gcc/mips-img-linux-gnu/4.9.2/include`, use `clang --gcc-toolchain=/Driver/Inputs/mips_img_v2_tree`

> The issue I was hitting is that by using compile_commands.json I don't have the ability to manipulate the directories.

You can post process `compile_commands.json` but it may be inconvenient. See the two initialization options `clang.excludeArgs` and `clang.extraArgs`. clang supports `--sysroot=` 

> And finally, the invocation of ccls to do the indexing is sort of "hidden" because it's being used with Emacs and company mode. I'll look into seeing how to pass through options there.

`ccls-extra-init-params` https://github.com/MaskRay/ccls/wiki/Emacs#initialization-options

>  it would be great for ccls to query the compiler for include directories. I realize that's much more effort than simply asking the clang library for a set of directories. I don't know what your thoughts are on this.

clang does all the heavylifting here. I try to avoid inventing any compiler driver logic in ccls as the extra work can often lead to loss of generality and get in the way.

* libc++: https://github.com/MaskRay/ccls/issues/125
* -march=armv7-a: https://github.com/MaskRay/ccls/issues/107

What ccls does should not be very different from what the compiler driver `clang` or other clang tools such as `c-index-test` do:

`c-index-test -index-file a.cc -resource-dir ~/llvm/Release/lib/clang/8.0.0 -isystem /xxx -I /yyy -cxx-isystem /cxx-xxx`

**Comment by MaskRay** [comment]
>  Because of the way --init encodes all of the configuration in one single JSON string, and only one --init is allowed, the wrapper will have to require jq (if it's a shell script) or be written in Python or something so it can break open the incoming --init and add in these extra options.

This is a reasonable feature request. I pushed a commit to support multiple `-init=`.

    Initialization options are applied (deserialized to the same object) in the following order:
    
    * "initializationOptions" from client
    * first -init=
    * second -init=
    * ...
    
    Scalar options will be overridden but arrays will get concatenated, e.g.
    
    ccls -log-file=/dev/stderr -index . -init='{"clang":{"extraArgs":["a"]}}' -init='{"clang":{"extraArgs":["b"]}}'
    
    results in clang.extraArgs: ["a", "b"]

> it handled finding all the right headers for my compilers perfectly the first time without any special customizations, which is great.

`cquery/src/platform.cc` uses reproc and spawns a process to collect search directories from `-v -xc++ /dev/null`. I don't like that approach and won't do the similar thing in ccls.

> But, it seemed to require a lot more resources, which is not great.

For cquery, remember to set `{cacheFormat: "msgpack"}`, otherwise the default `"json"` is selected and it is very inefficient as a serialization format.

**Comment by madscientist** [comment]
> You may forget these So questions and start from here

I see.  The problem is the hardcoded set of triples: our triple is `x86_64-generic-linux-gnu` which is not one of the ones predefined in Clang.  it's a shame they decided use an explicit list of triples rather than using globbing matches, such as `x86_64-*-linux-gnu`.  A hardcoded list can never be sufficient.  If I go through our compiler installation and create `x86_64-unknown-linux-gnu` symlinks to point to each `x86_64-generic-linux-gnu`, then it works.  I'm not sure I want to do that in general though.

> For cquery, remember to set `{cacheFormat: "msgpack"}`

I thought I had done that, but I realized I used `cacheformat` instead of `cacheFormat` and it silently ignored the misspelling (another hazard of using JSON for configuration :grin:)  After I fixed that the situation is better for sure.

There's something strange about my ccls output: cquery caches almost twice as many files.  Looking at the results, it seems like ccls is not caching most of my header files.  It's very strange because it does cache the matching `.cpp` file, right in the same directory.  In fact it only caches 67 of my 1631 header files.  I see no mention of the missing files in the log output.

> * "initializationOptions" from client
> * first -init=
> * second -init=
> * ...

Awesome!  I'm wondering: if things are added at the end and overridden by later values, shouldn't the options from the client come _last_ rather than first?  i would think that the arguments the server was started with should be overridden by the options provided by the client.

> `cquery/src/platform.cc` uses `reproc` and spawns a process to collect search directories from `-v -xc++ /dev/null`. I don't like that approach and won't do the similar thing in ccls.

I absolutely understand your distaste.

Nevertheless, I fear that this will keep ccls unsuitable for a number of dev environments.  Embedded development and a significant number of development teams (outside of FOSS) use non-default compilers.  Even when not doing cross-compilation, for co-ordinated teams your choices are (a) allow everyone to use their own native compiler and deal with the broken compiles from people using different versions, (b) force everyone to use identical OS distributions/versions so they all have the same native compiler, or (c) provide a separate compiler outside of the default locations so everyone can use the same one.  By far the least amount of hassle is (c) and that's how all the development shops I've worked at do things.  As above, it appears that if you're lucky and your environment matches something Clang expects you can configure things with only a few extra arguments (`--gcc-toolchain` and `--sysroot`), but if not you've got a long road ahead.

Anyway, thanks for your efforts on both `ccls` and `cquery`; it's great to have good indexing for C/C++ projects!

**Comment by MaskRay** [comment]
> shouldn't the options from the client come last rather than first?

For editors that are not as flexible as Emacs is: no buffer-local variables or dynamic scoping, it isn't easy to tweak client-side configuration and the shell wrapper responsible for starting the language server has the more flexibility here. I think it makes sense to let the flexible one (`-init`) overrides the inflexible one (`"initializationOptions"`).

> Embedded development and a significant number of development teams (outside of FOSS) use non-default compilers. Even when not doing cross-compilation, for co-ordinated teams your choices are (a) allow everyone to use their own native compiler and deal with the broken compiles from people using different versions, (b) force everyone to use identical OS distributions/versions so they all have the same native compiler, or (c) provide a separate compiler outside of the default locations so everyone can use the same one.

Thanks for elaborating on the complexity.

This run-clang-v-to-get-search-directories approach is not bulletproof and has caused many issues before.

`cquery/third_party/reproc/src/c/posix/fork.c:109`  `execvp(argv[0], (char **) argv);`

I haven't tried it by myself, but if I understand it correctly, `argv[0]` cannot be different from the executable name. This may break a use scenario as clang can infer the target/triple from `argv[0]` (you can create a symlink `powerpc64le-linux-gnu-clang` pointing to clang). https://github.com/MaskRay/ccls/issues/107

There are also users who don't code the full pathname of the compiler driver and rely on `PATH` when compiling (some virtualenv-like scripts). I wonder if this approach would still work.

clang has provided good emulation of gcc but nuance is unavoidable. Users have to fight with command line options if they want to use different versions of GCC or switch to clang. clangDriver is a gigantic thing, ycmd has probably done some crazy twiddling on their side, I think, doing the least and handing over everything to clangDriver is the cleanest/most robust approach. Adding `-isystem` to `clang.extraArgs` should be acceptable.

**Comment by MaskRay** [comment]
>  In fact it only caches 67 of my 1631 header files. I see no mention of the missing files in the log output.

Header files are not compiled on their own. For header files that are not included, they may not get indexes. Also see https://github.com/MaskRay/ccls/issues/72#issuecomment-425802220

**Comment by Riatre** [comment]
That said, I think writing your own hack-y wrapper doing include path detection then add to compile_commands/init options in your favorite scripting language might be a good idea for this use case: fits the need; could be simple as the compilers are under your control; won't be a surprise to user.
