### ISSUE TITLE
ccls can`t find c++ 3thparty libraries headers?

### ISSUE THREAD

**Issue by ydjee** [MaskRay/ccls#139]

**Comment by MaskRay** [comment]
It can, but you need to correctly pass `-I` `-isystem` ... to ccls. Please provide more description and also check out  https://github.com/MaskRay/ccls/wiki/FAQ#definitions

**Comment by ydjee** [comment]
Thank you for your attention. compile_commands.json ,I am a bit vague. I try to use .ccls file again, but i find that ccls can find 3thparty headers absolute path, relative path don`t work! can you help me?
eg: .ccls file:
/usr/local/bin/gcc -std=gnu11
/usr/loca/bin/g++ -std=gnu++11
-I/opt/libevent/include
-I/usr/local/include/c++/7.3.0
-I/home/jee/workspace/libevent_test/sample/ccc/include
is done!

--->but ...

/usr/local/bin/gcc -std=gnu11
/usr/loca/bin/g++ -std=gnu++11
-I/opt/libevent/include
-I/usr/local/include/c++/7.3.0
./include
can`t  find ./include 
I use ccls cmd: ccls -index=. -log-file=log

**Comment by MaskRay** [comment]
```
/usr/local/bin/gcc -std=gnu11
/usr/loca/bin/g++ -std=gnu++11
```

There are several problems. First, you shouldn't specify two compiler drivers. Second, the wiki has clearly stated that space-separated arguments should not be used.

> `./include`

`-I./include`

Please make some investigation by yourself before opening an issue without any description.
