### ISSUE TITLE
Macro redefinition error inside header stops whole compilation

### ISSUE THREAD

**Issue by Yanpas** [MaskRay/ccls#140]
UPD:
My project uses warnings intensively:
-Wall -Wextra -Werror=multichar -Wno-deprecated -Wno-unused-parameter -Woverloaded-virtual -Wnon-virtual-dtor -Werror -std=gnu++11 -Wno-unknown-pragmas.

I see macro redefinition error in many c++ files despite project compiles successfully. This error stops compilation on the point of error and autocompletion becomes too limited. The error is in some deep nested boost header, there is macro redefinition (compile command contains -D for that macro). After this error takes place whole compilation stops.

ORIGINAL COMMENT:
I switched from c3b4b7f75f19aea16e03992a81f283ab5ac2b84e  to 1111, since I get a lot of warnings in my project:
* size_t not found
* set, string, vector not found in std
* tons of others

**Comment by Yanpas** [comment]
A lot of files are skipped while parsing because of this weird error, which I don't face with cquery:
![image](https://user-images.githubusercontent.com/7345761/49226160-e425ff80-f3f6-11e8-98ea-bd4b8717dcb1.png)

It appears in a lot of files on the line 11 even if there is a comment on that line

**Comment by Yanpas** [comment]
Logs with -v=100 do not produce any meaningful errors. (ps I don't know what's the maximum level -v argument accepts)

**Comment by Yanpas** [comment]
clang++ <rest of the command of .cpp with error> compiles successfully.

**Comment by MaskRay** [comment]
`-v=1` (`LOG_V(1)` only has one call site in `project.cc`) so it won't give too much output.

You may also read https://github.com/MaskRay/ccls/issues/138#issuecomment-442318989 for some useful commands.

Can you give some more information? e.g. if the file is a header or a normal C++ source, as `.h` `.hpp` `.hh` ... header files are handled differently. They are not indexed on their own

https://github.com/MaskRay/ccls/wiki/FAQ#diagnostics-in-headers

**Comment by Yanpas** [comment]
The error is in some deep nested boost header, there is macro redefinition (compile command contains -D for that macro). After this error takes place whole compilation stops.

It looks like tthis:
command: g++ file.cpp -Dfoo

Some file included in file.cpp contains
#define foo

There seem to be no regressions, all ccls face this issue. Cqery handles it fine.

BTW project build takes place inside docker

**Comment by MaskRay** [comment]
Does `clang.extraArgs: ["-Wno-macro-redefined"]` or `-w` suppress the issue?

**Comment by Yanpas** [comment]
Yes, it does. It makes ccls usable since clang doesn't stop on that error and compiles source that goes after. Is there a way to configure libclang to skip such errors and compile each file as much as it can?

**Comment by Yanpas** [comment]
My project uses warnings intensively:
`-Wall -Wextra -Werror=multichar -Wno-deprecated -Wno-unused-parameter -Woverloaded-virtual -Wnon-virtual-dtor -Werror -std=gnu++11 -Wno-unknown-pragmas`

**Comment by Yanpas** [comment]
```diff
index fab5daf7..cdd2ff32 100644
--- a/src/clang_complete.cc
+++ b/src/clang_complete.cc
@@ -318,6 +318,7 @@ void BuildPreamble(CompletionSession &session, CompilerInvocation &CI,
   // prematurely because of -ferror-limit=. This also works around the issue
   // of -Werror + -Wunused-parameter in interaction with SkipFunctionBodies.
   auto &Ws = CI.getDiagnosticOpts().Warnings;
+  Ws.push_back("no-macro-redefined");
   Ws.erase(std::remove(Ws.begin(), Ws.end(), "error"), Ws.end());
   CI.getDiagnosticOpts().IgnoreWarnings = false;
   CI.getFrontendOpts().SkipFunctionBodies = true;
```

that didn't help, still get same error

**Comment by MaskRay** [comment]
Can you take a look at https://github.com/llvm-mirror/clang/blob/master/test/Index/preamble.c and use

* `c-index-test -write-pch t.pch <options>`
* `CINDEXTEST_EDITING=1 c-index-test -test-load-source-reparse 5 local -include t <options>`

to check if libclang has the same issue?

Please put all the pieces of information into one place. You can amend https://github.com/MaskRay/ccls/issues/140#issue-385693120

**Comment by Yanpas** [comment]
I've created COMMAND and COMMAND2 files. First one contains compile command without first argument (g++). Second is the same as first but without -Werror.

`c-index-test -write-pch t.pch $(< COMMAND)` printed 8 lines with the error "error: class 'XXX' was previously declared as a struct [-Wmismatched-tags]". Same with COMMAND2 didn't print anything.

`CINDEXTEST_EDITING=1 c-index-test -test-load-source-reparse 5 local -include t $(< COMMAND)` printed a loooot of `// CHECK` and `error: 'BOOST_NO_CXX11_HDR_CODECVT' macro redefined [-Wmacro-redefined]` at the end.

**Comment by MaskRay** [comment]
> c-index-test -write-pch t.pch $(< COMMAND) printed 8 lines with the error "error: class 'XXX' was previously declared as a struct [-Wmismatched-tags]". Same with COMMAND2 didn't print anything.

`-Wmismatched-tags` is enabled by `-Wmost` (and also `-Wall`). You do have issues in your header files. 

```zsh
% diagtool show-enabled -Wmost a.cc | grep mismatched-tag 
W  warn_struct_class_previous_tag_mismatch [-Wmismatched-tags]
W  warn_struct_class_tag_mismatch [-Wmismatched-tags]
```

You probably have `-Werror` somewhere which turns warnings to errors (note your diagnostic messages). Please delete them.

The default `-ferror-limit` is 19, after that many of errors clang will stop parsing.

**Comment by Yanpas** [comment]
Do these errors occur because of the logic of header parsing? (reduced number of header parsing)

**Comment by MaskRay** [comment]
Yes.

> "error: class 'XXX' was previously declared as a struct [-Wmismatched-tags]"

Delete your `-Wall` to make it a **warning**, or figure out why `Ws.erase(std::remove(Ws.begin(), Ws.end(), "error"), Ws.end());` does not fix it for you
