### ISSUE TITLE
available options for .ccls

### ISSUE THREAD

**Issue by matfranczyk** [MaskRay/ccls#141]
Hi,
first of all a big thanks for this plugin and your work :)
I've got a question, because I'm trying to tune it up and customize to my needs. 
Is there any resource (more than repo's wiki) with full description/howto about .ccls available options?

I've noticed two potential problems:
first)  - 'live linting' shows error on some line with include statement (sth like #include <clang/.../AST>), which is strange, because  I'm still able to jump to that file :/ so, in fact, indexer works as expected, even though line is marked as 'error'

second) I saw that indexer parsed also files from different folder. E.g.

<path>   //neovim had been fired from this folder - let's called it current working directory
   .ccls
   IncludeDirectory
   SrcDirectory
   catch.hpp

<path> // folder next to 'current working directory' - let's called it 'neighbor directory'
   IncludeDirectory
   SrcDirectory
   catch.hpp  

and what is interesting, when i'm trying to find definition in catch.hpp CCLS shows definition from 'neighbor directory' - seems weird for me ;/

PS if you need some help - I can create such HOWTO that you could post here in this repo

**Comment by MaskRay** [comment]
```cpp
// x/a.cc
#include "catch.hpp"
// x/catch.hpp
// omitted

// y/a.cc
#include "catch.hpp"
// y/catch.hpp
// omitted
```

`x/catch.hpp` and `y/catch.hpp` provide the same set of definitions. When you trigger `textDocument/definition`, what `messages/textDocument_definition.cc` does is to locate the symbol at point, get its USR (Unified Symbol Resolution), find what definitions are associated with the USR. In the case, there can be multiple and `textDocument/definition` will return every one. Some language client tries to be clever and jump to one instead.
