### ISSUE TITLE
ccls shows candidates from headers that are not included

### ISSUE THREAD

**Issue by ahsanp** [MaskRay/ccls#143]
Hi. I'm using ccls with lsp-mode using the very basic settings mentioned in the emacs setup page on ccls wiki. The problem is that ccls provides completion candidates from headers that I have not included anywhere in the file or the project. For example when in a C file I get the following completion candidates

![screenshot from 2018-11-30 04-18-37](https://user-images.githubusercontent.com/16830690/49283348-23843880-f457-11e8-92da-2e79130b3bde.png)

While I have included only the following headers

![screenshot from 2018-11-30 04-18-46](https://user-images.githubusercontent.com/16830690/49283381-36970880-f457-11e8-8582-4aea4fe9e5eb.png)

Additionally it is giving me several interfaces as completion candidates which ideally in a C file it shouldn't (especially without including the appropriate headers)

is there a way to solve this issue? 

Thank you!

**Comment by Riatre** [comment]
These "interface"s are actually macros. (There is no completion item kind defined in LSP for macro, I don't know why Interface is picked instead, though.) They are definitely defined in the headers included, maybe not directly, for example, your source code includes errno.h, errno.h includes feature.h, feature.h defines `__GNUC_PREREQ`.

So, technically, these are all "valid" completion candidates, they are mostly unwanted but there does not seem to be a good way to filter them out.

**Comment by MaskRay** [comment]
`bits/pthreadtypes.h` is included by `sys/types.h`

```
% pp-trace -ignore InclusionDirective,FileSkipped,FileNotFound,Defined,Ident,PragmaDirective,MacroDefined,MacroExpands,MacroUndefined,If,Ifdef,Ifndef,Else,Endif,SourceRangeSkipped a.cc
...
- Callback: FileChanged
  Loc: "/usr/include/x86_64-linux-gnu/sys/types.h:223:1"
  Reason: ExitFile
  FileType: C_ExternCSystem
  PrevFID: "/usr/include/x86_64-linux-gnu/sys/sysmacros.h"
- Callback: FileChanged
  Loc: "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h:1:1"
  Reason: EnterFile
  FileType: C_ExternCSystem
  PrevFID: (invalid)
```

**Comment by MaskRay** [comment]
completion: use Text for Macro{Instantiation,Definition}

```cpp
--- a/src/messages/textDocument_completion.cc
+++ b/src/messages/textDocument_completion.cc
@@ -264,7 +264,7 @@ CompletionItemKind GetCompletionKind(CXCursorKind cursor_kind) {

   case CXCursor_MacroInstantiation:
   case CXCursor_MacroDefinition:
-    return CompletionItemKind::Interface;
+    return CompletionItemKind::Text;
```
