### ISSUE TITLE
Surprising code completion after colon (with emacs and eglot)

### ISSUE THREAD

**Issue by amosnier** [MaskRay/ccls#144]
With emacs + eglot + ccls + company, I am getting some really surprising (at least to me) completion after typing colon.
Here comes an example:

![screenshot_2018-11-30_19-19-32](https://user-images.githubusercontent.com/9384772/49307378-4f460380-f4d5-11e8-908e-6d9fac201423.png)

I get the same issue after the colon in `for (auto i :`.

I tried to make sense of eglot's event buffer that shows LSP requests and replies, and unless I am mistaken, ccls seems to send all these completion propositions.

Any clue about where this comes from?

**Comment by MaskRay** [comment]
After `case 1:`, clang is completing a statement. `Gui` `Window` ... are all legitimate completion candidates though they may surprise you. When you are completing without completion text, I think the recall is very important.

**Comment by amosnier** [comment]
OK, I think I get it. Thanks a lot for being so responsive.

**Comment by Riatre** [comment]
I think there might be a bug.

As @MaskRay said, triggering the completion at this point do result in all these completion candidates, but the problem is it should not be triggered at this point.

The reason why you get a completion result after a single colon is LSP only supports single character as so-called "triggerCharacter", however we do want to trigger completion after "::". So what ccls does is announcing a single character ':' as triggerCharacter, then [do post filtering](https://github.com/MaskRay/ccls/blob/master/src/messages/textDocument_completion.cc#L484) on the completion request. 

The post filter relies on correct triggerKind and triggerCharacter being set in the [completion request](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion), could you please check whether eglot got this right?

**Comment by amosnier** [comment]
As far as I can see the last client request before I see the completion is:
```
client-request (id:86) Sat Dec  1 13:27:58 2018:
(:jsonrpc "2.0" :id 86 :method "textDocument/completion" :params
	  (:textDocument
	   (:uri "file:///home/alain/custom/repos/tint/src/main.cpp")
	   :position
	   (:line 13 :character 8)))
```
Neither `triggerKind` not `triggerCharacter` as you can see. Line 13, character 8 is the start of the word `switch` in:

![image](https://user-images.githubusercontent.com/9384772/49328267-ca5af880-f56d-11e8-826b-9c9cbdd6a6c3.png)

**Comment by amosnier** [comment]
I have just reported the same issue at https://github.com/joaotavora/eglot/issues/173.

**Comment by joaotavora** [comment]
> Neither triggerKind not triggerCharacter as you can see. Line 13, character 8 is the start of the word switch in:


You're looking in the wrong spot. Ccls does in fact annouce some trigger characters, in its response to Eglot's `initialize` method:

```
(:resolveProvider :json-false :triggerCharacters
                              ["." ":" ">" "#" "<" "\"" "/"])
```

LSP does not provide a good built-in way of filtering which events where these characters are typed should indeed trigger a completion request, so Eglot triggers for all of them.  Filtering on the LSP's server side, as @Riatre suggests, seems to be the only option, and thus I am inclined to consider this a fault on the server side.  But I am open to suggestions on how to fix this client-side.

**Comment by joaotavora** [comment]
Never mind, I misunderstood. @Riatre, @MaskRay  are you saying that if eglot sends the `completionContext` field for the completion request, then Ccls will behave differently than it does now?

**Comment by MaskRay** [comment]
Thank Riatre for pointing out the issue. In `case 1:`, when the `:` is inserted, both company-lsp and eglot send a `textDocument/completion` request. The expected client-side behavior here is not to suggest completion candidates.

1. The server announces that it supports `:` in `CompletionOptions.triggerCharacters`. Ideally it should be `::`, but there is a limitation that VSCode only accepts length-one strings and they don't intend to fix that https://github.com/Microsoft/language-server-protocol/issues/138 To work around this limitation, the following scheme has to be used.
2. When user inserts `:`, the client should send ``textDocument/completion` and provide `CompletionTriggerKind.TriggerCharacter` (company-lsp and eglot fail to do it now @tigersoldier)
3. The server checks if there is another colon before the just-inserted colon. If not, it returns an empty `CompletionList`.

```cpp
// ccls/src/messages/textDocument_completion.cc
  if (param.context.triggerKind == CompletionTriggerKind::TriggerCharacter &&
      param.context.triggerCharacter) {
    bool ok = true;
    int col = param.position.character - 2;
    switch ((*param.context.triggerCharacter)[0]) {
    case '"':
    case '/':
    case '<':
      ok = CCOpts.IncludeCodePatterns; // start with #
      break;
    case ':':
      ok = col >= 0 && buffer_line[col] == ':'; // ::
      break;
    case '>':
      ok = col >= 0 && buffer_line[col] == '-'; // ->
      break;
    }
    if (!ok) {
      reply(result);
      return;
    }
  }
```

**Comment by joaotavora** [comment]
So if eglot supplies `CompletionTriggerKind.TriggerCharacter` things will be +/- OK?

**Comment by MaskRay** [comment]
> So if eglot supplies CompletionTriggerKind.TriggerCharacter things will be +/- OK?

Yes!

**Comment by joaotavora** [comment]
>Yes!

OK. Let's follow up in https://github.com/joaotavora/eglot/issues/173
