### ISSUE TITLE
Is it possiable to run ccls server on a remote machine while editor and client running on local machine?

### ISSUE THREAD

**Issue by zhaozhao** [MaskRay/ccls#148]
I am working on a huge codebase (more than 100GB). It is compiled and running on Linux, and my local machine is running on mac os. 

I managed to generate the compile_commands.json and use sshfs to mount the remote file system to local dir. But ccls reported some error caused by some platform-specific difference, for example,  different system headers, system specific macro like `#ifdef linux`. There are more than 4k errors which make it impossible to just modify the source code to work around the problem.

I'm wondering is it possible to just run the ccls language server on the remote server, so that ccls could just use the same files as its compiling env? It seems that language server and client need to share the same filesystem under some circumstances. Is there any feather can't be implemented with this approach?

**Comment by whatacold** [comment]
Maybe you will be interested in https://github.com/joaotavora/eglot/issues/84, though I haven't try it.

**Comment by MaskRay** [comment]
> I am working on a huge codebase (more than 100GB).

Have you excluded binary artifacts?

> I'm wondering is it possible to just run the ccls language server on the remote server, so that ccls could just use the same files as its compiling env?

You can mount that remote directory with the same path locally or use some file mapping mechanism.

> It seems that language server and client need to share the same filesystem under some circumstances.

It shares, e.g. `#include`d files are accessed by clang but theirs contents are not transferred in the language server protocol.
