### ISSUE TITLE
100% cup usage while reading glibc code repo

### ISSUE THREAD

**Issue by Yanhao** [MaskRay/ccls#149]
environment:
debian sid
emacs 25.2.2

Here is what I've done:

1. download the glibc source code: `apt source glibc`.
2. create .root and .projectile in the root of source directory.
3. using emacs open any source file under the source root.

**Comment by MaskRay** [comment]
Which version are you using? If you use the version before 2018-11-08 (commit 57747871733c37b021e56dcbd61e05dac464fb8c) with `clang < 8`, there can be a problem indexing Linux.


I just tried glibc and it looks well.
