### ISSUE TITLE
cquery vs ccls

### ISSUE THREAD

**Issue by innerout** [MaskRay/ccls#15]
First of all congratulations for the great work on cquery and ccls.

I would like to ask what are the advantages of using ccls over cquery except the ones in Readme. 
For example in the longterm?

Also i would like to ask if there will be better support in the emacs plugin for ccls compared to cquery?

**Comment by innerout** [comment]
What about the emacs question?

**Comment by MaskRay** [comment]
There are not many differences, except for

```elisp
;; ccls.el
(defcustom ccls-project-root-matchers
  '(".ccls-root" projectile-project-root)
  "List of matchers that are used to locate the ccls project roots.
```

and I use `uint64_t` as primary key in the memory index of ccls, thus corresponding changes to `ccls-*-hierarchy.el`

**Comment by innerout** [comment]
Feature wise will you keep up with cquery or you will add your own features?

**Comment by MaskRay** [comment]
I heavily rely on a good C++ cross reference tool and clangd cannot meet my needs (I actually have a lot of complains to its index design).

In terms of features, the number of supported LSP features has been stable for some time.
cross references + hierarchies. There are no newer extensions after `$ccls/memberHierarchy`. I of course keep an eye on cquery development and backport useful commits (like some cleanup) but I also object to many of its choices:

* heuristic deriving of system include path. I replaced the project.cc code with clangDriver which I would enhance in the future to detect paths like `/usr/include` `/usr/include/c++/v1`

**Comment by innerout** [comment]
OK one last question. I am talking about emacs because cquery's master branch does not work with emacs-cquery plugin so if you change something you are the maintainer of the emacs-ccls and it will have instant support right?
It would be good to have a link to the other issue with the cquery vs ccls conversation and mine issue in readme so people can see it easier.

**Comment by innerout** [comment]
OK thanks i am closing the issue you answered everything i wanted to know.

**Comment by MaskRay** [comment]
scturtle uploaded https://github.com/MaskRay/ccls/issues/9#issuecomment-397608940

`vscode-cquery` does not support memberHierarchy which I use a lot. I also find it unnecessary to have so many customized variables for semantic highlighting `cquery.highlighting.enabled.memberFunctions`
