### ISSUE TITLE
Sharing indexes for shared files

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#151]
Perhapsthere's a reason to avoid this that I'm not thinking of, but in my C++ projects the amount of effort and disk space involved with indexing the STL and system headers is substantial: about 800 files and >21M of disk space.

Since I work in multiple Git worktrees at the same time, I was hoping to share these indexed files between projects as they almost never change.  I set `cacheDirectory` to a single location, hoping that would do it, but while ccls seems to know the difference between the system files and the project files (it puts them into different directories) both of these directories are still placed relative to the project directory.

For example something like this, if `cacheDirectory` is set to `~/.ccls-cache` and we've indexed a project in `/my/work/project` then I get files like:

```
~/.ccls-cache/@@my@work@project/@@usr@include@stdio.h
~/.ccls-cache/@my@work@project/include@myfile.h
```

Note how the common headers still are placed inside a directory prefixed by `@@my@work@project` so they won't be shared with any other workspace even though the files are the same.

Is this intentional?  I'm not sure what use the indexer makes of different `-D` options etc. but if the entire file is always indexed the same way couldn't we share these system header file indexes?

**Comment by MaskRay** [comment]
See

* https://github.com/MaskRay/ccls/wiki/FAQ#multi-version-headers
* https://github.com/MaskRay/ccls/issues/112#issuecomment-437633261
