### ISSUE TITLE
indexer.cc requires __STDC_FORMAT_MACROS to be defined

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#152]
According to the C++ standard if you want to use C-style inttypes PRI macros you must define `__STDC_FORMAT_MACROS` before including `inttypes.h` or `cinttypes`.

Without this I get compiler errors on my system, as `PRIu64` is not defined; FYI my `/usr/include/inttypes.h` contains:

```
#if !defined __cplusplus || defined __STDC_FORMAT_MACROS
```

wrapping all the PRI macro definitions.

Thanks!

**Comment by MaskRay** [comment]
A former instance https://github.com/MaskRay/ccls/pull/92

Maybe I should add it back

**Comment by madscientist** [comment]
The headers I'm using are the defaults shipped with the glibc in Red Hat Enterprise Linux 6, which predates C++11.  Because inttypes is part of the C runtime not part of the compiler, simply upgrading your compiler to C++11 won't fix this problem.  We compile with such old versions to ensure that the resulting binary will run essentially anywhere.

If you don't want to include the fix it might be useful to add this to a FAQ or similar.
