### ISSUE TITLE
Figuring out why indexing gives up

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#154]
I feel like I'm being a pain, but: I've read the Debugging wiki page but I wonder if there's any other advice to give when indexing itself is not working correctly.

I'm invoking `ccls` from the command line directly, using `ccls --index=/my/path`.  I'm using compile_commands.json and in all instances `ccls` locates all 1500 or so of my C++ source files and attempts to index them.  However in some configurations, that indexing takes quite a while (6 minutes or so) and generates 275M or so of output into `.ccls-cache` and seems to get at least most of my files.

In other configurations, it rips through all these files in 5 seconds and generates only 35M or so of output.  All the source files are there but most of the header files are missing.  By "configuration" here I mean (a) different arguments passed via `clang.extraArgs` and (b) different installations of Clang.

I've looked at the log output and there are no details there (except I can see most of my headers are missing from the log and never parsed in the short-time run) and tried to increase verbosity with the `-v=9` option as specified by `--help` but that doesn't seem to make much difference.

Is there a recommended way to approach debugging this?  It seems clear that the clang parsing is failing or being interrupted somehow but no messages are being generated.

**Comment by MaskRay** [comment]
When `clangIndex` gets stuck or fails to parse you don't more diagnostics. Can you add `-log-file=/tmp/cc.log` and compare the log files? You should find things similar to the following:

```
20:18:52 indexer2         pipeline.cc:298 I parse /tmp/d/a.cc
20:18:52 indexer2         pipeline.cc:327 I store index for /tmp/d/a.cc (delta: 1)
```

`parse *` means `pipeline.cc` decides to parse a file. `store index for *` means `clangIndex` has done its job and a cache file is written. If the parse fails, there won't be a `store index for` line.

**Comment by madscientist** [comment]
Thanks for the response and I don't mean to ghost anyone... I'm buried in work but I will get back to serious investigation ASAP.

**Comment by madscientist** [comment]
I think I have discovered the problem.  I was trying to build `ccls` then copy the binary around to various locations.  However, ccls requires also the resource directory from clang in order to work as it will always use various headers from there such as stddef.h, and ignore these headers even if they are found in any other directory on the search path (such as GCC's internal directories).

If the Clang resource directory is not found then no errors are shown in the log or output, and we do get output files generated for the code, but the index files are created very quickly and seem to be missing many things as I described in my initial message above (only 35M instead of 275M).

Since this is technically a configuration error we can probably close it, but it might be wise to note in the docs that the generated `ccls` binary is hard-coded to look for the resource directory in the build directory of ccls (at least if you're using GCC as your compiler), so you can't delete that after building `ccls` or things will no longer work correctly.  It might also be useful to generate some kind of error or message in the log if the resource directory doesn't exist, and/or if it doesn't contain `include/stddef.h` at least.

**Comment by MaskRay** [comment]
> If the Clang resource directory is not found then no errors are shown in the log or output, and we do get output files generated for the code

Correct.

>  but it might be wise to note in the docs that the generated ccls binary is hard-coded to look for the resource directory in the build directory of ccls (at least if you're using GCC as your compiler),

You get it. It has been noted at https://github.com/MaskRay/ccls/wiki/FAQ#check-if--resource-dir-is-correct for a while...

**Comment by madscientist** [comment]
OK thanks.  I've re-read that section both before and even after I've discovered the problem and I must admit, it didn't make the situation clear for me.  Maybe because I'm using cmake in my project so I have my own CMakeCache, I didn't realize that the CMakeCache etc. being discussed here are the ones from building `ccls`, and not something from the project being indexed.

I'm happy to spend a little time tweaking the wiki pages if that would be something you're interested in getting a PR for.

**Comment by MaskRay** [comment]
As my own note, this is similar to another Clang 7.0.0 bug https://github.com/MaskRay/ccls/issues/88 that @joelhock reported (fixed at some point between 7.0.0 and 8.0.0)

CrashRecoveryContext doesn't use `SA_ONSTACK`, so sigaltstack (should be called per-thread) is not useful..

**Comment by MaskRay** [comment]
> I'm happy to spend a little time tweaking the wiki pages if that would be something you're interested in getting a PR for.

If you'd like to do that, it'd be much appreciated for! As you can see the wiki pages are publicly editable...

**Comment by unphased** [comment]
Thank you for explaining what you did to troubleshoot, and highlighting the importance of the resource dir.
