### ISSUE TITLE
Configuring document formatting indentation

### ISSUE THREAD

**Issue by dkasak** [MaskRay/ccls#158]
Is it possible to configure how many spaces the document formatting feature uses for indentation?

**Comment by MaskRay** [comment]
You can customize `.clang-format`

The LSP requests ccls implements is an alternative entry point of the clangFormat library (`clang-format` being another)

https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by notorand-it** [comment]
Could you please elaborate more on how to setup ccls to define different formatting and indentation policies?
