### ISSUE TITLE
Why not cquery?

### ISSUE THREAD

**Issue by Compro-Prasad** [MaskRay/ccls#16]

**Comment by MaskRay** [comment]
See #15

**Comment by Compro-Prasad** [comment]
Better, have a section somewhere in README.md having the comparison or your opinions by providing an URL like https://github.com/MaskRay/emacs-ccls/issues/1#issuecomment-386179958 .

**Comment by balta2ar** [comment]
You don't have to be opinionated, just state facts/actual decisions and their
consequences, describe their impact. The point of the message is not to
critisize someone else's solutions, but to help users decide which project is
better suited to their needs. Put yourself into the shoes of an uninvolved user
who's not aware of the nuances of the internal design: two projects, one has
just been forked, they are identical from the user perspective, which one do I
choose and why?

As for the commitement, I think it's simple: just add a date and note that the
mentioned differences were valid at that point of time. You may add updates
later if you deem it necessary or mark them as outdated without getting into the
details.

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Visual-Studio-Code
