### ISSUE TITLE
Issues with prototypes having unnamed parameters

### ISSUE THREAD

**Issue by oblitum** [MaskRay/ccls#161]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

```
## versions

vim version: NVIM v0.3.1
node version: v11.4.0
coc.nvim version: 0.0.39
term: tmux-256color
platform: linux

## Error messages

## Output channel: prettier
```

**Describe the bug**

Two issues identified when prototypes have parameters without names:

1. completion suggestions for prototypes won't get refreshed on _remotion_ of parameter names, only when names are _changed_
    - `signatureHelp` gets refreshed though
2. "JumpPlaceholder" signatureHelp only works when parameters have name
   - using `autocmd  User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')`

**To Reproduce**

1. [ccls configuration](https://github.com/neoclide/coc.nvim/wiki/Language-servers#ccobjective-c)
2. See video

**Screenshots**

- <https://i.imgur.com/IJiZ2E7.mp4>

Issue migrated from https://github.com/neoclide/coc.nvim/issues/269.

**Comment by MaskRay** [comment]
https://github.com/maskray/ccls/blob/master/src/messages/textDocument_completion.cc#L547

```cpp
void MessageHandler::textDocument_completion(CompletionParam &param,
...
  if (cache.IsCacheValid(path, begin_pos)) {  //////// you have changed text in another place. The completion cache should have been invalidated, but the condition is hard to check.
```

Unless you can think of some good cache verification approach, I'll mark this as wontfix as such completion scenario usually doesn't matter.

**Comment by MaskRay** [comment]
What does `CocJumpPlaceholder` mean?

**Comment by oblitum** [comment]
I don't know technically, will have to check coc sources. But in general:

> The autocmd triggered as expected, you can try it with other command, ccls doesn't give correct active param (always 0), but clangd does. -- @chemzqm

Clang [contains information](http://nosubstance.me/articles/2015-01-29-better-completion-for-cpp/) for current parameter and LSP servers [should provide it on signatureHelp](https://reviews.llvm.org/D38048#889568), since [the protocol supports](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp). It seems clangd is doing it, but ccls isn't.

**Comment by oblitum** [comment]
I imagine that on caret jumping to argument placeholder, which is at completion position after parentheses or comma, `signatureHelp` with current parameter information should be provided.

**Comment by MaskRay** [comment]
Interesting. I wonder why ccls doesn't provide the current parameter.

https://github.com/maskray/ccls/blob/master/src/messages/textDocument_signatureHelp.cc#L92

```cpp
  void ProcessOverloadCandidates(Sema &S, unsigned CurrentArg,
                                 OverloadCandidate *Candidates,
                                 unsigned NumCandidates
#if LLVM_VERSION_MAJOR >= 8
                                 ,
                                 SourceLocation OpenParLoc
#endif
                                 ) override {
    ls_sighelp.activeParameter = (int)CurrentArg; //////////// current active parameter
```

**Comment by oblitum** [comment]
> I don't know technically, will have to check coc sources.

Or rather, verify ccls isn't doing it from command line.

**Comment by oblitum** [comment]
Does it depend on Clang 8? I'm on Clang 7 from ArchLinux AUR.

**Comment by oblitum** [comment]
I've added `CXCursor_OverloadCandidate` with dynamic `CurrentParameter` in 3.7.

**Comment by oblitum** [comment]
There's no need for `CocJumpPlaceholder` to reproduce this part of the issue, just writing the function call manually (without snippet) shows difference of behavior:

![simplescreenrecorder](https://user-images.githubusercontent.com/1269815/50005343-34719580-ff91-11e8-9443-0a6b5e0c13e8.gif)

**Comment by oblitum** [comment]
> [It seems clangd is doing it, but ccls isn't](https://github.com/MaskRay/ccls/issues/161#issuecomment-447221214).

My bad on that, I haven't checked it myself. clangd behavior on my machine [is the same as ccls](https://github.com/neoclide/coc.nvim/issues/269#issuecomment-447609174) for the part of not highlighting current parameter (it does refresh the signature correctly though).

**Comment by oblitum** [comment]
This gif is simpler for showing that issue because it doesn't involve snippet usage:

![simplescreenrecorder](https://user-images.githubusercontent.com/1269815/50005343-34719580-ff91-11e8-9443-0a6b5e0c13e8.gif)

**Comment by oblitum** [comment]
This is getting rather confuse, can be coc -or-> clangd and ccls -or-> clang internals.

**Comment by oblitum** [comment]
Cache issue still remains on ccls though, even though minor.

**Comment by oblitum** [comment]
> This is getting rather confuse, can be coc -or-> clangd and ccls -or-> clang internals.

coc issue: https://github.com/neoclide/coc.nvim/issues/269#issuecomment-447613123.
