### ISSUE TITLE
ccls returns incorrect items for completion in Objective-C.

### ISSUE THREAD

**Issue by shoorlyne** [MaskRay/ccls#162]
On trying completion, while ccls is able to return the correct items, it also returns several other false positives -- that is, these items don't exist in that context but they appear in the completion list.

Here is what I mean:

<img width="570" alt="screen shot 2018-12-14 at 6 35 15 pm" src="https://user-images.githubusercontent.com/20250340/49998479-54c04500-ffcf-11e8-8e99-2c297cf8c8bd.png">

As one can see, items like `howmany` and `__has_warning` and some others below should not appear on the list while they do.

Any idea?

**Comment by MaskRay** [comment]
`__has_warning` is a builtin macro in the result of `c-index-test -code-completion-at=a.m:15:4 a.m -I/home/maskray/GNUstep/Library/Headers -I/usr/include/GNUstep -I/usr/lib/gcc/x86_64-linux-gnu/7/include`. It may surprise you but it is probably a valid completion item at the point. If you use server-side filtering and sorting of completion items, as you see, it has low precedence.

`howmany` is a macro defined in `/usr/include/x86_64-linux-gnu/sys/param.h`: `# define howmany(x, y)  (((x) + ((y) - 1)) / (y))`

**Comment by shoorlyne** [comment]
Thanks for your explanation. Much appreciated!
