### ISSUE TITLE
semantic highlighting - vim support

### ISSUE THREAD

**Issue by LeonSkoog** [MaskRay/ccls#163]
Hi @MaskRay,
do you know a vim's plugins which supports ccls's semantic highlighting and preprocessor skipped regions?

**Comment by MagB93** [comment]
I'm not @MaskRay, but for neovim there is [chromatica.nvim](https://github.com/arakashic/chromatica.nvim). Maybe this is what you're looking for.

**Comment by LeonSkoog** [comment]
As far as I know [chromatica.nvim](https://github.com/arakashic/chromatica.nvim) doesn't support 'preprocessor skipped regions' feature.
It's a killer feature for me. I'm working on big project with a huge numbers of #if def 

I've tried [DyeVim](https://github.com/davits/DyeVim) , it works great but it's based on YCM which has some limitations

**Comment by krzbe** [comment]
I've made simple plugin for marking inactive regions, it works with cquery but shouldn't be hard to make it working also with ccls I believe (did not tried yet). Works with vim and neovim. It is not perfect as highlighting in vim is limited comparing to neovim. Here is a link to the plugin: https://github.com/krzbe/vim-lsp-inactive-regions.

**Comment by jackguo380** [comment]
@LeonSkoog I just completed one: https://github.com/jackguo380/vim-lsp-cxx-highlight like @krzbe's plugin it is based on vim-lsp. I have been testing out the plugin at work and so far it has been working pretty well with ccls for a C++14 code base. Please let me know if it works well for you.

Also @MaskRay could you please explain what `symbol.id` does, is it related to incremental highlighting? I have highlighting working correctly without it but there is probably room for optimization (currently for ccls/src/indexer.cc it takes ~0.4s to highlight).

**Comment by MaskRay** [comment]
> could you please explain what symbol.id does,

Every symbol is assigned an `uint64_t` ID.

> but there is probably room for optimization (currently for ccls/src/indexer.cc it takes ~0.4s to highlight).

The issue is on the client side but I don't think there is much can be improved. The ccls server spends no more than tens of milliseconds to collect the `$ccls/publishSemanticHighlight` information.

**Comment by jackguo380** [comment]
Sorry I didn't explain it that well but the 0.4s I am referring to is the parsing that happens in my plugin not anything to do with ccls. The issue I am running into is that vimscript is quite slow so I am looking for ways to improve the algorithm to make up for it.

> Every symbol is assigned an uint64_t ID.

How unique is this ID?

Say I have this line:
```cpp
std::string s = std::string(a) + std::string(b);
```
Would each `string` get its own ID or would they have the same ID?

Do the IDs stay the same after the file is modified (E.g. inserting a line before that line)?

**Comment by MaskRay** [comment]
Clang USR: Unified Symbol Resolution https://clang.llvm.org/doxygen/group__CINDEX__CURSOR__XREF.html

In `std::string s = std::string(a) + std::string(b);`

`std::string` -> `c:@N@std@N@__cxx11@T@string` -> hased to an `uint64_t` in ccls

`CINDEXTEST_INDEXLOCALSYMBOLS=1 c-index-test -index-file-full a.cc`

**Comment by jackguo380** [comment]
I see, that may not be of much help for highlighting then. Thanks though.

**Comment by LeonSkoog** [comment]
@jackguo380  Wow! Your plugin looks and works great! 
Thanks you!

**Comment by LeonSkoog** [comment]
Hi @MaskRay  and @jackguo380 ,
I would like to thank you for your hard work! 
Thanks to you, I can use VIM as an IDE for my daily CPP development. 

Should I close the ticket? 
@jackguo380's plugin covering my needs
