### ISSUE TITLE
CMake build issues

### ISSUE THREAD

**Issue by kkartaltepe** [MaskRay/ccls#164]
CMakeLists.txt reports minimum version as 3.1, Build documentation reports minimum version as 3.8

`DownloadAndExtractClang.cmake` downloads version 7.0.0, on cmake 3.8.0-rc4 fails to build as `CMakeLists.txt` requires version 6.0.0. Looking at `FindClang.cmake` I assume this is just how `find_package_handle_standard_args` works when you dont specify a version file as described in https://cmake.org/cmake/help/v3.3/command/find_package.html#command:find_package (near `When the [version] argument is given Config`)

**Comment by MaskRay** [comment]
Thanks. Raised cmake_minimum_required to 3.8, which is for C++17 support `set_property(TARGET ccls PROPERTY CXX_STANDARD 17)`
