### ISSUE TITLE
Remove win10 dependence

### ISSUE THREAD

**Issue by kkartaltepe** [MaskRay/ccls#165]
Currently the CMakeLists.txt manually links against `mincore.lib`. I'm not sure why this library was chosen as it forces a dependence on the win10 only api shim. You can simply replace this linkage with `version.lib` to produce an executable that is fully functional on all platforms (to my knowledge).

**Comment by kkartaltepe** [comment]
Interestingly, the MSDN on the troublesome functions is incorrect...
https://docs.microsoft.com/en-us/windows/desktop/api/winver/nf-winver-getfileversioninfosizew
reports it depends on the older `Api-ms-win-core-version-l1-1-0.dll`, however when compiled with the current version of VS2017 and 10.0.17763.0 win10 SDK it links against `Api-ms-win-core-version-l1-1-1.dll`.

**Comment by MaskRay** [comment]
`target_link_libraries(ccls PRIVATE Mincore.lib)` was added in #118 

I don't have a Windows box to test so have to mention the reporter @DsoTsin ...

**Comment by MaskRay** [comment]
So is it still relevant? Which system are you using? Does this `mincore.lib` have downsides? Sorry if I am asking silly questions as I am very unfamiliar with this platform. I'll incline to close it for now, but feel free to reopen it if you got more information.

**Comment by DsoTsin** [comment]
> `target_link_libraries(ccls PRIVATE Mincore.lib)` was added in #118
> 
> I don't have a Windows box to test so have to mention the reporter @DsoTsin ...

MinCore.lib is the dependency from LLVM(Windows version). If version.lib is ok to link with, you can replace MinCore.lib.

**Comment by kkartaltepe** [comment]
> So is it still relevant?

Presumably as long as you still link mincore

> Which system are you using?

This was tested on a win 8.1 machine, with the compiler and windows SDK mentioned above. However I have since stopped using windows 8.1.

> Does this `mincore.lib` have downsides?

Other than making the resultant library win10 only (maybe there is a way around this) I doubt it. There were only like 1 or 2 calls into this library which were also provided by the version.lib library mentioned. DsoTsin mentions this library was chosen as it was used by LLVM so if future calls into this library might be done by LLVM code, it may be safer to use mincore.
