### ISSUE TITLE
User defined variables not in completions

### ISSUE THREAD

**Issue by MarkGreeny** [MaskRay/ccls#167]
Hi,

in the code

```C++
#include <stddef.h>
int main() {
  int xal =32;
  xa
}
```

when typing `xa`, the option `xal` is not in the completion list. Is this intended behavior? Note that options from stddef are in the list. Note that

```
clang++ -cc1 -code-completion-at bla.cpp:4:4 bla.cpp
```
returns

> COMPLETION: xal : [#int#]xal

which indicates it should work. What could be my mistake?

I am using Neovim-Languager-Server 

I am adding that I built by

```
git clone --depth=1 --recursive https://github.com/MaskRay/ccls
cd ccls
cmake -H. -BRelease
cmake --build Release
```

**Comment by MaskRay** [comment]
> I am using Neovim-Languager-Server

Did you mean LanguageClient-neovim? You'll check out its document to configure

>  Integrated with deoplete or ncm2. Or with vim built-in omnifunc"
