### ISSUE TITLE
ccls assumes cc is clang

### ISSUE THREAD

**Issue by innerout** [MaskRay/ccls#17]
After properly setting up ccls for my project i got a problem from ccls server.
It assumes that cc is clang while on my system it is gcc and it passes some arguments like
``` -resource-dir=/usr/lib/clang/6.0.0, -fspell-checking, -fparse-all-comments, -working-directory ``` 
that gcc does not support and eventually lsp-stderr has this ```libclang crash detected during parsing```

**Comment by MaskRay** [comment]
Arch Linux `aur/ccls-git` is broken. Don't use clang 6.0.0-1

ccls uses clang api to index files. it has nothing to do with gcc

**Comment by innerout** [comment]
What should i do? Download the master branch?
