### ISSUE TITLE
100% CPU usage when reading VTK codebase

### ISSUE THREAD

**Issue by MarkGreeny** [MaskRay/ccls#174]
When reading the codebase of [vtk](https://github.com/Kitware/VTK), there is a 100% CPU usage. I read [this](https://github.com/MaskRay/ccls/issues/149) issue, where you noted that using `compile_commands.json` should be prefered to using `.ccls`file. Please note that I had done so. The `compile_commands.json` file was generated by cmake, using the `CMakeLists.txt` provided on the vtk repo.

I have installed ccls via

```
git clone --depth=1 --recursive https://github.com/MaskRay/ccls
cd ccls
cmake -H. -BRelease
cmake --build Release
```

Is it just the case that with this particular codebase, CPU demands are so high? Or am I doing something wrong? I thank you in advance. I do enjoy this project.

Adding I am running Ubuntu.

**Comment by MaskRay** [comment]
I can index the project with `compile_commands.json`
```
git clone https://github.com/Kitware/VTK
cd VTK
cmake -GNinja -H. -BDebug -DCMAKE_BUILD_TYPE=Debug -CMAKE_EXPORT_COMPILE_COMMANDS=On
ln -s Debug/compile_commands.json
ninja -C Debug  # there are some generated files in the build directory. Build them before indexing
ccls -index .
```

```
entries:  4766
pending:     0
```

**Comment by MarkGreeny** [comment]
@MaskRay Dear friend, thank you for such a swift response. I have not explicitly tried to index the codebase using `ccls -index .' Previously this was done implicitly by the client. I have now done so, and have seen that the problem is that my machine is very slow, and nothing more. Before, CPU usage was 100% for 5 minutes, so I assumed something was wrong. Now, I could see the progress (pending). After good 10 minutes, the codebase was indexed and everything works as expected. In short, the problem was my non-knowing and the fact that my machine is very old (and slow). Again, thank you and sorry for bothering you. This is a great project!
