### ISSUE TITLE
No more quickfixes

### ISSUE THREAD

**Issue by oblitum** [MaskRay/ccls#182]
As reported on coc.nvim gitter channel, ccls used to work when coc sent request on code action about quickfixes. It works on latest ccls release, doesn't work on lastest commit anymore.

**Comment by MaskRay** [comment]
Fixed in 0.20181225.2

**Comment by oblitum** [comment]
I tested on lastest master commit, it's same commit as that release.

**Comment by oblitum** [comment]
Ops, sorry, I was grabbing some cache not latest. It's fixed on tip.
