### ISSUE TITLE
%h %hpp not being applied to headers

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#185]
I'm testing the latest master as of today, and the `%h %hpp` options are not being applied, at least not all the time.

I've attached a test setup [cclstest.tar.gz](https://github.com/MaskRay/ccls/files/2717700/cclstest.tar.gz).  If you start Emacs with the header file as an argument to Emacs then the extra arguments are properly assigned.  But if you visit the file from within Emacs, then the extra arguments are not applied.  I've attached a test environment; if I run it like this:

```
cd /tmp
tar xzf cclstest.tar.gz
emacs -Q -l ccls-test.el
C-x C-f /tmp/cclstest/src/header.h
```

You'll see that `size_t` is not a known type, and if you check `/tmp/ccls-test.out` you'll see that although the `%h %hpp` is recognized it's not applied to the compile line when the session for `header.h` is created.  I did a little debugging and I can see that ProjectProcessor::Process() is never invoked for header files that are visited, it's only invoked for source files.

**Comment by MaskRay** [comment]
Fixed..

**Comment by madscientist** [comment]
Thanks for the quick response... did you push this?  I don't see any new commits in GitHub.  Cheers!
