### ISSUE TITLE
%h and %hpp not applied when initialBlacklist is "."

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#187]
My example in #185 is working, but if I modify it to add `index.initialBlacklist` set to `["."]` so that nothing is indexed by default, it again fails to correctly index header files.

In my example from #185 when I look at the log I now see an appropriate compile line:

```
preamble     sema_manager.cc:717 I create session for /tmp/cclstest/src/header.h
 gcc -I/tmp/cclstest/inc -o source.o -c /tmp/cclstest/src/source.c --include=global.h -working-directory=/tmp/cclstest/src
```

which includes the `--include` line and builds with `gcc` as I'd expect.

However, if I disable all indexing as in this example [cclstest.tar.gz](https://github.com/MaskRay/ccls/files/2720079/cclstest.tar.gz) by adding this to `ccls-test.el`:

```
  (setq ccls-initialization-options '(:index (:initialBlacklist ("."))))
```

then I get truly strange output for the compile line of the header file:

```
preamble     sema_manager.cc:717 I create session for /tmp/cclstest/src/header.h
 %clang -xobjective-c++-header /tmp/cclstest/src/header.h
indexer1         pipeline.cc:323 I parse /tmp/cclstest/src/header.h
 %clang -xobjective-c++-header /tmp/cclstest/src/header.h
indexer1         pipeline.cc:361 I store index for /tmp/cclstest/src/header.h (delta: 0)
```

Note that none of the options from the `compile_commands.json` are provided and I don't know where the `-xobjective-c++-header` came from or why it's showing  clang instead of GCC.

**Comment by MaskRay** [comment]
...amended master and uploaded tag 0.20181225.3 which fixes the issue.

**Comment by madscientist** [comment]
Thanks, it seems to be working now!
