### ISSUE TITLE
Getting function signature preview

### ISSUE THREAD

**Issue by MarkGreeny** [MaskRay/ccls#192]
First of all, ccls is amazing, I use it every day. Having setup

```vim
nn <silent> K :call LanguageClient#textDocument_hover()<cr>
```

and when using it with [pyls](https://github.com/palantir/python-language-server) it looks like this (figure 1):
![image](https://user-images.githubusercontent.com/40479001/50731357-d173b880-1162-11e9-95bd-f66877c3d489.png)

This is very useful, when one does not remember the signature.

Please note when I do this with **ccls**
![image](https://user-images.githubusercontent.com/40479001/50731382-65458480-1163-11e9-8734-75b96e54e721.png)

nothing appears. Only **after** the function call is completed
![image](https://user-images.githubusercontent.com/40479001/50731390-84dcad00-1163-11e9-8a9d-e09022b56abd.png)

we get the same result as in figure 1 above. But at that time, we do not need it anymore. I hope I have made my question clear:

Is it possible to have `hover`display the function signature **before** completing the function call? Meaning, like in figure 1.

Also, is there a different intended way to go about this? I wish for this feature as I cannot get the snippets to work properly.

Again, thank you for this project, i use it daily, it enables me to keep my work in vim, even on a large codebase.

**Comment by MaskRay** [comment]
> Is it possible to have hoverdisplay the function signature before completing the function call? Meaning, like in figure 1.

You may check out `textDocument/completion` and `textDocument/signatureHelp`.

`foo(int a) -> void` (`CompletionItem::label`) is a completion item in the result of `textDocument/completion`.

If you have multiple `foo` overloads, use `textDocument/signatureHelp`.

**Comment by MarkGreeny** [comment]
@MaskRay Thank you for the response. I will look into the completion option. Please allow me to ask a followup to your answer. You instruct that I should use `textDocument/signatureHelp`. Please note that I had tried this like so

```vim
function! LanguageClient#textDocument_signatureHelp(...) abort
    let l:params = {
                \ 'filename': LSP#filename(),
                \ 'line': LSP#line(),
                \ 'character': LSP#character(),
                \ 'handle': v:true,
                \ }
    call extend(l:params, a:0 >= 1 ? a:1 : {})
    let l:Callback = a:0 >= 2 ? a:2 : v:null
    return LanguageClient#Call('textDocument/signatureHelp', l:params, l:Callback)
endfunction
```

which is what comes implemented with the client. But I get no results back. Is there a different way the Language client should call?

To phrase my question differently: The above comes implemented with the Client, yet when used, it gives no results, nothing is returned. Is this expected on the ccls side? If not, than there is a bug in the client and I will ask there.

**Comment by MaskRay** [comment]
`textDocument/signatureHelp` is only available when you have typed `(` (e.g. `foo(|`). There is no result in `foo|`.

`textDocument/completion` may be the closest thing you can get when before `(` is typed. You can check all completion items and find the one whose label **exactly matches** the typed string.

For smaller projects, you may set [`index.onChange`](https://github.com/MaskRay/ccls/wiki/Customization#indexonchange) to true and you'll get on-the-fly `textDocument/hover` (by default the document is only indexed after `textDocument/{didOpen,didSave}`)
