### ISSUE TITLE
void-linux package request

### ISSUE THREAD

**Issue by ndowens** [MaskRay/ccls#193]
`❰ndowens❙/pkgs/hostdir/sources/ccls-0.20181225.3/ccls-0.20181225.3(git:ccls)❱✔≻ ccls --index=.
LLVMSymbolizer: error reading file: No such file or directory
#0 0x0000562fd58f6eba (ccls+0x1384eba)
#1 0x0000562fd58f5314 (ccls+0x1383314)
#2 0x0000562fd58f5495 (ccls+0x1383495)
#3 0x00007f260512b660 __restore_rt (/usr/lib/libpthread.so.0+0x12660)
#4 0x0000562fd58eae08 (ccls+0x1378e08)
#5 0x0000562fd56d8614 (ccls+0x1166614)
#6 0x0000562fd55c560f (ccls+0x105360f)
#7 0x0000562fd55c6568 (ccls+0x1054568)
#8 0x0000562fd55da465 (ccls+0x1068465)
#9 0x0000562fd553742a (ccls+0xfc542a)
#10 0x0000562fd5542500 (ccls+0xfd0500)
#11 0x0000562fd47ac7c3 (ccls+0x23a7c3)
#12 0x0000562fd47b2f55 (ccls+0x240f55)
#13 0x0000562fd48311f0 (ccls+0x2bf1f0)
#14 0x0000562fd4833699 (ccls+0x2c1699)
#15 0x0000562fd479bdac (ccls+0x229dac)
#16 0x0000562fd475bafd (ccls+0x1e9afd)
#17 0x00007f2604f7a09b __libc_start_main (/usr/lib/libc.so.6+0x2409b)
#18 0x0000562fd475ebfa (ccls+0x1ecbfa)
fish: “ccls --index=.” terminated by signal SIGSEGV (Address boundary error)`

cmake compile flags:
-DSYSTEM_CLANG=ON -DCMAKE_PREFIX_PATH=${XBPS_CROSS_BASE}/usr/lib/llvm/7"

**Comment by MaskRay** [comment]
> LLVMSymbolizer: error reading file: No such file or directory

Can you put `llvm-symbolizer` in a `PATH` directory so that the stack trace can be symbolized?

https://github.com/llvm-mirror/llvm/tree/master/lib/Support/Unix/Signals.inc#L557

I assume `${XBPS_CROSS_BASE}/usr/lib/llvm/7` is where you install llvm. Some information will be useful:

* llvm version, if it was built with `-DLLVM_ENABLE_RTTI=ON` (read https://github.com/MaskRay/ccls/wiki/Build#cmake-options)
* `readelf -d Release/ccls`
* If system clang and ccls are built with musl
*

**Comment by ndowens** [comment]
llvm ver: 7, no RTTI=ON


`❰ndowens❙/pkgs/hostdir/sources/ccls-0.20181225.3/ccls-0.20181225.3(git:ccls)❱✔≻ readelf -d ccls 

Dynamic section at offset 0x1808c20 contains 34 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libncursesw.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libformw.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000c (INIT)               0x1d4000
 0x000000000000000d (FINI)               0x13861d0
 0x0000000000000019 (INIT_ARRAY)         0x171bde8
 0x000000000000001b (INIT_ARRAYSZ)       176 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x171be98
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x340
 0x0000000000000005 (STRTAB)             0x27d0
 0x0000000000000006 (SYMTAB)             0x4f0
 0x000000000000000a (STRSZ)              9476 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x180a000
 0x0000000000000002 (PLTRELSZ)           7056 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x1d1e80
 0x0000000000000007 (RELA)               0x5230
 0x0000000000000008 (RELASZ)             1887312 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffb (FLAGS_1)            Flags: PIE
 0x000000006ffffffe (VERNEED)            0x4fc0
 0x000000006fffffff (VERNEEDNUM)         7
 0x000000006ffffff0 (VERSYM)             0x4cd4
 0x000000006ffffff9 (RELACOUNT)          76786
 0x0000000000000000 (NULL)               0x0
`
No musl, all glibc

**Comment by ndowens** [comment]
Awesome, figured out what was wrong. Didn't have the RTTI on . Sorry to waste your time

**Comment by MaskRay** [comment]
> Didn't have the RTTI on

Are you still investigating the issue?

> Also, other Archs besides x86-64 can not find clang, when I have llvm, clang and libllvm7 set as deps

Sorry I don't understand. Can you elaborate?

**Comment by ndowens** [comment]
Didn't have the RTTI on

Are you still investigating the issue?

It builds on x86_64, and i686  but not others because it says clang can not be found
