### ISSUE TITLE
missing "cd" in build instructions

### ISSUE THREAD

**Issue by kookjr** [MaskRay/ccls#194]
From the [build](https://github.com/MaskRay/ccls/wiki/Build) page, the second and third instructions fail because there is a missing cd command. It should read (cd line added):

    git clone --depth=1 --recursive https://github.com/MaskRay/ccls
    cd ccls
    cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release
    cmake --build Release

**Comment by MaskRay** [comment]
Thanks. Fixed!

You can actually fix it by yourself. The wiki is publicly editable.
