### ISSUE TITLE
CMake finds gcc-5, although gcc-7 is also available

### ISSUE THREAD

**Issue by root42** [MaskRay/ccls#195]
You include clang 7.0.0 when running cmake, but it does not seem to have the optional header:

```
In file included from /home/aschmitz/Programs/ccls/src/position.hh:18:0,
                 from /home/aschmitz/Programs/ccls/src/clang_tu.hh:18,
                 from /home/aschmitz/Programs/ccls/src/clang_tu.cc:16:
/home/aschmitz/Programs/ccls/src/utils.hh:18:20: fatal error: optional: No such file or directory
compilation terminated.
```

**Comment by root42** [comment]
Edited title. Bug is actually: wrong system compiler is being used.

**Comment by MaskRay** [comment]
Can you execute the following 3 commands and compare the results?

* `g++-5 -fsyntax-only -v -xc++ /dev/null`
* `g++-7 -fsyntax-only -v -xc++ /dev/null`
* `clang -fsyntax-only -v -xc++ /dev/null` (replace `clang` with `Clang_EXECUTABLE` in `Release/CMakeCache.txt`)
