### ISSUE TITLE
How to build llvm + clang on win10 1809?

### ISSUE THREAD

**Issue by 3038922** [MaskRay/ccls#198]
Sorry, I'm a novice.
I try to download git clone llvm.But he's too slow.
So I downloaded Pre-Built Binaries: Windows (64-bit)
Is there a simple way to use VC header files and libraries directly?
![image](https://user-images.githubusercontent.com/33926386/50980163-01d89f80-1533-11e9-89e2-fd87bf739917.png)

**Comment by MaskRay** [comment]
The prebuilt Windows archives on releases.llvm.org do not provide clang/llvm C++ header files, thus the default `-DSYSTEM_CLANG=OFF` is unusable. See https://github.com/MaskRay/ccls/wiki/Build#windows for two alternatives.

Please provide more description of your environment: compiler version, cmake command line. Diagnostics in a textual form are better than a screenshot. You may refer to some other issues.

**Comment by 3038922** [comment]
I only have msbuild(VS2019) and arm-gcc compiler. I want to use CCLS for embedded c++ development.
 used - DSYSTEM_CLANG=ON mainly because I downloaded LLVM slowly. I could not recompile LLVM.

git clone --depth=1 --recursive https://github.com/MaskRay/ccls
cd ccls
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DSYSTEM_CLANG=ON -DCMAKE_INSTALL_PREFIX="C:/Program Files/LLVM"
cmake --build Release

**Comment by MaskRay** [comment]
Please read https://github.com/MaskRay/ccls/wiki/Build `-DSYSTEM_CLANG=on` and some examples. You need `-DCMAKE_PREFIX_PATH=` when `-DSYSTEM_CLANG=on` is specified.

**Comment by zekrom-vale** [comment]
I give up I have no clue how to follow those instructions when I don't have `ninja` and `pacman`.  I am so lost.  I only wanted to use this to lint...
