### ISSUE TITLE
Error occur during linking.

### ISSUE THREAD

**Issue by ZWindL** [MaskRay/ccls#20]
OS: Archlinux With testing on and all up to date
llvm packages and version: 
```
local/clang-compiler-rt-svn 7.0.0svn_r334049-1 (llvm-toolchain-svn)
    The "compiler-rt" set of runtime libraries for Clang and LLVM
local/clang-svn 7.0.0svn_r334049-1 (llvm-toolchain-svn)
    C language family frontend for LLVM
local/clang-tools-extra-svn 7.0.0svn_r334049-1 (llvm-toolchain-svn)
    Standalone tools for Clang: syntax checking, formatting, refactoring, etc.
local/lib32-llvm-libs 6.0.0-1
    Low Level Virtual Machine (runtime library)(32-bit)
local/lld-svn 7.0.0svn_r334049-1 (llvm-toolchain-svn)
    A linker from the LLVM project
local/llvm-libs-svn 7.0.0svn_r334049-1 (llvm-toolchain-svn)
    The LLVM Compiler Infrastructure (runtime libraries)
local/llvm-svn 7.0.0svn_r334049-1 (llvm-toolchain-svn)
    The LLVM Compiler Infrastructure
```

When I installing `ccls-git` from aur, the error below occurred.
```
[100%] Linking CXX executable ccls
/usr/bin/ld: 找不到 -lLLVM_LIBRARY-NOTFOUND
collect2: 错误：ld 返回 1
make[2]: *** [CMakeFiles/ccls.dir/build.make:964：ccls] 错误 1
make[1]: *** [CMakeFiles/Makefile2:68：CMakeFiles/ccls.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2
```
I don't know what to do now. :(

**Comment by Synray** [comment]
See #14, it's most likely a problem with Arch's clang.
Try building from source with this:
```sh
cmake -H. -Brelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld -DCMAKE_EXPORT_COMPILE_COMMANDS=On
```
Worked for me and I'm also on Arch.
That will download clang binaries and use them. Make sure you have ninja installed from pacman.

**Comment by ZWindL** [comment]
@Synray Thanks, I will try it. btw. I know that issue, and I switched clang from `clang` to `clang-svn` from repo `[clang-svn]`, the issue still exists. Hope Arch will fix this.

**Comment by Synray** [comment]
@ZWindL it might work to replace `-G Ninja` with `-G "Unix Makefiles"`, I think because `makepkg` uses `make` internally.

**Comment by ZWindL** [comment]
@Synray Good, it works, though it has some conflict files, I'll try to figure that out.

**Comment by ZWindL** [comment]
@MaskRay I will make a test on 7.0.0 these days. btw. The clang 7 package is not official build package, it's from third-party repository.

**Comment by ZWindL** [comment]
Same issue occurred when linking the project using clang 7 from repo `llvm-svn`
```
...
[100%] Linking CXX executable ccls
/usr/bin/ld: 找不到 -lLLVM_LIBRARY-NOTFOUND
```

**Comment by ZWindL** [comment]
It only occurred in the `ccls-git` packaging process, not appeared in the manually building process.

**Comment by MaskRay** [comment]
If `-DUSE_SHARED_LLVM=on` (see https://github.com/MaskRay/ccls/wiki/Build `-DUSE_SHARED_LLVM=on`) is used, you should find `libLLVM.so` in system library directories or `CMAKE_PREFIX_PATH` directories.

The bundled clang+llvm archives downloaded from releases.llvm.org contain `libLLVMSupport.a libLLVMDemangle.a ...` but not `libLLVM.so`

**Comment by ZWindL** [comment]
I see, seems the `llvm-svn` package only contains a `/usr/lib/libLLVM.so.7.0.0svn-r334657 -> libLLVM-7svn.so` instead of `libLLVM.so`, maybe that's why the `ccls-git` couldn't find it.

**Comment by MaskRay** [comment]
Can you try `ln -s /usr/lib/libLLVM.so.7.0.0svn-r334657 /usr/local/lib/libLLVM.so` and continue using `-DUSE_SHARED_LLVM=on` (basically `-lLLVM`)

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/issues/25#issuecomment-403204474

**Comment by ZWindL** [comment]
It reports a different error
```[100%] Linking CXX executable ccls
CMakeFiles/ccls.dir/src/clang_utils.cc.o：在函数‘FileName[abi:cxx11](void*)’中：
clang_utils.cc:(.text+0x322)：对‘clang_File_tryGetRealPathName’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [CMakeFiles/ccls.dir/build.make:954：ccls] 错误 1
make[1]: *** [CMakeFiles/Makefile2:68：CMakeFiles/ccls.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2
```

**Comment by MaskRay** [comment]
`clang_File_tryGetRealPathName` is no longer used, along with all other libclang functions. Can you check if `llvm-libs-svn` works now?

**Comment by ZWindL** [comment]
I created a linking file `/usr/local/libLLVM.so` and the installation goes smoothly. But it still can't works well, here's the [logfile](https://ptpb.pw/geVt) BTW. I think the most useful line is 
```
22:26:54 WARN main src/languageclient.rs:2091 Failed to start language server automatically. No such file or directory (os error 2)
```
I can't figure out what's that mean.

This log file is directly created by `nvim` with options like that:
```
let g:LanguageClient_loggingLevel = 'DEBUG'
let g:LanguageClient_loggingFile = '/tmp/LanguageClient.log'
let g:LanguageClient_serverStderr = '/tmp/LanguageServer.log'
```

**Comment by ZWindL** [comment]
Arch just updated `clang` version to `6.0.1`, I'm trying to build it with `6.0.1` version of `clang`.

**Comment by MaskRay** [comment]
See https://github.com/MaskRay/ccls/issues/30#issuecomment-415594762

The SIGSEGV has been fixed.
