### ISSUE TITLE
How to deal with Linux Kernel modules

### ISSUE THREAD

**Issue by RobertBuhren** [MaskRay/ccls#201]
Hi,
I'm working on a linux kernel module and I can't get ccls to work with it (clangd works fine). 
My kernel resides in "root/linux" and the module in "root/mymodule". I created "compile_commands.json" for both the kernel and the module using "bear". 

ccls works fine on the linux kernel itself, but within the module it can't find the include paths. 
The makefile of the modules does a "cd ../linux" before calling the compiler. So any include path inside the kernel module's "compile_commands.json" is relative to the "root/linux" directory. 

Inside the module, ccls fails to find the headers files as the paths in my "compile_commands.json" are not valid within the "root/mymodule" directory.

What's the correct way to handle these situation? 

Thanks in advance,

Robert

**Comment by MaskRay** [comment]
See https://github.com/MaskRay/ccls/wiki/Project-Setup#linux-kernel

If generating `compile_commands.json` is tricky, you may consider using `.ccls`: https://github.com/MaskRay/ccls/issues/179#issuecomment-450060019

**Comment by RobertBuhren** [comment]
The wiki entries explains howto setup ccls for the linux kernel. This is not my issue here. ccls works fine for the linux kernel. However, ccls fails with kernel **modules** that are build **outside** the kernel tree. I looked at ```.ccls```. but I fail to see what options should help here (except from manually specifying all include folders relative to the module directory).

**Comment by MaskRay** [comment]
Replied too fast :( I've edited my comment.

I'm pretty sure this is a client-side issue. Can you provide more information about your environment? OS, editor, language client, etc

**Comment by RobertBuhren** [comment]
Sure:
Arch Linux
NVIM v.0.3.3
nvim-coc 0.0.46
bear 2.3.13

Here's an example entry from my "compile_commands.json"
```
    {
        "arguments": [
            "gcc",
            "-c",
            "-Wp,-MD,/home/robert/kernel/ccp_test/.ccp_test.mod.o.d",
            "-nostdinc",
            "-isystem",
            "/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include",
            "-I./arch/x86/include",
            "-I./arch/x86/include/generated",
            "-I./include",
            "-I./arch/x86/include/uapi",
            "-I./arch/x86/include/generated/uapi",
            "-I./include/uapi",
            "-I./include/generated/uapi",
            "-include",
            "./include/linux/kconfig.h",
            "-include",
            "./include/linux/compiler_types.h",
            "-D__KERNEL__",
            "-Wall",
            "-Wundef",
            "-Wstrict-prototypes",
            "-Wno-trigraphs",
            "-fno-strict-aliasing",
            "-fno-common",
            "-fshort-wchar",
            "-Werror-implicit-function-declaration",
            "-Wno-format-security",
            "-std=gnu89",
            "-fno-PIE",
            "-DCC_HAVE_ASM_GOTO",
            "-mno-sse",
            "-mno-mmx",
            "-mno-sse2",
            "-mno-3dnow",
            "-mno-avx",
            "-m64",
            "-falign-jumps=1",
            "-falign-loops=1",
            "-mno-80387",
            "-mno-fp-ret-in-387",
            "-mpreferred-stack-boundary=3",
            "-mskip-rax-setup",
            "-mtune=generic",
            "-mno-red-zone",
            "-mcmodel=kernel",
            "-funit-at-a-time",
            "-DCONFIG_AS_CFI=1",
            "-DCONFIG_AS_CFI_SIGNAL_FRAME=1",
            "-DCONFIG_AS_CFI_SECTIONS=1",
            "-DCONFIG_AS_FXSAVEQ=1",
            "-DCONFIG_AS_SSSE3=1",
            "-DCONFIG_AS_CRC32=1",
            "-DCONFIG_AS_AVX=1",
            "-DCONFIG_AS_AVX2=1",
            "-DCONFIG_AS_AVX512=1",
            "-DCONFIG_AS_SHA1_NI=1",
            "-DCONFIG_AS_SHA256_NI=1",
            "-pipe",
            "-Wno-sign-compare",
            "-fno-asynchronous-unwind-tables",
            "-mindirect-branch=thunk-extern",
            "-mindirect-branch-register",
            "-DRETPOLINE",
            "-fno-delete-null-pointer-checks",
            "-Wno-frame-address",
            "-Wno-format-truncation",
            "-Wno-format-overflow",
            "-Wno-int-in-bool-context",
            "-O2",
            "--param=allow-store-data-races=0",
            "-Wframe-larger-than=2048",
            "-fstack-protector-strong",
            "-Wno-unused-but-set-variable",
            "-Wno-unused-const-variable",
            "-fomit-frame-pointer",
            "-fno-var-tracking-assignments",
            "-g",
            "-gdwarf-4",
            "-Wdeclaration-after-statement",
            "-Wno-pointer-sign",
            "-Wno-stringop-truncation",
            "-fno-strict-overflow",
            "-fno-merge-all-constants",
            "-fmerge-constants",
            "-fno-stack-check",
            "-fconserve-stack",
            "-Werror=implicit-int",
            "-Werror=strict-prototypes",
            "-Werror=date-time",
            "-Werror=incompatible-pointer-types",
            "-Werror=designated-init",
            "-fmacro-prefix-map=./=",
            "-Wno-packed-not-aligned",
            "-DKBUILD_BASENAME=\"ccp_test.mod\"",
            "-DKBUILD_MODNAME=\"ccp_test\"",
            "-DMODULE",
            "-o",
            "/home/robert/kernel/ccp_test/ccp_test.mod.o",
            "../ccp_test/ccp_test.mod.c"
        ],
        "directory": "/home/robert/kernel/linux",
        "file": "../ccp_test/ccp_test.mod.c"
    },
```

IMHO: ccls should treat all path's relative to the directory specified in the "directory" entry of the json entry.

Regards,

Robert

**Comment by MaskRay** [comment]
> IMHO: ccls should treat all path's relative to the directory specified in the "directory" entry of the json entry.

ccls does that. For each `compile_commands.json` entry, it appends `-working-directory=` for that purpose.

Again, this is a client-side/configuration issue. You need to read how to enable workspace folders in your client.
