### ISSUE TITLE
Deleting releases

### ISSUE THREAD

**Issue by Mic92** [MaskRay/ccls#202]
It would be create if you would not delete tags as happened here: https://github.com/MaskRay/ccls/releases

Otherwise packaging ccls downstream becomes hard: https://github.com/NixOS/nixpkgs/pull/53888/checks?check_run_id=49440288

**Comment by MaskRay** [comment]
Thank you for porting it to NixOS (I've made some comments there). I'll be more considerate when deleting tags. I still do want to retire some broken tags with severe issues: maybe it can only be done when a newer release is pushed and gets stable.

**Comment by Mic92** [comment]
Sorry, but you deleted `0.20181225.7`. I will refer to commits for now.
