### ISSUE TITLE
ccls is reporting incorrect errors to flymake/flycheck in Emacs lsp-ui

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#204]
I'm not exactly sure where the fault lies here, but I just updated my ccls to the latest HEAD master and now I'm seeing flycheck and flymake report bogus errors in my C++ code, because classes that are definitely defined (in header files that are included) are being marked as unknown.

Unfortunately my attempts to create a standalone repro case have failed :frowning_face: 

I have a .cpp file with a syntax something like:

```
#include "Base.h"

class Derived : public Base
{...};
```

and when I visit this buffer in Emacs I get flycheck errors such as:

```
 Derived    4  24 error    4      ccls: expected class name (lsp-ui)
```

Since it says ccls, and I just updated ccls, I am filing this here.  However when I restarted my Emacs it automatically upgraded from ELPA so most likely lsp was updated as well.

I should point out that ccls does seem to have successfully parsed my files, though: if I set point on `Base` and run `xref-find-definition` then it successfully jumps over to the definition of that class in `Base.h`.  Also I don't see any weird ccls messages and the command line in the log file looks correct, etc.

Not sure where to go next for more info.

**Comment by madscientist** [comment]
I should point out that if I visit `Base.h` in Emacs, flycheck/flymake report no errors (and of course compiling the code succeeds!)

**Comment by madscientist** [comment]
Hmm, it's not just flycheck/flyspell.  I don't get symbol completion for the symbols obtained through included headers either, although it works for symbols I've forward-declared in the file rather than included their definition.  Something is definitely not right.

**Comment by MaskRay** [comment]
If you have both C and C++ files, and the project uses `.ccls`, it is possible that the command line options `a.h` are inferred from a C file and thus considered a C header.

If you are really certain that every `a.h` is valid C++ or you just want to get rid of these parsing errors (`expected class name`), add a line `%h -x c++-header` to `.ccls`

**Comment by MaskRay** [comment]
use a [shell script wrapper](https://github.com/MaskRay/ccls/wiki/Install#shell-script-wrapper)

**Comment by madscientist** [comment]
I really apologize for delays.  I'm so busy with getting a release out the door at $RealJob I'm just having to live with the flymake errors in my Emacs buffer for now :smile:  I will get to it this week...

I do enable log-file and v=0, by default, and all the output looks right to me.  I can cut and paste a directory directly from the `-I` arguments in the log and find the header files there.  Plus as I mentioned my attempts to make a simple repro case have failed.  It's all very mysterious.  I will track it down though!  I'm strongly motivated :grin:

**Comment by madscientist** [comment]
I finally delivered all my encryption work for $RealJob and have a chance to look into this.  I rebuilt from scratch using the latest master version but was not able to reproduce my problems: things are working well now.  I'll close this issue.  If I see it again I'll reopen with more details.

Thanks!
