### ISSUE TITLE
ccls crashes after some period of time

### ISSUE THREAD

**Issue by Yanpas** [MaskRay/ccls#205]
I rarely close vscode, usually when I come at work the next day I see that ccls has crashed.

Last log messages:
```
00:26:06 indexer0          indexer.cc:1304 E clang crashed for /home/yan/dev/trunk/.vscode/cclslog
00:26:07 indexer1          indexer.cc:1304 E clang crashed for /home/yan/dev/trunk/.vscode/cclslog
00:26:08 indexer1         pipeline.cc:323 I parse /home/yan/dev/trunk/.vscode
00:26:08 indexer0         pipeline.cc:121 I timestamp changed for /home/yan/dev/trunk/.vscode/cclslog
00:26:08 indexer0         pipeline.cc:323 I parse /home/yan/dev/trunk/.vscode/cclslog
00:26:09 indexer1          indexer.cc:1309 E failed to index /home/yan/dev/trunk/.vscode
00:26:13 indexer0          indexer.cc:1304 E clang crashed for /home/yan/dev/trunk/.vscode/cclslog
00:26:15 indexer1         pipeline.cc:121 I timestamp changed for /home/yan/dev/trunk/.vscode/cclslog
00:26:15 indexer1         pipeline.cc:323 I parse /home/yan/dev/trunk/.vscode/cclslog
00:26:19 indexer0         pipeline.cc:121 I timestamp changed for /home/yan/dev/trunk/.vscode/cclslog
00:26:19 indexer0         pipeline.cc:323 I parse /home/yan/dev/trunk/.vscode/cclslog
00:26:23 indexer1          indexer.cc:1304 E clang crashed for /home/yan/dev/trunk/.vscode/cclslog
00:26:57 indexer0         pipeline.cc:361 I store index for /home/yan/dev/trunk/.vscode/cclslog (delta: 1)
```

There were no stack trace in log and on each line logfile is mentioned for some reason instead of cpp files.

**Comment by MaskRay** [comment]
> I see that ccls has crashed.

I guess many indexer threads have crashed but the process is still alive.

> parse /home/yan/dev/trunk/.vscode

This is related to `workspace/didChangeWatchedFiles` (currently supported by VSCode and coc.nvim). HEAD should have been fixed but I'll need to check what vscode does when you save a file in the workspace.

The observed coc.nvim behavior is:

* it fires a `FileChangeType::Created` notification when an `IN_CREATE` event is received
* at this point the file is not on the disk and ccls thinks this index request actually deletes a file (thus it purges the empty index associated to the file => nothing happens)
* `IN_CLOSE_WRITE` event is received. I guess vscode defers the  `FileChangeType::Created` notification until this time point

**Comment by Yanpas** [comment]
ccls built with clang 7.0.1 shows it has from 1 to 5 jobs even if I don't do anything.

**Comment by MaskRay** [comment]
> ccls built with clang 7.0.1 shows it has from 1 to 5 jobs even if I don't do anything.

?

**Comment by Yanpas** [comment]
> > ccls built with clang 7.0.1 shows it has from 1 to 5 jobs even if I don't do anything.
>
> ?

You've said that clang 7.0.1 fixes some issue with infinite loop.

**Comment by MaskRay** [comment]
It is a bit tricky currently... The latest release should be more stable. The large patch number (7) reflects the instability of these newly-added features. I hope they'll stablize after the 0.20181225 release

I've switched to a very conservative workspace/didChangeWatchedFiles implementation:

```cpp
    std::string path = event.uri.GetPath();
    if ((g_config->cacheDirectory.size() &&
         StringRef(path).startswith(g_config->cacheDirectory)) ||
        lookupExtension(path).first == LanguageId::Unknown)
      return;
    for (std::string cur = path; cur.size(); cur = sys::path::parent_path(cur))
      if (cur[0] == '.')
        return;
```
