### ISSUE TITLE
Ccls suggests private members in autocompletion

### ISSUE THREAD

**Issue by Yanpas** [MaskRay/ccls#206]
![image](https://user-images.githubusercontent.com/7345761/51199078-eb519000-1906-11e9-82e3-9a45bf7c0a04.png)

```
struct A {
    void m1();
};

struct B : private A {
    void m2();
};

void foo () {
    B b;
    b.
```

**Comment by MaskRay** [comment]
This has been fixed in clang trunk (will be included in the next release 8)

llvm has a half-year release cadence. If everything goes well, there will be a final release in February, 2019 (see "Upcoming Releases" on https://llvm.org/)
