### ISSUE TITLE
Failed to start ccls with command "ccls".

### ISSUE THREAD

**Issue by ucasFL** [MaskRay/ccls#211]
I compile and configure ccls for vscode on Ubuntu 18.04 following the wiki. However, when start vscode, these error message appear: 
```
Failed to start ccls with command "ccls".
Couldn't start client ccls
```

**Comment by ucasFL** [comment]
I add ccls to PATH, the message above disappear, but it also cann't work: 
```
Language client is not ready yet

**Comment by cyberphysicalrobotics** [comment]
The followings are the way I was reporting my problem when ccls had segmentation fault.
This command will make .ccls-cache directory and index code. You can check if it works the size of directory will increase.
On the directory of ccls workspace which has .ccls file,
$ ccls --index=.

If you want to check if ccls has segmentation fault, you can use debug like the following.
$ gdb ccls
(gdb) run --index=.
When segmentation fault happens,
(gdb) bt
You can report your issue with backtrace.

**Comment by cyberphysicalrobotics** [comment]
You can make .ccls file on the project directory like the following. And then you can do "ccls --index=."

%compile_commands.json
%c -std=c11
%cpp -std=c++14
%cpp -stdlib=libc++
%c %cpp
%h %hpp
