### ISSUE TITLE
Where can I find arm-gcc8  Cross-compiling environment configuration tutorial under WINDOWS10?

### ISSUE THREAD

**Issue by 3038922** [MaskRay/ccls#212]
I'm a novice and I don't quite understand how to build it under WINDOWS.thank you.
The cross-compiling environment is a bit different. I tried the existing tutorials, but I couldn't.

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Build#windows
https://github.com/MaskRay/ccls/wiki/Project-Setup

> Where can I find arm-gcc8 Cross-compiling environment configuration

If your project uses `arm-linux-gnueabi-gcc`, e.g.

compile_commands.json
```javascript
[
    {
        "arguments": [ "arm-linux-gnueabi-g++", "-c", "-o", "a", "a.cc" ],
        "directory": "/tmp/c", 
        "file": "a.cc"
    }
]
```

The first argument (compiler driver) instructs the clangDriver library ccls uses to change target triple to ARM. You will see ARM related macros defined.

**Comment by 3038922** [comment]
build ccls still using "clang" or "msvc"?
