### ISSUE TITLE
Provide a mechanism to generate the flags for a particular file/project with arbitrary complexity

### ISSUE THREAD

**Issue by ElArtista** [MaskRay/ccls#222]
First of all thank you for your fantastic project!
I'm migrating my setup from vim + YouCompleteMe to vim + lsp client + lsp servers and ccls is the absolute beast of C family language servers!

The only thing i think its missing and i would love to have is the option to generate the build flags per file (or) project without having to generate compile_commands.json before.

For example see the following section of the YCM plugin regarding the .ycm_extra_conf.py script:
https://github.com/Valloric/YouCompleteMe#option-2-provide-the-flags-manually

Here is the example of my kind of config script that YCM did execute and was generating the list of arguments:

<details>
 <summary>Snippet</summary>

```
import os
import glob
import logging
import inspect
import subprocess

logger = logging.getLogger( __name__ )

def CSharpSolutionFile(filepath):
    logger.info('Got filepath value "' + filepath + '" in CSharpSolutionFile function')
    for root, dirs, files in os.walk(filepath):
        for file in files:
            if len(glob.glob(os.path.join(root, '*.sln'))) == 1:
                return os.path.join(root, file)

def FindFileInClosestParent(filename, filepath):
    for root, dirs, files in os.walk(filepath):
        #logger.info("FindFileInClosestParent: In root: " + root + ", with dirs: " + ','.join(dirs) + " and files: " + ','.join(files))
        for file in files:
            if file == filename:
                return os.path.join(root, file)
        break
    parent = os.path.abspath(os.path.join(root, os.pardir))
    if root != parent:
        return FindFileInClosestParent(filename, parent)
    else:
        return None

def IncludesFromMake(makecfg):
    # Retrieve makecfg relative path
    subproj_path = os.path.dirname(os.path.relpath(makecfg, os.getcwd()))
    # Handle top project case
    if subproj_path == "":
        subproj_path = "."
    logger.info("Using subproject: " + subproj_path)
    # Call makefile for include paths
    output = subprocess.Popen(["make", "showincpaths_" + subproj_path], stdout=subprocess.PIPE).communicate()[0]
    if output:
        # Convert it to string
        output = output.decode('utf8')
        # Take the first line and make space separated string a list
        incpaths = output.split('\n')[0].split()
        logger.info("Got include paths for subproject with config \"" + makecfg + "\"" + ": " + str(incpaths))
        # Make them absolute using the configuration file as a base
        #incs = map(lambda s : os.path.abspath(os.path.join(os.path.dirname(makecfg), s)), incs)
        return incpaths
    return []

def DefinesFromMake(makecfg):
    # Retrieve makecfg relative path
    subproj_path = os.path.dirname(os.path.relpath(makecfg, os.getcwd()))
    # Handle top project case
    if subproj_path == "":
        subproj_path = "."
    # Call makefile for include paths
    output = subprocess.Popen(["make", "showdefines_" + subproj_path], stdout=subprocess.PIPE).communicate()[0]
    if output:
        # Convert it to string
        output = output.decode('utf8')
        # Take the first line and make space separated string a list
        defines = output.split('\n')[0].strip().split()
        logger.info("Got defines for subproject with config \"" + makecfg + "\"" + ": " + str(defines))
        return defines
    return []

def FlagsForFile(filename, **kwargs):
    # Gather the source filetype
    data = kwargs['client_data']
    filetype = data['&filetype']

    # Debug
    #executable_dir = os.path.dirname(os.path.realpath(inspect.getfile(inspect.currentframe())))

    # Common flags
    flags = ['-Wall', '-Wextra']

    # Language variant specific flags
    lang_specific_flags = \
    {
        'cpp': ['-xc++', '-std=c++14'],
        'c'  : ['-xc']
    }
    flags.extend(lang_specific_flags[filetype])
    if os.name == 'nt':
        flags.append("--target=x86_64-w64-mingw32")

    # Gather include directories for given source file
    logger.info("Gathering include directories for file: " + filename)

    # Find closest project config file in parent directories
    start_search_path = os.path.dirname(filename)
    makecfg = FindFileInClosestParent("config.mk", start_search_path)
    if makecfg is not None:
        logger.info("Using configuration: " + makecfg)
        # Get subproject include search path list
        includes = IncludesFromMake(makecfg)
        # Construct include search path flags
        logger.info("Using includes: " + str(includes))
        for i in includes:
            flags.append('-I' + i)
        # Get subproject define list
        defines = DefinesFromMake(makecfg)
        for d in defines:
            flags.append('-D' + d)

    return {
        'flags': flags,
        'do_cache': True
    }
```
</details>
</br>

The kinda of functionality i'm seeking is really close to the existing 'compilationDatabaseCommand',
but the compile_commands.json that gets generated from this, cannot be created with generic contents that apply to all the project compilation units.

A plausible solution could be a similar 'cclsFileCommand' that could return a file in .ccls format that is way more flexible. Keep also in mind that different files under the same project folder (like different submodules) might use different compilation flags, so essentially this kind of command should be called for each c source that gets opened similar to how ycm_extra_conf.py works.

**Comment by MaskRay** [comment]
> but the compile_commands.json that gets generated from this, cannot be created with generic contents that apply to all the project compilation units.

If you use `compile_commands.json`, it does not need to be a complete listing. An entry for each subfolder (if its compile flags are different from its parent folder's) suffices. Compile flags for a file can be inferred from a file nearby.

Only entries in `compile_commands.json` will be indexed initially, unless you also have a `.ccls` to complement it.

There are cons and pros to provide a `.ycm_extra_conf.py` like mechanism. 
The [initialization option `compilationDatabaseCommand`](https://github.com/MaskRay/ccls/wiki/Customization#initialization-options) different from `.ycm_extra_conf.py` in these aspects:

* The latter is more flexible as files can be added dynamically.
* The former provides the full set of files to be indexed initially.

> Keep also in mind that different files under the same project folder (like different submodules) might use different compilation flags

https://github.com/MaskRay/ccls/wiki/Project-Setup#ccls-file Subfolders can also have `.ccls` files.

**Comment by ElArtista** [comment]
What i'm trying to avoid is having to generate -any- kind of configuration file that is project specific and inside my project's folder, that's why the compilationDatabaseCommand seems really the most suitable for my case.

> If you use compile_commands.json, it does not need to be a complete listing. An entry for each subfolder (if its compile flags are different from its parent folder's) suffices. Compile flags for a file can be inferred from a file nearby. 

Can you provide a minimal example of what a generic compile_commands.json could be? As far as I understand from here https://clang.llvm.org/docs/JSONCompilationDatabase.html, the command/arguments member should be a complete execution/compilation command for a specific unit. I do not understand how could i write something that applies over everything, could you explain?

**Comment by MaskRay** [comment]
Say your project is at `/tmp/c/` and it contains `/tmp/c/a.cc` `/tmp/c/b/b.cc` `/tmp/c/b/c.cc`

```zsh
% cat x
#!/bin/zsh
## Save this file at /tmp/c/x
print '
[{"arguments":["c++","-DB","-c","-o","b/b","b/b.cc"],"directory":"/tmp/c","file":"b/b.cc"},
 {"arguments":["c++","-c","-o","a","a.cc"],"directory":"/tmp/c","file":"a.cc"}]'
```

Set initialization option `{"compilationDatabaseCommand": "/tmp/c/x"}`

**Comment by ElArtista** [comment]
So if i get i correctly, if i provide only one compilation unit listing i will get inferred results for all others, or only the ones in the same folder?

**Comment by Riatre** [comment]
You get inferred results for all others.

But keep in mind that a lot of features of ccls (e.g. Find All References) rely on a project-wide index, which means ccls do *needs to know the flags of all your sources in advance*. If you only provide one compilation unit in compile_commands.json, ccls will index only this compilation unit, which may not be what you expected.
