### ISSUE TITLE
Does ccls support finding right virtual function?

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [MaskRay/ccls#225]
I was using the following code snippets to test support for virtual function. When I did  xref-find-definition at the bptr->print() and bptr->show(), it didn't go to the definition. Please let me know if ccls supports this feature, I haven't read about this feature on wiki though.

// CPP program to illustrate
// concept of Virtual Functions
#include <iostream>
using namespace std;

class base {
public:
  virtual void print() { cout << "print base class" << endl; }

  void show() { cout << "show base class" << endl; }
};

class derived : public base {
public:
  void print() { cout << "print derived class" << endl; }

  void show() { cout << "show derived class" << endl; }
};

int main() {
  base *bptr;
  derived d;
  bptr = &d;

  // virtual function, binded at runtime
  bptr->print();

  // Non-virtual function, binded at compile time
  bptr->show();
}

**Comment by FirstLoveLife** [comment]
![image](https://user-images.githubusercontent.com/37442588/51576821-9ad3c700-1ef2-11e9-812b-9d7b3414a11d.png)

ccls jumps to correct decl on my emacs+lsp-mode

so I think it is a client-side issue

**Comment by cyberphysicalrobotics** [comment]
What I meant was, when you do xref at the bptr->print(), it should jump to Derived::print().
But I think it doesn't work like that way. @FirstLoveLife, I can't check if your try works like that.

**Comment by MaskRay** [comment]
No, it doesn't support devirtualiazation at the indexer stage.

In clangCodeGen, `CodeGenFunction::EmitCXXMemberOrOperatorMemberCallExpr` can devirtualize a method but indexing runs til clangSema, devirtualization doesn't happen.

* After invoking `textDocument/definition` on `btr->print()`, you may do another `$ccls/inheritance` with `derived: true` to get the derived method.
* If you invoke `textDocument/references` on `Derived::print`, you'll find that `btr->print()` is also counted as a reference, although it is statically bound to `Base::print`.
