### ISSUE TITLE
Autocompletion issue with Sublime LSP

### ISSUE THREAD

**Issue by TheAifam5** [MaskRay/ccls#226]
Hey,
I noticed that the autocompletion entries looks like this 'a : int' and looks like thats is defined here: https://github.com/MaskRay/ccls/blob/a5f600a7db14b8b7e6d6de47796f298753c0d787/src/messages/textDocument_completion.cc#L365

So when I click on tab to autocomplete it, then the result looks like this:
`client->a : int`.
The same issue is with functions.

That `:` is somewhere in LSP defined or whats the reason to have it there?

Regards,
TheAifam5

**Comment by MaskRay** [comment]
I don't use Sublime but it seems its language client supports `insertText` but not `textEdit`, thus the issue. In your case, `insertText` is omitted and tge client inserts `label`.
