### ISSUE TITLE
ccls-git (arch linux) cannot index since jan 22 update

### ISSUE THREAD

**Issue by dfszb** [MaskRay/ccls#228]
The error message is:
20:01:32 ccls           initialize.cc:328 I use -resource-dir=/usr/lib/clang/7.0.1
20:01:32 ccls              project.cc:379 E failed to load <path>/compile_commands.json fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory

20:01:32 ccls           initialize.cc:364 I start 8 indexers
20:01:32 ccls           initialize.cc:372 I dispatch initial index requests
Note that the version before was working without any issues. There seems to be some new commit that handles compilation database problems on windows, maybe that introduced some regression.

**Comment by dfszb** [comment]
Note: building with version 4f5b013f83d21d614c4840058265a29221aa5a6c seems to result in a indexing without error.

**Comment by MaskRay** [comment]
I agree that the error ("No such file or directory") is spurious: 

```
20:01:32 ccls project.cc:379 E failed to load /compile_commands.json fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
```
It was reported here
```cpp
// src/project.cc
  if (!CDB) {
      LOG_S(ERROR) << "failed to load " << Path.c_str() << " " << err_msg;
  } else {
```

If `compile_flags.txt` or `compile_commands.json` does not exist, it is not necessary to print the error as `.ccls` can be used as an alternative. This is fixed in HEAD.

The old behavior is to index the whole directory if neither `.ccls` nor `compile_commands.json` exists. This has changed, see https://github.com/MaskRay/ccls/wiki/Project-Setup

**Comment by dfszb** [comment]
There is a compile_commands.json in the project root (and it has a .ccls-root file in the same directory, also there is a .projectile file in the same directory).
The compile_command.json is in fact a symlink to build/Debug/compile_commands.json.
Not sure what can be wrong then, should I set some other option? (I tried ccls indexing from lsp, and then used the ccls command only to reproduce the issue).
