### ISSUE TITLE
Unknown error occuranced 

### ISSUE THREAD

**Issue by bradprob** [MaskRay/ccls#230]
I am using ccls with the following configuration:
```
  (use-package company-lsp
    :ensure t
    :config
    (require 'company-lsp)
    (push 'company-lsp company-backends)
    (add-hook 'after-init-hook 'global-company-mode))

  (use-package lsp-mode
    :ensure t
    :config
    (require 'lsp-mode)
    (require 'lsp-clients)
   (add-hook 'c++-mode-hook
	      (lambda ()
		(setq flymake-diagnostic-functions (list 'lsp--flymake-backend))))
    (add-hook 'c++-mode-hook 'lsp)
    (add-hook 'c-mode-hook 'lsp))

  (use-package ccls
    :ensure t
    :config
    (require 'ccls)
    (setq ccls-executable "/path_to_ccls/ccls"))
```
Execution of `lsp-find-implementation` on a class type results in "Unknown error occuranced".
What is going wrong?

**Comment by MaskRay** [comment]
Did you actually follow https://github.com/MaskRay/ccls/wiki/Build and build the `ccls` executable at `/path/to/ccls/Release/ccls`?

**Comment by MaskRay** [comment]
Can you try

```
cd /tmp; mkdir c; cd c; git init; touch .ccls; echo 'int a;' > a.cc
/path/to/ccls/Release/ccls -index=/tmp/c
```

**Comment by bradprob** [comment]
19:21:44 ccls           initialize.cc:301 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cacheDirectory":".ccls-cache","cacheFormat":"binary","clang":{"excludeArgs":[],"extraArgs":[],"pathMappings":[],"resourceDir":""},"client":{"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":false,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialBlacklist":[],"initialWhitelist":[],"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"onChange":false,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
19:21:44 ccls           initialize.cc:328 I use -resource-dir=/usr/lib/llvm-7/lib/clang/7.0.1
19:21:45 ccls              project.cc:269 I use /tmp/c/.ccls: 
19:21:45 ccls              project.cc:440 I search directory: /usr/include/ <
19:21:45 ccls              project.cc:440 I search directory: /usr/include/x86_64-linux-gnu/c++/8/ <
19:21:45 ccls              project.cc:440 I search directory: /usr/include/c++/8/ <
19:21:45 ccls              project.cc:440 I search directory: /usr/include/c++/8/backward/ <
19:21:45 ccls              project.cc:440 I search directory: /include/ <
19:21:45 ccls              project.cc:440 I search directory: /usr/include/clang/7.0.1/include/ <
19:21:45 ccls              project.cc:440 I search directory: /usr/local/include/ <
19:21:45 ccls              project.cc:440 I search directory: /usr/include/x86_64-linux-gnu/ <
19:21:45 ccls              project.cc:440 I search directory: /usr/lib/llvm-7/lib/clang/7.0.1/include/ <
19:21:45 ccls           initialize.cc:364 I start 12 indexers
19:21:45 ccls           initialize.cc:372 I dispatch initial index requests
entries:     1
pending:     119:21:45 indexer0         pipeline.cc:324 I parse /tmp/c/a.cc
pending:     119:21:45 indexer0         pipeline.cc:362 I store index for /tmp/c/a.cc (delta: 0)
pending:     0
