### ISSUE TITLE
lsp-find-references issue

### ISSUE THREAD

**Issue by dfszb** [MaskRay/ccls#232]
I have a problem with lsp-find-references.
In a cmake project that includes a few sub-projects (library, unittest and application glue-code), in one of the files in the 'application' project, (one that relies heavily on company-wide frameworks seen as external headers), lsp-find-references does not seem to work for symbols coming from my library. (it will return 'unknown error occured'). lsp-find-definition works for the very same function and also completion works beautifully (the best feature I think is this versatile completion). Also the application sub-project seem to be able to find references for the symbols defined in the app sub-project.
Also the lsp-find-references works well between unit-test project and library project (it will find references in both).
I'm sorry for not being able to post logs and source examples (for company policy reasons), I will also try to reproduce this or to debug more - in fact I am asking for your help to let me know how I could debug this and maybe what config error is probable on my side (I generated the json formatted cache using the ccls indexer call from command line and it did not seem to have errors for my 'application' file).
I see no error in /tmp/ccls.log, and the strace attaching to the ccls executable just displays: 
```
[pid 21948] <... read resumed> "Content-Length: 273\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/references\",\"params\":{\"textDocument\":{\"uri\":\"file:///<filename>\"},\"position\":{\"line\":1015,\"character\":22},\"context\":{\"includeDeclaration\":false}},\"id\":108}\n", 4096) = 296                                                                                         
[pid 21948] read(0,  <unfinished ...>                                                                                                                                                                                                   
[pid 21949] write(1, "Content-Length: 38\r\n\r\n{\"jsonrpc\":\"2.0\",\"id\":108,\"result\":[]}", 60) = 60                                    
```

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/lsp-mode#projects-with-subprojects

**Comment by dfszb** [comment]
Thanks! I added the .ccls-root file already (just forgot to mention above).
However, I am not sure what to do about the whitelist setting, is it still needed if I have .ccls-root file added?

**Comment by MaskRay** [comment]
Can you call `(ccls--suggest-project-root)` in `project/a.cc` and `project/subproject/a.cc` respectively, check if they are the same? `(projectile-project-root)` is used by default and the subproject may be considered as a project on its own, thus no references from outside.

You may also try `M-x lsp-describe-session`.

There are two whitelists and blacklists

## lsp-mode

`lsp-project-whitelist` and `lsp-project-blacklist` were once in lsp-mode (before 5.0). They could be customized to not start lsp-mode for some paths.

## ccls

See `index.initialBlacklist` `index.blacklist` in https://github.com/MaskRay/ccls/wiki/Customization

**Comment by dfszb** [comment]
Calling the (ccls--suggest-project-root) (using M-x eval-expression while a c++ buffer is open, as the function seems to check for the major-mode first), returns the very same top-level directory, the common root of the project.
lsp-describe-session does not show any blacklisted directory. 
As I mentioned, lsp-find-references works OK in other files in the very same application directory, and completion works OK in all files (including the big 'application gluecode' file where the lsp-find-references won't work). What else could I try to debug?

**Comment by MaskRay** [comment]
```cpp
int a; // obviously you can call textDocument/references on the declaration
a; // but you can call textDocument/references on a reference
a; // ditto
```

> including the big 'application gluecode' file where the lsp-find-references won't work

Is this file considered part of the project? What do `(ccls--suggest-project-root)` and `(ccls-file-info)` say?

I can give some examples about client/user side issues:

* The buffer is not considered part of the project. Thus I asked you to clarify. If it is, you'll see a log line `create session for /path/to/buffer`
* Your file name is `*.inc` and it is not considered a `c++-mode` buffer. Check `M-: major-mode`
* The file where you invoke `textDocument/references` does not compile. This may be caused by incorrect command line options, missing source files (some source files may be generated in the build directory), etc

**Comment by dfszb** [comment]
ccls--suggest-project-root) in the big file returns the correct root.
(ccls-file-info) returns similar info to other files in the same dir (files that have lsp-find-references working).
I see a couple of lines with sema_manager.cc:717 I create session for <filepath>.
The files have extension .cpp and .h.
The file compiles with g++, and completion works ok. I'm also a rtags user and rtags finds references.
Source files generated in the build directory, hm, that is true, I put some code there (code that is generated by protocol buffers compiler). How can I debug this?

**Comment by MaskRay** [comment]
And `-v=1` to dump command line options in the log file: https://github.com/MaskRay/ccls/wiki/Customization
