### ISSUE TITLE
Problem compiling on RedHat

### ISSUE THREAD

**Issue by daniel6651** [MaskRay/ccls#234]
Hi

I tried to compile according to the instructions but run into some problem as seen below.
It's a RedHat 7 system with very old gcc and clang so I tried the method with downloading a clang binary

Could it be that I need to have clang header files downloaded as well and pointed to?

<pre>
cd /repo/xyz
tar xvf clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04.tar
cd ~/ccls
export CXX=/repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang++
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/

[:~/ccls] $ cmake --build Release/
Scanning dependencies of target ccls
[  2%] Building CXX object CMakeFiles/ccls.dir/third_party/siphash.cc.o
/repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang++: /lib64/libtinfo.so.5: no version information available (required by /repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang++)
/local/repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang-7: /lib64/libtinfo.so.5: no version information available (required by /local/repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang-7)
[  4%] Building CXX object CMakeFiles/ccls.dir/src/clang_tu.cc.o
/repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang++: /lib64/libtinfo.so.5: no version information available (required by /repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang++)
/local/repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang-7: /lib64/libtinfo.so.5: no version information available (required by /local/repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang-7)
In file included from /home/xyz/ccls/src/clang_tu.cc:16:
In file included from /home/xyz/ccls/src/clang_tu.hh:18:
In file included from /home/xyz/ccls/src/position.hh:18:
/home/xyq/ccls/src/utils.hh:18:10: fatal error: 'optional' file not found
#include <optional>
         ^~~~~~~~~~
1 error generated.
</pre>

**Comment by MaskRay** [comment]
Please refer to https://github.com/MaskRay/ccls/issues/87 (CentOS 7)

> fatal error: 'optional' file not found

See https://github.com/MaskRay/ccls/wiki/Build : g++ >= 7.2 is required (`optional,string_view,...` require libstdc++7 or higher)

You may need to install some devtoolset packages

> tar xvf clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04.tar
> cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/repo/xyz/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/

I worry about the ABI compatibility and my intuition does not say this is unsupported. (Read https://github.com/MaskRay/ccls/issues/71#issuecomment-455755963 for details)
