### ISSUE TITLE
Save error on windows

### ISSUE THREAD

**Issue by Yanpas** [MaskRay/ccls#235]
I do often save files which I edit, sometimes they are read by ccls and fails happen. As far as I remember WinAPI forbids reader and writer access to file. Maybe there are some winapi functions that fix it...
![image](https://user-images.githubusercontent.com/7345761/51941731-5da59280-2426-11e9-9413-ea6b3671ab8f.png)

**Comment by MaskRay** [comment]
Interesting issue.

* client sends `textDocument/didSave`
* main thread (`messages/textDocument_did.cc`) enqueues an indexing task (`pipeline::Index`)
* indexer thread (`pipeline.cc`) reads the file to check if the file index (`IndexFile`) is stale. If it is, call into clangIndex to index the file (many (uncontrollable) files may be read via `#include`)

Do you know the order of `textDocument/didSave` and the actual save event of the file?

**Comment by Yanpas** [comment]
I'm afraid I cannot. It happened when I hit save twice with 1 second interval

**Comment by MaskRay** [comment]
You remind me of another thing: clang 8 have nanosecond precision for timestamps. I'll work on that.

**Comment by MaskRay** [comment]
If vscode doesn't ensure `textDocument/didSave` is sent after the save action finishes, I think this can't be fixed on ccls' side.

**Comment by Riatre** [comment]
Even if VSCode ensure `textDocument/didSave` is sent after the save action finished, this can still happen, nothing prevents me from saving the file again while ccls is parsing the file. On Windows, if the file is opened without some strange flags like `FILE_SHARE_READ | FILE_SHARE_WRITE`, the file will be effectively locked, all subsequent `CreateFile` calls will fail until the owner closes this file. I don't know if there are ways to configure how clang reads file though.

**Comment by MaskRay** [comment]
If a failed `::CreateFileW(PathUTF16.begin(), Access, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, &SA, Disp, Flags, NULL);` (https://github.com/llvm-mirror/llvm/tree/master/lib/Support/Windows/Path.inc#L1097) call pops up a window, I cannot think of a way to fix it. It it doesn't do that and just returns a error number, there will be [a spurious `diag::err_pp_file_not_found` error](https://github.com/llvm-mirror/clang/tree/master/lib/Lex/PPDirectives.cpp#L1871):

```text
a.cc:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
```

**Comment by Riatre** [comment]
I see, there are indeed nothing to be fixed in ccls if it already opens the file with `FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE`. I suspect it is the client (vscode) wants exclusive access and that can only be fixed in their code.
