### ISSUE TITLE
%compile_commands.json in .ccls will ignore files which not listed in compile_commands.json

### ISSUE THREAD

**Issue by xVanTuring** [MaskRay/ccls#238]
If one source file is not list in `compile_commands.json`,  and `.ccls` has `%compile_commands.json` directive, it will cause that file get ignored when doing indexing.
https://github.com/MaskRay/ccls/blob/267385b4d16e81e0698eb9b9078d830eeb3cd39c/src/project.cc#L282
The `AppendToCDB(args)` will be true and the file will eventually get ignored.
If this is the default behaviour, it should be noted on wiki. 

---
``` bash
# command
ccls -index=./ -init="{\"cacheFormat\": \"json\"}"
```
* cache folder:
.ccls-cache/
├── @@home@xvan@Project@test
│   ├── @home@xvan@.local@include@myheader.h
│   └── @home@xvan@.local@include@myheader.h.json
└── @home@xvan@Project@test
    ├── main.cpp
    └── main.cpp.json
* dir:
.
├── build
├── CMakeLists.txt
├── compile_commands.json -> ./build/compile_commands.json
├── main.cpp
└── test.cpp

**Comment by MaskRay** [comment]
This is the expected behavior (`%compile_commands.json` applies on `compule_commands.json` entries) and it has been noted.
