### ISSUE TITLE
Error suggestion

### ISSUE THREAD

**Issue by JustAPerson** [MaskRay/ccls#24]
Hi,

```
19:27:39 comp-preload     clang_tu.cc:392 E libclang had ast read error for $file. Please try running the following, identify which flag causes the issue, and report a bug. ccls will then filter the flag for you  automatically.
c++ ...
```

It might be worth clarifying this should be `clang++` in case `c++` defaults to `g++`.

**Comment by MaskRay** [comment]
clang uses different `--driver-mode` when it is invoked as `clang++,clang-cl,clang,cc,...` I'm thinking how to handle this properly.

**Comment by JustAPerson** [comment]
Oh that is annoying. I was also trying to index a Windows project using the MSVC header paths etc but enabling some of the `-fms-compatability` options removes the `-resource-dir` option from the command line parser.

**Comment by MaskRay** [comment]
I think `-resource-dir=` can still be used with clang-cl mode, but `-working-directory` does not.

I had an old branch replace the current compile command option handling logic in `project.cc` with clangDriver (https://github.com/MaskRay/ccls/commit/296fcf95876c341d2b6d6385fc83b727460d5f38) but puzzled by a bug. I'll revisit it after transition from libclang indexer to clangIndex (https://github.com/MaskRay/ccls/tree/cxx I have plan to eventually remove libclang (haha large divergence from cquery

**Comment by MaskRay** [comment]
clangDriver has been enabled in `project.cc` (it can infer system search paths as `clang -xc++ -v -E /dev/null` prints) but I'm still not sure replacing `c++` with `clang++` is something correct to do.

**Comment by MaskRay** [comment]
I think ccls should only do minimal handling on compile command line options. Users can find the answers in wiki/FAQ
