### ISSUE TITLE
fails to complete when including GSL support library

### ISSUE THREAD

**Issue by jvillasante** [MaskRay/ccls#245]
I'm trying to use the Guidelines Support Library (https://github.com/Microsoft/GSL) with `ccls`
I include the library folder on my `.ccls` file `-I./libs/GSL/include`
The problem happens with `gsl::owner<T>` definition in `pointers` header.

If I do `#include <gsl/gsl>` I get the error "No member named owner in namespace gsl"
If I do `#include <gsl/pointers>` everything works and `ccls` is able to find the definition of `owner<T>` in namespace `gsl` just fine.

Any thoughts why is this happening?

**Comment by jvillasante** [comment]
Here's my `.ccls` file. I found out that if I delete `-Werror` it works!

```
clang
%c -std=gnu11
%cpp -std=c++17

# Compiler Flags
-Wall
-Wextra
-Werror
-DDEBUG

# System includes Clang: Output of 'echo | /usr/local/opt/llvm/bin/clang -v -x c++ -E -' command.
# -isystem/usr/local/Cellar/llvm/7.0.0/include/c++/v1
# -isystem/usr/local/include
# -isystem/usr/local/Cellar/llvm/7.0.0/lib/clang/7.0.0/include
# -isystem/usr/include
# -isystem/System/Library/Frameworks
# -isystem/Library/Frameworks

# System includes GCC: Output of 'echo | /usr/local/opt/gcc/bin/gcc-8 -v -x c++ -E -' command.
# -isystem/usr/include/c++/8
# -isystem/usr/include/x86_64-linux-gnu/c++/8
# -isystem/usr/include/c++/8/backward
# -isystem/usr/lib/gcc/x86_64-linux-gnu/8/include
# -isystem/usr/local/include
# -isystem/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed
# -isystem/usr/include/x86_64-linux-gnu
# -isystem/usr/include

# Local Includes
-I.
-I./src/include
-I./src/libs/GSL/include

```

**Comment by MaskRay** [comment]
> I found out that if I delete -Werror it works!

Interesting. It is known that `-Werror` may cause issue in completion, diagnostics and signatureHelp, thus it is removed in `BuildPreamble` https://github.com/maskray/ccls/blob/master/src/sema_manager.cc#L357

Does it mean I should do the same in `indexer.cc` (used for `textDocument/definition` etc) https://github.com/maskray/ccls/blob/master/src/indexer.cc#L1241
