### ISSUE TITLE
lsp-find-implementation: not found for

### ISSUE THREAD

**Issue by bradprob** [MaskRay/ccls#246]
Hi,
I have a very simple project as follow:
`test.cpp:`
```
#include "fib.hpp"
#include <iostream>


int main()
{
  fibo f;
  std::cout <<f.fib(30) << std::endl;
  return 0;
}
```
`fib.hpp`
```

#pragma once

class fibo
{
public:
  int fib(int nr);
};

```
`fib.cpp`

```
#include "fib.hpp"

int fibo::fib(int nr)
{
  switch (nr) {
  case 0:
    return 0;
  case 1:
    return 1;
  default:
    return nr + fib(nr - 1);
  }
}
```
the structure of the project is:
```
test
|____ CMakeLists.txt
|____ test.cpp
|____ fib.hpp
|____ fib.cpp
|____ compile_commands.json (symlink to ./build/compile_commands.json)
|____ build
          |______ compile_commands.json
          |______ ...
```
`lsp-find-implementation` on `fib(30)` in `test.cpp` results in `Not found for: fib`.

Why cannot `ccls` find the implementation of `fib()` in this project?

**Comment by MaskRay** [comment]
The meaning of `textDocument/implementation` is not well specified. In ccls, it is a special case of `$ccls/inheritance` which returns derived classes/member functions.
