### ISSUE TITLE
Can not index GL/glext.h.

### ISSUE THREAD

**Issue by oochen** [MaskRay/ccls#251]
Hi, I am using the ccls tool to do the completion. It is a great tool, however when I am using it to index GL/glext.h file, it doesn't show the candidates.  When I add the .ccls file using the -DGL_GLEXT_PROTOTYPES, it even can not show std::cout completions.  My file are name with .cpp extension.
Thanks.

**Comment by MaskRay** [comment]
Please include more information: OS, editor (implied from where you reported the issue), version, minimum reproduce (code snippet+interactive actions), screenshot/screencast (sometimes more useful than text), etc

You may refer to issues 30 191 197 for good questions. You may omit the information if you are confident you've spotted some bugs, e.g. 136 156

> it even can not show std::cout completions.

Please read the documentation carefully. Try this example:

`mkdir /tmp/c; cd /tmp/c; git init; touch .ccls; print '#include <iostream>\nint main(){std::cout;}' > a.cc`

**Comment by oochen** [comment]
Thanks. 
I should read the document carefully. I managed to get the completion with compile_commands.json file.
