### ISSUE TITLE
Can not use ccls to index boost

### ISSUE THREAD

**Issue by thongpv3** [MaskRay/ccls#252]
I just install `ccls` then write a simple project to check if it work. The code completion work but not completed, it can not found `std::printf()` from `<cstdio>`. 
Here is my code:

```
#include <iostream>
#include <boost/asio.hpp>
#include <stdlib.h>
#include <stdio.h>
#include <cstdio>

int main() {
  using boost::asio::ip::udp;
  constexpr auto addr = "localhost";
  constexpr auto port = 8795;
  std::cout << "Hello world" << std::endl;
  std::printf
  return 0;
}
```
These are problems that I found:
- I can not find reference of `boost` at the using statement. `ccls` told me that `ccls: use of undeclared identifier 'boost' [2]`. But I can navigate to `<boost/asio.hpp>` at the include statement
- The `cout` statement is correct but ccls said that: `ccls: invalid operands to binary expression ('std::ostream' (aka 'int') and 'const char [12]') [2]`
- The code completion can not find `std::printf` from `<cstdio>`

[screenshot](https://imgur.com/a/GB6oIeu)

Here is the `compile_commands.json`: 
```
[
  {
    "directory": "/home/thongpv87/workspace/test_asio/build",
    "command": "c++ -Idemo@exe -I. -I.. -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -pthread  -MD -MQ 'demo@exe/main.cpp.o' -MF 'demo@exe/main.cpp.o.d' -o 'demo@exe/main.cpp.o' -c ../main.cpp",
    "file": "../main.cpp"
  }
]
```

I also linked this file to the root directory of project. The way I try ccls is compile and install ccls from github, then enable lsp-ccls in spacemacs. I also disable rtags, gtags in spacemacs.

**Comment by MaskRay** [comment]
This is not related to boost.

From your screenshot, you shall notice the diagnostics: `'xxxxx' file not found`
```
#include <iostream>
         ~~~~~~~~~~
#include <cstdio>
         ~~~~~~~~
```

Your clang cannot find the g++ search directories. If you have g++ 8.0.1 installed, clang should find them:

```
% clang -fsyntax-only -v -xc++ /dev/null
 /usr/lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++/8.0.1
 /usr/lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/x86_64-linux-gnu/c++/8.0.1
 /usr/lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++/8.0.1/backward
...
```

**Comment by thongpv3** [comment]
The underline is because of spell checking, not because of syntax error or semantic error. `g++` was installed on my machine. I can compile and run that file (after remove std::printf line). Here is output of your command:

```
**[thongpv87@thongpv87 ~] $ clang -fsyntax-only -v -xc++ /dev/null
clang version 7.0.1 (Fedora 7.0.1-1.fc29)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
 "/usr/bin/clang-7" -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name null -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /usr/lib64/clang/7.0.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8 -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/x86_64-redhat-linux -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib64/clang/7.0.1/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/thongpv87 -ferror-limit 19 -fmessage-length 80 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -x c++ /dev/null -faddrsig
clang -cc1 version 7.0.1 based upon LLVM 7.0.1 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8
 /usr/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/x86_64-redhat-linux
 /usr/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/backward
 /usr/local/include
 /usr/lib64/clang/7.0.1/include
 /usr/include
End of search list.
```

**Comment by MaskRay** [comment]
> * The code completion can not find `std::printf` from `<cstdio>`

The symptom is because the clang libraries used by ccls cannot find the g++ search directories.

https://github.com/MaskRay/ccls/wiki/FAQ#some-cc-headers-are-not-recognized

I suggest you try some simply configuration first, e.g.

`cd /tmp; mkdir c; cd c; git init; touch .ccls`

`/tmp/c/a.cc`

```cpp
#include <cstdio.h> // header shipped with g++ /usr/include/c++/8/cstdio
```

> * But I can navigate to `<boost/asio.hpp>` at the include statement

Also be aware that if you open `/usr/include/boost/asio.hpp` directly, your language client may not consider the file `asio.hpp` is within the same project. It may start a new language server (a `ccls` process) in `/usr/include` or `/usr`. You won't get references from your source file.

See https://github.com/MaskRay/ccls/issues/145#issuecomment-443455014
