### ISSUE TITLE
LPS unable to find file although the path to the file is correct

### ISSUE THREAD

**Issue by shelper** [MaskRay/ccls#254]
so i am using mac, with latest clang and xcode installed, I installed ccls using homebrew, have spacemacs latest develop branch. 
i used the example A .ccls from wiki with clang in the project root, but i always get error message saying:
> LSP :: Unable to find file /Users/zyuan/develop/StereoVision-ADCensus/ADCensusBM/adcensuscv.h [13 times]
however, the path here is exactly the path to the header file, do I need to add the file to CMakelist or some thing like that for LSP to find it>

although saying not able to find the file. the flycheck still works, giving errors about using namespace, etc. and i believe it is checking the header file in c mode not c++ mode, even after renaming the file to .hpp, still the same error...

**Comment by shelper** [comment]
and if i remove .ccls file,  as mentioned in the wiki, it indexes the file when the file is opened, for which the flycheck checks the file as c file , not c++ file, no matter what file extension i uses, or emacs major mode i specifies. ...

**Comment by MaskRay** [comment]
> LSP :: Unable to find file /Users/zyuan/develop/StereoVision-ADCensus/ADCensusBM/adcensuscv.h

A `.h` file will not be indexed by itself. There should be some `.c` `.cc` `.cpp` files including it.

"During initial loading of the project, many `.h` files do not have owner `.cc` files. It is risky to index unknown `.h` files because they can be dependent and should not be indexed on their own. The heuristic used here is that is there is no pending index requests, indexing it should be pretty safe."

> but the flycheck checks the file as c file , not c++ file

https://github.com/MaskRay/ccls/wiki/Project-Setup

> You may add a line %h -x c++-header to make every *.h parsed as C++.

**Comment by shelper** [comment]
maybe i didnt explain well, 
1. the file is included by a cpp file in the same folder. 
2. i tried the `%h -x c++-header` and other means (changing the file extension), none of them works...

**Comment by MaskRay** [comment]
> if i remove .ccls file, the header file is indexed in c mode not c++mode, no matter what i setup

If neither `compile_commands.json` nor `.ccls` exists, a `*.h` file will be indexed as `clang -xobjective-c++-header a.h`

> if i add .ccls, header file cannot be indexed so `%h -x c++-header` is useless.

Again, if `a.cc` includes `a.h`. Only `a.cc` is indexed but the index provides index files for both `a.cc` and `a.h`. If you open a new file `b.h` and there is no files including it, `b.h` will also be indexed if there is no pending index requests. https://github.com/maskray/ccls/blob/capabilities/src/messages/textDocument_did.cc#L59
