### ISSUE TITLE
ubuntu18.04 must you compile and install llvm + clang yourself?

### ISSUE THREAD

**Issue by 3038922** [MaskRay/ccls#255]
#80
I see your answer.But I installed it in the'sudo apt install clang-7'way.

![image](https://user-images.githubusercontent.com/33926386/52536077-ead6d880-2d90-11e9-8572-59f3527e817c.png)
The contents of a directory are completely different from those of a directory.
`
cmake -H. -Bbuild \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH=/usr/lib/llvm-7 \
    -DLLVM_INCLUDE_DIR=/usr/lib/llvm-7/include \
    -DLLVM_BUILD_INCLUDE_DIR=/usr/include/llvm-7/ \
    -DLLVM_ENABLE_RTTI=on
`
I can't find clang folder in llvm-7

**Comment by MaskRay** [comment]
Please actually read the documentation before raising an issue.

https://github.com/MaskRay/ccls/wiki/Build#debian
```sh
apt install clang-7 libclang-7-dev
cmake -H. -BRelease -DCMAKE_PREFIX_PATH=/usr/lib/llvm-7 -DLLVM_ENABLE_RTTI=on
```

I'll delete this issue soon.
