### ISSUE TITLE
Template functions are not enlisted in document/symbols

### ISSUE THREAD

**Issue by Yanpas** [MaskRay/ccls#256]
Code example:
```cpp
template <typename X>
void tfoo(X) {

}

template <>
void tfoo(int) {

}

template <>
void tfoo(char) {
  
}

int foo() {
  return 5;
}

void bar() {
  tfoo('c');
}

```

ccls says that there is only foo and bar functions in this file.

**Comment by Yanpas** [comment]
Is it regression if cquery supports it?

**Comment by FirstLoveLife** [comment]
`textDocument/definition` + `tfoo('c')` can jump to `template <> void tfoo(char)` correctly on my local ccls(emacs + lsp-mode)

**Comment by Yanpas** [comment]
Hm, it seems that the problem is with this tree updates, ccls doesn't update symbol tree after I modify it and switch editors.

**Comment by Yanpas** [comment]
After update to master symbols information is updated more frequent.
