### ISSUE TITLE
Wrong error from syntax check

### ISSUE THREAD

**Issue by pavlosun** [MaskRay/ccls#257]
I use neovim 
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-flySZy/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-flySZy/neovim-0.3.4/build/config -I/build/neovim-flySZy/neovim-0.3.4/src -I/usr/include -I/build/neovim-flySZy/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-flySZy/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org
```
Everything seems ok but I have wrong syntax message:

![screenshot from 2019-02-12 13-39-22](https://user-images.githubusercontent.com/11482899/52663309-f975da80-2ecb-11e9-999c-35aab20715fc.png)

GdaConnectionEvent object is present in gda-connection-even.h file. This file included. I checked indexed files and gda-connection-event.h is indexed. This file is here
https://gitlab.gnome.org/GNOME/libgda/blob/master/libgda/gda-connection.h

In the same file another object is not found. The overall project can be compiled. 
How can I debug this problem? Please let me know what information is needed to clarify the issue. I will try my best. Thanks.

**Comment by MaskRay** [comment]
```
sudo apt install libjson-glib-dev libgtksourceview-3.0-dev

cd /tmp/p
git clone --depth=1 https://gitlab.gnome.org/GNOME/libgda/
CC=clang CXX=clang++ meson Debug/
ln -s Debug/compile_commands.json

# open libgda/gda-connection-event.h
```

ccls is able to locate the declaration of `typedef struct _GdaConnectionEvent GdaConnectionEvent;` at:

```c
// libgda/gda-connection-event.h
G_DECLARE_DERIVABLE_TYPE (GdaConnectionEvent, gda_connection_event, GDA, CONNECTION_EVENT, GObject)
```

**Comment by pavlosun** [comment]
I think I didn't explain problem well enough. I was able to jump to the symbol before. The problem with static code analysis. As you  can see in the picture, the error doesn't make sense to me. This type declared in the header which is included into the current file. This is mu .ccls file
```
%compile_command.json
%c -std=c11
%h
-I.
-I/home/pavlo/jhbuild/checkout/libgda
-I/home/pavlo/jhbuild/checkout/libgda/libgda
-I/home/pavlo/jhbuild/checkout/libgda/_build
-I/home/pavlo/jhbuild/install/include/gtk-3.0/unix-print
-I/home/pavlo/jhbuild/install/include/gtk-3.0
-I/home/pavlo/jhbuild/install/include/at-spi2-atk/2.0
-I/home/pavlo/jhbuild/install/include/at-spi-2.0
-I/home/pavlo/jhbuild/install/include/gtk-3.0
-I/home/pavlo/jhbuild/install/include/gio-unix-2.0
-I/home/pavlo/jhbuild/install/include/cairo
-I/home/pavlo/jhbuild/install/include/pango-1.0
-I/home/pavlo/jhbuild/install/include/fribidi
-I/home/pavlo/jhbuild/install/include/harfbuzz
-I/home/pavlo/jhbuild/install/include/atk-1.0
-I/home/pavlo/jhbuild/install/include/cairo
-I/home/pavlo/jhbuild/install/lib/cairomm-1.0/include
-I/home/pavlo/jhbuild/install/include/cairo
-I/home/pavlo/jhbuild/install/include/pixman-1
-I/home/pavlo/jhbuild/install/include/gdk-pixbuf-2.0
-I/home/pavlo/jhbuild/install/include/glib-2.0
-I/home/pavlo/jhbuild/install/lib/glib-2.0/include
-I/usr/include/dbus-1.0
-I/usr/lib/x86_64-linux-gnu/dbus-1.0/include
-I/usr/include/uuid
-I/usr/include/freetype2
-I/usr/include/libdrm
-I/usr/include/libpng16
-I/usr/include/postgresql
```
How does your syntax check looks like?

**Comment by MaskRay** [comment]
`compile_commands.json` is preferred and I've given the instruction to obtain it from meson. I get no spurious diagnostics.

> %h
`%h` must be followed by a flag. It cannot apply to the empty option. See `src/project.cc`

You may use `-log-file=/tmp/ccls.log -v=1` to get clang command line used to parse your header file. 
https://github.com/MaskRay/ccls/wiki/Customization . Check if your `.ccls` has every required flag.

**Comment by pavlosun** [comment]
ok, The problem solved. First of all, it was a typo in .ccls file. I put ```%compile_command.json```. Should be ```%compile_commands.json```. I thought ```%h``` should be included to process the header files. I removed it. I also removed all include flags that I have in ```compile_commands.json```. Now my .ccls flag looks like:
```
%compile_commands.json
%c -std=c11
```
I use meson and it does a very good job to make good compilation database. 
Thank you once again.

**Comment by MaskRay** [comment]
> %compile_commands.json
>
> %c -std=c11

It is likely you don't need `.ccls` at all.

* GCC 5/Clang 3.6 defaults to `-std=gnu11`
* GCC 8 defaults to `-std=gnu17`

**Comment by pavlosun** [comment]
Indeed. Good point. Thanks.
