### ISSUE TITLE
spurious ast read error

### ISSUE THREAD

**Issue by JustAPerson** [MaskRay/ccls#26]
I've been struggling to resolve the following `ccls.log` entry

```
16:35:35 indexer7         clang_tu.cc:392 E libclang had ast read error for $file Please try running the following, identify which flag causes the issue, and report a bug. ccls will then filter the flag for you  automatically:
```

When I try with the given arguments with `clang++` (both system and the one cmake downloads) it parses successfully and emits no output.

**Comment by MaskRay** [comment]
What does `c-index-test -index-file <clang command line options here>` say?

Example: `c-index-test -index-file -resource-dir  ~/Dev/Util/ccls/build/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04/lib/clang/6.0.0 -I../src a.cc`

**Comment by JustAPerson** [comment]
Hmm, it seems that the line that comes next in the log (the one with all the flags to try) sometimes has a `c++` executable at the beginning and includes the input file. This only happens in some projects. Other projects those two parts of the example command are missing.

The project that is broken and I cannot index does not include those two features. When I try `c-index-test` it reports `Failure (no details available)` but if I manually provide those two features then it emits a bunch of stuff.

**Comment by JustAPerson** [comment]
Oh I guess that's my fault. I was using `bear` to generate compile_commands in one project and using a hacky python script to piece together scons output into a compile_commands. I guess both the compiler and the input flags should be in the arguments of a compile_commands object
