### ISSUE TITLE
Watching for compile_commands.json modifications

### ISSUE THREAD

**Issue by BenjaminNavarro** [MaskRay/ccls#262]
It seems to me that if the `compile_commands.json` file is modified after the initial indexing it does not trigger a re-indexing of the project.

I use `ccls` trough the `atom-ide-ccls` plugin and my build system (CMake-based) copies the generated`compile_commands.json` to the root of the project when configured.

Is it a feature lacking to `ccls` or an issue related to my particular use of it?

Right now, if I add a new file and regenerate the compilation database I have to remove `.ccls-cache` and reopen the file to trigger a new indexation.

**Comment by MaskRay** [comment]
It shouldn't be ccls's job to watch `compile_commands.json`.

The language client can send `workspace/didChangeConfiguration` to trigger re-indexing.
https://github.com/maskray/ccls/blob/master/src/messages/workspace.cc#L37

```cpp
void MessageHandler::workspace_didChangeConfiguration(EmptyParam &) {
  for (const std::string &folder : g_config->workspaceFolders)
    project->Load(folder);
  project->Index(wfiles, RequestId());

  manager->Clear();
};
```
