### ISSUE TITLE
how to include cocoa header files of system in MacOS?

### ISSUE THREAD

**Issue by starcwl** [MaskRay/ccls#263]
how to fix  'Foundation/Foundation.h' file not found warning?

I think the ccls couldn't find the system path of header files.

**Comment by MaskRay** [comment]
Please describe more about your environment: OS, editor, ccls version, a minimal reproduce (filename, code, instructions, ...), screenshot, etc.

Figure out how to compile the file with proper clang command line options first then add a `.ccls` or `compile_commands.json`.

**Comment by starcwl** [comment]
I build the ccls with git version 'a3efa72'
build  command:
```
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/path/to/clang+llvm-700
cmake --build Release
```

environment:
MacOS: 10.14
VSCode: 1.31.1
VSCodeExtension-ccls: 0.1.22

**Comment by starcwl** [comment]
this problem fixed after build compile_commands.json
