### ISSUE TITLE
Does ccls support sublime text 3?

### ISSUE THREAD

**Issue by fusion-c** [MaskRay/ccls#265]
Because, Subliem Text is my favorite editor.

**Comment by MaskRay** [comment]
ccls speaks LSP. You just need a language client for your favorite editor. For Sublime Text 3, you may try https://github.com/tomv564/LSP

**Comment by fusion-c** [comment]
> 
> 
> ccls speaks LSP. You just need a language client for your favorite editor. For Sublime Text 3, you may try https://github.com/tomv564/LSP

thank you
