### ISSUE TITLE
在windows裏用MSYS2編譯完ccls，運行是顯示“無法找到程序輸入點”。

### ISSUE THREAD

**Issue by fusion-c** [MaskRay/ccls#266]
![tp](https://user-images.githubusercontent.com/10498248/52858592-82f40980-3165-11e9-90e3-c74f5e221c3b.PNG)

**Comment by jhasse** [comment]
Could be that it loads the wrong libstdc++ DLL. Can you check the DLL dependencies with [Dependency Walker](http://www.dependencywalker.com/)?
