### ISSUE TITLE
support for multi-byte characters?

### ISSUE THREAD

**Issue by 3038922** [MaskRay/ccls#267]
The actual development environment does not necessarily all use English.

For example, the output of TXT text in graphical interface.

Will this issue be added to the future agenda?

**Comment by Riatre** [comment]
Related: https://github.com/Microsoft/language-server-protocol/issues/376

**Comment by MaskRay** [comment]
indexer should take UTF-8 into account: https://github.com/MaskRay/ccls/pull/268 I hope the performance won't be too bad...

LSP using UTF-16 is considered bad by many people and many language servers/clients don't strictly conform to the specification in this regard. ccls will only support UTF-8 encoded text. Another data point: last year someone proposed to support UTF-16 in clang but it got very negative feedback.
