### ISSUE TITLE
extension from vscode marketplace does not work.

### ISSUE THREAD

**Issue by dibalavs** [MaskRay/ccls#269]
Hello. I installed extension from vscode marketplace (version 0.1.22).
But after re-starting  vscode, extension does not work.
I found log message:
`Server CWD is /opt/project/qt5.10/qtwebengine
ccls server connection was closed
[Error - 9:48:26 AM] Connection to server got closed. Server will not be restarted.`

Also I grep installation directory:
~/.vscode/extensions/ccls-project.ccls-0.1.22/

And unable to find ccls binary.
Looks like vscode extension installation is not full. 
Please provide ccls binary to vscode extension

**Comment by MaskRay** [comment]
You need to build ccls from source.  https://github.com/MaskRay/ccls/wiki

Binary release is unrealistic as ccls depends on the huge clang libraries and the `-resource-dir` path is hard-coded in the executable.
