### ISSUE TITLE
About header complement bug in neovim

### ISSUE THREAD

**Issue by arwtyxouymz** [MaskRay/ccls#270]
Hi I use this in `neovim` with `LanguageClient-neovim` and it's the fastest complement in other complement tools in neovim!

But it's one problem about header completion.
Please look at this gif
![ccls_completion](https://user-images.githubusercontent.com/16755660/52957413-f3549200-33d4-11e9-8ef5-fced3f897e70.gif)

When i input `/` for header, the completion candidates from ccls disappear.
In contrast, input header directory and files without `/`, completion works.
It's strange. 

I'm sorry if this bug is due to `LanguageClient-neovim`.

**Comment by MaskRay** [comment]
I have tried two other language clients and they work when `/` is typed.

ccls announces in the `initialized` message that its `CompletionOptions` supports
```cpp
    std::vector<const char *> triggerCharacters = {".", ":",  ">", "#",
                                                   "<", "\"", "/"};
```

The client is expected to send a `textDocument/completion` request when `/` is typed (and set `CompletionTriggerKind.TriggerCharacter`).
