### ISSUE TITLE
GoToDefinition (involving templates) jumps to wrong template parameter

### ISSUE THREAD

**Issue by bfrg** [MaskRay/ccls#271]
In the following testcase `ccls` jumps to the wrong type declaration (example requires [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page)):
```cpp
// main.cpp
#include <Eigen/Dense>

struct mykernel {
    using vec = typename Eigen::Vector3d;
};

template <typename Kernel>
struct foo {
    using vec = typename Kernel::vec; // put cursor on 'Kernel' and then 'Go To Definition'
};

int main()
{
    foo<mykernel> f;
}
```

When I put the cursor on `Kernel` on the line with the comment, I would have expected `ccls` to have jumped to `typename Kernel` two lines above but instead it jumps to a [file](https://github.com/eigenteam/eigen-git-mirror/blob/master/Eigen/src/Core/AssignEvaluator.h#L196) of the Eigen library which also contains a template parameter `Kernel`.

**Comment by MaskRay** [comment]
This is known. The actual problem is that clangIndex does not traverse template parameters. If you use `$ccls/semanticHighlight`, you'll notice that `Kernel` as in `typename Kernel` is not highlighted (which means it is not indexed).

`textDocument/definition` on `Kernel` as in `typename Kernel::vec` uses a heuristic to locate the declaration/definition with the same same.

**Comment by bfrg** [comment]
I don't know how they do it, but it works fine with Qt-Creator which is also based on clang.

**Comment by MaskRay** [comment]
I know that qt-creator's Clang Code Model works. Its implementation is in https://github.com/qt-creator/qt-creator/blob/master/src/tools/clangbackend/source/clangfollowsymbol.cpp
That approach requires to maintain an AST for opened document and process such definition/declaration and is different from ccls's: global index based. I don't think qt-creator handles finding-definition in another file as its approach is obviously single translation unit based.

**Comment by MaskRay** [comment]
If you build clang from trunk (there are notes on https://github.com/MaskRay/ccls/wiki/Build), `Kernel` in `Kernel::vec` will jump to the correct definition. https://github.com/MaskRay/ccls/pull/279
