### ISSUE TITLE
Indexer can generate too long filenames

### ISSUE THREAD

**Issue by rwestberg** [MaskRay/ccls#275]
At least on MacOS (and probably other posix systems) the maximum length of a filename is limited by NAME_MAX, which is set to 255. If you happen to have your toolchain in a custom location, this limit may be exceeded. Here's an example error message (with some PII removed):

```
utils.cc:168 E failed to write to /Users/rwestberg/git/xxx/xxxxxx-xxx/build/xxxxxx-slowdebug/.ccls-cache/@@Users@rwestberg@git@xxx@xxxxxx-xxx@build@xxxxxx-slowdebug/@private@var@tmp@xxx-rwestberg@install@xxx@xxxxx@builddeps@xxxxxx-macosx_x64@Xcode9.4-MacOSX10.13+1.0@xxxxxx-macosx_x64-Xcode9.4-MacOSX10.13+1.0.tar.gz@Xcode.app@Contents@Developer@Platforms@MacOSX.platform@Developer@SDKs@MacOSX.sdk@usr@include@sys@ptrace.h File name too long
```

Can probably work around it using symbolic links and editing the compile_commands.json file, but would be nice if the indexer could handle this.

**Comment by MaskRay** [comment]
Can you try https://github.com/MaskRay/ccls/pull/278?

Set the [initialization options](https://github.com/MaskRay/ccls/wiki/Customization)
```javascript
{
 "cache": {
  "useHierarchy": true
 }
}
```

**Comment by rwestberg** [comment]
Works fine, thanks for fixing!
