### ISSUE TITLE
Standalone ccls server w/ multiple editors

### ISSUE THREAD

**Issue by jcorina** [MaskRay/ccls#277]
Hi there,

Is it possible to run a standalone ccls server for a given project that multiple vim instances can connect to?

**Comment by MaskRay** [comment]
I think it is possible to support language clients but the language clients should cooperate (hence the work is on the client side). The clients should ensure the buffer is closed in all clients before sending `textDocument/didClose`, etc. I don't think there is any multiplexer doing this.

Also be aware that ccls stores cache files in the filesystem. To avoid conflict, you may want to use different `cacheDirectory` (https://github.com/MaskRay/ccls/wiki/Customization#initialization-options). There will be duplication though.
