### ISSUE TITLE
make a workspace variable for relative include path

### ISSUE THREAD

**Issue by shelper** [MaskRay/ccls#282]
assume i have a project like below, and in my `foo.cc` i would like to do 
`#include "module2/bar.hh"`
currently it seems your ccls is not able to find bar.hh, and autocompletion of `"module2/bar.hh"` also is not working. To make it work, i have to include like below:
`#include "../../module2/bar.hh"`
i 've read your documentation for ccls over and over, and still could not figure out how to make this work... can you provide some insights on this? or would it be need to setup a `workspace` folder, from where the include can use relative path w.r.t. `workspace`? e.g., here the `workspace` would be `project\source`.

<img width="147" alt="screen shot 2019-02-23 at 6 39 51 pm" src="https://user-images.githubusercontent.com/546163/53293034-81949380-379a-11e9-8bb1-e417098e879b.png">

**Comment by MaskRay** [comment]
See https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html, you need a `-I/path/to/project/source/module1` (or `-Isource`).

**Comment by shelper** [comment]
I am further confused. Are we using `clang` or `gcc`? and where should i put this `-Isource` option? I tried to put it in `.ccls` file but it doesn't work.
