### ISSUE TITLE
pipeline.cc has something wrong

### ISSUE THREAD

**Issue by mstsai** [MaskRay/ccls#283]
source code as following
![image](https://user-images.githubusercontent.com/4119849/53297965-53c65200-3861-11e9-9f21-81af061ea259.png)

pipeline.cc:153 red box may cause a build failed, message is as following

![image](https://user-images.githubusercontent.com/4119849/53298000-bae40680-3861-11e9-950f-16ef992a2dc5.png)

Would variable src change to ret to correct the flow?

**Comment by MaskRay** [comment]
Thanks. It should be fixed in HEAD.

**Comment by mstsai** [comment]
Use msys2 in windows
cmake 3.12.4
clang 7.0.1
gcc 8.3.0

![image](https://user-images.githubusercontent.com/4119849/53298137-4363a680-3864-11e9-9ce2-0f0af4581a0b.png)

**Comment by MaskRay** [comment]
Interesting, MSVC doesn't support `%z` (size_t) so far.. but it shouldn't be a big issue.
