### ISSUE TITLE
missing dependency on rapidjson

### ISSUE THREAD

**Issue by holgerschurig** [MaskRay/ccls#285]
Hi,

neither the README.md nor the cmake checks for rapidjson. One get a compilation error if this library is not installed.

Also note that Debian Sid's default rapidjson 0.12~git20141031+dfsg-1 isn't usable, because it doesn't contain the needed `rapidjson/fwd.h` file.

**Comment by FirstLoveLife** [comment]
it is used as a git submodule. https://github.com/MaskRay/ccls/blob/master/.gitmodules#L1

**Comment by MaskRay** [comment]
> Debian Sid's default rapidjson 0.12~git20141031+dfsg-1 isn't usable

That old version isn't usable. If you did't use `--recursive` when you cloned ccls, `git submodule update --init`
