### ISSUE TITLE
ccls-on-mac crash(clang crash)

### ISSUE THREAD

**Issue by gggin** [MaskRay/ccls#286]
addon is my compile_commands.json it's so big, so I 7z. but github only support zip so I rename to zip. but it's 7z.
[compile_commands.json.zip](https://github.com/MaskRay/ccls/files/2904645/compile_commands.json.zip)

I compile chromium on macos with the chromium default build, I built content_shell.
And then, I use ccls-vscode + ccls(my release build), the log said clang crash(almost every file).

**Comment by MaskRay** [comment]
You don't need to paste the full `compile_commands.json`, just a few entries should be sufficient, as most follow the same pattern.

These `-Xclang` options are suspicious
` -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang enforce-in-thirdparty-webkit -Xclang -plugin-arg-find-bad-constructs -Xclang check-enum-max-value `

Can you delete them?

You may change `clang <options> a.cc` to `c-index-test -index-file <options> a.cc` and see if it crashes. You can delete risky options until `c-index-test` exits cleanly. When you are done, use `compilationDatabaseCommand` (https://github.com/MaskRay/ccls/wiki/Project-Setup).

Closing as I believe this isn't a ccls issue.

**Comment by gggin** [comment]
When I use 
```bash
ninja -C out/Debug -t compdb cxx cc > compile_commands.json
```
for generation in Ubuntu it's all good.
Then I found that some chromium file are in `out/Debug/gen/..` And I delete the folder for space. So the crash maybe the header isn't exists? or -Ifolder isn't exists? when I re generate `out/Debug/gen/..` the problem is gone. Thank you very much!

**Comment by MaskRay** [comment]
> the log said clang crash(almost every file).

Please the related log lines. `clang crashed for ...` is different from `failed to index ...`

> when I re generate `out/Debug/gen/..` the problem is gone.

Some generated source files/header files are used directly or indirectly (via `#include`).

**Comment by gggin** [comment]
the log is really `clang crashed for`, but now I cannot reproduce that, and there is another crash.

https://github.com/MaskRay/ccls/issues/289

**Comment by MaskRay** [comment]
I just created an issue template https://github.com/MaskRay/ccls/blob/master/.github/ISSUE_TEMPLATE

Can you fill out the form?

**Comment by gggin** [comment]
git log hash 4cc9dda99434fbfb439ccb80040fa5080ea80625
OSX 10.13.2
clang+llvm-7.0.0-x86_64-apple-darwin
vscode-ccls
the crash stack is in another issue.

After many times try, I found that if I open vscode and wait for index everthing is good, but if I open a file in compile_commands.json when ccls is indexing the crash is happened!

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/blob/master/.github/ISSUE_TEMPLATE

https://github.com/MaskRay/ccls/wiki/Debugging

Can you attach the ccls process with a debugger and dump call stack and local variables near https://github.com/maskray/ccls/blob/master/src/indexer.cc#L1289 ?
