### ISSUE TITLE
Using optional and string_view

### ISSUE THREAD

**Issue by holgerschurig** [MaskRay/ccls#287]
utils.hh (but also other files) have statements like

    #include <optional>
    #include <string_view>

But the C++ compiler of Debian Stable isn't finding those, 

See also https://stackoverflow.com/questions/38253971/std-optional-no-such-file-or-directory.

I guess that the default 6.3.0-18+deb9u1 is simply too old.

Hint: if the project depends on llvm/clang >= 6, then maybe it should simply use clang-6, clang-7 or clang-8 for compilation instead of gcc?

**Comment by holgerschurig** [comment]
Hmm, while clang-8 might support this newer C++ standard, it doesn't have this optional include file.

It is in libc++-dev or libc++-6-dev, which are both older than the C++17 standard.

**Comment by MaskRay** [comment]
> But the C++ compiler of Debian Stable isn't finding those,

https://github.com/MaskRay/ccls/wiki/Build

`GNU GCC 7.2 or higher (optional,string_view require libstdc++7 or higher)`

> It is in libc++-dev or libc++-6-dev, which are both older than the C++17 standard.

On Linux, clang uses header files from libstdc++ (usually `/usr/include/c++/[6-8]`) by default. To use libc++, you need cxxflags and ldflags `-stdlib=libc++`
