### ISSUE TITLE
Spacemacs cache directory changed

### ISSUE THREAD

**Issue by bb4242** [MaskRay/ccls#288]
I think a recent commit (2fc2d1b16ca239f4d56ced02cbdb885ef345dce1) changed the behavior of where ccls stores its cache directory, at least when run under spacemacs.  Previously, the ccls cache was stored in a directory specified by the `c-c++-lsp-cache-dir` variable, which by default was set to `$HOME/.emacs.d/cache/lsp-ccls`.  Now, ccls seems to ignore that variable and instead places the cache in the root project directory.  Definitely not a big deal, but I'm just wondering if this change in behavior was intended?

**Comment by MaskRay** [comment]
It is changed by https://github.com/MaskRay/ccls/commit/2fc2d1b16ca239f4d56ced02cbdb885ef345dce1
The change is intended.

The wiki pages (e.g. https://github.com/MaskRay/ccls/wiki/Customization) have also been updated.

Can you file a issue in the spacemacs repo?

**Comment by myrgy** [comment]
I did PR to Spacemacs https://github.com/syl20bnr/spacemacs/pull/12014

**Comment by bb4242** [comment]
Thanks @MaskRay and @myrgy! :)

**Comment by smile13241324** [comment]
Merged
