### ISSUE TITLE
How can I find `/path/to/ccls/release/ccls` after installing from aur/ccls-git

### ISSUE THREAD

**Issue by FirstLoveLife** [MaskRay/ccls#29]
Environment: Arch Linux
Installation: `yaourt -S ccls-git`

Frome [MaskRay/emacs-ccls](https://github.com/MaskRay/emacs-ccls#quickstart): 

```
(require 'ccls)
(setq ccls-executable "/path/to/ccls/release/ccls")
```

After install `ccls-git` via `yaourt`, I used `locate ccls` to look for the `path`: 

```
400 ◯ : locate ccls                                                                                                                                                 ⏎ 
/home/chenli/.emacs.d/.cache/quelpa/melpa/recipes/ccls
```

But I failed. How can I find the path?

**Comment by MaskRay** [comment]
Please see my comment at https://aur.archlinux.org/packages/ccls-git Arch Linux `extra/clang 6.0.0-1` is known to have the "libclang crash ..." issue.

`aur/ccls-git` should install the executable (ccls language server) to `/usr/bin/ccls`. The file you pasted `.emacs.d/.cache/quelpa/melpa/recipes/ccls` is a Melpa recipe https://github.com/melpa/melpa/blob/master/recipes/ccls

@SyrakuShaikh has tried `aur/llvm-libs-svn` which seems to work with `aur/ccls-git` https://github.com/MaskRay/ccls/issues/25#issuecomment-403204474
