### ISSUE TITLE
index format with less memory usage.

### ISSUE THREAD

**Issue by kvaneesh** [MaskRay/ccls#290]
With the source code like Linux kernel, I am finding memory usage of a few Gigabytes. I know you looked at clangd index format earlier and rejected the idea. With the dex format do you think that can be looked at as an alternative? I read it work efficiently with a large code base.

**Comment by MaskRay** [comment]
clangd/index/dex is not designed for saving memory usage, but for improving performance of string lookup. It uses trigrams which actually increases memory usage a lot. For a project as large as llvm, the number of functions is in the scale of 200000. Most people work on projects smaller than this scale. I forget my last measurement but Linux kernel is of the similar scale of llvm's. For less-frequent requests like `workspace/symbol`, brute-force string comparison is probably the best approach. dex makes it faster but I doubt the value to do so.

There are other features that may be sped by an index format: index-based completion, include fixer, etc. I may at some point implement similar things but don't think dex is something ccls should adopt.
