### ISSUE TITLE
ccls does not quit after hitting EOF of stdin

### ISSUE THREAD

**Issue by Riatre** [MaskRay/ccls#297]
### Observed behavior

I can sometimes find obsolete ccls processes in my system. Look likes their parent process (editor) crashed so they didn't get killed. But since the stdin of these processes were already closed they should exit.

`pstree -t` looks like:
```
systemd─┬─agetty
        ├─2*[ccls─┬─{comp}]
        │         ├─{diag}]
        │         ├─{indexer0}]
        │         ├─{indexer10}]
        │         ├─{indexer11}]
        │         ├─{indexer1}]
        │         ├─{indexer2}]
        │         ├─{indexer3}]
        │         ├─{indexer4}]
        │         ├─{indexer5}]
        │         ├─{indexer6}]
        │         ├─{indexer7}]
        │         ├─{indexer8}]
        │         ├─{indexer9}]
        │         ├─{preamble}]
        │         └─{stdout}]
        ├─ccls─┬─{comp}
        │      ├─{diag}
        │      ├─{preamble}
        │      └─{stdout}
```

Notice that there are no stdin thread among them.

This can also be easily reproduced by executing ccls in terminal and press Ctrl+D.

### Expected behavior

ccls should exit after hitting EOF of stdin.

### Steps to reproduce

1. Build ccls from d3a3bcef3426481231030bbfd850fa86a1b02e1a
2. Run `./ccls` in terminal.
3. Hit Ctrl+D.

**Comment by MaskRay** [comment]
When the "stdin" thread exits, it doesn't set `pipeline::quit` to true thus the main thread isn't notified. Does https://github.com/MaskRay/ccls/pull/300 fix this issue?

**Comment by MaskRay** [comment]
When the "stdin" thread exits, it doesn't set `pipeline::quit` to true thus the main thread isn't notified. Does https://github.com/MaskRay/ccls/pull/300 fix this issue?

**Comment by Riatre** [comment]
Unfortunately it doesn't, so I decided to dig a little bit deeper.

1. There are two more return paths from stdin thread function:
https://github.com/MaskRay/ccls/blob/e18165b4f20dbe3f44a5a72c39d477d20d94615b/src/pipeline.cc#L513
https://github.com/MaskRay/ccls/blob/e18165b4f20dbe3f44a5a72c39d477d20d94615b/src/pipeline.cc#L529

2. `MultiQueueWaiter::Wait` waits indefinitely on the `on_indexed` and `on_request` (originated from https://github.com/MaskRay/ccls/blob/e18165b4f20dbe3f44a5a72c39d477d20d94615b/src/pipeline.cc#L680 )

I can confirm that after patching these places (with the following hacky patch) ccls is able to exit as expected.

```diff
diff --git a/src/pipeline.cc b/src/pipeline.cc
index 8645ca4a..243fb794 100644
--- a/src/pipeline.cc
+++ b/src/pipeline.cc
@@ -32,6 +32,7 @@ limitations under the License.
 #include <llvm/Support/Path.h>
 #include <llvm/Support/Process.h>
 #include <llvm/Support/Threading.h>
+#include <llvm/ADT/ScopeExit.h>

 #include <chrono>
 #include <mutex>
@@ -502,6 +503,11 @@ void LaunchStdin() {
   ThreadEnter();
   std::thread([]() {
     set_thread_name("stdin");
+    auto fini = make_scope_exit([]() {
+      quit.store(true, std::memory_order_relaxed);
+      ThreadLeave();
+    });
+
     std::string str;
     const std::string_view kContentLength("Content-Length: ");
     while (true) {
@@ -560,8 +566,6 @@ void LaunchStdin() {
       if (should_exit)
         break;
     }
-    quit.store(true, std::memory_order_relaxed);
-    ThreadLeave();
   }).detach();
 }

diff --git a/src/threaded_queue.hh b/src/threaded_queue.hh
index 103027aa..b7c37614 100644
--- a/src/threaded_queue.hh
+++ b/src/threaded_queue.hh
@@ -71,9 +71,10 @@ struct MultiQueueWaiter {
   bool Wait(std::atomic<bool> &quit, BaseThreadQueue... queues) {
     MultiQueueLock<BaseThreadQueue...> l(queues...);
     while (!quit.load(std::memory_order_relaxed)) {
+      using namespace std::chrono_literals;
       if (HasState({queues...}))
         return false;
-      cv.wait(l);
+      cv.wait_for(l, 1s);
     }
     return true;
   }
```

**Comment by MaskRay** [comment]
Thanks for investing it. I've changed #300 a bit. Does it work now?

**Comment by Riatre** [comment]
Works for me, thanks.

**Comment by MaskRay** [comment]
Cherry-picked #300
