### ISSUE TITLE
ccls does not working correctly on u-boot and linux kernel, while cquery works well

### ISSUE THREAD

**Issue by kaijajan** [MaskRay/ccls#299]
### Observed behavior

ccls does not working correctly on u-boot and linux kernel, while cquery works well

with the same compile_commands.json, tested on the following projects

1. live555 (with 200 KB compile_commands.json generated)

all functions work perfect, completion, find reference, rename, document, defination

2. ffmpeg-4.1.1 (with 3 MB compile_commands.json generated, default configuration with no specific flags)

all functions work perfect, completion, find reference, rename, document, defination

3. linux kernel, u-boot (TI Processor SDK 5.02)

pretty much everything not working at all
tried remove "march" flag, same result for ccls, but cquery works after removing flag (cquery bug)

turn on languageclient debug mode

```
let g:LanguageClient_loggingLevel='DEBUG'
let g:LanguageClient_loggingFile='/tmp/languageclient.log'
```

get the following message while finding defination

```
Error: ErrorMessage { msg: "Error: Failure { jsonrpc: Some(V2), error: Error { code: InvalidRequest, message: \"not indexed\", data: None }, id: Num(2) }" }
17:15:59 INFO unnamed src/rpcclient.rs:137 => None {"jsonrpc":"2.0","error":{"code":-32603,"message":"Error: Failure { jsonrpc: Some(V2), error: Error { code: InvalidRequest, message: \"not indexed\", data: None }, id: Num(2) }"},"id":1
```

### Expected behavior

everything works

### System information

- ccls version (`git describe --tags`): 5c5bbb956ba72c073287e2771b3e799444e6cf77 (commit sha1 value)
- OS: ubuntu 16.04
- Editor: neovim
- Language client (and version):
  ccls version: 7.0.1 (tags/RELEASE_701/final)
  cquery version: latest version (project dead)

coc.nvim and languageclient-neovim both tested
also, cross tested on different combination
coc.nvim + cquery (ok)
languageclient-neovim + cquery (ok)
coc.nvim + ccls (failed on linux kernel, u-boot, but work great on ffmpeg + live555)
languageclient-neovim + ccls (failed on linux kernel, u-boot, but work great on ffmpeg + live555)

folder structure:
```
root/
  compile_commands.json
```

**Comment by MaskRay** [comment]
Thanks for sharing you experience with live555 and ffmpeg!

For Linux kernel, you need to filter out some options, including at least the following:
```
      "-falign-jumps=1" "-falign-loops=1" "-fconserve-stack" "-fmerge-constants" "-fno-code-hoisting" "-fno-schedule-insns" "-fno-var-tracking-assignments" "-fsched-pressure"
       "-mhard-float" "-mindirect-branch-register" "-mindirect-branch=thunk-inline" "-mpreferred-stack-boundary=2" "-mpreferred-stack-boundary=3" "-mpreferred-stack-boundary=4" "-mrecord-mcount" "-mindirect-branch=thunk-extern" "-mno-fp-ret-in-387" "-mskip-rax-setup"
       "--param=allow-store-data-races=0" "-Wa arch/x86/kernel/macros.s" "-Wa -"
```

You can achieve that with the initialization option `clang.excludeArgs`

**Comment by MaskRay** [comment]
Oh, `compile_commands.json` can be gererated with this script

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b30204640192234d18f9168f19f9cd693485b86d

```sh
make defconfig
make
scripts/gen_compile_commands.py
```

**Comment by MaskRay** [comment]
ccls on HEAD supports glob patterns in `clang.excludeArgs`. You may customize initialization options like this: `{"clang":{"excludeArgs":["-m*", "-Wa*"]}}`

I believe most `-m` options can be simply filtered out. Some `-f` options may affect language options, it is good to filter out only bad ones.

**Comment by kaijajan** [comment]
Thanks for replying me :)

I figured out finally, because of the folder structure, which caused incorrect (or my misunderstanding) result.

1. root issue

folder structure
```
root/
  .git
  linux/ <---- where I open nvim and coding
    compile_commands.json
  uboot <---- where I open nvim and coding
    compile_commands.json
```

coc-settings.json
```
"rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"]
```

after simply traced ccls source code, i noticed ccls does not treat linux or uboot folder as root workspace, but using "root" as root workspace instead

not quite sure if this behavior is correct or is my misunderstanding of the rootPatterns setting

and i'm not really familiar with modern c++, so that unable to find out the root cause


2.  clang.excludeArgs does not working, and I have to manually use sed to remove all -m*, -Wa* -f* to get ccls work


Really thanks for this great work, and performance/accuracy is amazing.
