### ISSUE TITLE
Packaging ccls - testsuite and third_party modules?

### ISSUE THREAD

**Issue by dcermak** [MaskRay/ccls#305]
Hi @MaskRay, thanks for your work on ccls! I have recently switched to it from cquery and haven't looked back.

I am currently working on packaging ccls for OpenSUSE and wanted to ask whether ccls has a testsuite that I could include in the package building process to verify that ccls works as expected? I see that there is the subdirectory `index_tests` but I haven't found it referenced in `CMakelists.txt`. Can I compile and run these or are they not guaranteed to work?

Also, ccls bundles some third party software (fortunately very little, thanks for that! It makes my job so much easier). Bundling dependencies is generally frowned upon when building packages for Linux distributions, thus I'd like to unbundle some of these if possible. Rapidjson is present in most distributions, so that is not a problem. `macro_map.h` is heavily modified and no longer in the upstream repository, so I'd just keep that bundled.

Concerning `siphash.{cc|h}`, is this based on the reference SipHash implementation from this project https://github.com/veorq/SipHash? If yes, would you consider adding the other project as a submodule like you did with with rapidjson or accept a pull request doing that? This would make it clearer for packagers where this dependency comes from.

**Comment by MaskRay** [comment]
> I see that there is the subdirectory index_tests but I haven't found it referenced in CMakelists.txt.

I have to say sorry that ccls has very nearly no test at present. At some point I should add some. `index_tests/` is used to check the behavior of the indexer. However, the result can vary across different llvm/clang versions. I build llvm/clang from trunk but I don't expect others to do the same. So `index_tests/` really has very little value to an end user.

> Concerning siphash.{cc|h}, is this based on the reference SipHash implementation from this project https://github.com/veorq/SipHash?

Yes, the only non-bundled thirty-party library is rapidjson. `third_party/siphash.cc` (you may have noticed it, it is `.cc`, not `.c` to simplify the cmake configuration as I'm not confident to work with cmake :( Not sure making a git submodule is a good thing as with the current approach, ccls just imports 172 lines of code. ccls will not benefit much from following its development.

**Comment by dcermak** [comment]
> > I am currently working on packaging ccls for OpenSUSE
> 
> Really appreciate that. Now sure how OpenSuse packaging works but I find an old version https://build.opensuse.org/package/show/home:nuklly/ccls (I may soon create a patch version for the 0.20190301 release)

Thanks for the pointer, I'll take a look at that package.

> 
> You can also consider adding a section on https://github.com/MaskRay/ccls/wiki/Build

I intend to get it into the main openSUSE repositories, once it lands, I'll notify you and add an entry to the wiki.

> 
> > I see that there is the subdirectory index_tests but I haven't found it referenced in CMakelists.txt.
> 
> I have to say sorry that ccls has very nearly no test at present. At some point I should add some. `index_tests/` is used to check the behavior of the indexer. However, the result can vary across different llvm/clang versions. I build llvm/clang from trunk but I don't expect others to do the same. So `index_tests/` really has very little value to an end user.

I might be able to help out a little here, but unfortunately my time is currently rather limited. I'll create a new discussion issue about this (but from my private account).

> 
> > Concerning siphash.{cc|h}, is this based on the reference SipHash implementation from this project https://github.com/veorq/SipHash?
> 
> Yes, the only non-bundled thirty-party library is rapidjson. `third_party/siphash.cc` (you may have noticed it, it is `.cc`, not `.c` to simplify the cmake configuration as I'm not confident to work with cmake :( Not sure making a git submodule is a good thing as with the current approach, ccls just imports 172 lines of code. ccls will not benefit much from following its development.

Well the advantage of a git submodule is, that you don't have to follow its development, you simply insert a snapshot of the repository. Nevertheless, given that the upstream repository has had no code related activity for two years **and** literally no Linux distribution packages siphash **and** they provide no official way how to consume it as a library (e.g. via CMake) **and** it would complicate your work, I see very little actual benefit of undertaking that work. Thus I'd leave it bundled for the package.

**Comment by MaskRay** [comment]
Thanks to @FirstLoveLife for https://github.com/MaskRay/ccls/pull/306

I added a cmake option `-DUSE_SYSTEM_RAPIDJSON=on` to use system rapidjson if available https://github.com/MaskRay/ccls/pull/308

**Comment by dcermak** [comment]
@MaskRay @FirstLoveLife Thanks for that!

FYI: in the past versions you can simply not initialize the git submodule and have rapidjson installed on your system. Everything will then still work, as the C++ compiler only needs to find the rapidjson headers, which are usually in the include path.

But this solution is a lot cleaner.
