### ISSUE TITLE
Function pointer completion items should be snippets

### ISSUE THREAD

**Issue by yshui** [MaskRay/ccls#312]
### Observed behavior
Example code:

```c
int (*functionpointer)(int a, int b);
int main() {
	functionpointer | // <- cursor
}
```
`functionpointer` show up as one of the candidates, but it is as a variable, not a snippet.

### Expected behavior
The completion items should include `functionpointer`, and it should be a snippet.

### System information

* ccls version (`git describe --tags`): 0.20190308
* Editor: nvim + coc.nvim

**Comment by MaskRay** [comment]
A function pointer is indeed a variable, isn't it?

```c
int (*functionpointer)(int a, int b);
int main() {
	functionpointer = 0;
}
```

**Comment by yshui** [comment]
But it would be convenient if they are completed as snippet, because often times one could want to call them.

**Comment by MaskRay** [comment]
```cpp
int (*functionpointer)(int a, int b);
void (function)(int a, int b) {}
int main() {
  functionpointer = 0;
}
```

```zsh
% c-index-test -code-completion-at=a.cc:4:4 a.cc | grep function
FunctionDecl:{ResultType void}{TypedText function}{LeftParen (}{Placeholder int a}{Comma , }{Placeholder int b}{RightParen )} (50)
VarDecl:{ResultType int (*)(int, int)}{TypedText functionpointer} (50)
```
