### ISSUE TITLE
Default value of option completion.detailedLabel makes ccls unusable in lsp compliant implementations

### ISSUE THREAD

**Issue by ElArtista** [MaskRay/ccls#318]
Using ccls with vim/vim-lsp by default we get non sensible autocompletion behavior compared to clangd.

Here is an example of ccls completion with a minimal setup:
![image](https://user-images.githubusercontent.com/4622346/54149966-11476c80-4440-11e9-9253-9136f4bb27c6.png)

As you can see the type of the member is also inserted into the buffer along with the name.
After lots of digging around I found out this is a side effect of the `completion.detailedLabel`
option, that as stated by the wiki does this:

```
When this option is enabled, label and detailed are re-purposed:

label: detailed function signature, e.g. foo(int a, int b) -> bool
detailed: the name of the parent context, e.g. in S s; s.<complete>, the parent context is S.
```

That though, is not compliant to the lsp specification as we can see on the official page and protocol interface snippets:
https://microsoft.github.io/language-server-protocol/specification
```
interface CompletionItem {
	/**
	 * The label of this completion item. By default
	 * also the text that is inserted when selecting
	 * this completion.
	 */
	label: string;
        ...
        /**
	 * A human-readable string with additional information
	 * about this item, like type or symbol information.
	 */
	detail?: string;
```

So this option, despite having some useful usage somewhere, I think that it should be disabled by default to avoid confusion with perfectly compliant lsp configurations.

After disabling this option I noticed another minor (cosmetic) issue bellow:

The default pattern in the detail value seems kinda verbose for no reason, for example:
![image](https://user-images.githubusercontent.com/4622346/54150916-4eacf980-4442-11e9-9419-a7963e8d7da1.png)
The completion field is shown both in the `label` value (as it should) and in the `detail` value (excessive).

The same output from clangd for reference:
![image](https://user-images.githubusercontent.com/4622346/54150930-579dcb00-4442-11e9-97f0-97f89c39e0bf.png)

Link to the code that is relevant for the above:
https://github.com/MaskRay/ccls/blob/cbe875df5c104cd82cec238484853be0ea76e8e6/src/messages/textDocument_completion.cc#L395

**Comment by MaskRay** [comment]
> As you can see the type of the member is also inserted into the buffer along with the name.

The root cause is that the language client doesn't support `CompletionItem.textEdit`. ccls really requires it, otherwise the experience may be really bad. And I don't bother add compatibility code as `insertText` should really be deprecated.

> The default pattern in the detail value seems kinda verbose for no reason, for example:

That is true, but the result may look less ugly if `detail` not available but instead, shown as a tooltip when you select the completion item.
