### ISSUE TITLE
Incorrectly parsing include paths which end in trailing space

### ISSUE THREAD

**Issue by rgreenblatt** [MaskRay/ccls#321]
If an include path in .ccls ends with a trailing space, the path is incorrectly parsed.

For instance (note the trailing space):

-I/usr/include/something 

Will get parsed into:

/usr/include/something /

Then, any headers associated with the path aren't found.

I observed this using the CocInfo ccls output stream. Might not be a big problem, but I would imagine this would be simple to fix.

My system:
LLVM and clang 7
Ubuntu 18.1
coc.nvim
ccls 0.20190308

**Comment by MaskRay** [comment]
If you write `-I/usr/include/something ` in `.ccls`, it is as if you write `'-I/usr/include/something '` on the clang command line. "Then, any headers associated with the path aren't found." would be expected.
