### ISSUE TITLE
ccls should not search system include path if sysroot or gcc-toolchain is specified

### ISSUE THREAD

**Issue by kaijajan** [MaskRay/ccls#323]
### Observed behavior

no matter sysroot or gcc-toolchain specified, ccls always searches system include path first for standard libraries instead of searching specified compiler's toolchain
very obvious in "@@" folder, always search /usr/include and while using go to definition always loads header files in /usr/include
ccls even searches llvm headers which  used to building ccls itself (clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04@lib@clang@7.0.1@include  was found under ccls cache @@ folder )

### Expected behavior
since standard c headers can be vary, so that while cross toolchain flag specified, ccls should ignore system default include path

**Comment by MaskRay** [comment]
```
% pwd
/tmp/c
% ls -A
basic_freebsd64_tree/  a.c  .ccls
% cat a.c
#include <stdio.h>
% cat .ccls
clang
--sysroot=basic_freebsd64_tree
```

`/tmp/c/@@tmp@c/` is empty (no `@usr@include...`).

`--gcc-toolchain` does not suppress detection of default search paths.

**Comment by kaijajan** [comment]
Sorry did not describe the issue clearly, i recorded a video to present what issue i encountered.

https://youtu.be/j8VwI1IH0xo

The first few seconds shows the folder was before ccls cache built, and .ccls file
After executing neovim, appeared 1 warning and 1 error.
The warning message while hovered on uv_loop_new was implicit declatation
and error message on SIGINT used of undeclared identifier.
During this phase, goto definition seems to work well.
But the diagnostic messages were anonying, even the compiling process were fine.

At 32, 33 sec, I entered "gq" command, which map to CocRestart command.
It forces coc to restart, and everything looks good. No errors and no warnings.
But goto definition will search /usr/include at the time.

**Comment by kaijajan** [comment]
The above was using .ccls file.
Things went differently while using compile_commands.json
Printf function does not recognized even after restarting coc.nvim 

https://youtu.be/z8upTPuTd0Y

compile_commands.json
```
[
   [undefined] [W] Incorrect type. Expected "object".
      ¦   "arguments": [
      ¦   ¦   "/mnt/workspaces/bsp/ti-processor-sdk-linux-am437x-evm-05.02.00.10/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/arm-linux-gnueabihf-gcc",
      ¦   ¦   "-c",
      ¦   ¦   "-I/mnt/workspaces/bsp/ti-processor-sdk-linux-am437x-evm-05.02.00.10/test/libuv-1.26.0/include",
      ¦   ¦   "--sysroot=/mnt/workspaces/bsp/ti-processor-sdk-linux-am437x-evm-05.02.00.10/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi",
      ¦   ¦   "-nobuiltininc",
      ¦   ¦   "-o",
      ¦   ¦   "release/test.o",
      ¦   ¦   "test.c"
      ¦   ],
      ¦   "directory": "/mnt/workspaces/bsp/ti-processor-sdk-linux-am437x-evm-05.02.00.10/test/app",
      ¦   "file": "test.c"
      },
      {
      ¦   "arguments": [
      ¦   ¦   "/mnt/workspaces/bsp/ti-processor-sdk-linux-am437x-evm-05.02.00.10/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/arm-linux-gnueabihf-gcc",
      ¦   ¦   "-c",
      ¦   ¦   "-I/mnt/workspaces/bsp/ti-processor-sdk-linux-am437x-evm-05.02.00.10/test/libuv-1.26.0/include",
      ¦   ¦   "--sysroot=/mnt/workspaces/bsp/ti-processor-sdk-linux-am437x-evm-05.02.00.10/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi",
      ¦   ¦   "-nobuiltininc",
      ¦   ¦   "-o",
      ¦   ¦   "release/test1.o",
      ¦   ¦   "test1.c"
      ¦   ],
      ¦   "directory": "/mnt/workspaces/bsp/ti-processor-sdk-linux-am437x-evm-05.02.00.10/test/app",
      ¦   "file": "test1.c"
      }
  ]
```

**Comment by kaijajan** [comment]
include order also affects diagnostic messages

![local header behind](https://i.imgur.com/ebkfP2V.png)
![local header at beginning](https://i.imgur.com/12CHByL.png)

these issues only observed in cross toolchain so far.

**Comment by kaijajan** [comment]
Finally figured out why diagnostic messages popped up
I use *clang-check* to check the issue.
One of the issue is stddef not found which is described in FAQ.
And the others are caused by cross compiling flags. (e.g. -marm, -mfloat-abi, ...)
Some cross c headers treat these flags as define, so that replace the flag to appropriate define could solve the issue.

**Comment by MaskRay** [comment]
Relative --sysroot did not work. Worked around on 2019-11-09 by 444f0db1f2d617db545591367bbce75f9afa5d49

**Comment by pvonmoradi** [comment]
@MaskRay I'm experiencing this issue with arm-none-eabi-gcc compiler. When I `#include "stdio"`, CCLS jumps to /usr/lib defs instead of arm ones.
