### ISSUE TITLE
ccls doesn't exit after its project directory is deleted

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#328]
### Observed behavior

I use git worktrees almost exclusively which means I'm often visiting a new workspace, causing a new ccls to be started, then I hack on it for a few days, then I finish the change and push it and delete the worktree.

However, I just noticed that all the ccls instances from my old, deleted workspaces are still running.  Since there's really no way to tell, based on the command line / ps output, which one is using which workspace I relied on the /proc/<PID>/cwd value, which shows for a deleted workspace:
```
$ ll /proc/2476/cwd
lrwxrwxrwx 1 ms ms 0 Mar 19 16:41 /proc/2476/cwd -> '/work/ms/bug-25255/Foundation (deleted)'
```
I can then use `kill 2476` to kill that ccls.  But then my Emacs complains to me:
```
Server ccls:2476 exited with status signal. Do you want to restart it? (y or n) 
```

### Expected behavior

What I would like is two-fold:

First, ccls can wake up and notice that its project directory has disappeared, and if that happens it should exit (maybe with a message) on its own.

Second, there should be some way for an LSP server to notify the client that it is exiting "for good cause" (like the workspace disappeared) and that it should not be restarted.  I don't know if that exists already, or how much of it should be implemented in lsp-mode vs ccls vs ccls-emacs etc. but it would be nice if lsp-mode could give me a status area message but NOT ask to restart, since that won't help.

### System information

* ccls version (`git describe --tags`): 0.20190314
* OS: GNU/Linux (Ubuntu 18.04)
* Editor: Emacs 26.1
* Language client (and version): lsp-mode-20190310.2011

**Comment by MaskRay** [comment]
My first impression is https://github.com/MaskRay/ccls/issues/297 but that issue has been resolved. When the "stdin" thread receives EOF, it will exit.

I think this is probably more of a client-side issue. The client (lsp-mode) should send an [`exit` notification](https://microsoft.github.io/language-server-protocol/specification#exit) but for some reasons it doesn't. The background ccls processes do not receive `EOF` and are just waiting for future requests.

**Comment by madscientist** [comment]
Why should the client send an exit notification?  It has no idea that the worktree has disappeared.  I've deleted it by hand from the command line.  I'm not aware of any facility in Emacs that will do that, and notify lsp-mode that it was done.

**Comment by MaskRay** [comment]
After deleting a worktree, you have to close buffers separately and tell the language client to shutdown. On the language server side, I think it is totally fine to have temporarily unavailable files. Say you open `a.cc` or a directory `d` in Emacs and then delete them, ccls is still functioning. Later you may bring back `a.cc` and `d`.

```elisp
(defcustom lsp-keep-workspace-alive t
  "If non nil keep workspace alive when the last workspace buffer is closed."
  :group 'lsp-mode
  :type 'boolean)
```

You may want to set this variable to `nil`.

**Comment by madscientist** [comment]
I'm talking about the project directory itself being deleted, not just a file here or there.  I agree that individual files going away should not cause the server to exit.  However if the entire project directory is deleted it's a fair bet to close down the ccls server.  Even if the project does come back, you'll likely have to restart the server since your cache was deleted (at least for people who leave the cache in the project directory, which definitely anyone using this worktree style will since otherwise you have to go clean them up by hand).

Or, maybe you could shut down ccls if the cache directory is deleted: for me that would be sufficient since it happens at the same time as the project directory being deleted.

However, I'll look at lsp-keep-workspace-alive as an alternative.  It's not quite as good, though, because sometimes I delete my last Emacs buffers but still have the ccls server running.  It would be better or more accurate, IMO, if ccls terminated itself if the project directory disappeared.

**Comment by MaskRay** [comment]
> I'm talking about the project directory itself being deleted, not just a file here or there. 

My words apply to the project directory, too. ccls doesn't have excessive filesystem events unless you tell it to. Though weird, I think it is reasonable to wipe out the project directory and re-create it while using the same ccls process.

And check my note about existing filesystem watch mechanism that has to be used on the client side. You may file a feature request to lsp-mode.

**Comment by madscientist** [comment]
I guess we'll just have to disagree about this.  Given the amount of resources ccls will consume, having it still running when workspaces are removed is not good.  Forcing all the clients to implement some capability to shut it down, either automatically or by hand, seems like a suboptimal solution.

I wasn't thinking of excessive filesystem events: I was thinking ccls could wake up if it hadn't received a request from the client with 1 minute, or 5 minutes, or something and verify that the content still existed then either exit or go back to waiting.

I don't agree that deleting then recreating the workspace is something ccls should try to survive, but what about the cache?  If I delete the ccls cache then I see lots of errors in the logs about failing to write cache files / no such file or directory etc.  Having ccls exit when the cache was deleted would accomplish my goals as well.

**Comment by madscientist** [comment]
Regarding the client handling this: the problem is that the client may not be watching.  I will often use `C-x C-b` to view all my Emacs buffers and delete all of them for a given workspace, including the magit: buffer etc., then I go to my shell prompt and delete the workspace.  There's no reason that lsp-mode can or should be watching any content in my workspace anymore, and notice it disappeared.

On the other hand, when I delete the last buffer in Emacs for a given workspace it's not necessarily the case that I will be deleting the workspace, so I don't necessarily want ccls to exit.
