### ISSUE TITLE
Semantic highlighting offsets are wrong when line endings are CRLF

### ISSUE THREAD

**Issue by jackguo380** [MaskRay/ccls#329]
### Observed behavior

When ccls publishes `$ccls/publishSemanticHighlight` it uses byte offsets by default instead of the LSP standard range. The byte offsets are incorrect when the file has CRLF (`\r\n`) line endings. Instead of counting these line endings as 2 bytes ccls counts each line ending as 1 byte. So after 1 line the highlighting is off by 1 character. Some more investigation was done at jackguo380/vim-lsp-cxx-highlight#1.

### Expected behavior

The offsets should be correct.

### Steps to reproduce

I reproduced this using some ccls code specifically [src/test.hh](https://github.com/MaskRay/ccls/blob/master/src/test.hh) since it is small. ccls was indexed using the `compile_commands.json` generated with cmake option `-DCMAKE_EXPORT_COMPILE_COMMANDS=1`.

1. Ensure ccls is initialized with `highlight.lsRanges = false`
2. Convert file to CRLF `$ unix2dos src/test.hh`
3. Open the file and notice that the highlighting is incorrect.

Heres a captured message from ccls.
```json
{"method":"$ccls/publishSemanticHighlight","jsonrpc":"2.0","params":
{"uri":"file:///home/guoj/.vim/ccls/src/test.hh","symbols":[
{"id":121,"lsRanges":[],"storage":0,"kind":3,"ranges":[{"R":688,"L":684}],"parentKind":0},
{"id":108,"lsRanges":[],"storage":0,"kind":3,"ranges":[{"R":719,"L":716}],"parentKind":0},
{"id":99,"lsRanges":[],"storage":0,"kind":252,"ranges":[{"R":727,"L":721}],"parentKind":3},
{"id":209,"lsRanges":[],"storage":0,"kind":12,"ranges":[{"R":709,"L":696}],"parentKind":3}
]}}
```

If you check the bytes with this python script, you can see that the offsets don't match up with the things they are highlighting.
```python3
#! /usr/bin/python3
# E.g. python3 bytes.py src/test.hh 684 688
import sys

filename = sys.argv[1]
start_byte = int(sys.argv[2])
end_byte = int(sys.argv[3])

f = open(filename, 'rb')

b = f.read()

print('Bytes [%:%] =', b[start_byte:end_byte].decode('utf-8'))
```

### System information

* ccls version (`git describe --tags`): 0.20190314
* OS: Any OS (Tested on Windows and Linux Mint 19)
* Editor: Vim
* Language client (and version): vim-lsp

**Comment by MaskRay** [comment]
This exemplifies how to raise a good issue :) And thanks to your plugin!

I believe the problem is that the either vim-lsp or vim-lsp-cxx-highlight should normalize the line endings.

```typescript
export const EOL: string[] = ['\n', '\r\n', '\r'];
```

If you set a breakpoint at `src/message_handler.cc` (`gdb -p $(pgrep -fn Debug/ccls); b...; c` and save), you'll notice that the `wfile->buffer_content` uses `\n` as the line ending (vim-lsp normalizes the content in the `textDocument/didOpen` request). The range offsets ccls sends for `$ccls/publishSemanticHighlight` are related to the `\n` separated buffer. When the plugin highlights the buffer, it should replace `\r\n` with `\n` before computing offsets.

**Comment by jackguo380** [comment]
Oh I see I didn't realise vim-lsp also normalized line endings, thanks for looking into this. I will just recommend users turn on LSP ranges by default for my plugin, it would be too slow to calculate the line number without being able to use the builtin `byte2line` function in vim.
