### ISSUE TITLE
Headers not parsed correctly using latest ccls

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#335]
### Observed behavior

Using the newer version of ccls, it appears that issue #187 has reappeared, or something like it at any rate.

My `.ccls` file contains only:
```
%compile_commands.json
%h %hpp --include=Base.h
```
I use lsp-mode and my configuration in my init.el is:
```
  (setq ccls-initialization-options
        `(:clang (:extraArgs ("--gcc-toolchain=..." "--sysroot=..."))
          :index (:threads 6
                  :initialBlacklist ("."))
```
I generate my `compile_commands.json` from CMake and that all works fine.

In the ccls log file if I visit a .cpp file I see that the right compiler and flags are all used:
```
.../x86_64-rh65-linux-gnu-g++ -D.. -I... -ggdb3 -O2 ... -c /path/Socket.cpp --gcc-toolchain=... --sysroot=... -working-directory=/path/
```
but then if I visit a .h file (same directory), the log shows that none of my -D, -I, etc. options are used and I get a ton of reported errors from flymake etc.:
```
clang -xobjective-c++-header --gcc-toolchain=... --sysroot=... /path/Socket.h --gcc-toolchain=... --sysroot=... -working-directory=/path/
```
I'm not sure why the `--gcc-toolchain` and `--sysroot` options appear twice, but they both have the same (correct) values as their counterparts so it doesn't hurt anything.

### Expected behavior

The same set of compiler flags are used when visiting header files, so that I don't get errors.

### Steps to reproduce

The above should be sufficient but let me know if you need a self-contained repro case.

### System information

* ccls version (`git describe --tags`): 0.20181225.9-31-gb7d9ced0
* OS: GNU/Linux Ubuntu 18.04
* Editor: Emacs 26.1 
* Language client (and version): lsp-mode-20190320.2102

**Comment by MaskRay** [comment]
There are two unexpected things:

* `-xobjective-c++-header` in the `-v=1 -log-file=...` log. This is an indicator that the inference of the command line options fails and `src/project.cc` uses the fallback options (`GetFacllback`).
* `--gcc-toolchain=... --sysroot=...` is appended twice. `ret.args.resize(best->compdb_size);` should strip extra flags from `compile_commands.json` entries before appending `g_config->clang.extraFlags`.

Can you:
* set a breakpoint on `Project::FindEntry` (in `project.cc`) 
* in the editor, jump to `a.h`
* the breakpoint may be hit by two threads: `indexer*` `preamble`. `preamble` is the interesting one.
* see how the return value is computed

**Comment by madscientist** [comment]
This is apparently because of issue #338 .  If I use a compile_commands.json that refers to a non-existent file with an optimized build (where asserts are compiled out) then I get this weird behavior rather than a crash.  If I reset compile_commands.json so it doesn't refer to non-existing files then the behavior goes away.
