### ISSUE TITLE
Use of undeclared identifier when using non-standard keyword

### ISSUE THREAD

**Issue by erazor-de** [MaskRay/ccls#336]
### Observed behavior

I have an embedded project that uses an mcu-manufacturer customized gcc 5.4. This supports the non-standard keyword __flash, which clang doesn't know. For sake of ccls indexing I would like to replace it with "" by the preprocessor. ccls seems to still choke on the "removed" keyword.

Here's a minimal example:

main.c
```c
static int const __flash DEFAULT = 0;

int main(void) {
	int value = DEFAULT; // use of undeclared identifier 'DEFAULT'
	return 0;
}
```
.ccls
```
clang
-I~/opt/avr8-gnu-toolchain-linux_x86_64/avr/include
-DF_CPU=16000000UL
-D__AVR_ATmega328P__
-D__flash
```
Makefile
```makefile
CC = ~/opt/avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc
CFLAGS = -mmcu=atmega328p -DF_CPU=16000000UL -I~/opt/avr8-gnu-toolchain-linux_x86_64/avr/include -Wall -Wextra

main: main.c
```

### Expected behavior

I think this ccls configuration would "remove" the non-standard keyword and index without errors.

### System information

* ccls version (`git describe --tags`): 0.20190314
* OS: Fedora 29
* Editor: SublimeText with LSP plugin
* Language client (and version): clang 8.0.0

**Comment by erazor-de** [comment]
A workaround I found is to write this kind of nop into .ccls:
```
-D__flash=__attribute__(())
```

**Comment by MaskRay** [comment]
`clang -D__flash__ -E -xc =(printf 'x __flash__ x')`

`clang -D__flash__= -E -xc =(printf 'x __flash__ x')`
