### ISSUE TITLE
ccls doesn't work with network folders

### ISSUE THREAD

**Issue by SysRay** [MaskRay/ccls#339]
For example, I created a network drive in windows `X:\` pointing to `\\192.168.0.33\coding\` with my sources and builds.
The function `sys::fs::real_path(path, buf)` gives the following output:
`UNC/192.168.0.33/coding/test/code/`

For testing I adjusted the function `std::string RealPath(const std::string &path)`. `UNC/192.168.0.33` is simply replaced by `X:`. The diagnostic and autocompletion works fine now but not the indexer:
`store index for X:/ (delta: 0)`
...
```
[Error - 02:01:09] Request textDocument/documentLink failed.
  Message: not indexed
  Code: -32600 
```

**Comment by SysRay** [comment]
`StringRef clang::FileEntry::tryGetRealPathName()` also returns a UNC-path. After changing it the indexer started working correctly.

Any need for a fix?

**Comment by MaskRay** [comment]
Can you be more specific about the original return value of `tryGetRealPathName` and the changed value that makes it work?

**Comment by SysRay** [comment]
`tryGetRealPathName` returns buildDir + UNC-Path. Any idea why?
      `X:/test\build\UNC\192.168.0.33\test\code\testfile.cpp`

I simply let it call RealPath() for now.
`std::string PathFromFileEntry(const FileEntry &file) {
  return RealPath(file.getName().str())); // Only for windows, else use the code from before
}`

For the following code:
Path is `X:/test/code/`
UNC-Path is `UNC/192.168.0.33/coding/test/code/`

Luckily, we have the path with the drive "X:/" (pathOrig) and the corresponding UNC-Path (pathUNC). First step is to search for the first folder in Path ( `test`) and then search for this folder in the UNC-Path. Last step is to replace everything in the UNC-Path before `test` with the drive and convert '\\' to '/'.
This results to: X:/test/code/

If no folder is found, then just return the original path since it must be the root. 

```
std::string convertUNC(const std::string  &pathUNC, const std::string &pathOrig) {
  auto folderIteratorBegin = llvm::sys::path::begin(pathOrig);          // 'X:'
  std::string drive = folderIteratorBegin->str() + '/';
  if (++folderIteratorBegin != llvm::sys::path::end(pathOrig)) {        // '/'  (comparsion might be unnecessary)
      if (++folderIteratorBegin != llvm::sys::path::end(pathOrig)) {    // 'test'
        return llvm::sys::path::convert_to_slash(drive + pathUNC.substr(pathUNC.find(*folderIteratorBegin)));
      }
  }

  return llvm::sys::path::convert_to_slash(pathOrig);
}
```

```
std::string RealPath(const std::string &path) {
  SmallString<256> buf;
  sys::fs::real_path(path, buf,true); // expand ~ for tryGetRealPathName()

  if (buf.startswith("UNC")) {
    return convertUNC(buf.str(), path);
  }

  return llvm::sys::path::convert_to_slash(buf);
}
```

I'm still testing around but I think I'll stick with it.
