### ISSUE TITLE
lsp-ui-peek-jump-backward, lsp-ui-peek-jump-forward is supported?

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [MaskRay/ccls#346]
Hi, I'm using project maintainer's config for ccls.
https://github.com/MaskRay/Config/blob/master/home/.config/doom/modules/private/my-cc/autoload.el

In the lsp-ui-peek.el file, there is lsp-ui-peek-jump-forward, lsp-ui-peek-jump-backward setup. But I cannot use them. How can I use them?

**Comment by MaskRay** [comment]
See `lsp-ui-peek.el`

```elisp
(with-eval-after-load 'evil-jumps
  ;; We need to jump through some hoops to prevent the byte-compiler from
  ;; compiling this code.  We can’t compile the code without requiring
  ;; ‘evil-macros’.
  (eval '(progn
          (evil-define-motion lsp-ui-peek-jump-backward (count)
            (lsp-ui-peek--with-evil-jumps
             (evil--jump-backward count)
             (run-hooks 'xref-after-return-hook)))
          (evil-define-motion lsp-ui-peek-jump-forward (count)
            (lsp-ui-peek--with-evil-jumps
             (evil--jump-forward count)
             (run-hooks 'xref-after-return-hook))))
        t))
```

It requires you to load `evil-jumps` (part of evil-mode) before loading `lsp-ui-peek.el`.

This is not related to the ccls server and shouldn't be reported here. I'll move it to emacs-ccls.
