### ISSUE TITLE
Update building for fedora wiki section

### ISSUE THREAD

**Issue by WesterWest** [MaskRay/ccls#348]
### The issue

When installing on Fedora user is required to install more that `llvm` and `clang` packages. The project won't build without additional packages.

I love the work you have done
but please, update it. I was trying to build your project for an hour. I finally made it happen by installing all the `clang*` and `llvm*` packages (even though I know I installed a  lot of junk) and I would love to make it easier for others to build and use your project :)  

----- 

### PS
I guess its the `clang-devel` and `llvm-devel` packages but I can't put my finger on it. I'm just glad that it works now.

-----

### PSS
Also when you are using `--target install` you need to run it with sudo and I think that it should be noted somewhere

**Comment by myrgy** [comment]
you are right - fedora and centos use `*-devel` packages to populate libraries and headers. Regular `clang` and `llvm` will be installed as a `-devel` package dependency.

**Comment by MaskRay** [comment]
Can you check which packages on Fedora/CentOS provide the following files? (`/usr/lib/llvm-7` may be different on your systems)

```zsh
/usr/lib/llvm-7/lib/cmake/llvm/LLVMConfig.cmake
/usr/include/llvm-7/llvm/Config/llvm-config.h
/usr/lib/llvm-7/lib/libLLVMSupport.a

/usr/lib/llvm-7/lib/cmake/clang/ClangConfig.cmake
/usr/lib/llvm-7/include/clang/Config/config.h
/usr/lib/llvm-7/lib/libclangAST.a
```

If `clang-devel` has a dependency on `llvm-devel`, don't ask the user to install `llvm-devel` explicitly.

Similarly, if `clang-devel` has a dependency on `clang`, don't mention `clang` then.

**Comment by myrgy** [comment]
>>Can you check which packages on Fedora/CentOS provide the following files?
```
sudo dnf install clang-devel llvm-devel
rpm -ql clang-devel
rpm -ql llvm-devel
```

**Comment by WesterWest** [comment]
@MaskRay 
>https://github.com/MaskRay/ccls/wiki/Install mentions sudo and encourages to set -DCMAKE_INSTALL_PREFIX=<prefix>.

I mean it isn't that obvious, it's only mentioned on the bottom. I mean, it would help if it was somewhat indicated that the default path requires sudo (like with `#` or something)

**Comment by MaskRay** [comment]
Changed `wiki/Build.md` to mention `clang-devel llvm-devel` for Fedora.

sudo with `/usr/local` as the prefix is obvious. I don't think it needs more paragraph to explain that.

**Comment by myrgy** [comment]
I don't like to polute my system with non-package installs too.
I have ~/.opt/ folder for all such tool, which are installed using make install.

**Comment by D4N** [comment]
Hi folks, just FYI, I have packaged ccls for Fedora and pushed it for Rawhide. It should make it to the repositories soon, so you'll no longer have to compile it yourself. I'll also ship updates for Fedora 29 & 30, as soon as possible.
