### ISSUE TITLE
ccls is reindexing copied project due to different -working-directory arg

### ISSUE THREAD

**Issue by haridnr** [MaskRay/ccls#353]
### Observed behavior

ccls is reindexing a copied project setup using the "clang.pathMappings" option due to different 
"-working-directory" argument.

I initially indexed project1 at "/local-ssd/src/project1" using ccls and it works perfectly. I am also using a compile_commands.json file.

I copied project1 as project2 at "/local-ssd/src/project2" and also made sure that I copied the same compile_commands.json file and only updated the "project1" paths to "project2" in the JSON file.
I also made sure that the rsync of ccls cache folder was done correctly using the correct file paths.

I have setup the "clang.pathMappings" option as follows - 
{"clang": {"pathMappings": ["/local-ssd/src/project1>/local-ssd/src/project2/"]}

When I start ccls in project2 with logging using "-v=1" the following is the message I see in the logs for all the files -

_Logs from project2 -_ 
15:09:12 indexer10        pipeline.cc:134 V(1) args changed for /local-ssd/src/project2/Diagram.cpp
15:09:12 indexer10        pipeline.cc:337 I parse /local-ssd/src/project2/Diagram.cpp
  "-some_compiler_args" **-working-directory=/local-ssd/src/project2**

When I check the args from the ccls logs from project1 and compare the compilation args I do not see any difference except the **"-working-directory"**

_Logs from project1 -_
14:04:00 indexer10        pipeline.cc:337 I parse /local-ssd/src/project1/Diagram.cpp
  "-some_compiler_args" **-working-directory=/local-ssd/src/project1**

The "-some_compiler_args" section is exactly the same in the logs from project1 and project2. The only difference is the **-working-directory** argument.

And this is causing the re-indexing in my situation, please let me know if I made a mistake in the setup.

### Expected behavior
I expect that project2 does not start re-indexing again since I have setup up the "clang.pathMappings" value correctly.

### System information

* ccls version (`git describe --tags --long`): 0.20190301-0-gc9b2131
* clang version: clang version 7.0.1 (tags/RELEASE_701/final)
* OS: Debian 9
* Editor: GNU Emacs 25.1.1
* Language client (and version):

**Comment by MaskRay** [comment]
> ccls version (git describe --tags --long): 0.20190301-0-gc9b2131

0.20190301 was an old pre-release with some issues. Can you try HEAD? You'll have to re-run `cmake ` to make the output of `ccls --version` up-to-date.

> made sure that I copied the same compile_commands.json file and only updated the "project1" paths to "project2" in the JSON file.

With `{"clang": {"pathMappings": ["/local-ssd/src/project1>/local-ssd/src/project2/"]}`, you can leave `compile_commands.json` unchanged. See the logic around `project.cc:398`.

See https://github.com/MaskRay/ccls/wiki/Debugging#stopping-at-the-start-to-debug-early-issues Set a breakpoint near project.cc:408 and see if `DoPathMapping(entry.directory)` does the right thing.

**Comment by haridnr** [comment]
Thanks a lot.  Using the latest source from today I do not see this issue.

Also as you have suggested updating the paths in the compile_commands.json file in the copied project is not needed.
