### ISSUE TITLE
Question about Release

### ISSUE THREAD

**Issue by xu-cheng** [MaskRay/ccls#357]
Hi, I am working on packaging ccls to Homebrew in https://github.com/Homebrew/homebrew-core/pull/38117.

It seems that [current latest release](https://github.com/MaskRay/ccls/releases/tag/0.20181225.9) is from last year. The [Pie Day release](https://github.com/MaskRay/ccls/releases/tag/0.20190314) is only a pre-release. Therefore, I would like to ask if it is possible to tag a new stable release since the last one is a bit old.

Furthermore, it seems that you had retagged the pre-release. Please avoid to do so in the future as it would change the digest of the release and introduce troubles for downstream packaging. I would suggest to create a new minor release instead of retagging in this case.

**Comment by MaskRay** [comment]
Thank you for doing this. It seems 0.20190314 is stable enough now so I just untagged "pre-release"

> Furthermore, it seems that you had retagged the pre-release.

Sorry for any inconvenience. I keep an eye on https://repology.org/project/ccls/versions whether downstream packaging has happened.
