### ISSUE TITLE
Please don't force push tags

### ISSUE THREAD

**Issue by D4N** [MaskRay/ccls#360]
Hi @MaskRay,

I am currently packaging ccls for Fedora and encountered the issue that the SHA256 hashes of the latest release/tag differ on my two machines (I downloaded the release tarball on one machine about 1.5 weeks ago, on the other just today).

I strongly suspect that this is due to commits being force pushed away from the master branch and thereby the tag `0.20190314` also being modified. 

Could you please leave tags intact as they are? The issues is, that now the sources (and thus the resulting package) depend on the time when I downloaded the source tarball, which makes reproducible builds next to impossible.

Thanks in advance,

Dan

P.S.: Big fan of ccls, great work!

**Comment by MaskRay** [comment]
Sorry about that. 0.20190314 was a pre-release until yesterday, and I thought distributions hadn't packaged it (https://repology.org/project/ccls/versions)

**Comment by D4N** [comment]
No problem, I was just briefly very worried that I got a MITM. I'd suggest
