### ISSUE TITLE
Automatically infer clang resourceDir

### ISSUE THREAD

**Issue by sakshamsharma** [MaskRay/ccls#361]
I switched from cquery to ccls a while ago, and there's this particular low hanging issue that could ease initial setup / maintainability of user configs.
It took me a while to figure out why the same config as cquery wouldn't work (many missing headers etc) for ccls. Turns out, ccls does not try to determine clang resourceDir automatically, but cquery does.

Relevant link from cquery's FAQs:
https://github.com/cquery-project/cquery/wiki/FAQ#if--resource-dir-is-correct

Quoting:
> For --use-system-clang: it is recognized from -resource-dir option in the output of `clang++ '-###' -xc /dev/null)`

I did a quick check and that command does print the correct path, while the ccls binary continues to use the clang path that was available during the build step.

Not only does this deter new users, it also makes it tough for me to maintain my emacs config, since I often change the ccls binary I'm using depending on the clang version of the project. Ideally it would've all been handled by my PATH and the binaries available in it, but due to this issue that can't happen.

**Comment by MaskRay** [comment]
> https://github.com/cquery-project/cquery/wiki/FAQ#if--resource-dir-is-correct

I wrote this.

> Turns out, ccls does not try to determine clang resourceDir automatically

It detects it at build time, as what cquery does. See https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory

**Comment by sakshamsharma** [comment]
Still doesn't solve the issue for people using prebuilt binaries which may have a different resourceDir during buildtime and runtime.

In such cases, are you explicitly against running that clang command again at ccls init time, if the build-time-configured resource-dir doesn't exist? Perhaps adding a config flag that adds this changed behavior?

**Comment by MaskRay** [comment]
> Still doesn't solve the issue for people using prebuilt binaries which may have a different resourceDir during buildtime and runtime.

The wiki page says: `--init='{"clang": {"resourceDir": "/usr/local/clang/7.0.0"}}'`

> In such cases, are you explicitly against running that clang command again at ccls init time

I'm against running an external `clang/gcc` executable just to get `-resource-dir` and other system search paths. For system search path, leveraging Clang C++ API clangDriver is better. For `-resource-dir`, it relies on the hardcoded path on user-passed configuration.

**Comment by sakshamsharma** [comment]
I am already using that `init` config flag to get it to work right now. This ticket's intention was to infer that path dynamically because it may ease the job for some new users who don't have clang resources at standard locations, and for people who don't want to hardcode this path in their editor config (I'm already running that command in my editor config to generate that JSON dynamically though).

Being against external commands is an acceptable response though.

**Comment by MaskRay** [comment]
> This ticket's intention was to infer that path dynamically because it may ease the job for some new users who don't have clang resources at standard locations

The default `ResourceDir` is relative to the executable path, which doesn't work if the ccls executable is not beside `clang`. Obtaining the path of one of its depended clang libraries is possible but it doesn't work for statically linked ccls. `CLANG_LIBDIR_SUFFIX` `CLANG_VERSION_STRING` are variables, too. It is simply unrealistic to encode all the logic.

**Comment by madscientist** [comment]
FYI what I did was use a shell script wrapper around ccls that adds the `--init` command line argument then invokes the real ccls.  That way I don't have to put it into my editor config and neither does anyone else who may use that ccls.  Note you can have multiple `--init` options on the command line so you don't need to worry about taking over that option from users.
