### ISSUE TITLE
Some Header Files In  A Project Are Not Indexed

### ISSUE THREAD

**Issue by anupamk** [MaskRay/ccls#365]
### Observed behavior
I have been actively following the [dpdk project](git://dpdk.org/dpdk). Before checking out LSP based indexing schemes, I was using the older the cscope within emacs for browsing the code.

First I describe the setup (including layout of sources, ccls+lsp configuration etc.)

- dpdk.git clone lives in `~/source-code/dpdk.git/`
- my .ccls configuration looks like this:

```
%clang
-DALLOW_EXPERIMENTAL_API
-DBSD
-D_BSD_SOURCE
-D_DEFAULT_SOURCE
-D_FILE_OFFSET_BITS=64
-D_GNU_SOURCE
-DIPSEC_DEBUG
-DLINUX
-DNDEBUG
-DTAP_MAX_QUEUES=$(TAP_MAX_QUEUES)
-DUSE_JANSSON
-D_XOPEN_SOURCE=600
-D_XOPEN_SOURCE=700
-DZLIB_CONST
--gcc-toolchain=/usr
```
- entire source code is indexed with the following invokation
`ccls -index . -log-file=/tmp/ccls-test.out -v=2`

- barebones emacs-lsp + ccls configuration (ccls-test.el) looks like this:

```
(package-initialize)

(eval-when-compile
  (require 'use-package))

(use-package projectile
  :ensure t
  :bind-keymap ("C-c p" . projectile-command-map))

(use-package lsp-mode
  :ensure t
  :init (add-hook 'c-mode-common-hook #'lsp)
  :config
  (setq lsp-auto-guess-root t)
  (require 'projectile))

(use-package lsp-ui
  :ensure t)

(use-package ccls
  :ensure t
  :after lsp-mode
  :config
  (setq ccls-args '("--log-file=/tmp/ccls-test.out" "-v=3")))

(use-package company
  :ensure t
  :init (global-company-mode)
  :config
  (setq company-idle-delay 0.1)
  (add-to-list 'company-backends 'company-lsp))

(use-package company-lsp
  :ensure t
  :config (setq lsp-print-io t))
```

- I start emacs like so: `emacs -Q -l ~/tmp/ccls-test.el`

### Steps To Reproduce The Problem
- open `~/source-code/dpdk.git/drivers/net/tap/rte_eth_tap.c`

- in function `rte_pmd_tap_probe`  i try to look for the definition of `struct rte_eth_dev *eth_dev;` and i am greeted with a 'user-error: No definitions found for: rte_eth_dev'

### Logs
log in *lsp-log* buffer look something like this for this query
```
>>> ccls:26594(async)
Content-Length: 274

{
  "jsonrpc": "2.0",
  "method": "textDocument/definition",
  "params": {
    "textDocument": {
      "uri": "file:///home/anupam/source-code/dpdk.git/drivers/net/tap/rte_eth_tap.c"
    },
    "position": {
      "line": 2192,
      "character": 8
    }
  },
  "id": 106
}

<<<< ccls:26594
{
  "jsonrpc": "2.0",
  "id": 106,
  "result": []
}
```

### Expected behavior
Find the definition of 'struct rte_eth_dev'.  

Also, fwiw, following a chain of vanilla 'grep -r' shows the include file where this symbol is defined (lib/librte_ethdev/rte_ethdev_core.h) which is included by '~/source-code/dpdk.git/lib/librte_ethdev/rte_class_eth.c' And, as expected, this file is present in the .ccls-cache directory.

### System information

* ccls version (`git describe --tags --long`): 0.20190314-2-g64f9dbdc

* clang version: clang version 7.0.1 (tags/RELEASE_701/final)
* OS: Linux 4.19.29-1-lts (archlinux)
* Editor: emacs
* Language client (and version): lsp-mode 20190323.612

**Comment by MaskRay** [comment]
> -DTAP_MAX_QUEUES=$(TAP_MAX_QUEUES)

`.ccls` doesn't do shell variable expansion.

> -D_XOPEN_SOURCE=600
> -D_XOPEN_SOURCE=700

`-Wmacro-redefined` warning.


meson generates `compile_commands.json` by default` and works for me.

```
meson Debug/
ln -s Debug/compile_commands.json
# edit drivers/net/tap/rte_eth_tap.c
# check if `drivers@net@tap@rte_eth_tap.c.blob` is generated
```

**Comment by anupamk** [comment]
cool thanks ! using the meson generated compile_commands.json works as expected.
