### ISSUE TITLE
ccls should handle line numbers > 65535

### ISSUE THREAD

**Issue by rbresalier** [MaskRay/ccls#366]
I'm using a preprocessed file to try and reproduce an issue I'm seeing with ccls, because providing all the dependencies for you to repro the problem would be very difficult.

In this preprocessed file, the line numbers are much larger than 65535. For example, on line 197025 I try to "go to definition", where the definition is on line 196924, but ccls goes to line 65536 in gvim. Then if I do "find references" on line 197025, it says "Not found!".

I think it would be very useful if ccls used 32 bits for line numbers.

Not sure if my original problem is due to only 16 bit line numbers but this seems like a big limitation, especially if users want to provide you with preprocessed files as test cases as that would be much easier.

**Comment by MaskRay** [comment]
You may change `src/position.hh` `Pos::line` to `uint32_t` locally.

This struct is heavily used and should be kept small.

I agree that it is a limitation but I am not sure if it is a big limitation as it is unusual to have more than 65535 lines in a `.cc` or `.cpp`. Not being able to work for some `.ii` is an argument. I could use `int line:20; int column:12;` (some compilers may have trouble to handle bit fields of different types) to handle up to 524287 lines, but that can make the code (a bit) ugly and common usage (a bit) slow.

**Comment by rbresalier** [comment]
I wonder if this limitation has anything to do with the uninterruptible sleep issue that I have in #316 ?

Not being able to handle .ii files will make it very difficult to share some problems that I have encountered. It may be too big a burden to create a sharable test case with this limitation :(

**Comment by rbresalier** [comment]
Perhaps give a compile time option so that the users who need this can live with the extra memory/complexity, but most users can keep it at 16bit and not suffer?

**Comment by rbresalier** [comment]
I'm thinking of doing a fork and using compile time option to try out 32bits.

Can you tell me what changes are needed to serializer.cc? It is not that obvious to me?

I can see other changes that may be needed from commit https://github.com/MaskRay/ccls/commit/b110decc1ac6b7d85ce96f4dbf2a299df09aa2a8

Anything else to consider besides serializer.cc and the commit I referenced?

**Comment by MaskRay** [comment]
I don't think it deserves a compile time option. You can just apply this patch:

```patch
diff --git i/src/position.hh w/src/position.hh
index 24f4bd4e..759a584b 100644
--- i/src/position.hh
+++ w/src/position.hh
@@ -24,3 +24,3 @@ namespace ccls {
 struct Pos {
-  uint16_t line = 0;
+  int line = 0;
   int16_t column = -1;
@@ -87,3 +87,3 @@ template <> struct hash<ccls::Range> {
     } u{x};
-    static_assert(sizeof(ccls::Range) == 8);
+    static_assert(sizeof(ccls::Range) == 16);
     return hash<uint64_t>()(u.u64);
```

**Comment by rbresalier** [comment]
Thanks.

Without compile time option, I'll always need to apply this patch every time you change ccls. More work for me :(

If there is a compile time option, then I can take releases of ccls unchanged and apply the compile time option when I build it.

**Comment by rbresalier** [comment]
I think more changes needed than the patch you suggest.

For example from https://github.com/MaskRay/ccls/commit/b110decc1ac6b7d85ce96f4dbf2a299df09aa2a8

we see many casts to uint16_t as well as limiting to 16 bit numbers:

examples:

position.cc
```
uint16_t line = uint16_t(strtoul(p, &p, 10) - 1);
...
Pos p{(uint16_t)line, (int16_t)std::min<int>(column, INT16_MAX)};
```

Many more things specific to 16bit are shown in that commit.

**Comment by rbresalier** [comment]
Here is my first try at changing the code. It does compile, will test now.

https://github.com/rbresalier/ccls/commit/8fd3e75088754ec0b3163677c870036ce5bdc2f3

**Comment by rbresalier** [comment]
My changes seem to be working well. It found a definition in an .ii file that was on a line number > 65535. And it is working well in my larger project. Will probably make a pull request ;)

**Comment by MaskRay** [comment]
I know that changing a few `uint16_t` to `int` will work, but please don't send a PR. As I said, I think this is not useful to most people and will cluster the code.

**Comment by rbresalier** [comment]
Instead of changing uint16_t to int, I declared a new type for the line number, and use that type everywhere. The only extra clutter is small for declaring whether line type is uint16_t or int. Please take a look at how I did it. I think I kept clutter to a minimum - the only extra code is in position.hh and it is very small.

https://github.com/rbresalier/ccls/commit/8fd3e75088754ec0b3163677c870036ce5bdc2f3

**Comment by rbresalier** [comment]
For example:

```
#ifdef LINENUM_32BIT
  using LineNumType = int32_t;
  static LineNumType const lineNumMax = INT32_MAX;
#else
  using LineNumType = uint16_t;
  static LineNumType const lineNumMax = UINT16_MAX;
#endif
```

Then rest of code uses Pos::LineNumType instead of uint16_t or int.

So clutter is minimized.
