### ISSUE TITLE
How to get all symbols in a project

### ISSUE THREAD

**Issue by haridnr** [MaskRay/ccls#367]
Hi MaskRay,

I am indexing a very large project which might generate around 60 GB of ccls-cache, once I index this project the sources files are never changed. 

I would like to store all c++ classes and function name information in a separate cache so that I can quickly search this information without requesting the ccls server. (I would like to have a quick symbol search something similar to auto-complete)

One idea I have is to generate the ccls cache in JSON format and then run a process which extracts the information I need to a separate location. Then I can search for the symbols I need really fast.

Please let me know if there are better ways to do this?

Thanks.

**Comment by MaskRay** [comment]
> I am indexing a very large project which might generate around 60 GB of ccls-cache, once I index this project the sources files are never changed.

That's really huge. For llvm+clang+compiler-rt+lld+clang-tools-extra+libcxx+libcxxabi:

```
% du -sh .ccls-cache/
767M    .ccls-cache/
```

> One idea I have is to generate the ccls cache in JSON format and then run a process which extracts the information I need to a separate location. Then I can search for the symbols I need really fast.

That is a good idea. You can start with the JSON format, e.g. `ccls -index . -init='{"cache":{"format":"json"}}'`. Pretty print it with `jq . < .ccls-cache/@tmp@c/a.c.json ` and get some idea how symbols are represented. Caution: the `"usr"` only has 53-bit precision and is incompatible with the usr in the representation of `"callees"`. The data structure is described in `src/indexer.hh` (`IndexFile` and `Index{Func,Type,Var}`.

**Comment by haridnr** [comment]
Thanks a lot.

I was able to use the `ccls::Deserialize` function and get the necessary symbols from the cache files without any issues and the performance is also good.

**Comment by brenns10** [comment]
I encountered a need/wish to do something like this as well. Here's my solution, hopefully it speeds things up for people who land here in the future.
https://github.com/brenns10/ccls/commit/2657894fbc8dd98536964e1d70c966917c68dfec
