### ISSUE TITLE
[docs] .ccls how to properly index header files

### ISSUE THREAD

**Issue by dangom** [MaskRay/ccls#368]
First of all, thank you for this project.

I apologise if this question is too simple. I've tried to follow along the documentation but I'm having some difficulties setting up my project. I'm sure this is not a problem with CCLS, but rather the way I'm setting it up.

### Observed behavior

I'm trying to index a somewhat large project with ccls. The project tree is structured as follows:
```
$ tree -d -L 2
.
|-- opensource
|   |-- include/
|   `-- boost/
|-- pkg
|   |-- .ccls-root  # pkg is the root
|   |-- .ccls  # Contents described in the text below.
|   |-- Apps/
|   |-- Common/
|   `-- Servers/  # The project I want to work on lives in a subdir here.
`-- x86
    |-- delivery/
    `-- extsw/
```

I have a subproject which I want to work on living in `pkg/Servers/Projects/MyProject`. It's a c++98 legacy project I have to maintain. In the .cpp files of MyProject includes are listed both with respect to the project root (pkg) as well as with respect to the local directory, as in:

```cpp
# File pkg/Servers/Projects/MyProject/source.cpp

#include "header.h"  # would be Servers/Projects/MyProject/header.h
#include "Servers/OtherProjects/lib/header.h"
#include "Servers/Projects/JoesProject/header.h"
```

I've placed the project root at `pkg` as I'd like CCLS to index all headers within it. This is my .ccls:
```
%h -x c++-header
-I../x86
-I../opensource
-I.
```

### Expected behavior

With my current setup CCLS can only find the 1st header in the `source.cpp` file above. It does not find Servers/*.

As an alternative, I also tried setting the root to MyProject, and having a .ccls file with:
```
%h -x c++-header
-I../../../../../x86
-I../../../../../opensource
-I../../../../../pkg
-I.
```
This way I could find the headers, but then every time I `xref-find-definitions` and jumped to a header, I would be prompted whether I'd like to add a new root to LSP, which was annoying. Also, not all definitions were being found.
I should not that all headers (in all other subprojects) have their path starting at pkg (as in includes 2 and 3 in the source file above).

What is the correct way to tell .ccls how to find headers with respect to a given root? Should I place the .ccls file at pkg or at MyProject?

### System information

* ccls version (`git describe --tags --long`): 8.0.0
* clang version: 7.0.0
* OS: MacOS 10.13.6
* Editor: Emacs 26.1
* Language client (and version): Using lsp-mode, lsp-ui and company-lsp. Default settings.

**Comment by MaskRay** [comment]
> This is my .ccls:

```
clang
%h -x c++-header
-I../x86
-I../opensource
-I.
```

Don't omit the compiler driver `clang`.

**Comment by mschwartz** [comment]
Maybe add your .ccls to README?

I had a bit of work to find this out.

Thanks for the great program

**Comment by n-0** [comment]
Above solution made my ccls stop, for some strange reason.
Alternatively try
```
clang
%h -x
%h c++-header
```
taken from [docs](https://github.com/MaskRay/ccls/wiki/Project-Setup#ccls-file)
