### ISSUE TITLE
CCLS shows errors but clang -Wpedantic shows no errors

### ISSUE THREAD

**Issue by sab24** [MaskRay/ccls#372]
---

### Observed behavior

<img width="255" alt="Screenshot 2019-04-07 at 14 40 15" src="https://user-images.githubusercontent.com/3050374/55683732-78731680-5943-11e9-98ff-81bf40a27323.png">

<img width="956" alt="Screenshot 2019-04-07 at 14 40 05" src="https://user-images.githubusercontent.com/3050374/55683734-7c069d80-5943-11e9-9e5e-fd63b726d895.png">

.ccls
```
%compile_commands.json
%c -std=c11
%cpp -std=c++17
-I/usr/local/Cellar/llvm/8.0.0/include/c++/v1/
-I/usr/local/Cellar/llvm/8.0.0/Toolchains/LLVM8.0.0.xctoolchain/usr/include/c++/v1/
-I/usr/local/include
```

compile_commands.json
```
[
{
  "directory": "/Users/sab24/Downloads/TimeRegistration/c++/Debug",
  "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -I/usr/local/include  -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -o CMakeFiles/C++API.dir/connect.cpp.o -c /Users/sab24/Downloads/TimeRegistration/c++/connect.cpp",
  "file": "/Users/sab24/Downloads/TimeRegistration/c++/connect.cpp"
}
]
```

Describe what happened. Any aids you can include (that you think could be relevant) are a tremendous help.

* `compile_commands.json` or `.ccls` ([wiki/Project-Setup](https://github.com/MaskRay/ccls/wiki/Project-Setup))
* Reduce to A minimal set of `.c` `.cc` `.h` `.hh` files that can still demonstrate the issue.
* Consider a screencast gif.

### Expected behavior

No Errors

```
/usr/local/cellar/llvm/8.0.0/bin/clang++   -I/usr/local/include -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -MD -MT CMakeFiles/C++API.dir/connect.cpp.o -MF CMakeFiles/C++API.dir/connect.cpp.o.d -o CMakeFiles/C++API.dir/connect.cpp.o -c ../connect.cpp -Wpedantic
```

Gives no warnings.

### Steps to reproduce

```
#Include <string>

std::string teststring = "abc";
std::string test2("abc");
std::string s = "some string";
```

### System information

using vscode ccls
ccls version 0.20190314-0-g1976fec
clang version 8.0.0 (tags/RELEASE_800/final)
* OS: Macos 10.14.4
* Editor: VSCode 1.33.0
* Language client (and version): ccls in vscode version 0.1.26

**Comment by MaskRay** [comment]
```cpp
#Include <string>
```

-> `#include`

How did you install `clang version 8.0.0 (tags/RELEASE_800/final)`? If it is from Homebrew, there may be some other issues https://github.com/MaskRay/ccls/issues/369
