### ISSUE TITLE
Load compile_commands.json in subdirectory

### ISSUE THREAD

**Issue by dolmens** [MaskRay/ccls#378]
I have a big project which have several sub-projects, I generated compile_commands.json in each sub project directory but add the top project directory to lsp as root.

Is is reasonable or possible to load compile_commands.json in sub directrory?

**Comment by MaskRay** [comment]
> I have a big project which have several sub-projects

See https://github.com/MaskRay/ccls/issues/344#issuecomment-476031196

> I generated compile_commands.json in each sub project directory but add the top project directory to lsp as root.

`compile_commands.json` in subprojects are not read by ccls. Make sure your root `compile_commands.json` include everything. If not, cat these json files together.

> Is is reasonable or possible to load compile_commands.json in sub directrory?

There is a related thing called workspace folders, but clients may do bad things if your subprojects are under the root directory. I personally don't use that.

**Comment by FavonianKong** [comment]
> compile_commands.json in subprojects are not read by ccls. Make sure your root compile_commands.json include everything. If not, cat these json files together.

@MaskRay Hi，I cat the sub json files together and put the entire compile_commands.json in the root dir, but the index scan from the “new” json files are much less than expected...

**Comment by MaskRay** [comment]
> @MaskRay Hi，I cat the sub json files together and put the entire compile_commands.json in the root dir, but the index scan from the “new” json files are much less than expected...

`compile_commands.json` should look like `[{}, {}, {}]`... A simple concatenation may give you `[{}, {}][{}]`...

```
% cat a.json
[{}, {}]
% cat a.json a.json | jq '.[]' | jq --slurp '.'
[
  {},
  {},
  {},
  {}
]
```
