### ISSUE TITLE
textDocument/hover: no documentation from certain files

### ISSUE THREAD

**Issue by stloewen** [MaskRay/ccls#379]
I can't reopen #373 so I have to create a new issue. Feel free to delete this and reopen the original issue.

I'm afraid the issue in #373 is not fixed yet as I'm still not getting documentation for `printf`.

The problem seems to not be related to system headers.
I tried copying `/usr/include/stdio.h` into my test directory as `mystdio.h` and changed the include in `a.h` to `#include "mystdio.h"`.
Still not getting the doc-comment for `printf`.

**Comment by MaskRay** [comment]
> The problem seems to not be related to system headers.

It is related to system headers.

> Still not getting the doc-comment for printf.

You need to re-index the file, e.g. save the file, or just delete the cache file.

**Comment by stloewen** [comment]
I think there is another issue apart from system headers not being indexed.

```
❯ ccls --version                                                                                                                      [10:46:28]
ccls version 0.20190314-3-g6710dbc2
clang version 8.0.0 (tags/RELEASE_800/final)
```

```
❯ cat a.h b.h
// a.h
#include "b.h"
#include "mystdio.h"
void test() {
foobar(5);
printf("Hello world");
}
// b.h
/* This is helpful documentation
*
* param i: ignored
* returns: nothing
*/
void foobar(int i) {
return;
}

❯ cp /usr/include/stdio.h mystdio.h
❯ rm -rf ~/.cache/ccls/*
```

Still I'm getting documentation on `foobar()`, but not on `printf()`.

**Comment by Riatre** [comment]
I'm also seeing this with latest HEAD.

Interestingly, I can get documentation comments in completion / signature help for the same function.

**Comment by MaskRay** [comment]
b34550f3

**Comment by stloewen** [comment]
This seems to fix the problem for me.
Thanks a lot for your patience and your good work on this project.
