### ISSUE TITLE
Does it work with Monaco?

### ISSUE THREAD

**Issue by hifall** [MaskRay/ccls#38]
Since Monaco editor and VS Code share the same core, and ccls works with VS Code, I wonder if ccls works with Monaco as well?

Thanks for this nice project.

**Comment by MaskRay** [comment]
ccls speaks Language Server protocol but also provides some extensions. If the language client plugin of Manoco editor is able to locate the project root and provide correct initializationOptions (with `rootUri` `cacheDirectory` fields set), it should work. However, such language client plugin is generic don't understand ccls extensions, so you won't get semantic highlighting and many other xref extensions.
