### ISSUE TITLE
Providing binary packages for Linux ditributions 

### ISSUE THREAD

**Issue by BenjaminNavarro** [MaskRay/ccls#380]
I was wondering if it could be possible to provide prebuilt binary packages for Linux distributions (other than Archlinux which already has its package) to simplify the installation process of ccls.

I don't mind installing my software from source but for some people (e.g students) having to do this can be a deal breaker, and that's a shame because ccls is great!

So I looked into it and I was able to generate a deb package for Ubuntu 18.04 using CPack. I didn't know this tool before starting this but it saves me a lot of time and can handle many [packaging systems](https://gitlab.kitware.com/cmake/community/wikis/doc/cpack/PackageGenerators). The deb file I generated can successfully be installed inside a fresh Ubuntu 18.04 docker image so I assume that if we create a PPA for it it should be fine.

In order to generate the package I just had to add this to the CMakeLists.txt:
```
SET(CPACK_GENERATOR "DEB")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Benjamin Navarro")
SET(CPACK_DEBIAN_PACKAGE_DEPENDS "clang-7 (>=1:7-3~ubuntu0.18.04.1), libclang-7-dev (>=1:7-3~ubuntu0.18.04.1)")
INCLUDE(CPack)
```
Of course there are some other options to set to properly describe the package. 

What do you think?

**Comment by MaskRay** [comment]
ccls has been packaged by some distributions. https://repology.org/metapackage/ccls/versions Wait for someone to package it for Debian then:)

**Comment by BenjaminNavarro** [comment]
Do you mind if I try to provide a PPA ?
