### ISSUE TITLE
ccls internals question

### ISSUE THREAD

**Issue by hubgitname** [MaskRay/ccls#381]
Hi, 
I'm trying to understand the best way to work with ccls remotely (C/C++).
So I have **remote linux server** with a cross compiled toolchain on a workspace ( project root). Now the workspace is mounted on a **local linux directory** for easy access(nfs, sshfs mount). 
1) Is it important for the local ccls executable to access the cross-compile-toolchain (arm-linux-gnueabihf-gcc) or just the clang with compile_commands.json ? Helps me decide if I want to do the indexing remotely or locally. 
2) Does a local ccls query cross reference the code(that is remote) often during the query or does it just work with the .ccls-cache and accesses the code only to display ? Helps me decide if I have to store .ccls-cache remotely or locally.
3) Should a .ccls-cache always be stored at project root ? the ccls --help does not give an option
for the user to specify the project root. Would be helpful for the developer to choose where to 
store .ccls-cache, remotely or locally. 

Thanks.

**Comment by MaskRay** [comment]
1. No. You don't even need the `clang` executable (`/usr/bin/clang`) at runtime. It is just a build time dependency. https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory
2. A `.ccls-cache/**/*.blob` file is rewritten when a source file is re-indexed (`textDocument/didOpen`: if the cache is stale for the file or any of its included files; `textDocument/didSave`: save action). ccls doesn't read `.ccls-cache/**/*.blob` files when processing a cross reference request.
3. No. [`cache.directory`](https://github.com/MaskRay/ccls/wiki/Customization#cachedirectory) can be absolute or a path relative to the project root. `ccls --init='{"cache":{"directory":"/tmp/.ccls-cache"}}'`
