### ISSUE TITLE
Communicating with ccls  from monaco editor

### ISSUE THREAD

**Issue by haridnr** [MaskRay/ccls#382]
I see that you have mentioned Monaco editor in the editor configuration section for ccls - https://github.com/MaskRay/ccls/wiki/Monaco-Editor

Please can you provide a few pointers on how I can proceed. I would like to communicate with a standalone ccls process from a web browser using the monaco language client - https://github.com/TypeFox/monaco-languageclient

Thanks a lot.

**Comment by MaskRay** [comment]
That wiki page was contributed by someone else. I don't use Monaco. You may follow the instructions of https://github.com/TypeFox/monaco-languageclient

ccls provides good defaults. There is no initialization option that has to be specified to make use of its features. Specifying the executable path name should be sufficient.
