### ISSUE TITLE
CCLS does not handle version correctly in VersionedTextDocumentIdentifier

### ISSUE THREAD

**Issue by nagua** [MaskRay/ccls#387]
### Observed behavior

I tried to make the rename feature working with neovim and coc.nvim. If one renames something spanning more than one document and only one of them is currently opened in neovim, ccls is not sending a answer conforming to the LanguageServer specification resulting in coc.nvim not handling one of the `TextDocumentEdit` actions.

The source code in:
https://github.com/MaskRay/ccls/blob/4f602bfcd826b779e42aa0ee59dab23e1ca414dc/src/lsp.hh#L201-L205
lists the version option as either int or null, but the field is serialized by `ReflectMember(..., std:option)` which models a optional json field. This keeps coc.nvim from recognizing the edit as an `TextDocumentEdit` and this results in the change not being applied.

I have written a prove of concept implementation to test this, but I don't know how it could be possible to correctly implement this with the macros provided. Here is my ugly patch:

```patch
diff --git a/src/message_handler.hh b/src/message_handler.hh
index 61d7e1c3..85bbf18d 100644
--- a/src/message_handler.hh
+++ b/src/message_handler.hh
@@ -194,7 +194,43 @@ REFLECT_UNDERLYING_B(SymbolKind);
 REFLECT_STRUCT(TextDocumentIdentifier, uri);
 REFLECT_STRUCT(TextDocumentItem, uri, languageId, version, text);
 REFLECT_STRUCT(TextEdit, range, newText);
-REFLECT_STRUCT(VersionedTextDocumentIdentifier, uri, version);
+
+template <typename T> void ReflectMember2(JsonReader &vis, const char *name, T &v) {
+  vis.Member(name, [&]() { Reflect(vis, v); });
+}
+template <typename T> void ReflectMember2(JsonWriter &vis, const char *name, T &v) {
+  vis.Key(name);
+  Reflect(vis, v);
+}
+template <typename T> void ReflectMember2(BinaryReader &vis, const char *, T &v) {
+  Reflect(vis, v);
+}
+template <typename T> void ReflectMember2(BinaryWriter &vis, const char *, T &v) {
+  Reflect(vis, v);
+}
+
+template <typename T>
+void ReflectMember2(JsonWriter &vis, const char *name, std::optional<T> &v) {
+  // For TypeScript std::optional property key?: value in the spec,
+  // We omit both key and value if value is std::nullopt (null) for JsonWriter
+  // to reduce output. But keep it for other serialization formats.
+  vis.Key(name);
+  Reflect(vis, *v);
+}
+template <typename T>
+void ReflectMember2(BinaryWriter &vis, const char *, std::optional<T> &v) {
+  Reflect(vis, v);
+}
+
+template <typename Vis> void Reflect(Vis &vis, VersionedTextDocumentIdentifier &v) {                    \
+  ReflectMemberStart(vis);
+  std::string uri = "uri";
+  ReflectMember(vis, uri.c_str(), v.uri);
+  std::string version = "version";
+  ReflectMember2(vis, version.c_str(), v.version);
+  ReflectMemberEnd(vis);
+};
+
 REFLECT_STRUCT(DiagnosticRelatedInformation, location, message);
 REFLECT_STRUCT(Diagnostic, range, severity, code, source, message, relatedInformation);
 REFLECT_STRUCT(ShowMessageParam, type, message);
```

If someone can guide me to a better fix for this I can also submit a PR for this.

### Expected behavior

All reported edits should be applied.

### Steps to reproduce

1. Rename a variable spanning two source files, only one currently opened
2. Observe the sended `TextDocumentEdits`
3. The edit for the closed file misses the version field

### System information

* ccls version (`git describe --tags --long`): 0.20190314-5-ge496d4e5
* clang version: 8.8.8
* OS: Fedora 30
* Editor: neovim
* Language client (and version): coc.nvim (9ae35a8a5877fed145c6e97c053d786d44b3dcfc)

**Comment by chemzqm** [comment]
I've improved the TextDocumentEdit check with coc.nvim.

It now works with coc.nvim, but could fail with other client.

**Comment by MaskRay** [comment]
See https://microsoft.github.io/language-server-protocol/specification

> If a versioned text document identifier
	 * is sent from the server to the client and the file is not open in the editor
	 * (the server has not received an open notification before) the server can send
	 * `null` to indicate that the version is known and the content on disk is the
	 * truth (as speced with document content ownership).

**Comment by chemzqm** [comment]
@MaskRay The problem is `version` filed is missed from  `VersionedTextDocumentIdentifier` send from ccls, so the API `TextDocumentEdit.is` from vscode-languageserver-protocol package returns false for that` TextDocumentEdit`.

**Comment by MaskRay** [comment]
Sorry I didn't notice that. Fixed
