### ISSUE TITLE
ccls backtrace on Fedora 30

### ISSUE THREAD

**Issue by D4N** [MaskRay/ccls#389]
### Observed behavior

I've received the following report from Fedora's automated backtrace collection system: https://retrace.fedoraproject.org/faf/reports/2537092/. Unfortunately, I haven't run personally into this issue, so I cannot provide more details than are present in the provided link.

### System information

* ccls version: 0.20190314
* clang version: 8.0.0
* OS: Fedora 30
* Editor: n/a
* Language client (and version): n/a

**Comment by MaskRay** [comment]
Thank you for the information. I'll have to close this issue as there is no concrete action item on the ccls side. I tried reverse engineering a bit to investigate what was going on.


```
% readelf -n ./usr/lib64/libclangAST.so.8 | grep NT_GNU_BUILD_ID
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)         Build ID: 26e3ee7fce69d178f479f1c580f661d8e8a130ae
% objdump --no-show-raw-insn -Cdr usr/lib64/libclangAST.so.8
...
  362ee0:       movzx  esi,BYTE PTR [rcx+0x1]
  362ee4:       cmp    sil,0x2f
  362ee8:       je     363098 <clang::RawComment::RawComment(clang::SourceManager const&, clang::SourceRange, cl
ang::CommentOptions const&, bool)@@Base+0x348>
  362eee:       cmp    sil,0x2a
  362ef2:       jne    362e14 <clang::RawComment::RawComment(clang::SourceManager const&, clang::SourceRange, cl
ang::CommentOptions const&, bool)@@Base+0xc4>
  362ef8:       cmp    BYTE PTR [rcx+rdx*1-0x2],0x2a
```

0x362ef8 compared `Comment[Comment.size() - 2] != '*'` (`clang/libAST/RawCommentLine.cpp`). The probability that `Comment.size() < 2` has been precluded by a previous if condition. What might go wrong was that the file was read as a non-volatile file and this accessed a unmapped region. This might rarely happen when the user is upgrading the system include files (or `-isystem`) while causing ccls to re-parse the buffer.

**Comment by D4N** [comment]
Thank you for taking a look, that's greatly appreciated! 

Unfortunately no one reported a bug on Fedora's Bugzilla, thus I don't have a reproducer. Since the crash did not reappear for ~2 weeks, I'd consider it solved.
