### ISSUE TITLE
Problem with accepting header completion, append one more quotes, see gif

### ISSUE THREAD

**Issue by mihaelartz** [MaskRay/ccls#394]
![Webp net-gifmaker](https://user-images.githubusercontent.com/29631158/57607390-40c34400-756b-11e9-9611-63ced0b16d7f.gif)

Same problem appear in vscode with ccls extension

**Comment by SysRay** [comment]
With llvm > 8 the header include completion is now handled by llvm  and not by ccls anymore. 

The completion list contains only the filename with an additional quotation mark at the end with llvm > 8. As you can see in your gif it's `test.h"`.
With version < 9 it's `#include "test.h"` replacing the full text not just adding the filename + " in between the quotation marks.

```
#if LLVM_VERSION_MAJOR < 8
  ParseIncludeLineResult preprocess = ParseIncludeLine(buffer_line);
  if (preprocess.ok && preprocess.keyword.compare("include") == 0) {
    CompletionList result;
    char quote = std::string(preprocess.match[5])[0];
    {
      std::unique_lock<std::mutex> lock(
          include_complete->completion_items_mutex, std::defer_lock);
      if (include_complete->is_scanning)
        lock.lock();
      for (auto &item : include_complete->completion_items)
        if (quote == '\0' || (item.quote_kind_ & 1 && quote == '"') ||
            (item.quote_kind_ & 2 && quote == '<'))
          result.items.push_back(item);
    }
    begin_pos.character = 0;
    end_pos.character = (int)buffer_line.size();
    FilterCandidates(result, preprocess.pattern, begin_pos, end_pos,
                     buffer_line);
    DecorateIncludePaths(preprocess.match, &result.items, quote);
    reply(result);
    return;
  }
#endif
```
For simplicity I just removed the addtional quotation mark if using llvm > 8 in 
`void FilterCandidates(CompletionList &result, const std::string &complete_text,`
See https://github.com/SysRay/ccls/commit/1203f5e7ef557d121e767b9456e594624e409a11


Hope this helps.

**Comment by mihaelartz** [comment]
@SysRay Thanks you! This commit SysRay@1203f5e helped me.
