### ISSUE TITLE
Some aliased types are reported as typedef int

### ISSUE THREAD

**Issue by jdemilledt** [MaskRay/ccls#396]
### Observed behavior
Some aliased types are returned by ccls as typedef int. This is contradictory to the definiton `Go To Definition` points at. This causes linting to throw errors about things such as not initializing int with a string.

![Screen Recording 2019-05-20 at 08 16 45](https://user-images.githubusercontent.com/29146969/58021095-05c79000-7ad8-11e9-98f0-5c60835ebd7a.gif)

### Expected behavior

Aliased types evaluate to what their aliases point to

### Steps to reproduce

1. Make CMake project, export compile commands
2. Open VSCode with ccls extension on this folder
3. Try to make a u8string or u16string, etc.

### System information

* ccls version (`git describe --tags --long`): 0.20190314
* clang version: 8.0.0 from Homebrew
* OS: macOS Mojave
* Editor: VSCode Insiders 1.35.0-insider
* Language client (and version): VSCode ccls extension 0.1.26

**Comment by jdemilledt** [comment]
![Screen Recording 2019-05-20 at 08 13 06](https://user-images.githubusercontent.com/29146969/58022246-0e6d9580-7adb-11e9-8714-1972e92d5078.gif)
This is a higher quality GIF for you.

**Comment by jdemilledt** [comment]
New info: I updated to 20190314.1 with a from-source build, and now, while the hover still shows some types as typedef int (clicking go to definition shows a typedef that is not int), the linting does not throw.

**Comment by liushihao456** [comment]
I have been having the same issue, since recently. However, everything worked fine about two weeks ago. I am not very sure what happened meanwhile. 

For example, ccls gave the hover flycheck message 
```
ccls: invalid operands to binary expression ('std::__1::ostream' (aka 'int') and 'const char [6]')
```
for the following code
```
std::cout << "what?" << std::endl;
```

I am also on MacOS Mojave. I think the problem might come from a recent software update (not very sure).

**Comment by joelhock** [comment]
I'm not sure if this will point you both in the right direction, but using recent brew ccls, boost, icu4c, and llvm; vscode; vscode ccls extension; and os mojave, this works for me with no diagnostics and correct jump-to-definition:

```cpp
#include <string>
#include <iostream>
#include <unicode/unistr.h>
#include <boost/regex/icu.hpp>

void foo() {
  using namespace std::string_literals;
  std::string sa = "Hello, World!"s;
  std::u8string sb(u8"Hello, World!");
  std::cout << "what?" << std::endl;
}
```

with .ccls file:
```
clang
%cpp %h -std=c++2a
-I
/usr/local/opt/llvm/include/c++/v1
-I
/usr/local/opt/icu4c/include
```

**Comment by liushihao456** [comment]
After building ccls myself (llvm was installed via Homebrew), instead of installing the Homebrew pre-built version, the problem got solved. So I think maybe the Homebrew ccls have to be updated.
```
  brew install llvm
  git clone --depth=1 --recursive https://github.com/MaskRay/ccls
  cd ccls
  cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/Cellar/llvm/8.0.0_1/ # note the version number here, it depends
  cmake --build Release --target install
```

**Comment by neiljohari** [comment]
I'd like to reopen this issue. I am having the same problem @liushihao456 was having (`ccls: invalid operands to binary expression ('std::__1::ostream' (aka 'int') and 'const char [6]')`), and I've also recompiled ccls myself with llvm 10.0.0.

The simple test in the wiki with a temp dir + `a.cc` works perfectly fine, with jumping to definitions not being an issue.

**Comment by JiaweiZhan** [comment]
You can try to download llvm@9 by brew install llvm@9 and compile ccls again based on that. I met the same question as you did and found that it is the llvm 10's mistake.

**Comment by Jane42070** [comment]
> You can try to download llvm@9 by brew install llvm@9 and compile ccls again based on that. I met the same question as you did and found that it is the llvm 10's mistake.

Thanks, it's work for me

**Comment by neiljohari** [comment]
Unfortunately this did not work for me. I tried to install ccls against the new 11.0.0, and previous versions 9.0.1 and 9.0.0.

Any ideas?
