### ISSUE TITLE
Option to exclude directories from compile_commands.json

### ISSUE THREAD

**Issue by maindoor** [MaskRay/ccls#397]
Hi,

Thanks for this nice tool.
Quick question, I have a project like this.
parent/hw1 parent/hw2. Used bear, Generated json file while building both
hw1 and hw2 sources. But I know I am using only hw2. Is there any way to 
generate indexes with only hw2 entries ?

Thanks.

**Comment by maindoor** [comment]
A typical use case would be when the master build is done from parent and that in turn builds hw1 and hw2 targets for two versions of hardware. But I am currently only focussed on hw2.

**Comment by MaskRay** [comment]
Initialization option `{"index":{"blacklist":["hw2"]}}`

If you use a [shell script wrapper](https://github.com/MaskRay/ccls/wiki/Install#shell-script-wrapper)
`ccls -init='{"index":{"blacklist":["hw2"]}}' "$@"`

If you want to defer indexing hw2 until the files are opened, use ``{"index":{"initialBlacklist":["hw2"]}}``

**Comment by maindoor** [comment]
Thank you for the solution. Pls document the blacklist option. Only Initialblacklist is documented.
Can the initialization option be given on a per project basis in a file that ccls can understand ?
Currently for every project switch, I have to re-evaluate
setq ccls-initialization-options ...

**Comment by MaskRay** [comment]
You'll have to check how to use different initialization options for different projects in your language client.

If your client isn't flexible enough to provide a way, you may add the logic to the shell script wrapper: check `$PWD` and supply different `-init='{"index":{"blacklist":["hw2"]}}'`. ccls chdir to the project root at startup so checking `$PWD` works.
