### ISSUE TITLE
Failed to create a watch  for File watching not possible, no file descriptor left: 975: message

### ISSUE THREAD

**Issue by thermopyle** [MaskRay/ccls#399]
### Observed behavior

When I open a cpp-file I get a lot of the following error messages in the lsp-log buffer:

`Failed to create a watch for File watching not possible, no file descriptor left: 975: message`

If I try to use lsp commands in the cpp-buffer I get the message "LSP :: not indexed".

I have increased the open file limit using `ulimit -n 30000` but I still get the errors. I also turned off Dropbox which I think might be a problem here but it makes no difference.

### Expected behavior

I expect ccls to index the project without errors.

### Steps to reproduce

1. Set `ulimit -n 30000` in Terminal.
2. Start emacs in Terminal.
3. Check the lsp-log buffer.

### System information

* ccls version : 7.0.1 (installed using homebrew) 
* clang version: Apple LLVM version 9.1.0 (clang-902.0.39.2) 
* OS: MacOS 10.14.5
* Editor: emacs (installed using homebrew)
* Language client (and version): ccls 20190513.157

**Comment by MaskRay** [comment]
One user watch per directory. If you have many directories, you may run out of the available user watches.

```
% sysctl fs.inotify.max_user_watches
fs.inotify.max_user_watches = 8192
```

lsp-mode may lack the support for ignoring directories. `lsp-enable-file-watchers` `lsp-file-watch-ignored`
