### ISSUE TITLE
Can't find some includes and types

### ISSUE THREAD

**Issue by nickenchev** [MaskRay/ccls#400]
I'm running into an issue where CCLS can't seem to find certain include files, types etc. I've wasted a bunch of time hunting this problem down and don't know what else to do.

![Screen Shot 2019-06-05 at 1 05 05 PM](https://user-images.githubusercontent.com/8262271/58975381-ca44eb00-8792-11e9-906e-3454ad41e215.png)

This is reported both by flymake or flycheck, depending on which I enable. I see other "notes" about not being able to convert '''const char * to basic_string''' and such. If I disable ccls and run clangd instead all of this goes away.

The cmake project that is generating the compile_commands.json compiles just fine, yet LSP keeps complaining. Weirdest thing is another project of mine relies entirely on the project having the issues, and all of the completion and error reporting works just fine in the 2nd project.

lsp-mode-20190604.1818
lsp-ui-20190523.1521
ccls-20190513.157
company-lsp-20190525.207
Emacs 26.2

Just compiled / installed from latest ccls source today (June 5, 2019)

**Comment by madscientist** [comment]
Have you verified that you have the Clang resource directory set properly?  See https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory  This is the most common reason for issues like this _especially_ when you build ccls yourself.

Enable verbose logging (https://github.com/MaskRay/ccls/wiki/Debugging) and make sure that the paths being shown there look correct etc.

**Comment by nickenchev** [comment]
I saw the resource dir section but I'm kinda confused by it. 
```The path is derived from clang -print-resource-dir at CMake configure time.```

Does this not mean that CMake automatically configures the resource dir into the executable when I build? 

```If you want to install ccls and delete the build directory, you need to copy the contents of the resource directory before building ccls.```

When I built ccls, I pointed it to the LLVM path from homebrew.

**Comment by MaskRay** [comment]
If you use an older version of clang, you'll need https://github.com/MaskRay/ccls/wiki/Build#macos

Please also read https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory

**Comment by nickenchev** [comment]
I don't use an older version of Clang, and please read my comment above the one I just posted.

**Comment by MaskRay** [comment]
> The path is derived from clang -print-resource-dir at CMake configure time.

`grep CLANG_RESOURCE_DIRECTORY Release/build.ninja`. It is hard coded in the `ccls` executable.

And read https://github.com/MaskRay/ccls/wiki/Debugging#logs

**Comment by nickenchev** [comment]
None of this explains what is actually going on. The issue is quite strange, if I open my ```engine.cpp``` source file and put ```#include "core/entity.h"``` it works fine and I get ccls completions. In my ```system.h``` file, I  have the same ```#include "core/entity.h"``` and Flymake/ccls seems to complain. This makes no sense to me. I don't think any of this is resource directory related.
