### ISSUE TITLE
Cannot find the right function overload 

### ISSUE THREAD

**Issue by shelper** [MaskRay/ccls#403]
i have two overloads of the same function name in a header file:
```c++
    void add_option(const std::string &   names,
                    const std::string &   description,
                    const std::string &   parameter_names,
                    Flags flags         =  flag_none,
                    const std::string &   default_value = "");

    void add_option(const Option &option);
```
and i am using the first one in one source code, but i got ccls saying cannot find the function as the function only takes one arguments, and the error message pointing to the second overload.

### System information

* ccls version (`git describe --tags --long`): latest cloned from git yesterday
* clang version: 8.0
* OS: ubuntu
* Editor: tried both vscode and emacs
* Language client (and version): lsp

**Comment by MaskRay** [comment]
You need to make sure `flag_none` is in the scope.

```cpp
#include <string>

enum Flags {flag_none};
struct Option {};

void add_option(const std::string &   names,
                const std::string &   description,
                const std::string &   parameter_names,
                Flags flags         =  flag_none,
                const std::string &   default_value = "");

void add_option(const Option &option);
int main() {
    add_option(Option());
    add_option("a", "b", "c");
}
```

**Comment by shelper** [comment]
I think i am having the `flag_none` in the scope....
