### ISSUE TITLE
Build not pass: indexer.cc:1379

### ISSUE THREAD

**Issue by WaskiWaski** [MaskRay/ccls#404]
Hi,
i'm trying to compile ccls, but during building src/indexer.cc.o i receive this kind of error:
my_source_repos/ccls/src/indexer.cc:1379:36: error: expected ')'
  snprintf(buf, sizeof buf, "%s|%" PRIu64 "|%d|%d", v.range.ToString().c_str(),
                                   ^
source_repos/ccls/src/indexer.cc:1379:11: note: to match this '('
  snprintf(buf, sizeof buf, "%s|%" PRIu64 "|%d|%d", v.range.ToString().c_str()

Of cource compilation failing.
Ccls repository is checkouted to: 0.20190314 tag (SHA-1 1976fec59559b7)

Error occure when gcc or clang is used to compile.
Gcc version:  9.1.1
clang version: 8.0.1
cmake version: 3.9.6

Commands used to build:
 cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/path/to/bin -DCMAKE_INSTALL_PREFIX=/path/to/bin -DCMAKE_CXX_COMPILER=/path/to/bin/bin/clang++
cmake --build Release

OS version: 3.17 (kernel)

Regards,
Robert

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Build#red-hat--centos

`-DCMAKE_CXX_FLAGS=-D__STDC_FORMAT_MACROS`

**Comment by WaskiWaski** [comment]
Ok, it works.
Thanks!
