### ISSUE TITLE
stdlib.h file not found during build

### ISSUE THREAD

**Issue by Narice** [MaskRay/ccls#405]
### Observed behavior

when building ccls with the recommended settings on arch linux:
`cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_CXX_COMPILER=/usr/bin/clang++`
and then:
`cmake --build Release`
I'm getting this error:
```
In file included from /home/narice/ccls/src/clang_tu.cc:16:
In file included from /home/narice/ccls/src/clang_tu.hh:18:
In file included from /home/narice/ccls/src/position.hh:18:
In file included from /home/narice/ccls/src/utils.hh:18:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../include/c++/8.3.0/optional:38:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../include/c++/8.3.0/stdexcept:39:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../include/c++/8.3.0/string:52:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../include/c++/8.3.0/bits/basic_string.h:6400:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../include/c++/8.3.0/ext/string_conversions.h:41:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../include/c++/8.3.0/cstdlib:75:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
```

### System information

* ccls version:  git master ` d3808de`
* clang version: 8.0.0
* OS: Arch Linux

**Comment by innerout** [comment]
Although not solving the problem directly, you can install ccls-git version from the archlinuxcn repo.

**Comment by MaskRay** [comment]
You have to make ensure your `/usr/include/stdlib.h` is intact.

**Comment by Narice** [comment]
@MaskRay my stdlib.h is present on my system and doesn't seem damaged, how do I check for full integrity of the file?  
I opened it in an editor and it seemed fine to my eyes
@innerout I first tried installing ccls with yay and then ccls-git but it didn't work, then, I tried doing it manually but had the results you see just above

**Comment by innerout** [comment]
Archlinuxcn is not aur. It has a prebuilt version of ccls and ccls-git so you can install it with a pacman -S command.

**Comment by Narice** [comment]
@innerout oh I missread, sorry, I'll check it out! thanks ^^
