### ISSUE TITLE
ccls still has worse diagnostics than clangd

### ISSUE THREAD

**Issue by RedBeard0531** [MaskRay/ccls#407]
I couldn't reopen #391, so I'm opening a new issue with my last comment from that ticket:

This is still an issue, although it is better. Using the same code, I now get this with ccls:
![image](https://user-images.githubusercontent.com/118456/57717754-ebaa2f80-7649-11e9-95b6-2e9e6ae01997.png)

And this with clangd:
![image](https://user-images.githubusercontent.com/118456/57717849-18f6dd80-764a-11e9-9fd8-9a1709dc0cac.png)

**Comment by MaskRay** [comment]
See https://github.com/MaskRay/ccls/issues/391#issuecomment-507169334
