### ISSUE TITLE
Ccls with Coc.vim can implement System header but can't implement the function in the header 

### ISSUE THREAD

**Issue by FledgeXu** [MaskRay/ccls#408]
### Observed behavior
![IMAGE 2019-06-12 14:40:55](https://user-images.githubusercontent.com/16664654/59328867-16a6a280-8d20-11e9-800d-1e290c084c32.jpg)
![IMAGE 2019-06-12 14:41:26](https://user-images.githubusercontent.com/16664654/59328900-2920dc00-8d20-11e9-912f-e7895e8b6275.jpg)

### Expected behavior
Should implement function such as `printf`.
### System information

* ccls version: ccls: `stable 0.20190314.1 (bottled), HEAD (install use Homebrew)`
* clang version: 
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
* OS: 
`macOS 10.14.5`
* Editor: 
`Neovim`
* Language client (and version): 
`CoC.vim a0ab9a09d08e28169954be07327ab13907541d6f`
* CoC config json
```
{
    "languageserver": {
        "ccls": {
            "command": "ccls",
            "filetypes": [
                "c",
                "cpp",
                "objc",
                "objcpp"
            ],
            "initializationOptions": {
                "cache": {
                    "directory": "/tmp/ccls"
                },
                "clang": {
                    "extraArgs": [
                        "-isystem",
                        "/usr/local/Cellar/llvm/8.0.0_1/include/c++/v1"
                    ],
                    "resourceDir": "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0"
                }
            },
            "rootPatterns": [
                ".ccls",
                "compile_commands.json",
                ".vim/",
                ".git/",
                ".hg/"
            ]
        }
    },
    "suggest.noselect": true,
    "suggest.triggerAfterInsertEnter": true
}
```

**Comment by FledgeXu** [comment]
I just update Coc.vim to `ea70c2a428d23922a75d59fa6ba1014cbc9b556e` still not work.

**Comment by MaskRay** [comment]
`printf` cannot be completed in the toplevel.

```c
int main() {
   pr|       // trigger textDocument/completion here
}
```

**Comment by FledgeXu** [comment]
Sorry, What does it mean?
If i want to complete the `printf`, How should I configure？
