### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by damon-kwok** [MaskRay/ccls#41]
OS: LinuxMint18.3 (Ubuntu 16.04.1)
Emacs:27.1
CMake:3.12.20180715-g1a1e
Clang:6.0.1

````shell
cd $DEV_ROOT/ccls/build/
cmake .. \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_CXX_STANDARD=17 \
    -DCMAKE_CXX_STANDARD_REQUIRED=ON \
    -DCMAKE_INSTALL_PREFIX=$HOME/.ccls \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=YES \
    -DCMAKE_BUILD_TYPE=Release \
    -DSYSTEM_CLANG=OFF
make install
````
<details>
-- The CXX compiler identification is Clang 3.8.0

-- Check for working CXX compiler: /usr/bin/clang++

-- Check for working CXX compiler: /usr/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

**-- Using downloaded Clang**

-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  

-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 

**-- Clang already downloaded**

-- Found Clang: /home/damon/.dev/ccls/build/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/lib/libclangIndex.a (found suitable version "6.0.1", minimum required is "6.0.0") 

-- Looking for C++ include pthread.h

-- Looking for C++ include pthread.h - found

-- Looking for pthread_create

-- Looking for pthread_create - not found

-- Check if compiler accepts -pthread

-- Check if compiler accepts -pthread - yes

-- Found Threads: TRUE  

-- Configuring done

-- Generating done

-- Build files have been written to: /home/damon/.dev/ccls/build

Scanning dependencies of target ccls

[  1%] Building CXX object CMakeFiles/ccls.dir/third_party/siphash.cc.o

[  3%] Building CXX object CMakeFiles/ccls.dir/src/clang_complete.cc.o

In file included from /home/damon/.dev/ccls/src/clang_complete.cc:1:

In file included from /home/damon/.dev/ccls/src/clang_complete.h:3:

In file included from /home/damon/.dev/ccls/src/clang_tu.h:2:

In file included from /home/damon/.dev/ccls/src/position.h:3:

In file included from /home/damon/.dev/ccls/src/maybe.h:5:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/utility:70:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:59:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/move.h:54:

/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2656:5: error: 'inline' can only appear on functions

    _GLIBCXX17_INLINE constexpr bool is_swappable_v =
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/x86_64-linux-gnu/c++/7.3.0
/bits/c++config.h:127:29: note: expanded from macro '_GLIBCXX17_INLINE'

#  define _GLIBCXX17_INLINE inline
                            ^
In file included from /home/damon/.dev/ccls/src/clang_complete.cc:1:

In file included from /home/damon/.dev/ccls/src/clang_complete.h:3:

In file included from /home/damon/.dev/ccls/src/clang_tu.h:2:

In file included from /home/damon/.dev/ccls/src/position.h:3:

In file included from /home/damon/.dev/ccls/src/maybe.h:5:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/utility:70:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:59:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/move.h:54:
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2661:5: error: 'inline' can only appear on functions
    _GLIBCXX17_INLINE constexpr bool is_nothrow_swappable_v =
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/x86_64-linux-gnu/c++/7.3.0/bits/c++config.h:127:29: note: expanded from macro '_GLIBCXX17_INLINE'
#  define _GLIBCXX17_INLINE inline
                            ^
In file included from /home/damon/.dev/ccls/src/clang_complete.cc:1:

In file included from /home/damon/.dev/ccls/src/clang_complete.h:3:

In file included from /home/damon/.dev/ccls/src/clang_tu.h:2:

In file included from /home/damon/.dev/ccls/src/position.h:3:

In file included from /home/damon/.dev/ccls/src/maybe.h:5:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/utility:70:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:59:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/move.h:54:

/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2740:5: error: 'inline' can only appear on functions

    _GLIBCXX17_INLINE constexpr bool is_swappable_with_v =
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/x86_64-linux-gnu/c++/7.3.0
/bits/c++config.h:127:29: note: expanded from macro '_GLIBCXX17_INLINE'

#  define _GLIBCXX17_INLINE inline
                            ^
In file included from /home/damon/.dev/ccls/src/clang_complete.cc:1:

In file included from /home/damon/.dev/ccls/src/clang_complete.h:3:

In file included from /home/damon/.dev/ccls/src/clang_tu.h:2:

In file included from /home/damon/.dev/ccls/src/position.h:3:

In file included from /home/damon/.dev/ccls/src/maybe.h:5:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/utility:70:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:59:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/move.h:54:

/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2745:5: error: 'inline' can only appear on functions

    _GLIBCXX17_INLINE constexpr bool is_nothrow_swappable_with_v =
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/x86_64-linux-gnu/c++/7.3.0/bits/c++config.h:127:29: note: expanded from macro '_GLIBCXX17_INLINE'
#  define _GLIBCXX17_INLINE inline
                            ^
In file included from /home/damon/.dev/ccls/src/clang_complete.cc:1:

In file included from /home/damon/.dev/ccls/src/clang_complete.h:3:
In file included from /home/damon/.dev/ccls/src/clang_tu.h:2:
In file included from /home/damon/.dev/ccls/src/position.h:3:
In file included from /home/damon/.dev/ccls/src/maybe.h:5:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/utility:70:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:59:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/move.h:54:
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2877:5: error: 'inline' can only appear on functions
    inline constexpr bool is_invocable_v = is_invocable<_Fn, _Args...>::value;
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2881:5: error: 'inline' can only appear on functions
    inline constexpr bool is_nothrow_invocable_v
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2886:5: error: 'inline' can only appear on functions
    inline constexpr bool is_invocable_r_v
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2891:5: error: 'inline' can only appear on functions
    inline constexpr bool is_nothrow_invocable_r_v
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2898:3: error: 'inline' can only appear on functions
  inline constexpr bool is_void_v = is_void<_Tp>::value;
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2900:3: error: 'inline' can only appear on functions
  inline constexpr bool is_null_pointer_v = is_null_pointer<_Tp>::value;
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2902:3: error: 'inline' can only appear on functions
  inline constexpr bool is_integral_v = is_integral<_Tp>::value;
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2904:3: error: 'inline' can only appear on functions
  inline constexpr bool is_floating_point_v = is_floating_point<_Tp>::value;
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2906:3: error: 'inline' can only appear on functions
  inline constexpr bool is_array_v = is_array<_Tp>::value;
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2908:3: error: 'inline' can only appear on functions
  inline constexpr bool is_pointer_v = is_pointer<_Tp>::value;
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2910:3: error: 'inline' can only appear on functions
  inline constexpr bool is_lvalue_reference_v =
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2913:3: error: 'inline' can only appear on functions
  inline constexpr bool is_rvalue_reference_v =
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2916:3: error: 'inline' can only appear on functions
  inline constexpr bool is_member_object_pointer_v =
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2919:3: error: 'inline' can only appear on functions
  inline constexpr bool is_member_function_pointer_v =
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/type_traits:2922:3: error: 'inline' can only appear on functions
  inline constexpr bool is_enum_v = is_enum<_Tp>::value;
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
CMakeFiles/ccls.dir/build.make:75: recipe for target 'CMakeFiles/ccls.dir/src/clang_complete.cc.o' failed
make[2]: *** [CMakeFiles/ccls.dir/src/clang_complete.cc.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/ccls.dir/all' failed
make[1]: *** [CMakeFiles/ccls.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

</details>

**Comment by MaskRay** [comment]
See https://github.com/MaskRay/ccls/wiki/Build

> C++ Compiler with C++17 support:
> * Clang 5 or higher
> * GCC 7 or higher (optional,string_view require libstdc++7 or higher)

**Comment by damon-kwok** [comment]
-- The CXX compiler identification is Clang 3.8.0

-- Check for working CXX compiler: /usr/bin/clang++

-- Check for working CXX compiler: /usr/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- **Using downloaded Clang**

-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so

-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")

**-- Clang already downloaded**

**Comment by MaskRay** [comment]
There are two clang's here.

1. The C++ compiler driver `/usr/bin/clang++`. The system search paths (`clang++ -v -xc++ /dev/null -E`) usually include `/usr/include`
2. The clang libraries (`libclang*.{a,so}`) which ccls link against.

The `clang+llvm-*` archive contains both libraries and the C++ compiler driver. You may use `-DCMAKE_CXX_COMPILER` to override the compiler picked by cmake.

**Comment by unphased** [comment]
Sorry for not making a separate issue to be clearer, but I feel like I am really close to the issue I'm having. 

I have Ubuntu 16.04 and I'm trying not to clobber my system, and it *sounds* like it should be possible to take this extracted Clang 7.0.1 and point ccls cmake build at this extracted package in my Downloads directory to perform the build from source. 

However it dies being unable to find <optional> header. But it is clearly present here: 

`clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04/include/c++/v1/optional`

I invoked cmake with `cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/slu/Downloads/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04/ -DCMAKE_CXX_COMPILER=/home/slu/Downloads/clang+llv
m-7.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang++`.

**Comment by garfunklett** [comment]
some prebuilt binaries are strongly needed for old ubuntus.

**Comment by unphased** [comment]
I was able to build it but am using a ccls that i obtained with a snap on the 16.04. For now.
