### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by vushu** [MaskRay/ccls#410]
### Observed behavior

Using this following header I get No such file or directory message from ccls, but I can go to definition, and such, It just shows this warning

### Expected behavior

Describe what you expected to happen.

### Steps to reproduce

Using ubuntu 18.04, 
sudo apt install libgtk-3-dev
create a main.c with:

```
#include <gtk/gtk.h>
int main(int argc, char **argv) {
  GtkWidget *win;
  gtk_init(&argc, &argv);
  win = gtk_window_new(GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title(GTK_WINDOW(win), "Hello there");
  g_signal_connect(win, "destroy", G_CALLBACK(gtk_main_quit), NULL);
  gtk_widget_show(win);
  gtk_main();
}
```
creating a meson.build:
```
project('tutorial', 'c')
gtkdep = dependency('gtk+-3.0')
executable('demo', 'main.c', dependencies : gtkdep)
```
Inserting these commands:
```
meson Debug
ln -s Debug/compile_commands.json 

```

Screenshot:
![nosuchfile](https://user-images.githubusercontent.com/1658625/59490382-cdbc2e80-8e84-11e9-8baf-a4e6a9c07204.png)

### System information

* ccls version (`git describe --tags --long`): 
No tags found so revision number:
d3808de26ac00b36263aac73d8f64432472dff88
* clang version:  clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
* OS: Ubuntu 18.04
* Editor: Nvim
* Language client (and version): Coc.nvim

**Comment by MaskRay** [comment]
This is a nice report but I think you missed some gtk headers. I tried your example and it works on my box.

https://github.com/MaskRay/ccls/wiki/Debugging#logs

```
  cc -Idemo@exe -I. -I.. -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -pthread -MD -MQ demo@exe/main.c.o -MF demo@exe/main.c.o.d -o demo@exe/main.c.o -c ../main.c --gcc-toolchain=/usr -DE -working-directory=/tmp/p/debug
```

**Comment by vushu** [comment]
I tried uninstalling Ale, which somehow interferes, now it works thanks
