### ISSUE TITLE
Do not insert parentheses when completing function

### ISSUE THREAD

**Issue by cdelledonne** [MaskRay/ccls#412]
### Observed behavior

I'm using **ccls**+**LanguageClient** as a source for completion items for **deoplete** for C files in Neovim. Say that we have this C file:

![Screenshot from 2019-06-14 18-41-49](https://user-images.githubusercontent.com/24732205/59524495-5f9f5800-8ed4-11e9-8d3b-605b15661e33.png)

If I start typing `foo`, the completion menu presents me with the options `foo_noarg`, which is a function that takes no arguments, and `foo_witharg`, a function that takes one argument.

The `"newText"` completion string of `foo_noarg` is `"foo_noarg()"`, with both parentheses inserted

![Screenshot from 2019-06-14 18-43-38](https://user-images.githubusercontent.com/24732205/59524636-bb69e100-8ed4-11e9-9250-4a195df6167e.png)

The `"newText"` completion string of `foo_witharg` is `"foo_witharg("`, with only the left parenthesis inserted

![Screenshot from 2019-06-14 18-42-59](https://user-images.githubusercontent.com/24732205/59524675-cde41a80-8ed4-11e9-8852-72bb2e4e132c.png)

### Preferred behavior

Though I understand the rationale for this design choice, I would like to be given the option of not automatically inserting parentheses.

The first reason is that parentheses are not needed when assigning to a function pointer, e.g.:
```C
typedef void (* fp)();
fp foo = foo_noarg;
```

The second reason is that I use a Vim plugin that, when pressing `)`, brings the cursor to the next closing parenthesis in the buffer, rather than inserting a parenthesis. This requires that all opening parentheses have a matching closing parenthesis, which, in the case of `foo_witharg(`, is not true.

The first reason is more generic, the second more personal, but I think it would be great to at least give the user the option to choose whether to auto-insert parentheses or not.

**Comment by MaskRay** [comment]
The many upvotes suggest that this is probably the desired behavior when `client.snippetSupport` is false (either specified via initialization options, or the client does not snippets).

Rather than add another initialization option `completion.justIdentifier`, I simply change the behavior of client.snippetSupport == false`:

* `func(` -> `func`
* `Class<` -> `Class`

https://github.com/MaskRay/ccls/pull/497

**Comment by MaskRay** [comment]
@jhasse, @harikrishnan94, @funbringer, and @mcpca I decide to add another initialization option `completion.placeholder` and make 3 completion styles available. Please see #497
