### ISSUE TITLE
ubuntu18.04 build no pass

### ISSUE THREAD

**Issue by e190** [MaskRay/ccls#413]
# Observed behavior
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
fatal: 没有发现名称，无法描述任何东西。
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sniper/ccls/Release

---------------------------------------------------------------------

[100%] Linking CXX executable ccls
/usr/bin/ld: 找不到 -lz
/usr/bin/ld: 找不到 -ltinfo
collect2: error: ld returned 1 exit status
CMakeFiles/ccls.dir/build.make:1195: recipe for target 'ccls' failed
make[2]: *** [ccls] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/ccls.dir/all' failed
make[1]: *** [CMakeFiles/ccls.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

### Expected behavior

sucessful build

### Steps to reproduce
1.  wget -c http://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
2.  tar xf clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
3.  cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$PWD/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04
4. cmake --build Release

### System information

* ccls version (`git describe --tags --long`):  0.20190314.1-10-gd3808de26ac0
* gcc version: 7.4.0
* clang version: 8.0.0
* OS: Linux version 4.18.0-21-generic (buildd@lcy01-amd64-006)
* Editor: 
* Language client (and version):

**Comment by MaskRay** [comment]
`apt install zlib1g-dev libncurses-dev`
