### ISSUE TITLE
Compiler error on pipeline.cc using clang-cl on Windows

### ISSUE THREAD

**Issue by tuankiet65** [MaskRay/ccls#414]
OS: Windows 10 version 1903

Visual Studio: 2017

clang-cl version:
```
E:\ccls\Release>%LLVM_DIR%\build\Release\bin\clang-cl -v
clang version 9.0.0 (https://github.com/llvm/llvm-project.git 4bde5d3c08182dec9faa3f6d0d66f584f7366c9a)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: E:\llvm-project\build\Release\bin
```

clang-cl output: https://gist.github.com/tuankiet65/27aa320271c5ef266ea2569cbd4a7b25

Seems like the workaround at utils.hh#L147 should be extended to include Clang. I changed it to
```c
#if ((__GNUC__ == 7 && __GNUC_MINOR__ < 4) || (__GNUC__ < 7) || __clang__)
```
and the build proceeds normally.

**Comment by MaskRay** [comment]
Changed to `#if !(__clang__ || __GNUC__ > 7 || __GNUC__ == 7 && __GNUC_MINOR__ >= 4) || defined(_WIN32)`

https://github.com/MaskRay/ccls/pull/371 should be similar
