### ISSUE TITLE
build no pass in msys2 (win7) 

### ISSUE THREAD

**Issue by e190** [MaskRay/ccls#416]
### Observed behavior
Administrator@PC-20190426HQEG MINGW64 ~/work/ccls
# cmake -H. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_PREFIX_PATH="D:/home/work/llvm/Release;D:/home/work/llvm/Release/tools/clang;D:/home/work/llvm;D:/home/work/llvm/tools/clang"
-- The CXX compiler identification is Clang 9.0.0
-- Check for working CXX compiler: D:/home/work/llvm/Release/bin/clang-cl.exe
-- Check for working CXX compiler: D:/home/work/llvm/Release/bin/clang-cl.exe -- broken
CMake Error at D:/msys64/mingw64/share/cmake-3.11/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "D:/home/work/llvm/Release/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/home/work/ccls/Release/CMakeFiles/CMakeTmp

    Run Build Command:"D:/msys64/mingw64/bin/ninja.exe" "cmTC_db52e"
    [1/2] Building CXX object CMakeFiles\cmTC_db52e.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_db52e.exe
    FAILED: cmTC_db52e.exe
    cmd.exe /C "cd . && D:\msys64\mingw64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_db52e.dir --manifests  -- D:\msys64\usr\bin\link.exe /nologo CMakeFiles\cmTC_db52e.dir\testCXXCompiler.cxx.obj  /out:cmTC_db52e.exe /implib:cmTC_db52e.lib /pdb:cmTC_db52e.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_db52e.dir/manifest.res CMakeFiles\cmTC_db52e.dir/manifest.rc" failed (exit code 0) with the following output:
    绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "D:/home/work/ccls/Release/CMakeFiles/CMakeOutput.log".
See also "D:/home/work/ccls/Release/CMakeFiles/CMakeError.log".

### Expected behavior

build pass

### Steps to reproduce

# build clang+llvm firstly and sucessed !
git clone https://git.llvm.org/git/llvm.git
git clone https://git.llvm.org/git/clang.git llvm/tools/clang

cd llvm
cmake -H. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DLLVM_TARGETS_TO_BUILD=X86
ninja -C Release clangFormat clangFrontendTool clangIndex clangTooling clang

# then build ccls and failed!
cd ccls
cmake -H. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_PREFIX_PATH="D:/llvm/Release;D:/llvm/Release/tools/clang;D:/llvm;D:/llvm/tools/clang"

### System information

* ccls version (`git describe --tags --long`):  lasted
* clang version: 9.0.0
* OS: win7
* Editor: 
* Language client (and version):

**Comment by e190** [comment]
Administrator@PC-20190426HQEG MINGW64 ~/work/ccls
# cmake -H. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_PREFIX_PATH="D:/home/work/llvm/Release;D:/home/work/llvm/Release/tools/clang;D:/home/work/llvm;D:/home/work/llvm/tools/clang"
-- The CXX compiler identification is Clang 9.0.0
-- Check for working CXX compiler: D:/home/work/llvm/Release/bin/clang++.exe
-- Check for working CXX compiler: D:/home/work/llvm/Release/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: D:/home/work/ccls/Release

Administrator@PC-20190426HQEG MINGW64 ~/work/ccls
# ninja -C Release
ninja: Entering directory `Release'
[1/43] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_info.cc.obj
[2/43] Building CXX object CMakeFiles/ccls.dir/src/working_files.cc.obj
[3/43] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_inheritance.cc.obj
[4/43] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_member.cc.obj
[5/43] Building CXX object CMakeFiles/ccls.dir/third_party/siphash.cc.obj
[6/43] Building CXX object CMakeFiles/ccls.dir/src/utils.cc.obj
[7/43] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_call.cc.obj
[8/43] Building CXX object CMakeFiles/ccls.dir/src/config.cc.obj
[9/43] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_navigate.cc.obj
[10/43] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_vars.cc.obj
[11/43] Building CXX object CMakeFiles/ccls.dir/src/fuzzy_match.cc.obj
[12/43] Building CXX object CMakeFiles/ccls.dir/src/filesystem.cc.obj
[13/43] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_reload.cc.obj
[14/43] Building CXX object CMakeFiles/ccls.dir/src/log.cc.obj
[15/43] Building CXX object CMakeFiles/ccls.dir/src/clang_tu.cc.obj
[16/43] Building CXX object CMakeFiles/ccls.dir/src/include_complete.cc.obj
[17/43] Building CXX object CMakeFiles/ccls.dir/src/platform_posix.cc.obj
[18/43] Building CXX object CMakeFiles/ccls.dir/src/lsp.cc.obj
[19/43] Building CXX object CMakeFiles/ccls.dir/src/main.cc.obj
FAILED: CMakeFiles/ccls.dir/src/main.cc.obj
D:\home\work\llvm\Release\bin\clang++.exe  -DCCLS_VERSION="\"<unknown>\"" -I../src -isystem ../third_party -isystem D:/home/work/llvm/include -isystem D:/home/work/llvm/Release/include -isystem D:/home/work/llvm/tools/clang/include -isystem D:/home/work/llvm/Release/tools/clang/include -isystem ../third_party/rapidjson/include -O3 -DNDEBUG   -Wall -Wno-sign-compare -fno-rtti -pthread -std=c++1z -MD -MT CMakeFiles/ccls.dir/src/main.cc.obj -MF CMakeFiles\ccls.dir\src\main.cc.obj.d -o CMakeFiles/ccls.dir/src/main.cc.obj -c ../src/main.cc
../src/main.cc:81:19: error: no member named 'Categories' in 'llvm::cl::Option'
    if (I.second->Categories[0] != &C)
        ~~~~~~~~  ^
1 error generated.
[20/43] Building CXX object CMakeFiles/ccls.dir/src/position.cc.obj
[21/43] Building CXX object CMakeFiles/ccls.dir/src/platform_win.cc.obj
[22/43] Building CXX object CMakeFiles/ccls.dir/src/indexer.cc.obj
FAILED: CMakeFiles/ccls.dir/src/indexer.cc.obj
D:\home\work\llvm\Release\bin\clang++.exe   -I../src -isystem ../third_party -isystem D:/home/work/llvm/include -isystem D:/home/work/llvm/Release/include -isystem D:/home/work/llvm/tools/clang/include -isystem D:/home/work/llvm/Release/tools/clang/include -isystem ../third_party/rapidjson/include -O3 -DNDEBUG   -Wall -Wno-sign-compare -fno-rtti -pthread -std=c++1z -MD -MT CMakeFiles/ccls.dir/src/indexer.cc.obj -MF CMakeFiles\ccls.dir\src\indexer.cc.obj.d -o CMakeFiles/ccls.dir/src/indexer.cc.obj -c ../src/indexer.cc
../src/indexer.cc:1378:36: error: expected ')'
  snprintf(buf, sizeof buf, "%s|%" PRIu64 "|%d|%d", v.range.ToString().c_str(),
                                   ^
../src/indexer.cc:1378:11: note: to match this '('
  snprintf(buf, sizeof buf, "%s|%" PRIu64 "|%d|%d", v.range.ToString().c_str(),
          ^
1 error generated.
[23/43] Building CXX object CMakeFiles/ccls.dir/src/message_handler.cc.obj
[24/43] Building CXX object CMakeFiles/ccls.dir/src/pipeline.cc.obj
ninja: build stopped: subcommand failed.

**Comment by MaskRay** [comment]
```
../src/main.cc:81:19: error: no member named 'Categories' in 'llvm:cl:Option'
if (I.second->Categories[0] != &C)
~~~~~~~~ ^
1 error generated.
```

Your clang 9.0.0 is not new enough to include the change rL360179. Unfortunately there is no good way to make a ifdef that dispatches on the exact revision number, so you'll have to update. Here is the version information of my clang:
```
% clang --version
clang version 9.0.0 (trunk 363759) (llvm/trunk 363758)
```
```cpp
// src/main.cc
#if LLVM_VERSION_MAJOR >= 9 // rL360179
    if (I.second->Categories[0] != &C)
#else
    if (I.second->Category != &C)
#endif
```

**Comment by MaskRay** [comment]
```
../src/main.cc:81:19: error: no member named 'Categories' in 'llvm:cl:Option'
if (I.second->Categories[0] != &C)
~~~~~~~~ ^
1 error generated.
```

Your clang 9.0.0 is not new enough to include the change rL360179. Unfortunately there is no good way to make a ifdef that dispatches on the exact revision number, so you'll have to update. Here is the version information of my clang:

```
% clang --version
clang version 9.0.0 (trunk 363759) (llvm/trunk 363758)
```

```cpp
// src/main.cc
#if LLVM_VERSION_MAJOR >= 9 // rL360179
    if (I.second->Categories[0] != &C)
#else
    if (I.second->Category != &C)
#endif
```

**Comment by MaskRay** [comment]
```
../src/main.cc:81:19: error: no member named 'Categories' in 'llvm:cl:Option'
if (I.second->Categories[0] != &C)
~~~~~~~~ ^
1 error generated.
```

Your clang 9.0.0 is not new enough to include the change rL360179. Unfortunately there is no good way to make a ifdef that dispatches on the exact revision number, so you'll have to update. Here is the version information of my clang:

```
% clang --version
clang version 9.0.0 (trunk 363759) (llvm/trunk 363758)
```

```cpp
// src/main.cc
#if LLVM_VERSION_MAJOR >= 9 // rL360179
    if (I.second->Categories[0] != &C)
#else
    if (I.second->Category != &C)
#endif
```

**Comment by e190** [comment]
how to show llvm`s trunk ?
My version is : 
`Administrator@PC-20190426HQEG MINGW64 ~/work/llvm/Release/bin
# ./clang.exe --version
clang version 9.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:\home\work\llvm\Release\bin
`
# where download new enough llvm ?

I download llvm where is github .
`git clone https://git.llvm.org/git/llvm.git
git clone https://git.llvm.org/git/clang.git llvm/tools/clang`

**Comment by e190** [comment]
> 
> 
> ```
> ../src/main.cc:81:19: error: no member named 'Categories' in 'llvm:cl:Option'
> if (I.second->Categories[0] != &C)
> ~~~~~~~~ ^
> 1 error generated.
> ```
> 
> Your clang 9.0.0 is not new enough to include the change rL360179. Unfortunately there is no good way to make a ifdef that dispatches on the exact revision number, so you'll have to update. Here is the version information of my clang:
> 
> ```
> % clang --version
> clang version 9.0.0 (trunk 363759) (llvm/trunk 363758)
> ```
> 
> ```c++
> // src/main.cc
> #if LLVM_VERSION_MAJOR >= 9 // rL360179
>     if (I.second->Categories[0] != &C)
> #else
>     if (I.second->Category != &C)
> #endif
> ```

how to show llvm`s trunk ?
My version is :

`Administrator@PC-20190426HQEG MINGW64 ~/work/llvm/Release/bin
./clang.exe --version

clang version 9.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:\home\work\llvm\Release\bin
`
where download new enough llvm ?

I download llvm where is github .
git clone https://git.llvm.org/git/llvm.git git clone https://git.llvm.org/git/clang.git llvm/tools/clang
