### ISSUE TITLE
ccls does not normalize/canonicalize workspace paths

### ISSUE THREAD

**Issue by eklitzke** [MaskRay/ccls#418]
I have two indexed projects, `~/code/ccls` and `~/code/cruise`. In my ccls workspace cache I see four entries:
```
$ ls -l
total 9316
drwxrwx--- 2 eklitzke eklitzke   57344 Jun 20 11:38 @@home@eklitzke@code@ccls
drwxrwx--- 2 eklitzke eklitzke    4096 Jun 20 11:38 @home@eklitzke@code@ccls
drwxrwx--- 2 eklitzke eklitzke 7512064 Jun 19 12:54 @@home@eklitzke@code@cruise
drwxrwx--- 2 eklitzke eklitzke 1937408 Jun 19 14:22 @home@eklitzke@code@cruise
```

It appears this is because for some reason some of the paths of files are starting with `//` instead of just `/`, but these after normalization these are considered to be the same paths on Unix. The implementation of `NormalizePath()` in `platform_posix.cc` only removes dots, but not duplicated slashes:
```c++
std::string NormalizePath(const std::string &path) {
  llvm::SmallString<256> P(path);
  llvm::sys::path::remove_dots(P, true);
  return {P.data(), P.size()};
}
```

I'm not that familiar with the LLVM fs stuff, but I didn't see any methods to normalize or canonicalize paths. In C++17 there is `std::filesystem::canonical` that will handle this case, or else it would be trivial to write a small amount of code to handle this case.

**Comment by MaskRay** [comment]
> It appears this is because for some reason some of the paths of files are starting with // instead of just /,

No, this is a deliberate choice to encode paths outside of workspace folders.

```cpp
// src/pipeline.cc
std::string GetCachePath(std::string src) {
  ...
  ///////// paths outside of workspace folders are encoded as @@path@to@file
  return g_config->cache.directory + '@' +
         EscapeFileName(g_config->fallbackFolder.substr(
             0, g_config->fallbackFolder.size() - 1)) +
         '/' + EscapeFileName(src);
}
```

Two projects may share some global include files. Because the included files may be included with different defined macros (think: `_FILE_OFFSET_BITS`), it is better for them not to share cache files, so these paths are prefixed with `@@path@to@project`.

> In C++17 there is std::filesystem::canonical that will handle this case, or else it would be trivial to write a small amount of code to handle this case.

Yes, C++17 has std::filesystem. However, it gets you into trouble when you start to write `-lstdc++fs` (libstdc++) or `-lc++experimental` (FreeBSD/macOS/etc libc++)...

```
a.cc:(.text._ZNSt10filesystem7__cxx114pathC2IA5_cS1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5IA5_cS1_EERKT_NS1_6formatE]+0x5e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
```

```cmake
if(${CMAKE_SYSTEM_NAME} STREQUAL Darwin)
  target_link_libraries(ccls PRIVATE -lc++experimental)

elseif(${CMAKE_SYSTEM_NAME} STREQUAL Linux)
  if(NOT CLANG_USE_BUNDLED_LIBC++)
    target_link_libraries(ccls PRIVATE -lstdc++fs)
  endif()
  # loguru calls dladdr
  target_link_libraries(ccls PRIVATE ${CMAKE_DL_LIBS})

elseif(${CMAKE_SYSTEM_NAME} STREQUAL FreeBSD)
  # loguru::stacktrace_as_stdstring calls backtrace_symbols
  # sparsepp/spp_memory.h uses libkvm
  # src/platform_posix.cc uses libthr
  find_package(Backtrace REQUIRED)
  target_link_libraries(ccls PRIVATE ${Backtrace_LIBRARIES} kvm thr)
  if(SYSTEM_CLANG)
    target_link_libraries(ccls PRIVATE c++experimental)
  endif()
```
