### ISSUE TITLE
Crashed with invalid constexpr functions

### ISSUE THREAD

**Issue by nodamushi** [MaskRay/ccls#420]
### Observed behavior
ccls crashed with invalid constexpr functions whose name are sequential number.

### Expected behavior

Highlight the wrong codes without crashing.

### Steps to reproduce

ccls crashed with the following code:

```cpp
constexpr int foo2(int x){return foo1(foo1(x));}
constexpr int foo1(int x){return x;}
constexpr int Foo= foo2(0);

int main(int argc, char *argv[])
{
  return 0;
}
```
![image](https://user-images.githubusercontent.com/581955/59919905-b2908680-9463-11e9-9236-756fb9d94a70.png)

However, ccls does not stop with the following codes:

```cpp
constexpr int foo2(int x){return foo1(x);}
constexpr int foo1(int x){return x;}
constexpr int Foo= foo2(0);

int main(int argc, char *argv[])
{
  return 0;
}
```
![image](https://user-images.githubusercontent.com/581955/59919820-73facc00-9463-11e9-9da2-0fc2d45053a4.png)

```cpp
constexpr int foo(int x){return bar(bar(x));}
constexpr int bar(int x){return x;}
constexpr int Foo= foo(0);

int main(int argc, char *argv[])
{
  return 0;
}
```
![image](https://user-images.githubusercontent.com/581955/59919846-82e17e80-9463-11e9-9d93-67db510827f0.png)

### System information
* ccls version 0.20190314.1-10-gd3808de2
* clang version 8.0.0 (tags/RELEASE_800/final)
* OS:  Windows10  (MSYS2)
* Editor: Emacs26.2
* Language client (and version): eglot 20190512.1047

**Comment by MaskRay** [comment]
My ccls linked against clang built from trunk does not have the issue.

If this is a clang bug, you can probably wait for the 8.0.1 release and try again..
