### ISSUE TITLE
files with *.d extension

### ISSUE THREAD

**Issue by pavlosun** [MaskRay/ccls#428]
Hi,
I use ccls with neovim via coc. Everything works ok. The only one thing that bugs me is a amount of files with *.d extension. Same name as my source files. I am not sure what programm genertaes them. Could you please confirm if this is ccls and any settings that will alow redirection of these files to a different location. 

Thanks.

**Comment by MaskRay** [comment]
`.d` may be generated by `-MMD` (depfile with user headers) or `-MD` (depfile with user+system headers).

They should be dropped even if `-fsyntax-only` is used. Fixed in HEAD.

**Comment by pavlosun** [comment]
Sorry, I compiled and installed the HEAD but *.d files still generated. They begin from the line:
-MF: <path to the opened source> \
<path to the header> \

**Comment by MaskRay** [comment]
Fixed.. I think you used `compile_commands.json` but I fixed just `.ccls`

**Comment by pavlosun** [comment]
Just compiled HEAD ccls. Removed all cache files, updated all plugins. *.d files. However, *.d files still there. Do I need to use any particular settings? Thanks.

**Comment by pavlosun** [comment]
I found te origin of this problem. *.d files were generated by chromatica plugin.
