### ISSUE TITLE
support suppress diagnostic

### ISSUE THREAD

**Issue by meritozh** [MaskRay/ccls#430]
llvm use `x-macro` trick consistently, such as _DiagnosticOptions.def_.

so if I open this file in VSCode ,it will raise many unexpected warning or error, hope ccls can provide some way to suppress specific diag. for example:

```c
/// [[ccls:noerror]]
#error "this is a error diag"
```

will suppress any error throw by next line.

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/FAQ#diagnostics-in-headers

Such markers are intrusive and bad. An initialization option to custom what diagnostics in what files are blacklisted may be better.

**Comment by MaskRay** [comment]
Emm, I believe this is already possible with recursive `.ccls` files (https://github.com/MaskRay/ccls/wiki/Build#msys2)

You can write:

```
%compile_commands.json
-Wno-foobar
```
