### ISSUE TITLE
ccls show unexpected diagnostic

### ISSUE THREAD

**Issue by meritozh** [MaskRay/ccls#431]
### Observed behavior

<img width="942" alt="Screen Shot 2019-07-01 at 11 34 58 PM" src="https://user-images.githubusercontent.com/7543300/60449442-3b74a280-9c5a-11e9-8b68-5a5d26a348dc.png">

### Expected behavior

No diagnostic

### Steps to reproduce

1. `git clone git@github.com:llvm/llvm-project.git`
2. open VSCode, check _clang/Basic/Diagnostic.h_
3. see unexpected diagnostic in L286-288

### System information

* ccls version: stable 0.20190314.1 (bottled)
* clang version: 8.0.0
* OS: macOS 10.14.4
* Editor: VSCode
* Language client (and version): vscode-ccls

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Project-Setup#llvm-multirepo

```zsh
LLVM_COMMON=(-GNinja -DCMAKE_CXX_COMPILER=$HOME/llvm/Stable/bin/clang++ -DCMAKE_C_COMPILER=$HOME/llvm/Stable/bin/clang -DBUILD_SHARED_LIBS=On -DLLVM_ENABLE_LLD=On)

cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release ${LLVM_COMMON}

cmake -H. -BDebug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS=-Wl,--gdb-index -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--gdb-index -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_USE_SPLIT_DWARF=On ${LLVM_COMMON}
ln -s Debug/compile_commands.json
```

**Comment by meritozh** [comment]
I have run,

```
cmake -G Ninja ../llvm -DLLVM_APPEND_VC_REV=OFF -DLLVM_ENABLE_PROJECTS="clang;llvm;libcxx;libcxxabi;lld;lldb;clang-tools-extra;libunwind;compiler-rt" -DCMAKE_INSTALL_PREFIX=/Users/gaoge/Develop/dev_tool -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

Same result.

How I start from to solve this issue?

**Comment by MaskRay** [comment]
Your cmake command line should have `-DCMAKE_EXPORT_COMPILE_COMMANDS=On`. Then symlink it to the project root.

I enable `-DCMAKE_EXPORT_COMPILE_COMMANDS=On` for my Debug build as it (LLVM_ENABLE_ASSERTIONS=on) compiles some code that is not compiled into a Release/RelWithDebInfo build.

**Comment by meritozh** [comment]
I have try `ninja -t compdb` and `-DCMAKE_EXPORT_COMPILE_COMMANDS=On`, same result. I will try to provide more helpful information about this issue.

By the way, you cannot reproduce?
