### ISSUE TITLE
.ccls file do not work, can not include the head file which the .ccls config

### ISSUE THREAD

**Issue by wutianjun5858** [MaskRay/ccls#434]
.ccls file
```
clang
%cpp -std=c++11
-I/opt/ros/kinetic/include/
```
System information
- ccls version (git describe --tags --long): 0.20190314.1-16-g990925d
- clang version: clang version 7.0.1 (binary)
- OS: ubuntu16.04
- Editor: emacs(spacemacs branch: develop git commit_id: d6c8df)

**Comment by MaskRay** [comment]
Problem?

Please follow the issue template.

**Comment by wutianjun5858** [comment]
sorry
just add one picture on the top
