### ISSUE TITLE
cannot build/configure ccls under msys2

### ISSUE THREAD

**Issue by ducttapecoder** [MaskRay/ccls#436]
Hi,

I'm trying to build ccls with msys2/mingw64 and got the following errors when running CMake.

$ cmake -H../ccls -BRelease -G"Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-D__STDC_FORMAT_MACROS

    -- The CXX compiler identification is GNU 9.1.0
    -- Check for working CXX compiler: C:/building/msys64/mingw64/bin/c++.exe
    -- Check for working CXX compiler: C:/building/msys64/mingw64/bin/c++.exe     -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for C++ include pthread.h
    -- Looking for C++ include pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - found
    -- Found Threads: TRUE
    fatal: No names found, cannot describe anything.
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/NotBackedUp/c++/lib/ccls-build/Release

Tried to change to clang from the msys2 repo but also got the same error:
$ cmake -H../ccls -BRelease -G"Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld

    -- The CXX compiler identification is Clang 8.0.0
    -- Check for working CXX compiler: C:/building/msys64/mingw64/bin/clang++.exe
    -- Check for working CXX compiler: C:/building/msys64/mingw64/bin/clang++.exe     -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for C++ include pthread.h
    -- Looking for C++ include pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - found
    -- Found Threads: TRUE
    fatal: No names found, cannot describe anything.
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/NotBackedUp/c++/lib/ccls-build/Release

Both failed when running build step

$ cmake --build . --target install
    Error: could not load cache

Could you please help? hank you

**Comment by MaskRay** [comment]
`cmake --build . --target install`

You specified the wrong build directory. If you do `cmake -H. -BRelease ...`, the corresponding build command should be `ninja -C Release`
