### ISSUE TITLE
ccls not echoing ID from initialize request in response

### ISSUE THREAD

**Issue by thomasjm** [MaskRay/ccls#437]
### Observed behavior

The LSP spec says that the `id` field of an `initialize` request should be included in the corresponding `ResponseMessage`. But when I send one, the `ResponseMessage` with the `InitializeResult` always seems to contain the string `"0"` for the ID.

### Expected behavior

The response to my `initialize` request should contain the request ID I sent.

### Steps to reproduce

1. Start the `ccls` language server
2. Send a valid `initialize` request with a nontrivial `id` and observe the response.

Maybe the ID is just not getting initialized and most LSP clients tolerate this?

### System information

* ccls version: I'm using the "Pi Day" release
* clang version: N/A
* OS: Linux
* Editor: N/A
* Language client (and version): custom client I'm writing

**Comment by MaskRay** [comment]
> But when I send one, the ResponseMessage with the InitializeResult always seems to contain the string "0" for the ID.

You may have misread the request/response messages. If the `initialize` request specifies `"id":0`, the ResponseMessage will encode `"id":0`. It cannot be `string "0"`.

**Comment by thomasjm** [comment]
@MaskRay the LSP spec allows request/response IDs to be either numbers or strings. So it had better be possible for it to be the string `"0"` or that would be another issue.

In fact, I think that's where the bug lies. I just switched my client to send numeric IDs instead of strings, and that makes it work.

So there is indeed a bug with handling string IDs.

**Comment by Riatre** [comment]
I have read JSONRPC spec again, it indeed allows request ID to be either numbers or **arbitrary** strings. (I'd say this is pretty much fucked up though) 

ccls already tries to handle this, but it assumes string IDs are numeric, which explains those zeros you saw. If you really want arbitrary strings as ID, try the following patch:

```patch
diff --git a/src/lsp.cc b/src/lsp.cc
index 5c56f324..a41a809f 100644
--- a/src/lsp.cc
+++ b/src/lsp.cc
@@ -26,16 +26,16 @@ namespace ccls {
 void Reflect(JsonReader &vis, RequestId &v) {
   if (vis.m->IsInt64()) {
     v.type = RequestId::kInt;
-    v.value = int(vis.m->GetInt64());
+    v.value = std::to_string(int(vis.m->GetInt64()));
   } else if (vis.m->IsInt()) {
     v.type = RequestId::kInt;
-    v.value = vis.m->GetInt();
+    v.value = std::to_string(vis.m->GetInt());
   } else if (vis.m->IsString()) {
     v.type = RequestId::kString;
-    v.value = atoll(vis.m->GetString());
+    v.value = vis.m->GetString();
   } else {
     v.type = RequestId::kNone;
-    v.value = -1;
+    v.value.clear();
   }
 }
 
@@ -45,11 +45,10 @@ void Reflect(JsonWriter &visitor, RequestId &value) {
     visitor.Null();
     break;
   case RequestId::kInt:
-    visitor.Int(value.value);
+    visitor.Int(atoll(value.value.c_str()));
     break;
   case RequestId::kString:
-    auto s = std::to_string(value.value);
-    visitor.String(s.c_str(), s.size());
+    visitor.String(value.value.c_str(), value.value.size());
     break;
   }
 }
diff --git a/src/lsp.hh b/src/lsp.hh
index b097a541..5a137964 100644
--- a/src/lsp.hh
+++ b/src/lsp.hh
@@ -23,6 +23,7 @@ limitations under the License.
 
 #include <chrono>
 #include <iosfwd>
+#include <string>
 
 namespace ccls {
 struct RequestId {
@@ -31,7 +32,7 @@ struct RequestId {
   enum Type { kNone, kInt, kString };
   Type type = kNone;
 
-  int value = -1;
+  std::string value;
 
   bool Valid() const { return type != kNone; }
 };
diff --git a/src/pipeline.cc b/src/pipeline.cc
index 65de7d51..b9f440e2 100644
--- a/src/pipeline.cc
+++ b/src/pipeline.cc
@@ -810,11 +810,10 @@ static void Reply(RequestId id, const char *key,
     w.Null();
     break;
   case RequestId::kInt:
-    w.Int(id.value);
+    w.Int(atoll(id.value.c_str()));
     break;
   case RequestId::kString:
-    auto s = std::to_string(id.value);
-    w.String(s.c_str(), s.length());
+    w.String(id.value.c_str(), id.value.length());
     break;
   }
   w.Key(key);
```

**Comment by thomasjm** [comment]
Thanks for the fix! That patch works for me.

Can we get this patch into `ccls`?
