### ISSUE TITLE
LSP spec violation: returning CodeActionOptions when the client hasn't signaled support

### ISSUE THREAD

**Issue by thomasjm** [MaskRay/ccls#438]
### Observed behavior

I observed the language server returning a `CodeActionOptions` result for the `codeActionProvider` of the `ServerCapabilities`, even when the client did not signal that it could handle this. According to the LSP spec:

```
The `CodeActionOptions` return type is only valid if the client signals code action literal support via the property `textDocument.codeAction.codeActionLiteralSupport`.
```

### Expected behavior

The `codeActionProvider` must be a boolean if the client does not provide `textDocument.codeAction.codeActionLiteralSupport`.

### Steps to reproduce

1. Send an `initialize` request that does not contain `codeActionLiteralSupport` and observe the response. The one I used for this test was as follows:

```
{"jsonrpc":"2.0","id":4414,"method":"initialize","params":{"rootPath":"/home/user","rootUri":"file:///home/user","trace":"verbose","capabilities":{"workspace":{"applyEdit":false,"workspaceEdit":{"documentChanges":false},"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":false},"workspaceFolders":false,"configuration":false},"textDocument":{"synchronization":{"dynamicRegistration":false,"willSave":false,"willSaveWaitUntil":false,"didSave":false},"completion":{"dynamicRegistration":false,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":true},"hover":{"dynamicRegistration":false,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":false,"signatureInformation":{}},"references":{"dynamicRegistration":false},"documentHighlight":{"dynamicRegistration":false},"documentSymbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":false},"rangeFormatting":{"dynamicRegistration":false},"onTypeFormatting":{"dynamicRegistration":false},"definition":{"dynamicRegistration":false},"typeDefinition":{"dynamicRegistration":false},"implementation":{"dynamicRegistration":false},"codeAction":{"dynamicRegistration":false},"codeLens":{"dynamicRegistration":false},"documentLink":{"dynamicRegistration":false},"colorProvider":{"dynamicRegistration":false},"rename":{"dynamicRegistration":false},"publishDiagnostics":{"relatedInformation":true},"foldingRange":{"dynamicRegistration":false,"rangeLimit":5,"lineFoldingOnly":false}}}}}
```

### System information

* ccls version (`git describe --tags --long`): using the "Pi Day" release
* clang version: N/A
* OS: Linux
* Editor: N/A
* Language client (and version): custom client I'm writing. (It uses [haskell-lsp-types](http://hackage.haskell.org/package/haskell-lsp-types) which does not yet have full support for `CodeActionOptions`.)

**Comment by MaskRay** [comment]
> The `CodeActionOptions` return type is only valid if the client signals code action literal support via the property `textDocument.codeAction.codeActionLiteralSupport`.

I think this can be explained this way: the `codeActionProvider` field of the result is invalid if `textDocument.codeAction.codeActionLiteralSupport` is not true. The server is still free to return this field but the client just should not interpret it.

Actually, these param/result types are just JavaScript objects, and it is fairly common for servers/clients to add additional fields for extensions/debugging purposes/etc. It is more of a problem if you rigidly disallow additional fields.

**Comment by thomasjm** [comment]
@MaskRay that doesn't make sense. We're not talking about an "additional" field here. When LSP 3.11.0 was released, the type changed from 

```
	/**
	 * The server provides code actions.
	 */
	codeActionProvider?: boolean;
```

to

```
	/**
	 * The server provides code actions. The `CodeActionOptions` return type is only
	 * valid if the client signals code action literal support via the property
	 * `textDocument.codeAction.codeActionLiteralSupport`.
	 */
	codeActionProvider?: boolean | CodeActionOptions;
```


So clearly returning an object for `codeActionProvider` when the client hasn't signalled their support is a violation of the spec, since it will confuse a pre-3.11.0 client who is expecting a boolean.

Could you please take another look at this?

**Comment by MaskRay** [comment]
@thomasjm Thanks for taking a closer look at this issue. My feeling is that it is not worth extending it to `boolean | CodeActionOptions;`.

The first problem is that ccls uses Reflect to serialize a JSON object, it will introduce much boilerplate to support it. The second is that we don't necessarily support every LSP minor version. Some, as you observed, were designed without deliberate thoughts (some of my rants are recorded at wiki/LSP). In this case, the client (usually implemented with a dynamically-typed language where expression such variant constructs are much more convenient) can do a better job handling this. I'd rather offload the duty to the client.

**Comment by thomasjm** [comment]
Thanks for the response @MaskRay. A couple final thoughts:

* Since we both agree `ccls` is violating the spec here, why not just keep the issue open? Maybe then someone can send a PR to fix it.
* A type going from `boolean` to `boolean | Something` is pretty common as the LSP spec has evolved. If you're going to refuse to support such things then you're going to introduce a backwards compatibility problem every time this happens.
* This attitude towards compliance with the spec makes me sad because I really like `ccls`, but writing an LSP client is hard enough without language server authors picking and choosing which parts of the spec to follow. This particular issue is not a huge one, but this kind of thing might force me to find a different backend :(

**Comment by MaskRay** [comment]
@thomasjm I really appreciate your suggestions to ccls.

For compliance on legacy LSP things, I take them on a case-by-case basis. `CodeActionOptions` is really something that the spec writer didn't pay enough attention and they then messed it with the variant types. ccls was born on April 1, 2018. LSP 3.11 came out on August 21, 2018 when ccls still didn't have many users. I don't want to introduce LSP compatibility code when most prominent language clients already support the replacements just to meet the compliance requirement of legacy LSP things. It is especially sad that LSP is not a community maintained protocol. A lot of stuff are tightly coupled with VSCode internals.

 I agree it does require some efforts to figure out good parts from LSP and it isn't an easy task ;-)
