### ISSUE TITLE
[Question] Emacs' lsp-mode and project-wide error reporting

### ISSUE THREAD

**Issue by aschneid1** [MaskRay/ccls#439]
I've just switched over from irony-server to ccls/lsp-mode.  Really liking a lot of the features, so thanks!

What I want to know: Is it at all possible to show all errors in a project within the treemacs-error-list?  For example, if I only have one open buffer (a.hpp), and change a function name, is there a way to have ccls and/or lsp display all of the resulting errors (preferably without having to manually call ccls-reload).  

One thing I'm uncertain of is how ccls integrates with lsp-mode, and more specifically, the lsp-treemacs-error-list.  Judging by ccls' logging, opening a new buffer starts a clang session that watches the file for edits?  And after digging through some code here, it looks like there may be a maximum of 10 sessions, correct?

Not a huge deal if not, but I've looked at the docs for both lsp-mode and ccls and haven't been able to turn up anything concrete (aside from the customization variables "track dependency" and "on change" for ccls which maybe have something to do with this?).

Thanks for any help!

**Comment by MaskRay** [comment]
> Is it at all possible to show all errors in a project within the treemacs-error-list?

You'll have to open all files (`textDocument/didOpen`) to get all diagnostics.

> if I only have one open buffer (a.hpp), and change a function name, is there a way to have ccls and/or lsp display all of the resulting errors (preferably without having to manually call ccls-reload).

Say you have `a.cc` and `b.cc` that include `a.hpp` opened. `$ccls/reload` triggers re-indexing of `a.cc`, `b.cc` (opened) and `c.cc` (not-opened) but the indexer doesn't refresh the diagnostics. You have to send `textDocument/didChange` with empty change to `a.cc` and `b.cc` to retrieve the updated diagnostics.

This choice is deliberate. There can be hundreds of files that include `a.hpp`. A change of `a.hpp` should never re-trigger diagnostics computing (compilation) on all dependent files automatically. Actually, on some large file, computing diagnostics may take 1 second or longer (try `clang++ -fsyntax-only huge.cc`), even if the preamble part is cached.

**Comment by aschneid1** [comment]
Fair enough.  Thanks for the quick response!  

If you don't mind my asking (and have the time/energy/will to bother responding), how do other IDEs and (presumably) LSP engines handle this situation?

**Comment by aschneid1** [comment]
Follow up/Feature request: Would it be possible to create a function that forces this behavior for a particular file?  That is, an elisp function that identifies the dependencies of a header and triggers the diagnostic for them?  

I understand there may be a performance penalty, but it would be mitigated f this only happens when forced by a user.  Plus this seems like a must-have feature for large refactoring tasks where someone making a change in a header needs to know everything that broke from the change (preferably without leaving emacs or using a separate compilation process).

**Comment by MaskRay** [comment]
In emacs-ccls, I have added an optional parameter to `ccls-file-info`. You can use `(ccls-file-info '(:dependencies t :includes t))` to dump includes (direct #include) and dependencies (transitive #include).

Write some elisp snippets to:

1. When a .cc file is opened, retrieve dependency information with `ccls-file-info` and record it.
2. When a `.h` is edited (e.g. adding a hook to `after-change-functions`), look it up which `.cc` files directly/transitively include it and call `(lsp-on-change 0 0 0)` on their buffers.

**Comment by aschneid1** [comment]
I finally had a chance to play around with this a bit.  I've managed to get the basic skeleton of this working, but I'm running into an issue with (lsp-on-change).  Here's the chunk of code I've cobbled together so far: 

```elisp
(setq ccls-file-dependency-hash (make-hash-table :test 'equal))

;;Setup initial blacklist locations
(setq ccls-path-prefix-blacklist '("/usr/local/include"  "/usr/local" "/usr/include"
                                   "/Applications/Xcode.app" "/Library/Developer"))

(require 'seq)

;; check if a string matches a pattern
(defun file-blacklisted-p (file)
  "Checks if the passed file path is part of ccls-path-prefix-blacklist"
  (not (string-match-p (concat (regexp-opt ccls-path-prefix-blacklist)  ".*")
                  file)))

;; remove items that are blacklisted
(defun insert-into-hash ()
  "Inserts the dependencies of the currently selected buffer into ccls-file-dependency-hash"

  ;;Fails if ran by adding hook to c++-mode directly.  I think it's
  ;;because the LSP client hasn't been started/initialized, yet?  If
  ;;there's a ccls hook to notify that the client for a file is up and
  ;;running that would be better
  (when (eq major-mode 'c++-mode)
    (let ((file-list (gethash "dependencies"
                              (ccls-file-info '(:includes t :dependencies t)))))
      (dolist (file-dependency (seq-filter 'file-blacklisted-p file-list))
        (let ((dependency-list (gethash file-dependency ccls-file-dependency-hash)))
          (setf (gethash file-dependency ccls-file-dependency-hash)
                (add-to-list 'dependency-list buffer-file-name)))))))


(add-hook 'before-save-hook 'insert-into-hash)

;; make myBuf current temporarily
(defun notify-buffer-changed (file &optional force-open)
  ;;; Check if a buffer corresponding to file is open.  If so, send notification to lsp-server
  (if force-open
      (find-file-noselect file))
  (if (find-buffer-visiting file)
        (with-current-buffer (find-buffer-visiting file)
          (message "Checking file %s in buffer %s" file (current-buffer))
          (lsp-on-change 0 0 0))))



(defun notify-dependencies-of-change (&optional force-open depth file)
  (unless file (setq file buffer-file-name))
  (unless depth (setq depth 2))
  (message "file: %s and dpeth: %s" file depth)
  (if (> depth 0)
        (let ((file-list (gethash file ccls-file-dependency-hash)))
          (dolist (file-dependency file-list)
            (notify-buffer-changed file-dependency force-open)
            (notify-dependencies-of-change force-open (- depth 1) file-dependency)))))
```

After opening and saving a couple of files, some entries in the hash table should be populated.  After changing a header file (in one of the registered dependencies), you can call notify-dependencies-of-change to traverse the files that depend on the altered header file (up to a default depth of 2).  However, I'm currently running into a wall with the call to lsp-on-change in notify-buffer-changed.  I currently get the error 

> Debugger entered--Lisp error: (args-out-of-range #<buffer FileName.h/cpp/whatever> 0 0)

I've tried playing with the parameters a bit (for instance, changing 0 0 0 to 1 (buffer-size) 0), but that just induces a lot of incorrect error reports from ccls.  I've looked at the implementation of lsp-on-change but I'm struggling to find any actual uses of the function that I could use as an example.  Any advice for me?

Also, apologies for the rough draft of the elisp above.   Still very much a work in progress.
