### ISSUE TITLE
index.onChange=true doesn't work for documentSymbols/hover/etc. when filling in an empty document

### ISSUE THREAD

**Issue by thomasjm** [MaskRay/ccls#443]
### Observed behavior

**Note**: I made a simple repro script, which can be found here: https://github.com/thomasjm/ccls_index_repro

The issue I'm seeing is that `ccls` does not properly index files in response to a `textDocument/didChange` event. I'm using these steps:

1. Launch `ccls` with options `{"index": {"onChange": true}}`
2. Create a blank file by sending a `textDocument/didOpen` command with empty text.
3. Send a `textDocument/didChange` command that updates the contents of the file to something simple. I'm using

```c
#include <stdio.h>

int main() {
    printf();
}
```

3. Send a command such as `textDocument/documentSymbol`. It comes back with no symbols, when it should contain a single symbol `main`. Other things like `textDocument/hover` on the `printf` also don't work.

Interestingly, it **does** publish diagnostics correctly. The example code I'm using produces a warning that `printf` is called with too few arguments, and this diagnostic appears after the code is added.

### Expected behavior

Based on my reading of the FAQ and the documentation for `index.onChange`, you should be able to paste content into an empty file and immediately get document symbols, hover, etc. to work.

### Steps to reproduce

See above.

### System information

* ccls version (`git describe --tags --long`): `0.20190314.1` (Pi Day)
* clang version: `5.0.2`
* OS: Linux
* Editor: N/A
* Language client (and version): N/A

**Comment by MaskRay** [comment]
The interaction script is so great! You can debug ccls with `gdb -p $(pgrep -fn Debug/ccls)`.

If you set a breakpoint at pipeline.cc:Indexer_Parse, you'll notice that the following lines will run:

```cpp
  if (deleted) {
    indexes.push_back(std::make_unique<IndexFile>(request.path, "", false));
    if (request.path != path_to_index)
      indexes.push_back(std::make_unique<IndexFile>(path_to_index, "", false));
```

A non-existent file is considered deleted, and its file index will be deleted if present before. I know in your reproduce you just created a new file, and expected the file to be indexed. The two cases are really difficult to differentiate. Think: if `a.cc` includes `a.h` and there's cache for both `a.cc` (`.ccls-cache/xxx/a.cc.blob`) and `a.h`. If `a.h` was deleted in another terminal, the client may not notice it (it can if it supports `workspace/didChangeWatchedFiles` but the deleted file may not be opened (thus watched) by the client).

I think the resolution is that you should make sure the file exists.

**Comment by thomasjm** [comment]
Thanks for looking into why this is happening!

Unfortunately this isn't a satisfactory resolution at all -- it's a super common workflow to create a new file in your editor, which might not have been saved yet, and start typing code in it. You still want the language server to work. I suspect this is the entire reason the LSP protocol was designed to include the `text` in the `textDocument/didOpen` request.

I've worked with several language servers now and `ccls` is the only one I've encountered that has this problem. In particular, I just tried `clangd` and it doesn't have this problem.

Why not keep this issue open so we can work towards a fix?

**Comment by MaskRay** [comment]
Give it another thought. I think it makes sense to trust the client if it sends a workspace/didChangeWatchedFiles notification with a deletion event.

```
    case FileChangeType::Deleted:
-      pipeline::Index(path, {}, mode, false);
+      pipeline::Index(path, {}, IndexMode::Delete, false);
```

In `index.onChange:true` mode, it probably makes sense not to consider a non-consistent file deleted if there is a working file (seen a `document/didOpen` but not a `document/didClose`). Can you check #444?

**Comment by thomasjm** [comment]
Thanks!!! Yes, I'll try the PR tomorrow.
