### ISSUE TITLE
LSP spec violation: returning signature label offsets when the client hasn't signaled support

### ISSUE THREAD

**Issue by thomasjm** [MaskRay/ccls#446]
This is the exact same situation as issue #438 . In this case, `ccls` is returning signature label offsets even though the client hasn't set `signatureHelp.signatureInformation.parameterInformation.labelOffsetSupport` in their client capabilities.

I'm filing this one as its own issue in case you want to handle it separately. This is a more recent LSP feature than the previous issue, part of 3.14.0 from mid-December 2018.

**Comment by MaskRay** [comment]
This is one which I am very unhappy with:( (Both the initial proposal, and the amended spec) It was pretty much a mistake to make it 

`label: string;` at first then change it to

`label: string | [number, number];` afterwards.

See https://github.com/microsoft/language-server-protocol/issues/640
