### ISSUE TITLE
Option to do a quiet index ?

### ISSUE THREAD

**Issue by maindoor** [MaskRay/ccls#447]
I started ccls from the command line and it started spewing out the commands it is executing
by default. I have tested it on my codebase and I trust it is building it properly. I don't want
to see all the commands it is internally invoking..not to mention the time it can save by not
outputting to the slow console. 
I tried setting the "-v=0" and  "-v=1" none of it helped. 
Even tried  "2>&1 > /dev/null", that didn't help either, wonder why.

Is there an option to do a quiet indexing ?

**Comment by MaskRay** [comment]
See https://github.com/MaskRay/ccls/wiki/Project-Setup `ccls --index ~/project` to index a project.

In language server mode, read `--log-file` `-v` on https://github.com/MaskRay/ccls/wiki/Debugging
