### ISSUE TITLE
company-lsp crashes ccls.

### ISSUE THREAD

**Issue by amosbird** [MaskRay/ccls#45]
log
```
00:06:44 comp-query   clang_complete.cc:371 I create completion TU for /home/amos/cc/playground/default^2018-08-04-000454/snippet.cpp
00:06:44 comp-query       clang_tu.cc:106 E clang crashed for /home/amos/cc/playground/default^2018-08-04-000454/snippet.cpp
clang++ -std=c++17 -I/usr/local/include -I/usr/include /home/amos/cc/playground/default^2018-08-04-000454/snippet.cpp -resource-dir=/usr/local/lib/clang/7.0.0 -working-directory=/home/amos/cc/playground/default^2018-08-04-000454/ -Wno-unknown-warning-option -fsyntax-only
```

ccls   924fedbb02be07e19fd2a5372a09e89779973d41
llvm  https://reviews.llvm.org/rL338899

A minimal reproducible case is
```
#include <iostream>

using namespace std;

int mymain(int argc, char *argv[]) {
    cou|
    return 0;
}
```
and `M-x company-lsp` at point.

The ccls launching script I used is,

```
exec ~/git/ccls/release/ccls --log-file=/tmp/cq.txt --init="{\"cacheDirectory\": \"/home/amos/.cache/.ccls_cached_index\", \"client\": {\"snippetSupport\": true}, \"index\": {\"reparseForDependency\": 1, \"comments\": 0}, \"diagnostics\": {\"frequencyMs\": 3000}, \"completion\": {\"includeBlacklist\": [\"llvm\", \"QT\", \"c++/7.3.0\", \"polly\", \"clang\"]},  \"extraClangArguments\": [\"-fno-delayed-template-parsing\", \"-std=c++1z\", $includes]}" "$@"
```

**Comment by MaskRay** [comment]
I'm having to reproduce.

> 00:06:44 comp-query       clang_tu.cc:106 E clang crashed for /home/amos/cc/playground/default^2018-08-04-000454/snippet.cpp

Can you attach the process with `cgdb -p $(pgrep -fn ccls)` before some clang thread crashed? The lack of stack trace and local variables make diagnosis hard.

**Comment by MaskRay** [comment]
https://github.com/llvm-mirror/clang/tree/master/include/clang/Frontend/ASTUnit.h#L808

Do you mean the last argument of `ASTUnit::LoadFromCommandLine` may be an uninitialized non-null pointer?

**Comment by amosbird** [comment]
Yes, I've tried lvalue/rvalue/default constructions, none of them work. I also tried static/dynamic llvm built. No luck either. I've examined the ccls dependencies via `ldd` and make sure all the so files are up to date. I also removed all related clang/llvm header files before rebuilding.

**Comment by MaskRay** [comment]
Just a tip. If you copy `ld.lld` (>= llvm 6.0) to your PATH directory, you may use

`cmake -H. -BDebug -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS=-Wl,--gdb-index  -DLLVM_ENABLE_LLD=ON -DBUILD_SHARED_LIBS=ON -DLLVM_INCLUDE_GO_TESTS=OFF
 -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_USE_SPLIT_DWARF=On -DLLVM_OPTIMIZED_TABLEGEN=On`

`-DLLVM_ENABLE_LLD=ON -DBUILD_SHARED_LIBS=ON -DLLVM_OPTIMIZED_TABLEGEN=On` are important for a faster build.

**Comment by amosbird** [comment]
I've even cloned a new llvm repo from https://git.llvm.org/git/llvm.git and followed the exact steps of 
https://github.com/MaskRay/ccls/wiki/Build#link-against-clangllvm-libraries-compiled-from-source

**Comment by MaskRay** [comment]
Closing.

**Comment by MaskRay** [comment]
A similar issue from scturtle https://notepad.pw/raw/g20i6ai72

**Comment by MaskRay** [comment]
Close as they seem to work by linking libclang*.a and libLLVM*.a 

Their use of libclang*.so libLLVM*.a can lead to conflicts.
