### ISSUE TITLE
ccls does not quit after sublime closed

### ISSUE THREAD

**Issue by wsw0108** [MaskRay/ccls#451]
### Observed behavior

**Before sublime close:**
![image](https://user-images.githubusercontent.com/4977975/61991074-c12f1680-b07d-11e9-9249-5143b19b49aa.png)

**After sublime close:**
![image](https://user-images.githubusercontent.com/4977975/61991087-f6d3ff80-b07d-11e9-9100-b28f140365f8.png)

### Expected behavior

ccls should quit after sublime closed.

### Steps to reproduce

1. Globally enable ccls for tomv565/LSP
2. Open a project contains a simple hello.c, and open this hello.c, ccls launched
3. Close sublime

### System information

* ccls version (`git describe --tags --long`): 0.20190314.1-20-gaf72b59d
* clang version: 8.0.0
* OS: Windows 10
* Editor: sublime
* Language client (and version): tomv564/LSP

**Comment by MaskRay** [comment]
This doesn't happen for other clients. Can you check if the client sends the "shutdown" request, after receiving the `null` response, sends the "exit" notification?

Even if the client doesn't send the "exit" notification, if it closes the write end of the pipe, the "stdin"` thread of ccls will receive EOF and exit.

**Comment by wsw0108** [comment]
Below is the log of tomv564/LSP, version 0.8.5:
The first line indicate that a new window for project 'D:\Github\ccls' opened.
LSP client shows that it sends 'exit' after 'shutdown'.

```
git: tracking working dir D:\Github\ccls
git: tracking working dir D:\Github\ccls\third_party\rapidjson
git: tracking working dir D:\Github\ccls\third_party\rapidjson\thirdparty\gtest
LSP: window 7 has override for cquery {'enabled': False}
LSP: window 7 has override for clangd {'enabled': False, 'command': ['C:/Program Files/LLVM/bin/clangd.exe']}
LSP: window 7 has override for ccls {'enabled': True, 'initializationOptions': {'compilationDatabaseDirectory': 'build', 'cache': {'directory': '/tmp/ccls'}}}
LSP: window 7 requests ccls for D:\Github\ccls\src\main.cc
LSP: starting in D:\Github\ccls
LSP: starting ['ccls', '-log-file=stderr']
LSP:  --> initialize
LSP: window 7 added session ccls
LSP:  --> initialized
LSP:  --> textDocument/didOpen
LSP: <--  $ccls/publishSkippedRanges
LSP: Unhandled notification $ccls/publishSkippedRanges
LSP: <--  $ccls/publishSemanticHighlight
LSP: Unhandled notification $ccls/publishSemanticHighlight
LSP: <--  $ccls/publishSemanticHighlight
LSP: Unhandled notification $ccls/publishSemanticHighlight
LSP: <--  textDocument/publishDiagnostics
git: untracking working dir D:\Github\ccls\third_party\rapidjson
git: untracking working dir D:\Github\ccls\third_party\rapidjson\thirdparty\gtest
LSP: closing D:\Github\ccls\src\main.cc ccls
LSP:  --> textDocument/didClose
LSP: window 7 closed, ending sessions
LSP: unloading session ccls
LSP:  --> shutdown
git: untracking working dir D:\Github\ccls
LSP:  --> exit
LSP: session ccls ended
LSP: clients for window 7 unloaded
LSP: window 7 closed and sessions unloaded
```

**Comment by wsw0108** [comment]
Sorry, this should be the bug of tomv564/LSP.
