### ISSUE TITLE
Code completion in headers

### ISSUE THREAD

**Issue by theorlangur** [MaskRay/ccls#456]
There's a project structure like following:
 a 'central' header (much like stdafx.h) that includes all (or most of) other headers and this central header is included by every TU-cpp file in the project. Headers (other than 'central') on their own have **no** includes and rely a lot on the order they're included in the central header, so that all necessary types are declared/defined when they are needed.

Code completion works nicely in cpp's, but fails when used in headers (e.g. when writing some inline methods). Is it possible somehow, when there're no "firm" completion results to try to 'guess', based on where the current file is included and what is possible 'visible' for it? Or maybe there's already a solution/workaround for this kind of organization?

Thanks!

**Comment by MaskRay** [comment]
Added the following to the wiki https://github.com/MaskRay/ccls/wiki/FAQ#diagnostics-in-headers

If missing declarations are known to be provided by base.h, you can specify --include, e.g.

```
%compile_commands.json
%h %hpp --include=base.h
```

The syntax is documented at https://github.com/MaskRay/ccls/wiki/Project-Setup#compile_commandsjson-1
