### ISSUE TITLE
Failed to index errors, possibly related to unescaped clang calls.

### ISSUE THREAD

**Issue by RobRuckOB** [MaskRay/ccls#458]
My project uses precompiled headers (via cotire), and also contains a number of version related defines, such as:
`VERSION_MAJOR="0"`. These carry through, properly escaped, to the compile_commands.json that ccls uses, i.e.:
`-DVERSION_MAJOR=\\\"0\\\"`

## Observed behavior

When ccls runs clang against a file _before_ the PCH is generated, it will work correctly and ccls will index the file.

When ccls attempts to run clang against a file _after_ the PCH has been generated, the clang call will fail, citing macro definition errors:

`error: definition of macro 'VERSION_MAJOR' differs between the precompiled header ('"0"') and the command line ('0')`

 a ccls indexing error will then occur, and the file will continue to be unindexed until the build is cleaned and the PCH no longer exists.

### Expected behavior

ccls should call clang with the same escape characters as compile_commands.json, i.e.

`/usr/bin/clang++ "-DVERSION_MAJOR=\"0\""`

and not what looks like an unescaped version:

`/usr/bin/clang++ -DVERSION_MAJOR="0"`

### Steps to reproduce

1. Have a build define with a string value in a project that uses a PCH
2. Run ccls against a source file before the PCH is generated, see that there are no errors in the clang call (besides the missing PCH - unimportant presumably)
3. Generate the PCH (I'm doing a normal build via VS Code)
4. Run ccls against the same source file, and see that the clang call throws the macro definition error

### System information

* ccls version (No names found, cannot describe anything): Revision 8b0332173f51389d3ab914313b874cea04f4ead4
* clang version: 
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
* OS: OSX 10.13.6
* Editor: VS Code

**Comment by MaskRay** [comment]
If your `compile_commands.json` entries use `"command"` but not `"arguments"` https://clang.llvm.org/docs/JSONCompilationDatabase.html , one probably problem is that how clang unescapes the arguments is different from the shell. You have to use the `"arguments"` format.

See https://github.com/MaskRay/ccls/wiki/Project-Setup#cmake for an closely related Windows problem.

**Comment by RobRuckOB** [comment]
Thanks for replying, and after some research this appears to be a problem not confined to just ccls, and effects everything that uses clangs own compilation database loader code and it's poor unescaping code. 

I'm now left at somewhat of a deadend with ccls:
- ninja offers no capability to generate `"arguments"` vs `"command"`
- cmake has no post generation step functionality for me to hook in a simple convert script to go from `"command"` to `"arguments"`
- having another step that requires manual calling isn't feasible
- raising an issue about this with clang might get a fix in _years_ to come, but not anytime soon

Is there any interest in not using `clang/Tooling/CompilationDatabase.h` for loading the database, in light of it's problems? The compile_commands.json format is largely static, and wouldn't be changed in any kind of a hurry by clang/llvm. I can see from a standards and convenience point of view that it's easier to stick with the official

The VS Code C++ extension appears to entirely sidestep it, and so has no problems executing commands as they are intended with all appropriate escaping - comparing the two clang calling styles is what showed up this issue for me in the first place.
