### ISSUE TITLE
Failed to index caused by -Xclang

### ISSUE THREAD

**Issue by 4B5F5F4B** [MaskRay/ccls#460]
Here are some things you should try before filing a bug report:

+ For client issues related to [emacs-ccls](https://github.com/MaskRay/emacs-ccls) or [vscode-ccls](https://github.com/MaskRay/vscode-ccls), report in their own repository.
+ For build problems, check https://github.com/MaskRay/ccls/wiki/Build
+ Check https://github.com/MaskRay/ccls/wiki/Debugging
+ Check [the FAQ](https://github.com/MaskRay/ccls/wiki/FAQ) to see if your issue is mentioned.

If none of those help, remove this section and fill out the four sections in the template below.

---

### Observed behavior

compile options  ```-Xclang -add-plugin``` leads to indexing failure.

+ compile_commands.json
```
[
	{
	   "directory": "/home/fuzzer/tmp/test_ccls",
	   "command": "clang++ -Xclang -add-plugin -Xclang plugin-foo -Xclang plugin-bar  test.cc -o test",
	    "file": "src/test.cc"
	}
]

```

+ test.cc
```
int foo()
{
    return 0;
}
int main()
{
   foo();
}
```

+ result
```
pending:     209:17:47 indexer0         pipeline.cc:349 I parse /home/fuzzer/tmp/test_ccls/src/test.cc
09:17:47 indexer0          indexer.cc:1310 E failed to index /home/fuzzer/tmp/test_ccls/src/test.cc
pending:     0

```

### Expected behavior

If you remove  ```-Xclang -add-plugin``` it works

+ compile_commands.json
```
[
	{
	   "directory": "/home/fuzzer/tmp/test_ccls",
	   "command": "clang++ test.cc  -Xclang plugin-foo -Xclang plugin-bar -o test",
	    "file": "src/test.cc"
	}
]

```

+ result

```
pending:     209:33:32 indexer2         pipeline.cc:349 I parse /home/fuzzer/tmp/test_ccls/src/test.cc
09:33:32 indexer2         pipeline.cc:387 I store index for /home/fuzzer/tmp/test_ccls/src/test.cc (delta: 0)
pending:     0

```

### Steps to reproduce

1. make directory named test_ccls, and make sub-directory named src
2. place compile_commands.json in test_ccls and test.cc in src
3. open terminal in directory test_ccls, and run ```ccls -index=.```

### System information

* ccls version:
commit: 1b1b7fbc8a4419b552773f0a90838aba9baf9105
* clang version: 
clang version 9.0.0 (tags/RELEASE_900/rc1)
* OS: Ubuntu 19.0.4

**Comment by 4B5F5F4B** [comment]
I write a few line of python codes to remove all -Xclang related compiler options in compile_commands.json to make ccls happy

```
import sys
import os


def convert(old_file_path):
    old_file_name = os.path.basename(old_file_path)
    bak_file_name = "%s.bak" % old_file_name
    bak_file_path = os.path.join(os.path.dirname(old_file_path), bak_file_name)
    os.system("mv %s %s" % (old_file_path, bak_file_path))
    bak_file_handle = open(bak_file_path, "r")
    new_file_path = old_file_path
    new_file_handle = open(new_file_path, "w")
    json_code = bak_file_handle.readline()
    while json_code != "":
        if json_code.find("\"command\":") != -1:
            compiler_args = json_code.split(":")[1]
            compiler_args = compiler_args[compiler_args.find("\"") + 1: compiler_args.rfind("\"")].split(" ")
            compiler_options = ""
            i = 0
            while i < len(compiler_args):
                if compiler_args[i] == "-Xclang":
                    i += 2
                else:
                    compiler_options += compiler_args[i] + " "
                    i += 1
            json_code = "    \"command\": \"%s\",\n" % (compiler_options)
        new_file_handle.write(json_code)
        json_code = bak_file_handle.readline() 
    
    bak_file_handle.close()
    new_file_handle.close()
    return



if __name__ == "__main__":
    convert(sys.argv[1])
```

**Comment by MaskRay** [comment]
If the clang library cannot find the plugin, it will fail. There are multiple ways to solve the problem.

1) `sed -Ei 's/-Xclang [^ ]+ //g' compile_commands.json`
2) https://github.com/MaskRay/ccls/wiki/Project-Setup Use `compilationDatabaseCommand`
3) `-Xclang` is removed after https://github.com/MaskRay/ccls/pull/480
