### ISSUE TITLE
Failed to index correctly after updating macOs/Xcode

### ISSUE THREAD

**Issue by sunbubble** [MaskRay/ccls#462]
I've run in to this issue twice already and has caused me confusion. I just want to describe the problem and the solution here since I didn't find it documented anywhere. Maybe you can add this to the wiki or if you already mention this somewhere, make it more visible.

I'm using ccls with emacs-lsp and every once in a while when the seasonal macOs update comes around, ccls stops indexing properly. Since I rarely open Xcode I often miss that after such an update when you open the application a dialog pops up letting you know that you have to download some extra stuff for the compilation toolchain in macOs.

**Solution:** Long story short, after you open Xcode and download the missing bits, ccls works as expected again.

Cheers

**Comment by MaskRay** [comment]
> ... download the missing bits

What are the missing bits? Can you share your build instructions?

I just want to note one thing I think that may be relevant: ccls links against llvm/clang libraries found somewhere at cmake configure time. If the libraries get updated, you have to rebuild ccls. Sometimes Clang resource directory (https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory) may change. It may work with minor version bumps but generally this may not be very reliable.

**Comment by sunbubble** [comment]
I think it's the updated command line tools. I probably won't be able to reproduce the problem until the next version of Xcode is released.

I haven't tried the clang-resource-directory approach, that may very well fix the problem.
