### ISSUE TITLE
"compilationDatabaseDirectory" not working

### ISSUE THREAD

**Issue by Gollum999** [MaskRay/ccls#466]
### Observed behavior

`compile_commands.json` only loads when found in project root, not when path is specified via 
`compilationDatabaseDirectory`.  See below for example.

### Expected behavior

`compilationDatabaseDirectory` should help find `compile_commands.json` when located in another directory.

### Steps to reproduce

```
$ cat main.cpp
#include <iostream>

int main(int argc, char *argv[]) {
    std::cout << "Hello world\n";
    return 0;
}

$ cat CMakeLists.txt
cmake_minimum_required(VERSION 2.8)
project(Demo)

add_executable(demo main.cpp)
target_compile_definitions(demo PUBLIC "TEST")

$ touch .ccls

$ cd ../bld

$ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ../src
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tsanders/demo/bld

$ cd -

$ rm -rf .ccls-cache

$ ccls -v=1 --index=. --init='{"compilationDatabaseDirectory":""}' |& grep loaded

$ rm -rf .ccls-cache

$ ccls -v=1 --index=. --init='{"compilationDatabaseDirectory":"/home/tsanders/demo/bld/"}' |& grep loaded  # This does not find compile_commands.json when it should

$ ln -s /home/tsanders/demo/bld/compile_commands.json

$ rm -rf .ccls-cache

$ ccls -v=1 --index=. --init='{"compilationDatabaseDirectory":""}' |& grep loaded  # Symlinking works as expected
18:27:15 ccls              project.cc:428 I loaded /home/tsanders/demo/src/compile_commands.json

$ rm -rf .ccls-cache

$ ccls -v=1 --index=. --init='{"compilationDatabaseDirectory":"/home/tsanders/demo/bld/"}' |& grep loaded  # Specifying "compilationDatabaseDirectory" overrides the local file, as expected, but still doesn't find the file in the build directory

$ tree -L 2
.
|-- bld
|   |-- CMakeCache.txt
|   |-- CMakeFiles
|   |-- cmake_install.cmake
|   |-- compile_commands.json
|   `-- Makefile
`-- src
    |-- CMakeLists.txt
    |-- compile_commands.json -> /home/tsanders/demo/bld/compile_commands.json
    `-- main.cpp

3 directories, 7 files

```

Am I doing anything wrong here?  I've tried things like adding a `.ccls-root` file, using relative paths, etc., but the only thing I've found that works is to put `compile_commands.json` in my root directory.

### System information

* ccls version: `git describe --tags --long` finds no names; my HEAD is at: `commit 9079c48c77207108c61ebde0a6d26948d661df7c, Date: Sun Aug 11 18:06:47 2019 +0800`
* clang version: 8.0.1
* OS: CentOS 7.4
* Editor: Emacs 26.2 (Doom 2.0.9)
* Language client (and version): lsp-mode 20190629.54

**Comment by MaskRay** [comment]
Thanks for the detailed and easy-to-reproduce instructions.

It seems absolute `compilationDatabaseDirectory` never works before. `llvm::sys::path::append` does not delete existing path components when an absolute component is seen. Can you try https://github.com/MaskRay/ccls/pull/468 ?

> $ touch .ccls

If `.ccls` is present, it will recursively index other files in the directory, not just files described by `compile_commands.json`. You should delete it if you don't want other files to be indexed.

https://github.com/MaskRay/ccls/wiki/Project-Setup#ccls-file

**Comment by Gollum999** [comment]
#468 seems to work.  Thanks for the very fast fix!

**Comment by ValouBambou** [comment]
I faced the exact same problem today using ccls inside neovim. I used the compilationDatabaseDirectory option to search for build directory, but it doesn't work. But adding an empty .ccls file solved the issue, I'm not sure if this is the expected behavior.
