### ISSUE TITLE
FR: C designated initializers

### ISSUE THREAD

**Issue by Synray** [MaskRay/ccls#47]
Hello, great work with this project, for me it's the holy grail of Vim autocompletion.

ISO C99 added "Designated Initializers": you can give the elements of a struct initializer in any order, by specifying the name of each field to initialize with _`.fieldname =`_. For example:
```c
struct VkInstanceCreateInfo inst_info =
{
    .sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
    .pNext = NULL,
    .flags = 0,
    //...
};
```
Since each undeclared field is initialized to `0`, designated initializers are safer because they avoid undefined behavior caused by uninitialized fields. This feature is only in C.

These initializers are often a lifesaver for me. Would it be possible to add field completion for this?

**Comment by MaskRay** [comment]
clang does not seem to support completion of designated initializers.

You may try
`clang -fsyntax-only -Xclang -code-completion-at=b.c:9:7 -fallow-editor-placeholders b.c`

**Comment by Synray** [comment]
> clang does not seem to support completion

That's a shame, although clang gives an error message for it. It's probably just not implemented yet then. Thanks for looking into it anyways.
