### ISSUE TITLE
Hou should i index a project built using bazel

### ISSUE THREAD

**Issue by landcold7** [MaskRay/ccls#470]
Hi, My issue as I mentioned in the title, [bazel](https://bazel.build) is another build tool.

**Comment by MaskRay** [comment]
https://stackoverflow.com/questions/44966133/how-to-generate-compile-commands-json-for-a-c-bazel-project
https://github.com/grailbio/bazel-compilation-database
https://github.com/MaskRay/ccls/wiki/Project-Setup#ccls-file

**Comment by cpsauer** [comment]
@allenanswerzq, or anyone else reading this trying to use CCLS w/ Bazel:

Come check out https://github.com/hedronvision/bazel-compile-commands-extractor! It's replaced the above, and it's actively being used with CCLS.
