### ISSUE TITLE
Support IAR ARM compiler?

### ISSUE THREAD

**Issue by mkitby** [MaskRay/ccls#476]
I use CMake and IAR ARM compiler to compile my code for an ARM processor. The CMake generates compile_commands.json and ccls knows the complete command line. I want ccls to support the IAR ARM compiler and can jump to the IAR ARM compiler header files.

The C runtime and compiler header files are installed in ../Config/exec/arm/inc/c, and \_\_ICCARM\_\_ is an internal preprocessor defined by the IAR ARM compiler.

Here is my .ccls file, 

```
%compile_commands.json
-target
arm
-D__ICCARM__
-I../Config/exec/arm/inc/c
```

Now the problem is why macro \_\_GNUC\_\_ is defined with -target arm? If I remove -target arm in .ccls, then macro _MSC_VER will be defined. Is there a -target support the IAR ARM compiler? If no, how to set the configuration to not define any compiler macro like _MSC_VER and \_\_GNUC\_\_

**Comment by MaskRay** [comment]
ccls is a clang based tool. It reuses clangDriver, clangLex, clangParse, clangSema, etc. The predefined macros are provided by the driver. According to the target triple and some command line options, the compiler supplies a set of predefined macros.

`__GNUC__` is by default defined by clang unless MSVC compatibility is enabled. I don't think `-fms-compatibility` is what you desire, so you should probably use `-U__GNUC__` to undefine the macro.

```zsh
% clang -target armv7-linux-gnueabi -E -dM -xc /dev/null | grep GNUC              
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_STDC_INLINE__ 1
#define __GNUC__ 4
% clang -target armv7-linux-gnueabi -E -dM -xc /dev/null -fms-compatibility | grep GNUC
% fclang -target armv7-linux-gnueabi -E -dM -xc /dev/null -U __GNUC__ | grep GNUC  
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_STDC_INLINE__ 1
```

**Comment by mkitby** [comment]
Thanks for your help, it works.

**Comment by davidanderle** [comment]
@mkitby I wonder if you somehow managed to convert IAR .ewp files to CMake format automatically, or you just created the CMake by hand?

**Comment by mkitby** [comment]
I created CMake by hand
