### ISSUE TITLE
.CClS for armv7/armv9 devkitpro  

### ISSUE THREAD

**Issue by chandrahmuki** [MaskRay/ccls#477]
Hi , 

i'm trying to configure my .ccls to work with devkitpro which is globally a custom C compiler for arm processor ( GBA , 3DS) 

here is what i tried but without any success , its probably pretty wrong.

```
-target 
arm-none-eabi

# Includes
-I/usr/bin/../lib/gcc/arm-none-eabi/9.1.0/include
-I/usr/bin/../lib/gcc/arm-none-eabi/9.1.0/include-fixed
-I/usr/bin/../lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/include
-I/opt/devkitpro/libgba/include
# -I space_is_not_allowed
```

Thanks a lot for your help

**Comment by MaskRay** [comment]
Please take a look at https://github.com/MaskRay/ccls/issues/476#issuecomment-527276310

> custom C compiler for arm

Can you just name the compiler?

**Comment by chandrahmuki** [comment]
it is GCC

**Comment by MaskRay** [comment]
I think you should resolve your issue with the #476 suggestion applied. Closing this one.

> here is what i tried but without any success , its probably pretty wrong.
