### ISSUE TITLE
Compile ccls(indexer.cc) with clang10 failed

### ISSUE THREAD

**Issue by hei-threebody** [MaskRay/ccls#478]
* ccls version: newest
* clang version: g++7.3.0/clang10
* OS: Scientific linux 6

Use the newest ccls repository, but still have error as below:
[  2%] Building CXX object CMakeFiles/ccls.dir/src/indexer.cc.o
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc: In member function ‘virtual std::unique_ptr<clang::ASTConsumer> ccls::{anonymous}::IndexFrontendAction::CreateASTConsumer(clang
::CompilerInstance&, llvm::StringRef)’:
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc:1204:32: error: ‘createIndexingASTConsumer’ is not a member of ‘clang::index’
     consumers.push_back(index::createIndexingASTConsumer(
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc:1204:32: note: suggested alternative: ‘createIndexingAction’
     consumers.push_back(index::createIndexingASTConsumer(
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
                                createIndexingAction
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc: In function ‘std::vector<std::unique_ptr<ccls::IndexFile> > ccls::idx::index(ccls::SemaManager*, ccls::WorkingFiles*, ccls::VFS
*, const string&, const string&, const std::vector<const char*>&, const std::vector<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&, bool, bool&)’:
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc:1373:22: warning: unused variable ‘_’ [-Wunused-variable]
     for (auto &[_, it] : entry->uid2lid_and_path)
                      ^
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc:1392:24: warning: unused variable ‘_’ [-Wunused-variable]
     for (auto &[_, file] : param.uid2file) {
                        ^
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc: In function ‘void ccls::reflect(ccls::JsonWriter&, ccls::SymbolRef&)’:
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc:1439:36: error: expected ‘)’ before ‘PRIu64’
   snprintf(buf, sizeof buf, "%s|%" PRIu64 "|%d|%d", v.range.toString().c_str(),
                                    ^~~~~~
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc:1440:43: warning: spurious trailing ‘%’ in format [-Wformat=]
            v.usr, int(v.kind), int(v.role));
                                           ^
/home/hzhang/Documents/Downloads/ccls/src/indexer.cc:1440:43: warning: too many arguments for format [-Wformat-extra-args]

**Comment by MaskRay** [comment]
If you build clang from git HEAD or use a snapshot version, please make sure your clang is newer than 2019-08-29 rC370337.

**Comment by skywb** [comment]
I got the same error when compile ccls with clang11
/tmp/ccls/src/indexer.cc: In function ‘void ccls::reflect(ccls::JsonWriter&, ccls::SymbolRef&)’:
/tmp/ccls/src/indexer.cc:1449:36: error: expected ‘)’ before ‘PRIu64’
   snprintf(buf, sizeof buf, "%s|%" PRIu64 "|%d|%d", v.range.toString().c_str(),
