### ISSUE TITLE
invalid params of initialize

### ISSUE THREAD

**Issue by bb4242** [MaskRay/ccls#482]
With ccls version `0.20190823.1-1-g2b552f61` and lsp-mode version 20190916.1858 in emacs, I'm having trouble getting ccls to start.  The Messages buffer in emacs has the following error:

`LSP :: invalid params of initialize: expected object for /capabilities/workspace/didChangeWatchedFiles`

I'm not sure whether this is a problem with ccls or lsp-mode.

**Comment by bb4242** [comment]
I investigated a bit further, and I think [this commit](https://github.com/emacs-lsp/lsp-mode/commit/67745ab4abd28fb077cd51eae311d13c08028463) in lsp-mode seems to have introduced the problem.

**Comment by MaskRay** [comment]
@bb4242 Thanks for the report. If my understanding is correct, this client should not use `null` as the value. Created https://github.com/emacs-lsp/lsp-mode/pull/1030

**Comment by bb4242** [comment]
Great, thanks @MaskRay !
