### ISSUE TITLE
[Bug] Aliases not recognized (reported as error), when a certain file is included

### ISSUE THREAD

**Issue by ZigaSajovic** [MaskRay/ccls#483]
### Contents
In the [bug.zip](https://github.com/MaskRay/ccls/files/3618157/bug.zip) you will find
* **CppML**: needed to run
* **Core**: needed to run
* **util.hpp**: minimal file which defines alias in question
    * **StandardDereferencer**
* **AlgebraMonad.hpp**: file which causes the behaviour.
* **main.cpp**: small main file to demonstrate the error

### What happens:

The alias `StandardDereferencer` from `utils.hpp` is not recognized.

We see that the alias is clearly defined:

![image](https://user-images.githubusercontent.com/10235589/64992787-ebaa8c80-d8d4-11e9-8973-fb8540afc5c7.png)

yet the **ccls** offers only `StandardDereferencer_f`, but not the alias `StandardDereferencer`.

![image](https://user-images.githubusercontent.com/10235589/64992521-57d8c080-d8d4-11e9-90f6-00f699e6d59c.png)

even more, it marks it as an error

![image](https://user-images.githubusercontent.com/10235589/64992632-9e2e1f80-d8d4-11e9-8343-00687b5d20d6.png)

### Details and Inspection

Please note, that the above behaviour only happens, when you **include the** `AlgebraMonad.hpp`, which is included i the `utils.hpp`. Furthermore when you **comment-out** the `#include "AlgebraMonad.hpp"` in the `utils.hpp` things again work as expected. It is thus the offending file.

### Last version of CCLS which worked for me

Before I updated (to latest commit), I had the commit [`5d030f9e8a6c69ad5f5f818ac1b401bde675b7df`](https://github.com/MaskRay/ccls/commits/5d030f9e8a6c69ad5f5f818ac1b401bde675b7df) compiled. Using that ccls binary, everything works as expected.
Note that I tried compiling with clang+llvm-7 and 8, with identical results.

Please tell me if you need anything else. I enjoy using **ccls**.

**Comment by MaskRay** [comment]
After unpacking bug.zip

```
% clang -fsyntax-only main.cpp
./Core/Meta.hpp:7:10: fatal error: '../CppML/CppML/Functional.hpp' file not found                               
#include "../CppML/CppML/Functional.hpp"
```

So I replaced CppML with a fresh clone of CppML.

```
% clang -fsyntax-only main.cpp
...
./AlgebraMonad.hpp:57:61: error: expected '(' for function-style cast or type construction                     
                    std::is_default_constructible_v<Accesor>,
% clang -std=c++17 -fsyntax-only main.cpp # good
```

You have to read a bit about https://github.com/MaskRay/ccls/wiki/Project-Setup.

A simplest `.ccls` file that makes the completion item available:
```
clang
-std=c++17
```

**Comment by ZigaSajovic** [comment]
@MaskRay Firstly, thank you for the quick response. It seems that i was incorrectly using the `ccls`file. Could you please point out the error in my `ccls` file? 

### ccls
```
%clang
%cpp -std=c++17
%h -std=c++17
-Wall
-Winline
-pthread
```

**Comment by MaskRay** [comment]
`%clang` is the same as `clang`. `%clang` existed and expanded to either `clang` or `clang++` according to the extension name. That turns out to be unnecessary.

* `clang++` defaults to GXXMode (g++). It treats a `.c` file as C++ and issues a warning.
  `clang` defaults to GCCMode (gcc). It correctly treats `.c` files as C and `.cpp` files as C++. ccls can just use the `clang` semantic.
* In GXXMode, C++ stdlib link options are added. ccls does not need the linker stage.

So I removed special treatment of `%clang` (in `src/project.cc`) and recommended plain `clang` since then. However, I don't see what's wrong in your `.ccls`.

https://github.com/MaskRay/ccls/wiki/Debugging#logs If `-v=1` is added, the clang command line will be dumped. The sema_manager.cc log is related to diagnostics and completion.

```
10:16:17 preamble     sema_manager.cc:744 I create session for /tmp/d/util.hpp
  clang -std=c++17 /tmp/d/util.hpp --gcc-toolchain=/usr -working-directory=/tmp/d/
```

**Comment by FirstLoveLife** [comment]
> `%clang` is the same as `clang`. `%clang` existed and expanded to either `clang` or `clang++` according to the extension name. That turns out to be unnecessary.
> 
> * `clang++` defaults to GXXMode (g++). It treats a `.c` file as C++ and issues a warning.
>   `clang` defaults to GCCMode (gcc). It correctly treats `.c` files as C and `.cpp` files as C++. ccls can just use the `clang` semantic.
> * In GXXMode, C++ stdlib link options are added. ccls does not need the linker stage.
> 
> So I removed special treatment of `%clang` (in `src/project.cc`) and recommended plain `clang` since then. However, I don't see what's wrong in your `.ccls`.

such thorough explanation deserves to put into wiki

**Comment by MaskRay** [comment]
> such thorough explanation deserves to put into wiki

Thanks for the suggestion. wiki/Project-Setup actually mentions this but was probably less clear. Just updated the contents.

**Comment by ZigaSajovic** [comment]
@MaskRay When I use the identical `.ccls` file, but use `clang` instead of the `%clang`, things work properly. I am now using the latest build, with such a ccls.
For clarity: in [5d030f9e8a6c69ad5f5f818ac1b401bde675b7df](https://github.com/MaskRay/ccls/commits/5d030f9e8a6c69ad5f5f818ac1b401bde675b7df), both `clang` and `%clang` worked on this example. Now (latest build) `clang` works as expected, while `%clang` reproduces the error I described.

### %clang config log

> 11:51:02 preamble     sema_manager.cc:744 I create session for /home/ziga/monadZ/Examples/IteratorMonad/Arange.cpp
  -std=c++17 -pthread -Wall -Winline -I/home/ziga/monadZ /home/ziga/monadZ/Examples/IteratorMonad/Arange.cpp -working-directory=/home/ziga/monadZ/

Results in no completion.

### clang config log

> 11:54:34 preamble     sema_manager.cc:744 I create session for /home/ziga/monadZ/Examples/IteratorMonad/Arange.cpp
  clang -std=c++17 -pthread -Wall -Winline -I/home/ziga/monadZ /home/ziga/monadZ/Examples/IteratorMonad/Arange.cpp -working-directory=/home/ziga/monadZ/

Results as expected.

---

As can be seen in above logs, when using the `%clang` config, the **clang** directive seems to be missing. But i do not yet know enough about the inner workings of **ccls**  to deduce what, if anything, it implies.

**Comment by QiangZiBro** [comment]
Hello, I also got the similar problem, found that ccls can recognize `typedef` for alias but not `using`, is there anything I should modify for `.ccls`?

Here is the code:
![image](https://user-images.githubusercontent.com/30493365/210739132-eefe8aa7-6095-4241-9032-80f836a4d8f8.png)

My env:
```bash
❯ ccls --version
Homebrew ccls version <unknown>
clang version 15.0.5
❯ clang --version
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by QiangZiBro** [comment]
## Update
Just rebuilt the ccls source code, now it seems to work fine. So it should be the version reason.
