### ISSUE TITLE
C++17 headers appear to not be parsed

### ISSUE THREAD

**Issue by clauniel** [MaskRay/ccls#488]
Using a single c++ file a.cc
```
#include <any>

int main() {
    std::any foo;
}
```

and a .ccls file
```
-std=gnu++17
-isystem/usr/include/c++/9.1.0
```

I get the following error
```
use of undeclared identifier std
```

I can import a different header, like `<vector>`, which will then cause std to be declared and shift the error to report `any` as undeclared.

If I use xref-find-definitions on the `<any>` header, I am taken to the header file, so it must be found. If I use xref-find-definitions on std::`any`, the definition is not found. The header file also appears in the .ccls-cache directory.

* ccls version: latest ccls-git from aur.archlinux.org
* clang version: 8.0.1
* OS: Arch Linux
* Editor: Emacs
* Language client (and version): emacs-ccls 20190720.935

**Comment by MaskRay** [comment]
Use

```
clang
-std=gnu++17
-isystem/usr/include/c++/9.1.0
```

**Comment by clauniel** [comment]
Thank you! After adding the clang driver specification to the .ccls file and removing clang as a flycheck backend it now works and shows no diagnostic errors.
