### ISSUE TITLE
link error when building ccls in WSL environment

### ISSUE THREAD

**Issue by fiddleyuan** [MaskRay/ccls#490]
Hi,

I met a link error when I was trying to build ccls for WSL(Ubuntu 18.04).
I used to build cquery successfully in same WSL envrironment.
I also tried to build ccls on another real Linux machine (Ubuntu 18.04), and it succeeded too.

I followed the instruction in wiki:
`wget -c http://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz`
`tar xf clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz`
`cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$PWD/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04`
`cmake --build Release`
The compilation is good, the link error info gives:

[100%] Linking CXX executable ccls
/usr/bin/cmake -E cmake_link_script CMakeFiles/ccls.dir/link.txt --verbose=1
/usr/bin/c++  -O3 -DNDEBUG   CMakeFiles/ccls.dir/third_party/siphash.cc.o CMakeFiles/ccls.dir/src/clang_tu.cc.o CMakeFiles/ccls.dir/src/config.cc.o CMakeFiles/ccls.dir/src/
filesystem.cc.o CMakeFiles/ccls.dir/src/fuzzy_match.cc.o CMakeFiles/ccls.dir/src/main.cc.o CMakeFiles/ccls.dir/src/include_complete.cc.o CMakeFiles/ccls.dir/src/indexer.cc.
o CMakeFiles/ccls.dir/src/log.cc.o CMakeFiles/ccls.dir/src/lsp.cc.o CMakeFiles/ccls.dir/src/message_handler.cc.o CMakeFiles/ccls.dir/src/pipeline.cc.o CMakeFiles/ccls.dir/s
rc/platform_posix.cc.o CMakeFiles/ccls.dir/src/platform_win.cc.o CMakeFiles/ccls.dir/src/position.cc.o CMakeFiles/ccls.dir/src/project.cc.o CMakeFiles/ccls.dir/src/query.cc
.o CMakeFiles/ccls.dir/src/sema_manager.cc.o CMakeFiles/ccls.dir/src/serializer.cc.o CMakeFiles/ccls.dir/src/test.cc.o CMakeFiles/ccls.dir/src/utils.cc.o CMakeFiles/ccls.di
r/src/working_files.cc.o CMakeFiles/ccls.dir/src/messages/ccls_call.cc.o CMakeFiles/ccls.dir/src/messages/ccls_info.cc.o CMakeFiles/ccls.dir/src/messages/ccls_inheritance.c
c.o CMakeFiles/ccls.dir/src/messages/ccls_member.cc.o CMakeFiles/ccls.dir/src/messages/ccls_navigate.cc.o CMakeFiles/ccls.dir/src/messages/ccls_reload.cc.o CMakeFiles/ccls.
dir/src/messages/ccls_vars.cc.o CMakeFiles/ccls.dir/src/messages/initialize.cc.o CMakeFiles/ccls.dir/src/messages/textDocument_code.cc.o CMakeFiles/ccls.dir/src/messages/te
xtDocument_completion.cc.o CMakeFiles/ccls.dir/src/messages/textDocument_definition.cc.o CMakeFiles/ccls.dir/src/messages/textDocument_did.cc.o CMakeFiles/ccls.dir/src/mess
ages/textDocument_foldingRange.cc.o CMakeFiles/ccls.dir/src/messages/textDocument_formatting.cc.o CMakeFiles/ccls.dir/src/messages/textDocument_document.cc.o CMakeFiles/ccl
s.dir/src/messages/textDocument_hover.cc.o CMakeFiles/ccls.dir/src/messages/textDocument_references.cc.o CMakeFiles/ccls.dir/src/messages/textDocument_rename.cc.o CMakeFile
s/ccls.dir/src/messages/textDocument_signatureHelp.cc.o CMakeFiles/ccls.dir/src/messages/workspace.cc.o  -o ccls ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libcl
angIndex.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangFormat.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangTooling.a ../clang+llvm-8.0.
0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangToolingInclusions.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangToolingCore.a ../clang+llvm-8.0.0-x86_64-linux
-gnu-ubuntu-18.04/lib/libclangFrontend.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangParse.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclan
gSerialization.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangSema.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangAST.a ../clang+llvm-8.0.
0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangLex.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangDriver.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/l
ib/libclangBasic.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVMOption.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVMSupport.a ../clang+llv
m-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangFormat.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangToolingInclusions.a ../clang+llvm-8.0.0-x86_64-linu
x-gnu-ubuntu-18.04/lib/libclangToolingCore.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVMMCParser.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/l
ibLLVMProfileData.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangEdit.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangAnalysis.a ../clang+l
lvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVMBitReader.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangRewrite.a ../clang+llvm-8.0.0-x86_64-linux-gnu-
ubuntu-18.04/lib/libclangASTMatchers.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangAST.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangLex
.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libclangBasic.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVMCore.a ../clang+llvm-8.0.0-x86_64-linu
x-gnu-ubuntu-18.04/lib/libLLVMMC.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVMBinaryFormat.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVM
DebugInfoCodeView.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVMDebugInfoMSF.a ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVMSupport.a -lz -
lrt -ldl -ltinfo -lpthread -lm ../clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/libLLVMDemangle.a -pthread
/usr/bin/ld: cannot find -lz
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/ccls.dir/build.make:1198: recipe for target 'ccls' failed
make[2]: *** [ccls] Error 1
make[2]: Leaving directory '/mnt/c/workspace/misc/ccls/Release'
CMakeFiles/Makefile2:102: recipe for target 'CMakeFiles/ccls.dir/all' failed
make[1]: *** [CMakeFiles/ccls.dir/all] Error 2
make[1]: Leaving directory '/mnt/c/workspace/misc/ccls/Release'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2

Apparently, /usr/bin/ld doesn't have -lz, which caused this issue, IMO

So I tried on my WSL, /usr/bin/ld indeed doesn't have -lz options, while on my Linux machine, it does.
But what I don't understand is the ld on both machine seem to have exact same version, how come they differ in the options? Is there anything to do with my building steps?

If you happen to meet similar issue, please kindly let me know.
Thanks!

**Comment by MaskRay** [comment]
I don't have Windows but I guess you have to install zlib1g-dev

**Comment by fiddleyuan** [comment]
> I don't have Windows but I guess you have to install zlib1g-dev

Very impressive, thank you, MaskRay!
