### ISSUE TITLE
ccls thinks struct field is a function

### ISSUE THREAD

**Issue by jstaursky** [MaskRay/ccls#493]
# Observed behavior

I have been working on [this file](https://gist.github.com/jstaursky/92c82e4ed30db5e7e392ee1abd60d474)
and ccls warns me of the following

![image](https://user-images.githubusercontent.com/25406664/66256966-91794a80-e761-11e9-8cfa-092fed8e1f85.png)
![image](https://user-images.githubusercontent.com/25406664/66256975-a8b83800-e761-11e9-9e3c-27c8310bbe1e.png)
![image](https://user-images.githubusercontent.com/25406664/66256986-d4d3b900-e761-11e9-98c9-a9bb193ea340.png)

Which is clearly not the case.

### Expected behavior

no false positives.

### Steps to reproduce

I just open the file in spacemacs. My config starts ccls. I am using the `c-c++` layer from spacemacs which has details [here](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/c-c%2B%2B)
I tried looking through their source for the options passed onto `ccls` but could not find anything.

### System information

* ccls version 
I installed this a while back and I tried `ccls --version` but it replies `ccls version <unknown>`
However running `file $(which ccls)` gives the following
`/usr/local/bin/ccls: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=0ad8d813bf804be7fa823d0ee32aad5eb15222d1, with debug_info, not stripped` 
* clang version:  `clang version 8.0.0-svn356034-1~exp1~20190313093039.54`
* OS: ubuntu 18.04
* Editor: Emacs (spacemacs)
* Language client (and version): I'm not sure what this is asking me. The language is C for the file I am working on. Let me know if I need to provide more information.

**Comment by MaskRay** [comment]
This is almost certainly a configuration error, unrelated to ccls. You can find many similar problems in the issue tracker. Make sure `bfd.h` and `capstone/capstone.h` are in the search path (`-I` `-isystem` ...).

You can extract the clang command line with `(ccls-file-info)`. Replace the compiler driver (`gcc` or `clang`) with `clang`, append `-fsyntax-only`, and invoke the command in a shell. It will likely suggest similar errors.

**Comment by jstaursky** [comment]
So I tried `(ccls-file-info)` and got
![Screenshot_2019-10-06_12-43-59](https://user-images.githubusercontent.com/25406664/66272550-2dc25080-e839-11e9-86f5-63c466bdd81c.png)

but it is unclear to me how this translates to the cmdline options that you list on your [wiki](https://github.com/MaskRay/ccls/wiki/Customization#command-line).

So I next tried 
![image](https://user-images.githubusercontent.com/25406664/66272828-73cce380-e83c-11e9-967e-6d770407006e.png)

which yields
![image](https://user-images.githubusercontent.com/25406664/66272913-374db780-e83d-11e9-9520-1eb804153ee6.png)

but nothing there means much to me.

I made a gif to show that there isn't a search path issue as my autocomplete is being filled with suggestions corresponding to `capstone.h` and `bfd.h`

![optimised](https://user-images.githubusercontent.com/25406664/66272865-c0182380-e83c-11e9-9dc0-707b1d257307.gif)

I'm not sure how my config would be affecting it as its a premade config "layer" from spacemacs. If it were wrong then I feel I would not be the only one affected by it.

Anyway I hope this is helpful, if not would you mind giving uninstall directions? Maybe I can just try reinstalling it. I'm just not sure what other folders and files I would need to delete outside of the `ccls` binary. I installed it a while ago and its only been for this file that I have been running into trouble.

BTW I wish that were the case! `libbfd` is for handling executable file formats so I can extract just the `.text` section for disassembling. `Capstone` is of course just disassembling.  
That's the extent of their abilities as far as I am aware of, but it would be welcome news to hear there is a capstone api to replace libbfd with!

**Comment by MaskRay** [comment]
There is more information on https://github.com/MaskRay/ccls/wiki/Debugging

`(ccls-file-info)` says the clang command line is `clang path/to/file.c`. There should be a trailing `-working-directory=/path/to/directory/`. The absence of the option suggests that you are probably using an ancient version of ccls.

Even though, I think that old ccls may behave correctly. There is no `-I` so I am not sure ccls can find `capstone/capstone.h` and `bfd.h`.

> Anyway I hope this is helpful, if not would you mind giving uninstall directions?

`ninja install` just copies the `ccls` executable to `$CMAKE_PREFIX_PATH/bin/ccls`. Just delete the file to uninstall. https://github.com/MaskRay/ccls/wiki/Install#cmake-install
