### ISSUE TITLE
CCLS resolves bool value as macro highlight group

### ISSUE THREAD

**Issue by davidanderle** [MaskRay/ccls#494]
### Observed behavior
Installing an LSP highlight [plugin](https://github.com/jackguo380/vim-lsp-cxx-highlight) resulted in my boolean values being highlighted with a PreProc/Macro [vim syntax](http://vimdoc.sourceforge.net/htmldoc/syntax.html) highlight group color.

At the end of the day this is an "expected" behavior as in `<stdbool.h>` these values are `#define`d
![image](https://user-images.githubusercontent.com/17354704/66258496-d6bb6d80-e79d-11e9-9f47-5dc9a013bcf0.png)
#### CCLS settings (using CoC)
```
{
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
      "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
      "initializationOptions": {
         "cache": {
           "directory": ".ccls-cache"
         },
         "publishSkippedRanges": true,
         "publishSemanticHighlight": true,
         "highlight": {"lsRanges": true }
       }
    }
  }
}
```

### Expected behavior
CCLS evaluates `true`, `TRUE`, `false`, `FALSE`, etc.. as Number/Boolean highlight group.

### Steps to reproduce
For this demonstration you need to have [jackguo380/vim-lsp-cxx-highligh](https://github.com/jackguo380/vim-lsp-cxx-highlight) installed in your vim. Unfortunately, I am a complete rookie in LSP and know too little about it to dig up where the highlight indexing occurs.
1. `$ printf '#include <stdbool.h>\nint main(void){while(true);}' > a.c`
2. `$ vim a.c`
![image](https://user-images.githubusercontent.com/17354704/66258396-9d363280-e79c-11e9-89e2-475fb8c849b3.png)
3. Navigate cursor to `true`, and do `:LspCxxHlCursorSym`. The plugin will tell you that CCLS evaulated `true` in the PreProc/Macro highlight group.
![image](https://user-images.githubusercontent.com/17354704/66258355-3dd82280-e79c-11e9-8f2f-26074677ef50.png)
4. Disabling CCLS highlight confirms this `:LspCxxHighlightDisable`
![image](https://user-images.githubusercontent.com/17354704/66258407-cb1b7700-e79c-11e9-8eb8-df343dc13df5.png)

### System information

* ccls version (`git describe --tags --long`): 
`ccls version <unknown>`
* clang version: 
`clang version 8.0.0 (tags/RELEASE_800/final)`
* OS: 
`Windows 10, WSL Ubuntu 18.04`
* Editor: 
`NVIM v0.4.2 Release`
* Language client (and version): 
`CoC 0.0.57`

**Comment by MaskRay** [comment]
The first few non-comment lines of `stdbool.h` shipped with glibc reads:

```c
#ifndef _STDBOOL_H
#define _STDBOOL_H

#ifndef __cplusplus

#define bool	_Bool
#define true	1
#define false	0
```

So `true` and `false` are indeed macros.

**Comment by davidanderle** [comment]
That is exactly what I'm saying... Nevertheless, this should be handled as a special case

**Comment by MaskRay** [comment]
While I understand the need, I think I prefer it works like it is. `true` and `false` are not keywords in C. They don't have special meanings. If they are defined as macros, they should be colored as macros.
