### ISSUE TITLE
wrong "not found" on header files in qt-project

### ISSUE THREAD

**Issue by pe200012** [MaskRay/ccls#502]
### Observed behavior

I'm a newcomer to ccls. Currently I'm trying to use it in a qt project, but it seems that ccls has problems dealing with header files.
```
CMakeTest
├── CMakeLists.txt
├── compile_commands.json
├── lib
└── src
    └── main.cpp
```
```
// main.cpp
#include <QApplication>

int main(int argc, char *argv[]){
  QApplication app(argc, argv);
  return app.exec();
}
```
```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.5)

project(OSD LANGUAGES CXX)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON) # export .compile_commands.json used for completion

set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Qt5 COMPONENTS Widgets REQUIRED)
include_directories (src)

add_executable(OSD
  src/main.cpp
)

target_link_libraries(OSD PRIVATE Qt5::Widgets)
```
And ccls complains as below:
![Screenshot_20191013_125503](https://user-images.githubusercontent.com/13463539/66711195-df253100-edb9-11e9-8885-b9c34a0c95b0.png)

EDIT: .compile_commands.json
<pre>
[
{
  "directory": "/mnt/Data/Document/CodeCollection/c/CMakeTest",
  "command": "/usr/bin/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/mnt/Data/Document/CodeCollection/c/CMakeTest/main_autogen/include -I/mnt/Data/Document/CodeCollection/c/CMakeTest/src -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++    -fPIC -std=gnu++2a -o CMakeFiles/main.dir/main_autogen/mocs_compilation.cpp.o -c /mnt/Data/Document/CodeCollection/c/CMakeTest/main_autogen/mocs_compilation.cpp",
  "file": "/mnt/Data/Document/CodeCollection/c/CMakeTest/main_autogen/mocs_compilation.cpp"
},
{
  "directory": "/mnt/Data/Document/CodeCollection/c/CMakeTest",
  "command": "/usr/bin/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/mnt/Data/Document/CodeCollection/c/CMakeTest/main_autogen/include -I/mnt/Data/Document/CodeCollection/c/CMakeTest/src -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++    -fPIC -std=gnu++2a -o CMakeFiles/main.dir/src/main.cpp.o -c /mnt/Data/Document/CodeCollection/c/CMakeTest/src/main.cpp",
  "file": "/mnt/Data/Document/CodeCollection/c/CMakeTest/src/main.cpp"
}
]
</pre>

### Expected behavior

Should not have any error.

### Steps to reproduce

1. Create a new project
2. Add files and CMakeLists.txt as above.
3. Open Emacs, and open ```main.cpp```

### System information

* ccls version <unknown>
* clang version 9.0.0 (tags/RELEASE_900/final)
* OS: ArchLinux
* Editor: Emacs
* Language client (and version): emacs-ccls 20190927.246

**Comment by MaskRay** [comment]
The example works perfectly on my system.

`INCLUDES = -I. -I../ -IOSD_autogen/include -I../src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++`


I suspect your qt5 include paths are incorrect. Many problems are possible, e.g. your `qt/` directory is not qt5.
