### ISSUE TITLE
Build in msys2 failed as libz3.dll.a missing

### ISSUE THREAD

**Issue by zijianyue** [MaskRay/ccls#503]
I followed these steps:

> pacman -S mingw-w64-x86_64-clang mingw-w64-x86_64-clang-tools-extra 
> mingw64/mingw-w64-x86_64-polly mingw-w64-x86_64-cmake mingw-w64-x86_64-jq 
> mingw-w64-x86_64-ninja mingw-w64-x86_64-ncurses
> cmake -H. -BRelease -G Ninja -DCMAKE_CXX_FLAGS=-D__STDC_FORMAT_MACROS
> ninja -C Release

But it failed:

> xxx@xxx MINGW64 /g/ccls
> $ cmake -H. -BRelease -G Ninja -DCMAKE_CXX_FLAGS=-D__STDC_FORMAT_MACROS
> -- The CXX compiler identification is GNU 9.2.0
> -- Check for working CXX compiler: G:/msys64/mingw64/bin/c++.exe
> -- Check for working CXX compiler: G:/msys64/mingw64/bin/c++.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Setting build type to 'Release' as none was specified.
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
> -- Found Threads: TRUE
> -- Configuring done
> -- Generating done
> -- Build files have been written to: G:/ccls/Release
> 
> xxx@xxx MINGW64 /g/ccls
> $ ninja -C Release
> ninja: Entering directory `Release'
> ninja: error: '/mingw64/lib/libz3.dll.a', needed by 'ccls.exe', missing and no known rule to make it
> 
> xxx@xxx MINGW64 /g/ccls
> $ ll /mingw64/lib/libz3.dll.a
> -rw-r--r-- 1 xxx Domain Users 437080 10月  3 17:10 /mingw64/lib/libz3.dll.a

**Comment by MaskRay** [comment]
`-DLLVM_WITH_Z3=off` when building llvm/clang.

**Comment by finalpatch** [comment]
Try use the "MSYS Makefiles" generator. 
Works for me.

**Comment by LanternD** [comment]
Open "./Release/build.ninja", search for "libz3", you would find two occurrences. 

Change "/lib/libz3.dll.a" to an absolute path, then the `ninja -C Release` works.
