### ISSUE TITLE
cache's command line change detection seems broken

### ISSUE THREAD

**Issue by maddanio** [MaskRay/ccls#505]
Ok, so I am trying to fnd out why ccls consumes so many resources each ide start (sublime text in my case) even though not much changed.
I am now reducing this to manual index runs, and looking at the ccls output it seems to have mixed up "old" command line flags. I can say this because I run ccls multple times with no changes to compile commands (as verified by md5) and the "old" command line flags it keeps mentioning never are found in the compile commands for the given file.

**Comment by maddanio** [comment]
where are these flags stored by the way?

**Comment by maddanio** [comment]
ok, so it seems it only happens with header caches of header files added to the compile commands with compdb. is that a known problem maybe?

**Comment by maddanio** [comment]
ok, I set the index format to json and diffed one index file that got recreated before and after, and they are byte for byte the same, including args. so the arg compare mechanism must be broken. will debug further later this week

**Comment by maddanio** [comment]
its not reducible very easy. if I only have that one file in compile commands it will not happen, so there is some kind of cross talk.

**Comment by maddanio** [comment]
its not a threading issue: using only one thread does not help. so somehow indexing one file is influenced by files that have been indexed before it

**Comment by MaskRay** [comment]
I don't think ccls is responsible. Use `-log-file=/tmp/ccls.log -v=1` to learn why a file is re-indexed https://github.com/MaskRay/ccls/wiki/Debugging#logs

The cache file is considered stale if

* The timestamp of the file, or any of its dependency has changed. See `pipeline.cc:indexer_Parse`.
* The clang command line options have changed. See `pipeline.cc:cacheInvalid`.

For different branches, the files that are not touched will not be re-indexed.

**Comment by maddanio** [comment]
Hmm, how do you get to that conclusion. In my case absolutely nothing happens between runs. The source files are unchanged and the compile commands also

**Comment by maddanio** [comment]
Also: I did. look at logs, and they say the compile arguments changed, which I know they did not...

**Comment by maddanio** [comment]
Ccls kinda says that itself, since the index file, which contains the arguments, is the same after the first and second runs

**Comment by maddanio** [comment]
Ok, I got it. My problem basically was that making compile commands for header files with compdb (https://github.com/Sarcasm/compdb#id5) as for example EasyClangComplete requires to provide help with headers (https://github.com/niosus/EasyClangComplete) is incompatible with the way ccls does indexing.
I would kindly request a warning note of this kind somewhere, so not someone else loses a days worth of debugging over this.

**Comment by maddanio** [comment]
I mean say somewhere on the wiki that ccls should not be used together with compilation dbs that have been enriched with headers via compdb

**Comment by maddanio** [comment]
What that leads to is a lot of useless reindexing of easily 1000 headers at each server start

**Comment by MaskRay** [comment]
> I mean say somewhere on the wiki that ccls should not be used together with compilation dbs that have been enriched with headers via compdb

Again, examples.

The concepts have been explained on the wiki.
