### ISSUE TITLE
Failed to indexing with Dlib

### ISSUE THREAD

**Issue by ingjieye** [MaskRay/ccls#506]
### Observed behavior

ccls could not found Dlib header though the file exist and it's path is present in `compile_command.json` with `-I `

```
{
  "directory": "/home/yeyj/dev/source_code/dlib/tools/archive/build",
  "command": "/usr/bin/c++   -I/home/yeyj/dev/source_code/dlib/dlib/..  -O3 -DNDEBUG   -DDLIB_JPEG_SUPPORT -DDLIB_USE_BLAS -DDLIB_USE_LAPACK -DDLIB_PNG_SUPPORT -Wreturn-type -std=gnu++11 -o CMakeFiles/train_face_5point_model.dir/train_face_5point_model.cpp.o -c /home/yeyj/dev/source_code/dlib/tools/archive/train_face_5point_model.cpp",
  "file": "/home/yeyj/dev/source_code/dlib/tools/archive/train_face_5point_model.cpp"
}
```

![截屏2019-10-15下午3 10 34](https://user-images.githubusercontent.com/13421169/66808522-00bf1d80-ef5e-11e9-9f52-7df16aa5b242.png)

Line 9 was added by myself to test if the file did exist.

### Expected behavior

Find and index the Dlib header

### Steps to reproduce

```bash
git clone https://github.com/davisking/dlib
cd dlib/tools/archive
mkdir build && cd build
cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=YES
cd .. && ln -s build/compile_command.json .
vim train_face_5point_model.cpp
```

### System information

* ccls version (`git describe --tags --long`): 0.20190823.3-5-geeda288
* clang version: clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04
* OS: 16.04.1-Ubuntu
* Editor: vim
* Language client (and version): 0.0.74

**Comment by ingjieye** [comment]
The `CocInfo` output:
[cocinfo.txt](https://github.com/MaskRay/ccls/files/3727793/cocinfo.txt)

**Comment by MaskRay** [comment]
Works here. Make sure you have set `rootPatterns`.

`touch /tmp/p/dlib/tools/archive/.ccls-root`

```zsh
% realpath /proc/$(pgrep -fn ccls)/cwd
/tmp/p/dlib/tools/archive/build
```

coc-settings.json:
```jsonc
{
  "languageserver": {
    "ccls": {
      "command": "ccls.debug",
      "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
      "rootPatterns": [".ccls-root"]
      }
    }
  }
}
```

**Comment by ingjieye** [comment]
Thanks, somehow don't know why I've removed rootPatterns from my coc.nvim settings file. I added it back and everything works fine now.
