### ISSUE TITLE
ccls returns empty uri response for textDocument/references

### ISSUE THREAD

**Issue by haridnr** [MaskRay/ccls#509]
I am seeing this issue (https://github.com/emacs-lsp/lsp-mode/issues/1113) because of an invalid response from ccls for a "textDocument/references" request.

In the response I see sections such as the following with empty **uri** - 
  ```json
{ "range": {
      "end": {
        "character": 52,
        "line": 25
      },
      "start": {
        "character": 43,
        "line": 25
      }
    },
    "uri": "file://"
  }
```
Based on the previous and next items in the response from ccls I see that this is happening probably because of GMOCK code such as the following - 

`MOCK_CONST_METHOD2(fooE1, void(mynamespace::myClassPtr, const std::string&));
`

I had searched for the references of 'myClassPtr' and I do see that the previous item in the response has the same **range** section and a valid **uri**. But the next item in the response has the same range sections but with an empty **uri** as shown above.

Do you have any suggestions as to why this could be happening?

Is this an issue with compilations commands or an issue in the ccls code ?
Please let me know.

### System information

* ccls version : (git show) eeda2882f313fd7e19a969e68544944041e44cae
* clang version: clang 9
* OS: Debian 9
* Editor: emacs
* Language client (and version):  lsp-mode

**Comment by MaskRay** [comment]
Can you provide a minimal, self-contained (complete) file that can reproduce the issue?

**Comment by haridnr** [comment]
I will try to get you a minimal repro file. It might take me some time to do this, I am not sure how much work it will take.

Is there anything else I can check within the ccls code base using a debug build ?

**Comment by MaskRay** [comment]
> Is there anything else I can check within the ccls code base using a debug build ?

Not easy, but if you really want to try investigating it by yourself:

Near `src/query.cc`:726, add something like:

```cpp
if (uri.raw_uri == "file://")
  raise(SIGSTOP);
```

The ccls process wil stop itself when an invalid reference is encountered.

Then, you'll need to trace how the invalid reference goes into `Query{Func,Type,Var}::uses` in query.cc

**Comment by haridnr** [comment]
I am closing this issue for now. I have seen this issue a few times but I have not been able to get a reproducible example for this.
