### ISSUE TITLE
The prebuilt LLVM 9 packages are linked against libc++ and the build fails.

### ISSUE THREAD

**Issue by nicber** [MaskRay/ccls#510]
# Observed behavior
I followed the wiki procedure to build ccls in Ubuntu 14.04 using the the packages from http://releases.llvm.org/download.html

I got many linking errors like 
```
/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-14.04/lib/libLLVMSupport.a(ToolOutputFile.cpp.o): In function `llvm::ToolOutputFile::ToolOutputFile(llvm::StringRef, std::__1::error_code&, llvm::sys::fs::OpenFlags)':
ToolOutputFile.cpp:(.text._ZN4llvm14ToolOutputFileC2ENS_9StringRefERNSt3__110error_codeENS_3sys2fs9OpenFlagsE+0xde): undefined reference to `std::__1::__basic_string_common<true>::__throw_length_error() const'
/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-14.04/lib/libLLVMSupport.a(ToolOutputFile.cpp.o): In function `llvm::ToolOutputFile::ToolOutputFile(llvm::StringRef, int)':
ToolOutputFile.cpp:(.text._ZN4llvm14ToolOutputFileC2ENS_9StringRefEi+0xc5): undefined reference to `std::__1::__basic_string_common<true>::__throw_length_error() const'
```
Adding `-stdlib=libc++` to `CXXFLAGS` fixes this problem after a rebuild.
This issue might affect other linux versions when using LLVM9.

**Comment by MaskRay** [comment]
Only clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-14.04 has the problem. I reported it at https://lists.llvm.org/pipermail/llvm-dev/2019-November/136468.html Hopefully this will be fixed.

**Comment by vityafx** [comment]
`clang+llvm-9.0.0-x86_64-linux-sles11.3` has the same problem.
