### ISSUE TITLE
Target triple isn't inferred from toolchain name

### ISSUE THREAD

**Issue by gessen** [MaskRay/ccls#511]
### Observed behavior

When using ccls in cross-compilation environment, a user must manually add `--target=` flag for the correct behaviour despite the fact that the triple could be inferred from GCC binary name.

### Expected behavior

Similar to how clangd behaves now, when target triple is missing from CDB ccls could infer target name from the binary name.

[https://reviews.llvm.org/D63194](https://reviews.llvm.org/D63194)

### Steps to reproduce

1. Have compile_commands.json created by Bear/CMake for a cross-compiled project
2. Open any project file
3. Notice that parsed project is borked
4. Create .ccls with `%compile_commands.json --target=<arch>-<vendor>-<os>`
5. Completion is working correctly, everything was parsed correctly

### System information

* ccls version 0.20190823.3-5-geeda2882
* clang version 9.0.0 (tags/RELEASE_900/final)
* OS: Linux
* Editor: any
* Language client (and version): any

**Comment by MaskRay** [comment]
Thanks for the information. We construct `CompilerInvocation` with `clang::createInvocationFromCommandLine`, which calls `driver::ToolChain::getTargetAndModeFromProgramName`. The function looks up the llvm target triple, so yes, we need to initialize target info.

```cpp
ParsedClangName
ToolChain::getTargetAndModeFromProgramName(StringRef PN) {
...
  bool IsRegistered = llvm::TargetRegistry::lookupTarget(Prefix, IgnoredError);
  return ParsedClangName{Prefix, ModeSuffix, DS->ModeFlag, IsRegistered};
```

**Comment by MaskRay** [comment]
We don't actually need to call `llvm::InitializeAllTargetInfos()` which requires us to link against the pseudo target library `AllTargetsInfos` (`llvm/cmake/modules/LLVM-Config.cmake`).
