### ISSUE TITLE
included string.h but still see "implicitly declaring library function 'memcpy'"

### ISSUE THREAD

**Issue by randy3k** [MaskRay/ccls#512]
I am using Sublime Text [LSP](https://github.com/tomv564/LSP) in macOS.

The c file
```
#include <string.h>

// something else

void utf8_to_utf32_callback(int cp, int m, void* data, long i) {
    uint32_t x = cp;
    memcpy((char*) data + sizeof(uint32_t) * i, &x, sizeof(uint32_t));
}

```

Diagnostic
```
      104:5   	ccls        	warning   	implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)'
             	            	          	
             	            	          	utftools.c:104:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
      104:5   	ccls        	info      	include the header <string.h> or explicitly provide a declaration for 'memcpy'
```

When I check the ccls log file, I could see string.h is indexed.

```
10:01:30                  pipeline.cc:389 I store index for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h (delta: 0)
```

But having a closer look of the `string.h`, it doesn't contain the definiation of `memcpy` but the following derivative

```
#include_next <string.h>
```

Does it mean that ccls is not following the `#include_next` derivative? I cannot see other `string.h` file being indexed except `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h`.

Please let me know if you need more information.

- ccls installed freshly from homebrew.
- the file could be compiled without problems.

**Comment by randy3k** [comment]
Ok. I found a solution, I think it may affect other macOS users with more recent OSs.
Bascially, standard headers are no longer located at `/usr/include` they are located at

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
``
or 
```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
```

So I fix the issue by pass `-isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include` in `clang.extraArgs`.

Not only that, but I also need the fix in https://github.com/MaskRay/ccls/issues/191#issuecomment-453809905

**Comment by zero4drift** [comment]
@randy3k Your solution here helps me a lot, Thank you! I've been struggling on Catalina 15.2 for nearly two days!

**Comment by MaskRay** [comment]
Does https://github.com/MaskRay/ccls/wiki/Build#macos include all the information now? (It is publicly editable BTW)

**Comment by zero4drift** [comment]
@MaskRay I suppose it's a MacOS Catalina only problem, I've updated the wiki page you posted with a tip, hoping it could help somebody in the future.

**Comment by apple-ihack-geek** [comment]
For those whom run into this error and find this page via google,
I had the same issue with Xcode 11.0 running on 10.4.6.  I'm guessing the error was the opposite of what these users ran into.  I'm guessing my Xcode was looking in the Catalina location and not the old Mojave location.  I was able to resolve my issue by simply updating my Xcode to 11.3.
Best of luck to all of you and that's to the original answerers for giving me the idea to update.
