### ISSUE TITLE
Support for preselect property of CompletionItem

### ISSUE THREAD

**Issue by oblitum** [MaskRay/ccls#513]
As reference, gopls is one language server that supports it, it's quite useful (coc.nvim supports in on NeoVim, if server provides it).

**Comment by MaskRay** [comment]
I am not clear why there is `TextDocumentClientCapabilities.completion.completion.completionItem.preselect`. Does that mean if the language server feels comfortable to make the first (items are sorted by relevance from high to low) item preselected, do that, if not, don't preselect an item? Isn't it a client side job?

**Comment by oblitum** [comment]
> Does that mean if the language server feels comfortable to make the first (items are sorted by relevance from high to low) item preselected, do that, if not, don't preselect an item?

Yes.

> Isn't it a client side job?

I'm not sure whether it's a client side job in principle, LSP added it as server feature, so coc.nvim for example, won't preselect any item by itself (unless there's a full text match, which means it's not available most of the time by itself). When the feature is provided by the server, like with gopls, you can get preselection most of the time, as ranked by the server, which means the client maybe be ranking items differently, but the server has one item marked preselect that may not even be the top one the client displays, because its ranking is different.

At least with gopls I feel it's quite useful, preselect doesn't harm to have, but makes preselection of items available most of the time, which is useful to avoid manual selection before confirmation.

**Comment by MaskRay** [comment]
If ccls is to support the `preselect` property, the implementation will be simply marking the first item as `preselect`ed, because the completion items are already ordered. Then, I am not sure specifying the poperty on the server side makes lots of sense. gopls sets `preselect` but that may be because it does not sort items by relevance. I think we need more evidence that this is useful before implementing it.

**Comment by oblitum** [comment]
It would be great if ccls did that, the simplest implementation that's easy to remove later in any case. As of now preselect without server support makes preselect useless, as at the end of the day LSP have it designed it that way. Completion experience is definitely better for servers that do.

**Comment by oblitum** [comment]
> If ccls is to support the `preselect` property, the implementation will be simply marking the first item as `preselect`ed, because the completion items are already ordered. This seems pretty much a client side decision.

No, because clients may implement their own ranking, and can't know whether server is sending ranked items (so it can't assume to pick the first item is relevant for ordering at all).

> Then, I am not sure specifying the poperty on the server side makes lots of sense. gopls sets `preselect` but that may be because it does not sort items by relevance. I think we need more evidence that this is useful before implementing it.

I think whatever is the design to be provided for having this feature, it'll need information being provided by the server regarding ranking/order, otherwise the client can't simply assume ordering. As I ignore about the protocol having support for ranking schemes, I guess this preselect flag comes as a least intrusive solution/feature.
