### ISSUE TITLE
Improperly handle template explicit instantiation

### ISSUE THREAD

**Issue by xVanTuring** [MaskRay/ccls#516]
### Observed behavior
Given the following code and cache file generated
``` cpp
template <typename T> struct Foo {};
template struct Foo<int>;
int main() {
  Foo<int> a;
}
```
``` jsonc
{
  "usr2type": [
    {
      "usr": 10528472276654770367,
      "detailed_name": "struct Foo {}",
      "qual_name_offset": 7,
      "short_name_offset": 7,
      "short_name_size": 3,
      "hover": "",
      "comments": "",
      "spell": "1:30-1:33|1:23-1:36|2|-1",
      "bases": [],
      "funcs": [],
      "types": [
        2455108169471532340
      ],
      "vars": [],
      "alias_of": 0,
      "kind": 23,
      "parent_kind": 1,
      "declarations": [],
      "derived": [],
      "instances": [],
      "uses": [
        "2:17-2:20|4|-1",
        "4:3-4:6|4|-1"
      ]
    },
    {
      "usr": 5123806965838456033,
      "detailed_name": "",
      "qual_name_offset": 0,
      "short_name_offset": 0,
      "short_name_size": 0, // ...
      "kind": 0,
      "instances": [
        13894193650254991204
      ],
      "uses": []
    }
  ],
  "usr2var": [
    {
      "usr": 13894193650254991204,
      "detailed_name": "Foo<int> a",
      "qual_name_offset": 9,
      "short_name_offset": 9,
      "short_name_size": 1, // ...
      "spell": "4:12-4:13|4:3-4:13|2|-1",
      "type": 5123806965838456033,
      "kind": 13,
      "parent_kind": 12,
    }
  ]
}
```
The type of usr "5123806965838456033" was created when getting the type of variable `a`. Because the `explicit instantiation` makes `s->getTypeAsWritten()` in function `getAdjustedDecl` to be not `nullptr`, it ends up adding a new type.
https://github.com/MaskRay/ccls/blob/3e04997061bd1313676dafb9897f4a9590f90eeb/src/indexer.cc#L356-L363
### Expected behavior
The type of variable `a` should be `struct Foo`, but it point to a `ClassTemplateSpecializationDecl`
### How I solve
I replaced the `s->getTypeAsWritten()` to `s->isExplicitSpecialization()`, it will only skip when there is an `Explicit Specialization` instead of  `Explicit Instantiation`
### System information

* ccls version (`git describe --tags --long`): 0.20190314.2-4-g3e049970
* clang version:  9.0.0
* OS: Arch Linux
* Editor: 
* Language client (and version):

**Comment by MaskRay** [comment]
Thanks for the analysis and the fix!
