### ISSUE TITLE
[feature request]run only one true ccls when two editor is opened

### ISSUE THREAD

**Issue by findNextStep** [MaskRay/ccls#520]
when we have one project(like linux), ccls have to use lot of memory .But when i open two client with same param,ccls use twice memory

### Observed behavior

if we have two screen, and open two vim in different screen , two ccls launched and use twice memory
### Expected behavior

the second server just send command to first ccls and use as less as it can, like
vim 2 --command--> ccls2 --command--> ccls1 <--command-- vim1

**Comment by MaskRay** [comment]
Duplicate of #491
