### ISSUE TITLE
Feature request: platform specific options in .ccls

### ISSUE THREAD

**Issue by theorlangur** [MaskRay/ccls#523]
### Feature request

it would be nice to be able to specify different options in .ccls file, depending on the platform (linux, windows, mac).
Use case:

an **"--include=file.h"** is provided in **.ccls** to help ccls index things and it works nicely under linux (presumabely also under mac, haven't tried), but under windows with **clang-cl** driver it doesn't work at all and a **-Xclang** is needed before it.
But specifying **-Xclang** before destroys indexing under linux.
If it would be possible to specify as the first options something like:

**%win** < *and here an option for windows only* >

this would help a lot.
Suggestion for names:

 * %win
 * %lin
 * %mac

Cheers!

**Comment by MaskRay** [comment]
Do `%win`, `%lin` and `%mac` apply on the host environment or the target environment?

If they apply on the host, the build can vary depending on the host environment. I think this makes cross compilation complex. If they apply on the target, I think you can achieve the same by appending `-target x86_64-linux-gnu`, `-target x86_64-apple-darwin`, etc. `%win` may be an abbreviation if you don't want to maintain `.ccls` for different platforms. However, I don't think they are sufficient. There are many other things that can affect the build, e.g. `__arm__` (architecture), `__FreeBSD__` (OS), `__GNUC__`. `__GLIBC__`, `__FLOAT128__`, etc.

**Comment by theorlangur** [comment]
In my understanding we were talking about the environment where ccls runs. In my case there are two of those: Ubuntu and Windows and I would like to have a way to provide some platform-specific options in .ccls
Because otherwise:
-include=path/to/common/header.h

Works for Linux, but doesn't for Windows.

-Xclang
-include=path/to/common/header.h

Works for Windows but breaks Linux.
Is there maybe some other existing solution to this issue? (".ccls" files are checked out in the git repo)

**Comment by MaskRay** [comment]
If the clang command line can vary from Linux to Windows, I think you probably should switch from `.ccls` to `compile_commands.json`.

Create multiple build directories and create a symlink or use the initialization option `compilationDatabaseDirectory` to point to `out/x86_64-linux-gnu/compile_commands.json` and `out/x86_64-pc-windows/compile_commands.json`

**Comment by Riatre** [comment]
> Because otherwise:
> -include=path/to/common/header.h
> 
> Works for Linux, but doesn't for Windows.
> 
> -Xclang
> -include=path/to/common/header.h
> 
> Works for Windows but breaks Linux.

Could you please paste the first few lines of .ccls here? It sounds like ccls uses clang-cl driver on Windows, which might be unexpected.
