### ISSUE TITLE
can one vscode workspace support more then one compile_commands.json?

### ISSUE THREAD

**Issue by HarmonyAngel** [MaskRay/ccls#527]
I have a project which need to be compiled more than once under different directories. So, there will be more than one compile_commands.json genereated.
Like, cd ${SourceRoot}, bear make, make install; cd ${SourceRoot}/third_part/neteasy, bear make, make install; cd ${SourceRoot}/../other_directory, bear make, make install;
These are very common in large engineering projects. But it seems that ccls can only support one compile_commands.json. 
We really need such feature. 
Thank you~
and also thank you for ccls

**Comment by MaskRay** [comment]
Search for "workspaceFolders" in existing issues. For example, https://github.com/MaskRay/ccls/issues/479#issuecomment-531623702

**Comment by HarmonyAngel** [comment]
my project maybe very huge, and I'd like to use bear to generate the compile_commands.json file, not .ccs. And, it seems that the workspaceFolders interface only allows one directory configure. If you can let this interface param support a directory list ccontained compile_commands.json, then that will be very good.
Thank you~

**Comment by HarmonyAngel** [comment]
appending:
when I try to add directories to my workspace, it seems to work!
