### ISSUE TITLE
ccls exits when parsing a cpp file

### ISSUE THREAD

**Issue by kangjianbin** [MaskRay/ccls#528]
### Observed behavior
ccls exits when parsing this file:
https://raw.githubusercontent.com/scarsty/kys-cpp/master/src/Event.cpp
Message:
```
LSP :: ccls has exited (finished)
Server ccls:199574 exited with status exit. Do you want to restart it? (y or n) y
```

* `compile_commands.json` or `.ccls` ([wiki/Project-Setup](https://github.com/MaskRay/ccls/wiki/Project-Setup))
.ccls configuration is: 
```
%cpp -std=c++11
%c -std=c99
-Wall
-W
-Ikys-cpp/common
-Ikys-cpp/others
-Ikys-cpp/local/include
```
ccls is in parent directory of the project

* Reduce to A minimal set of `.c` `.cc` `.h` `.hh` files that can still demonstrate the issue.
https://raw.githubusercontent.com/scarsty/kys-cpp/master/src/Event.cpp

* Consider a screencast gif.

### Expected behavior
ccls parses the file successfully.

### Steps to reproduce
1. Open Event.cpp. 
2. ccls exits

### System information

* ccls version (`git describe --tags --long`): 
0.20190823.5-9-gcef02034

* clang version: 
llvm-8
* OS: 
linux debian testing

* Editor: 
emacs

* Language client (and version): 
emacs-ccls

**Comment by MaskRay** [comment]
Can you try http://releases.llvm.org/ clang 9.0.0 ? Use -DCMAKE_PREFIX_PATH=/path/to/clang+llvm-xxx https://github.com/MaskRay/ccls/wiki/Build

**Comment by kangjianbin** [comment]
Still has the issue. I find a simple method to reproduce it:

Save this code using `gb18030` coding. Then revert it to `utf-8` (`revert-buffer-with-coding-system`).
I can see ccls exits after reverting.

```
#include <stdio.h>

int main(void)
{
    printf("你好，世界\n");
    return 0;
}

```
Not sure if there is something related to https://github.com/emacs-lsp/lsp-mode/issues/1246

**Comment by MaskRay** [comment]
`M-x revert-buffer-with-coding-system RET utf-8 RET` works for me. I believe the buffer will be out-of-sync so no LSP features will be usable, but the ccls process does not crash.

If you do think it can crash, attach a debugger and get a stack trace `gdb -p $(pgrep -fn ccls)` https://github.com/MaskRay/ccls/wiki/Debugging
