### ISSUE TITLE
Build fails after 100% reached

### ISSUE THREAD

**Issue by jrwrigh** [MaskRay/ccls#532]
### System information

* ccls version (`git describe --tags --long`): From latest master (commit cef0203)
* clang version: 9.0.0 (pre-buiilt binaries for ubuntu 14.04)
* OS: Debian 8
* Cmake: 3.8.0

### Commands
```
➜ cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/.local/share/clang-LLVM/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-14.04 -DCMAKE_INSTALL_PREFIX=~/.local/share/ccls
-- The CXX compiler identification is GNU 8.2.0            
-- Check for working CXX compiler: /usr/local/gcc/8.2.0/bin/c++                                                        
-- Check for working CXX compiler: /usr/local/gcc/8.2.0/bin/c++ -- works                                               
-- Detecting CXX compiler ABI info                         
-- Detecting CXX compiler ABI info - done                  
-- Detecting CXX compile features                          
-- Detecting CXX compile features - done                   
-- Looking for C++ include pthread.h                       
-- Looking for C++ include pthread.h - found               
-- Looking for pthread_create                              
-- Looking for pthread_create - not found                  
-- Check if compiler accepts -pthread                      
-- Check if compiler accepts -pthread - yes                
-- Found Threads: TRUE                                     
fatal: No names found, cannot describe anything.           
-- Configuring done                                        
-- Generating done                                         
-- Build files have been written to: /users/jrwrigh/temp/ccls/Release
➜ cmake --build Release --target install &> lololol2.log
```
Where [`lololol2.log` is this 7000 line error file](https://drive.google.com/file/d/1UaBdweR8UrvjgfWLMrZIbznuILreYZ92/view?usp=sharing) (hence the lol's). 

I'm really not sure where to even start in diagnosing what is wrong here. I think it has something to do with not accessing the the llvm libraries, but I have no experience in clang/llvm. Any help would be appreciated.

**Comment by MaskRay** [comment]
> clang_tu.cc:(.text+0x1f26): undefined reference to `llvm::sys::getDefaultTargetTriple[abi:cxx11]()'

In my build:
```
% nm -C CMakeFiles/ccls.dir/src/clang_tu.cc.o | grep getDefaultTarget
                 U llvm::sys::getDefaultTargetTriple[abi:cxx11]()
```

This may be caused by multiple reasons. `ninja -C Release -v` output that displays the full linker command line will be helpful.

1) The llvm libraries are not correctly configured. This should not happen with a standard compiler/llvm library installation. (Note there is a non-standard GCC path `/usr/local/gcc/8.2.0/bin/c++`). If you want to specify an exact llvm installation path, pass `-DCMAKE_PREFIX_PATH=/usr/lib/llvm-9` to cmake.
2) The llvm libraries were compiled without `_GLIBCXX_USE_CXX11_ABI` (https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html). Again, this should not happen with a standard installation.

**Comment by mjkramer** [comment]
FWIW, I got a similar flood of linker errors when building ccls in a very nonstandard Cray environment. For reasons I cannot hope to understand, the linker was not including libstdc++. Setting CMAKE_CXX_FLAGS to -lstdc++ took care of it.

**Comment by jrwrigh** [comment]
Doing `-DCMAKE_CXX_FLAGS=-lstdc++` didn't help me unfortunately. 

Back to @MaskRay 's comment, my LLVM install is not standard. I'm simply downloading the binaries like the documentation says. There is another (old) version of LLVM installed on my system which it might be trying to reference. I tried to set the `-DDEFAULT_RESOURCE_DIRECTORY` flag like it says [here](https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory), but cmake reports that it isn't used.

Is there a way to more explicitly point cmake/ccls to the correct llvm libarary? Beyond the `-DCMAKE_PREFIX_PATH=` option?

And yes, I know that I have a non-standard gcc install directory. That's just how the cluster I'm working on operates. Is that a problem?

**Comment by mjkramer** [comment]
@jrwrigh, after the build fails, you can peek at `Release/CMakeFiles/ccls.dir/link.txt` to see the final call to the linker. That might provide some insight as to which installation of LLVM/libstdc++ it is trying to link against. You might be able to add appropriate `-L` and `-l` directives to make the link succeed (assuming that the correct headers were used during compilation, which you might be able to determine by looking at `flags.make` in the same dir as `link.txt`).

**Comment by jrwrigh** [comment]
Looking at the `link.txt` shows that it's actually referencing the correct locations for everything, though a search for `std` or `c++` doesn't turn up anything other than the declaration.

Actually, running `find ./ -iname '*std*'` in the LLVM directory didn't turn up a `libstdc++`. There's a `libc++` in the LLVM directory, but nothing else.

**Comment by jrwrigh** [comment]
I got it! I've been running with LLVM binaries for Ubuntu 14.04 (I'm running on a very old Debian system which is circa 2014). For whatever reason **ccls doesn't like the Ubuntu 14.04 binaries**, but it doesn't like the 18.04 binaries either. Per Goldilocks, Ubuntu 16.04 binaries proved to be *juuust* right.
