### ISSUE TITLE
vscode 语法高亮在切换头文件/源文件的时候不生效

### ISSUE THREAD

**Issue by Yuan-Hang** [MaskRay/ccls#539]
目前发现在vscode中, 只有通过点击sidebar打开文件才会显示ccls的语法高亮.
如果通过cpptools的切换头/源文件, 那么颜色不会生效. 显示的默认主题的颜色

**Comment by mkitby** [comment]
cpptools 需要被禁用，不然可能有冲突，

```
   "C_Cpp.intelliSenseEngine": "Disabled",
   "C_Cpp.autocomplete": "Disabled",
   "C_Cpp.formatting": "Disabled",
```
切换头/源文件， 可以安装Header source switch

**Comment by MaskRay** [comment]
Thanks, mkitby!
