### ISSUE TITLE
Report index status

### ISSUE THREAD

**Issue by unphased** [MaskRay/ccls#540]
On large codebases, indexing may take several minutes on a particular source file.

### Expected behavior

I hope that status of the count of (e.g. concurrent index jobs count), and the names of the source files that are currently being processed, could be shown in the status, e.g. with coc.nvim. I don't know what the mechanism is for reporting status, but I'm referring to the thing that shows e.g. `E2` when there are 2 errors. 

If we can see which files are being indexed we will be able to see whether or not we can expect indexing to be done soon, and have a chance to estimate how much longer we'll likely need to wait.

**Comment by MaskRay** [comment]
You can send a request `$ccls/info` to ccls and it will dump `pendingIndexRequests`. See `src/messages/ccls_info.cc`

**Comment by damnskippy** [comment]
@MaskRay , could you please provide some guidance on using this request from coc.nvim for instance?  Thanks.

**Comment by damnskippy** [comment]
Never mind - I think I've got this: `CocRequest('ccls', '$ccls/info')`
