### ISSUE TITLE
Deprioritize a .c compile_commands.json entry when looking for the best match for .hpp or .hh

### ISSUE THREAD

**Issue by Frydac** [MaskRay/ccls#543]
Hi,

My problem is that I have a CMake generated `compile_commands.json` with both C++ and C entries.
I have a few C++ header files (.hpp) which seem to be parsed with C options, as I get the error `unknown type name 'namespace'`. I think this header file is only included in C++ translation units (.cpp), but I'm not 100% sure (lots of includes). The target (unit test executable by doctest) for which the compile_comands.json are generated, builds fine, so I would think it is only included in C++ TUs.
When I remove all the C entries from the compile_commands.json, and reindex, it is parsed as C++ by ccls and everything works as expected.

EDIT: 
ok I read some more in the faq, but I still don't understand:
When I manually index using my compile_commands.json, I can see in the logs that the index `store` of the .hpp file is preceded by a `parse` of a correct .cpp file, and should have been indexed with the correct options. But when I open that .hpp file in vim/coc.nvim and look at the log, the `preamble` line shows a compile command with the c compiler with some unrelated .c file.

So, I'm guessing the .hpp file is reparsed when I open it, and for some reason that .c file is chosen in stead of the original .cpp file from which it was indexed?
I can see that the logs list the line nrs in the ccls code, maybe I can find how/why this decision is made if I find the motivation :). I would expect that the .cpp file which first gives cause to storing the index for the .hpp file is remembered/reused when available, or at least a 'close' .cpp file is used for .hpp files (and not the .c file as in my case).
I could probably solve this by creating .ccls files in my project, however, I feel like this could be automated more correctly in e.g. my case.

FYI: this .hpp file has no similarly named .cpp file (template class) and lives in a directory with only other .hpp files. The .c file is chosen from a parent directory. This parent directory only contains C .c files and C++ .hpp files.

I imaging the ideal case where for a given header, ccls knows all TU's that #include this header, and I would be able to list these when editing a header file, and then select which TU I want to use the compile options from (potentially using something fzf to fuzzy search them, as there could be a lot of them).
Though I guess, that lsp does not provide for this kind of interaction between the client and server.

I'm using:

ccls version 0.20190823.5-9-gcef02034
clang version 9.0.0 (tags/RELEASE_900/final)
on Manjaro linux, with vim/nvim and coc.nvim

**Comment by MaskRay** [comment]
Say, we have `/tmp/d/{a.c,b.hpp,c.cc}`.

`compile_commands.json`:
```json
[
    {
        "arguments": [ "cc", "-c", "-o", "a.o", "a.c" ], 
        "directory": "/tmp/d", 
        "file": "a.c"
    },
    {
        "arguments": [ "c++", "-c", "-o", "c.o", "c.cc" ], 
        "directory": "/tmp/d", 
        "file": "c.cc"
    } 
]
```

In `project.cc` `Project::findEntry`, the `a.c` entry may be picked and `b.hpp` will be parsed as C, hence the error `unknown type name 'namespace'`. Note, if we have `c.cpp`, because `c.cpp` shared a suffix with `b.hpp`, it will get larger score and will be more likely to match.

Can you check if #549 fixes the problem?

**Comment by Frydac** [comment]
Thanks, but it seems not.

I don't get any `preamble` line in the logs when opening my header file, using commit https://github.com/MaskRay/ccls/pull/549/commits/d770dba0a40ca5b5fb126f789f4d565ac5aa4ce6 .
Which seems to result in ccls not finding the included headers (in one of  the include folders that should have been part of the compilation options)

I double checked by checking out master again, and using the same process:
- remove cache.
- manually index cache.
- start gvim and reopen file.

which does result in a `preamble` line at the moment of the last step (using an 'incorrect' `.c` file)

I'll try and reproduce the issue with a minimal example, as I suspect our specific directory layout is making things more complicated.
Ok, I think this has the same issue:
files:
`/tmp/d/a.c`
`/tmp/d/dir1/b.hpp`
`/tmp/d/dir2/c.cc`
with compile_commands.json
```
[
    {
        "arguments": [ "cc", "-c", "-o", "a.o", "a.c" ], 
        "directory": "/tmp/d", 
        "file": "a.c"
    },
    {
        "arguments": [ "c++", "-c", "-o", "c.o", "c.cc"], 
        "directory": "/tmp/d/dir2", 
        "file": "c.cc"
    } 
]
```
In this case when opening `dir1/b.hpp` no `preamble` line is in the logs.

**Comment by MaskRay** [comment]
> In this case when opening dir1/b.hpp no preamble line is in the logs.

I made a mistake in #549 


```
--- c/src/project.cc
+++ i/src/project.cc
@@ -560,3 +560,3 @@ Project::Entry Project::findEntry(const std::string &path, bool can_redirect,
               // Decrease score if .c is matched against .hh
-              auto [lang1, header1] = lookupExtension(best->filename);
+              auto [lang1, header1] = lookupExtension(e.filename);
               if (lang != lang1 && !(lang == LanguageId::C && header))
```

Before #549:

```
14:37:57 preamble     sema_manager.cc:734 I create session for /tmp/d/dir1/b.hpp
  cc -c -o a.o a.c --gcc-toolchain=/usr -working-directory=/tmp/d
14:37:57 indexer0         pipeline.cc:340 I parse /tmp/d/dir1/b.hpp
  cc -c -o a.o a.c --gcc-toolchain=/usr -working-directory=/tmp/d
```

After #549:

14:42:55 indexer1         pipeline.cc:340 I parse /tmp/d/dir1/b.hpp
  c++ --driver-mode=g++ -c -o c.o c.cc --gcc-toolchain=/usr -working-directory=/tmp/d/dir2
14:42:55 preamble     sema_manager.cc:734 I create session for /tmp/d/dir1/b.hpp
  c++ --driver-mode=g++ -c -o c.o c.cc --gcc-toolchain=/usr -working-directory=/tmp/d/dir2

**Comment by Frydac** [comment]
This seems to have fixed my issue, thank you so much!!
