### ISSUE TITLE
'iostream' file not found on macOS

### ISSUE THREAD

**Issue by cdelledonne** [MaskRay/ccls#544]
I'm trying to index the simplest of C++ projects on macOS. Just one file:
```cpp
#include <iostream>
```

The `.ccls` file at the root of the project is:
```
clang++
```

I compiled ccls from source:
```
git clone --depth=1 --recursive https://github.com/MaskRay/ccls
cd ccls/third_party
wget -c https://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-darwin-apple.tar.xz
tar xf clang+llvm-9.0.0-x86_64-darwin-apple.tar.xz
cd ..
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$PWD/third_party/clang+llvm-9.0.0-x86_64-darwin-apple
cmake --build Release
```

The ccls server is started as `ccls -v=2 -log-file=/tmp/ccls.log` and with the following init options:
```
cache.directory = "/tmp/ccls-cache"
completion.detailedLabel = false
completion.caseSensitivity = 1
diagnostics.onChange = -1
```

### Observed behavior

When indexing the above C++ file, ccls returns `'iostream' file not found` on the first line. On a side note, the same happens with `ccls` and `clang+llvm` installed via Homebrew.

There's one thing from the ccls.log that strikes me, that is
```
I use -resource-dir=/Users/carlo/builds/ccls/third_party/clang+llvm-9.0.0-x86_64-darwin-apple/lib/clang/9.0.0
```

Why is the Clang resource directory that? Shouldn't it be just the root `clang+llvm-9.0.0-x86_64-darwin-apple`? If ccls searches includes only downwards (that I can't tell from the logs), then `iostream` is not gonna be found. Its path is `clang+llvm-9.0.0-x86_64-darwin-apple/include/c++/v1/iostream`.

### Expected behavior

I expect ccls to look for system include files in the right paths, and not to return `'iostream' file not found`.

### System information

* ccls version: 0.20190823.5-9-gcef02034
* clang version: 9.0.0
* OS: macOS Catalina 10.15.1
* Editor: Nvim 0.5
* Language client (and version): Nvim's builtin LSP client

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory described Clang resource dir. It is something like:

```
% clang -print-resource-dir
/home/ray/llvm/Release/lib/clang/10.0.0
```

https://github.com/MaskRay/ccls/wiki/Build#macos

**Comment by cdelledonne** [comment]
Your brief answer does solve my issue, unfortunately.

As I carefully explained above, I followed the build procedure from the wiki, using cmake+llvm downloaded from https://releases.llvm.org/download.html. The download and build procedure completes successfully, but `iostream` still cannot be found.

As I noted above, `iostream` is in
```
clang+llvm-9.0.0-x86_64-darwin-apple/include/c++/v1/iostream
```

Starting from the CLANG_RESOURCE_DIR, the path would be
```
$CLANG_RESOURCE_DIR/../../../include/c++/v1/iostream
```

Do you have any clue why ccls/clang cannot find `iostream`? Note that just compiling with clang (no ccls) works fine.

By the way, I took some time to describe the issue quite carefully. Closing the issue with such a short reply is not that helpful.

**Comment by phphong** [comment]
@cdelledonne I think your issue is related to  https://github.com/MaskRay/ccls/issues/191. I had the same issue as you and I have resolved it. See my comment there.
