### ISSUE TITLE
[Feature request] Monaco editor support?

### ISSUE THREAD

**Issue by shoorlyne** [MaskRay/ccls#55]
As [Monaco editor](https://github.com/Microsoft/monaco-editor) is rising to a dominance status, I wonder if you have any plan to add some support to it, including adding some instructions on how to make ccls work with Monaco, just like what's done for VS Code?

Thanks for this awesome work!

**Comment by MaskRay** [comment]
If you use an extension speaking Language Server Protocol and provide the root directory, textDocument/definition textDocument/references workspace/symbol textDocument/completion etc should work fine.

ccls extensions to LSP will not available though:
semantic highlighting, $ccls/inheritanceHierarchy, various parameters in textDocument/references, $ccls/vars, ... https://github.com/MaskRay/ccls/wiki/Neovim#custom-cross-references
