### ISSUE TITLE
ccls exits with error code -1073740940 on Windows when started through vim-lsp

### ISSUE THREAD

**Issue by n00bmind** [MaskRay/ccls#551]
### Observed behavior

ccls process exits everytime I start vim with vim-lsp configured to auto start it.
Starting it from the command line with the --index argument shows no errors (and the process keeps running until killed).
The log file specified as output with the -log-file argument doesn't show any errors either.
However vim-lsp's own log file always shows messages like:

> 25/12/2019 19:37:37:["s:on_exit",2,"ccls","exited",-1073740940]

at the bottom.
Also executing ':LspStatus' in vim shows 'ccls: exited'

I'm not using any compile_commands.json. My .ccls file is very simple:

```
clang-cl
%h c++-header
```

### Expected behavior

ccls process keeps running while vim-lsp is running.

### Steps to reproduce

1. Open vim with a .c/.cpp file
2. Notice that ccls.exe process is not running

### System information

* ccls version (`git describe --tags --long`): 0.20190823.5-11-g98f25b52
* clang version: 10.0.0
* OS: Windows 10 Home 10.0.18362
* Editor: Vim 8.1 (2018 May 18, compiled Nov 21 2019 23:03:11)
* Language client (and version): vim-lsp v0.1.0-517-g5d6de67

I used the instructions for self-compiling llvm & ccls in https://github.com/MaskRay/ccls/wiki/Build#windows pretty much verbatim and had no problems while doing so.

Any help greatly appreciated!

**Comment by MaskRay** [comment]
```
clang-cl
%h c++-header
```

This is not correct. clang-cl does not accept the option named `c++-header`. You can have an empty .ccls to get started.  https://github.com/MaskRay/ccls/wiki/Project-Setup#ccls-file

**Comment by n00bmind** [comment]
Well, my first version had 'clang' in the first line, that one was just me trying things out..
It doesn't seem to matter much, as the result is the same. I also just tried with an empty .ccls file, and it made no difference either.

As mentioned in my post, running the server in index mode works fine, as does running with the --help argument.
