### ISSUE TITLE
textDocument/hover response is always empty after line 32768

### ISSUE THREAD

**Issue by adizero** [MaskRay/ccls#552]
### Observed behavior
textDocument/hover response is always empty after line 32768

Tested with two different LSP clients in Vim (LanguageClient-neovim and ALE)

### Expected behavior

See the symbol documentation/type info

### Steps to reproduce

1. Add blank lines to the top of any c/cpp file.
2. Check hover information of any symbol on line > 32768

### System information

* ccls version (`git describe --tags --long`): 
98f25b52fff3bc3c06ffe18ab99cc93f953e27fd Dec 22 2019
* clang version: 
9.0.1
* OS:
CentOS 6.6
* Editor: 
Vim 8.2
* Language client (and version): 
LanguageClient-neovim 0.1.155-13-g48f8833
ALE v2.6.0-59-g1c69ef1

**Comment by adizero** [comment]
I have found and fixed the bug. Will add pull request soon.

**Comment by MaskRay** [comment]
I will not call this a bug. It is a limitation. There is nothing with the code.

I do wonder why you have files with more than 32768 lines.

**Comment by MaskRay** [comment]
Close via #553
