### ISSUE TITLE
Comment positioning

### ISSUE THREAD

**Issue by g-suraj** [MaskRay/ccls#554]
C++ documentation style can vary across libraries. For example, the Bloomberg basic dev environment places function docs at the [bottom of the mode](https://github.com/bloomberg/bde/blob/master/groups/bsl/bslstl/bslstl_string.h#L713-L719). 

```C++
class X {
    public:
        // My comment for foo
        static void foo() {};

        static void bar() {};
        // My comment for bar
  };

int main() {

    X::foo(); // Docs displayed
    X::bar(); // Docs not displayed

    return 0;
}
```

Not sure if this is an issue with ccls itself or some other clang library

**Comment by MaskRay** [comment]
`clang -fsyntax-only -Xclang -ast-dump -fparse-all-comments a.cc`

A `TextComment` is attached to `X::foo`. `X::bar` does not have one. I think this is on purpose. People rarely write comments after a declaration.

```
| |-CXXMethodDecl 0x143e418 <line:4:9, col:28> col:21 used foo 'void ()' static
| | |-CompoundStmt 0x143e5c0 <col:27, col:28>
| | `-FullComment 0x143ea10 <line:3:11, col:29>
| |   `-ParagraphComment 0x143e9e0 <col:11, col:29>
| |     `-TextComment 0x143e9b0 <col:11, col:29> Text=" My comment for foo"
| `-CXXMethodDecl 0x143e4d8 <line:6:9, col:28> col:21 used bar 'void ()' static
|   `-CompoundStmt 0x143e5d0 <col:27, col:28>
```

**Comment by g-suraj** [comment]
> People rarely write comments after a declaration

Well, like I linked in my initial comment, there is an entire organisation which places the `TextComment` below declarations (including classes). Is there any workaround to this problem that doesn't warrant me pulling my hair out?

**Comment by myrgy** [comment]
They decided to implement there our "Doxygen" https://github.com/bloomberg/bde-tools/tree/master/contrib/bdedox

I assume that there is no easy way to support it - clang support normal comment(ie placed before).

**Comment by g-suraj** [comment]
>Because even your sample leads to errors:

It's more of an either / or thing. Obviously mixing the two would be ambiguous.
