### ISSUE TITLE
Link error in ccls build

### ISSUE THREAD

**Issue by solotim** [MaskRay/ccls#556]
### Observed behavior

Build ccls all look good till linking:

`/llvm-8.0.0/lib/libLLVMSupport.a(Process.cpp.o): undefined reference to symbol 'del_curterm'
/lib64/libtinfo.so.5: error adding symbols: DSO missing from command line`

With some googling, it points me to adding terminfo lib. But if manually add `-ltinfo`, tons of undefined reference error show up. It seems the compiler can't even find out the basic c++ symbols: `main.cc:(.text+0x299): undefined reference to 'operator new(unsigned long)'`

### Expected behavior

Build success

### Steps to reproduce

Just build according to the build guide of ccls

### System information

* ccls version (`git describe --tags --long`): 0.20190823.5-14-g64e3e8f2
* clang version: 8.0
* OS: CentOS release 6.6
* Editor: Vim
* Language client (and version): C++
* ccls build compiler: gcc-9.1.0

**Comment by MaskRay** [comment]
> Build ccls all look good till linking:

Does your CentOS 6.6 have a newer glibc that does not require `-D__STDC_FORMAT_MACROS` (https://github.com/MaskRay/ccls/wiki/Build#red-hat--centos)?

> With some googling, it points me to adding terminfo lib. But if manually add -ltinfo, tons of undefined reference error show up.

`ninja -C build_directory -v` prints the linker command line (g++/clang++). You can add `-ltinfo` and run the command.

During cmake configuring, pass `-DCMAKE_CXX_LINKER_FLAGS=-ltinfo`
