### ISSUE TITLE
How to auto generate .ccls file from some tools?

### ISSUE THREAD

**Issue by jiangjianshan** [MaskRay/ccls#557]
Here are some things you should try before filing a bug report:

+ For client issues related to [emacs-ccls](https://github.com/MaskRay/emacs-ccls) or [vscode-ccls](https://github.com/MaskRay/vscode-ccls), report in their own repository.
+ For build problems, check https://github.com/MaskRay/ccls/wiki/Build
+ Check https://github.com/MaskRay/ccls/wiki/Debugging
+ Check [the FAQ](https://github.com/MaskRay/ccls/wiki/FAQ) to see if your issue is mentioned.

If none of those help, remove this section and fill out the four sections in the template below.

---

### Observed behavior

Describe what happened. Any aids you can include (that you think could be relevant) are a tremendous help.

* `compile_commands.json` or `.ccls` ([wiki/Project-Setup](https://github.com/MaskRay/ccls/wiki/Project-Setup))
* Reduce to A minimal set of `.c` `.cc` `.h` `.hh` files that can still demonstrate the issue.
* Consider a screencast gif.

### Expected behavior

Describe what you expected to happen.

### Steps to reproduce

1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.

### System information

* ccls version (`git describe --tags --long`): 
* clang version: 
* OS: 
* Editor: 
* Language client (and version): 

Hello,
    Because some projects can't generate the compile_commands.json correctly or hard to do it. Is there exist tool can generate the .ccls file automatically?

**Comment by MaskRay** [comment]
`.ccls` is useful for simple projects. Larger projects should use `compile_commands.json`.

If you are certain most files share the same compiler command line, you can extract `-I` `-D` `-isystem` from then and construct your `.ccls`. This trial-and-error process is hard to automate.
