### ISSUE TITLE
Is there are some method to simulate didOpen method and index the file offline? 

### ISSUE THREAD

**Issue by Abbyyan** [MaskRay/ccls#558]
Sorry to bother you. I'm using ccls on a large project and it use a lot of memory to index the files。 
I've write a proxy using python and get the input and output of ccls .  I want to ask if there is some way to simulate the `didOpen` method and  index the file in the `compile_commands.json` offline.(That is to say, I have the files in my computer and index them one by one  without open them。 Then when i open the file , it can just load cache from `.ccls-cache`)。 Thanks a lot.

**Comment by MaskRay** [comment]
The command line option `-index` enables the standalone mode. https://github.com/MaskRay/ccls/wiki/FAQ#can-ccls-be-started-directly

`ccls --index=$HOME/llvm --init='{"clang":{"extraArgs": ["-DA"]}}'`

**Comment by Abbyyan** [comment]
It does work and help a lot . Thank you very much.

**Comment by Abbyyan** [comment]
I have some trouble with using `ccls --index`.

My project `/home/abby/workspace`  is a soft link just as `/home/abby/workspace = /data/user/abby/workspace` .  When i use `ccls --index=/home/abby/workspace` , it create the index but can't be used when the file is opened by `vim + coc-nvim`. But when i changed it to `ccls --index=/data/user/abby/workspace`, the generated index can be used in vim. 

I would appreciate it if you could explain why this happens. Thanks a lot. @MaskRay

**Comment by findNextStep** [comment]
https://github.com/MaskRay/ccls/wiki/Customization#clangpathMappings may help

**Comment by Abbyyan** [comment]
> https://github.com/MaskRay/ccls/wiki/Customization#clangpathMappings

Should I use the clangPathMapping as `{"clang": {"pathMappings": ["/home/abby/workspace/>/data/user/abby/workspace/"]}`   or just `{"clang": {"pathMappings": ["/home/>/data/user/"]}`   in my condition

**Comment by Abbyyan** [comment]
Sorry to bother you again. I use the `{"clang": {"pathMappings": ["/home/abby/workspace/>/data/user/abby/workspace/"]}` but it seems like that it parse the index from scratch. How could i know if the old index has been used ?

**Comment by Abbyyan** [comment]
Is only  the user directory  can be replaced?

**Comment by Abbyyan** [comment]
I've see the source code and find it's just a string replacement in `cache` and `compile_commands.json`. But i wonder how could i know if the old index has been used ? It seems that the project is parsed again.  Thanks a lot . @findNextStep

**Comment by findNextStep** [comment]
> I've see the source code and find it's just a string replacement in `cache` and `compile_commands.json`. But i wonder how could i know if the old index has been used ? It seems that the project is parsed again. Thanks a lot . @findNextStep

you may try set Cache:directory in init

here is my set up    `ccls -index=./ -init="{\"compilationDatabaseDirectory\":\"./build/Debug\",\"cache\":{\"directory\":\"./.ccls-cache\"} }, \"clang\":{\"extraArgs\":[\"-isystem\",\"/usr/local/opt/llvm/include/c++/v1\",\"-Wold-style-cast\"],\"resourceDir\":\"/usr/local/opt/llvm/lib/clang/9.0.1\"},\"index\":{\"threads\":12}}"` I just set every thing in init 😂, for more config you can read config.hh or wiki, or you can try to read log file to get save set up as your editor use

**Comment by Abbyyan** [comment]
> > I've see the source code and find it's just a string replacement in `cache` and `compile_commands.json`. But i wonder how could i know if the old index has been used ? It seems that the project is parsed again. Thanks a lot . @findNextStep
> 
> you may try set Cache:directory in init
> 
> here is my set up `ccls -index=./ -init="{\"compilationDatabaseDirectory\":\"./build/Debug\",\"cache\":{\"directory\":\"./.ccls-cache\"} }, \"clang\":{\"extraArgs\":[\"-isystem\",\"/usr/local/opt/llvm/include/c++/v1\",\"-Wold-style-cast\"],\"resourceDir\":\"/usr/local/opt/llvm/lib/clang/9.0.1\"},\"index\":{\"threads\":12}}"` I just set every thing in init 😂, for more config you can read config.hh or wiki, or you can try to read log file to get save set up as your editor use

Thanks a lot. But it really bother me whether the old index has been used. Is there some thing wrong when i use the config? The old  project path is `/home/abby/workspace`  and  the new project path is `/home/abby/mail_test` , where  the config setting is`"pathMappings": ["workspace>mail_test"]`. Is is the right way to use this config please?

**Comment by Abbyyan** [comment]
I've figured out that it because i didn't change the name of the cache after copy it to the new project. Thanks for your help. Thanks a lot !
