### ISSUE TITLE
Can I use HOME directory for cache directory in the initialization option?

### ISSUE THREAD

**Issue by brglng** [MaskRay/ccls#559]
For example, I would like to use something like `--init="{\"cache\": {\"directory\": \"~/.cache/ccls\"}"` or `--init="{\"cache\": {\"directory\": \"$HOME/.cache/ccls\"}"`, but those do not work now actually.

Thank you for your great project!

**Comment by MaskRay** [comment]
Tilde expansion is complex. On POSIX, you need to check `getenv("HOME")`, `getpwnam_r`, and probably also `getpwuid_r`. I think we should defer that to the user.
