### ISSUE TITLE
build fails on Ubuntu with llvm-9

### ISSUE THREAD

**Issue by ibentsion** [MaskRay/ccls#562]
### Observed behavior
Build fails with error
```
➜  ccls git:(master) ✗ cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-9/lib/clang/9.0.0
CMake Error at /usr/lib/llvm-9/lib/cmake/clang/ClangTargets.cmake:588 (message):
  The imported target "clangBasic" references the file

     "/usr/lib/llvm-9/lib/libclangBasic.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/llvm-9/lib/cmake/clang/ClangTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/cmake/clang-9/ClangConfig.cmake:19 (include)
  CMakeLists.txt:71 (find_package)


-- Configuring incomplete, errors occurred!

```

### Expected behavior

build success

### Steps to reproduce
install clang-9
install cmake
git clone --depth=1 --recursive https://github.com/MaskRay/ccls

cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-9/lib/clang/9.0.0

### System information

* ccls version (git hash 1834f8195bac38d9aec0c64f5f9e2901bfa989c5): 
* clang version: clang version 9.0.0-2~ubuntu18.04.1 (tags/RELEASE_900/final)
* OS: ubuntu18.04.1

The system is: Linux - 4.15.0-74-generic - x86_64
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/c++ 
Build flags: 
Id flags:

**Comment by mertzt89** [comment]
Try the following

Install dependencies
`sudo apt install clang-9 libclang-9-dev`

Configure
`cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH=/usr/lib/llvm-9 \
    -DLLVM_INCLUDE_DIR=/usr/lib/llvm-9/include \
    -DLLVM_BUILD_INCUDE_DIR=/usr/include/llvm-9/`

Build
`cmake --build Release`

**Comment by ibentsion** [comment]
worked.
thanks for the quick response.
