### ISSUE TITLE
Build failure with master

### ISSUE THREAD

**Issue by htjain** [MaskRay/ccls#563]
### Observed behavior
latest code from master is failing with following errors:

> ccls/src/main.cc: In function ‘int main(int, char**)’:
> /home/htjain/src/ccls/src/main.cc:143:44: error: no matching function for call to ‘std::__cxx11::basic_string<char>::basic_string(llvm::SmallString<256>&)’
>        pipeline::standalone(std::string(root));

> 
> In file included from /usr/include/c++/7/string:52:0,                                                                                                                                                                           [94/7422]
>                  from /usr/include/c++/7/bits/locale_classes.h:40,
>                  from /usr/include/c++/7/bits/ios_base.h:41,
>                  from /usr/include/c++/7/ios:42,
>                  from /usr/include/c++/7/istream:38,
>                  from /usr/include/c++/7/sstream:38,
>                  from /home/htjain/src/ccls/src/log.hh:6,
>                  from /home/htjain/src/ccls/src/main.cc:4:
> /usr/include/c++/7/bits/basic_string.h:639:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::__sv_wrapper, const _Alloc&) [with _CharT = char; _
> Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
>        basic_string(__sv_wrapper __svw, const _Alloc& __a)
>        ^~~~~~~~~~~~
> /usr/include/c++/7/bits/basic_string.h:639:7: note:   candidate expects 2 arguments, 1 provided
> /usr/include/c++/7/bits/basic_string.h:629:2: note: candidate: template<class _Tp, class> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Tp&, const _Alloc&)
>   basic_string(const _Tp& __t, const _Alloc& __a = _Alloc())
>   ^~~~~~~~~~~~
> /usr/include/c++/7/bits/basic_string.h:629:2: note:   template argument deduction/substitution failed:
> /usr/include/c++/7/bits/basic_string.h:618:2: note: candidate: template<class _Tp, class> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Tp&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, s
> td::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&)
>   basic_string(const _Tp& __t, size_type __pos, size_type __n,
>   ^~~~~~~~~~~~
> /usr/include/c++/7/bits/basic_string.h:618:2: note:   template argument deduction/substitution failed:
> /home/htjain/src/ccls/src/main.cc:143:44: note:   candidate expects 4 arguments, 1 provided
>        pipeline::standalone(std::string(root));
> 

### Expected behavior

Build should pass

### Steps to reproduce

1. Clone using 

> git clone --depth=1 --recursive https://github.com/MaskRay/ccls

2. Build 

> cmake --build Release

### System information

* ccls version (`git describe --tags --long`):  master 2760296 [origin/master] Adapt llvmorg-11-init-1314-g777180a32b6: StringRef's conversion to std::string is now explicit.
* clang version:  clang-9
* gcc version: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
* OS:  Ubuntu 18.04.3 LTS
* Editor:  N/A
* Language client (and version):  N/A

**Comment by MaskRay** [comment]
Sorry for the breakage. Fixed at HEAD.

Also tested LLVM 7.

**Comment by htjain** [comment]
Thanks. Its working now
