### ISSUE TITLE
ccls docker setup

### ISSUE THREAD

**Issue by AndreasAZiegler** [MaskRay/ccls#564]
This is more a question than an issue.

I'm running Arch Linux but often have to build/compile for Debian and/or Ubuntu. For this I'm compiling within a docker container.

I'm currently evaluating if clangd or ccls better suites my setup. I asked on the [clangd GitHub repo about the setup](https://github.com/clangd/clangd/issues/269) and I'm wondering if I can use the same setup for ccls (using the ccls ```clang.pathMappings``` instead of the clangd ```--path-mappings```)?

**Comment by MaskRay** [comment]
ccls `clang.pathMappings` works differently. It was designed for reusing remotely built `compile_commands.json` and `.ccls-cache`

Remote:

1. Generate `compile_commands.json`
2. Run ccls and generate `.ccls-cache/`

Local:

1. Mount remote directories `/remote` locally, say, `/mount/remote`
2. Configure your project and generate `compile_commands.json`
3. Make sure local and remote `compile_commands.json` only differ for paths, not additional flags
4. Set `clang.pathMappings` to `/remote:/mount/remote`
5. Run ccls locally.
