### ISSUE TITLE
Missing libclangBasic.a and other files on Ubuntu 18.04 with LLVM-8

### ISSUE THREAD

**Issue by SethGower** [MaskRay/ccls#565]
### Observed behavior

I am trying to install `ccls` on my work computer, which is running Ubuntu 18.04, and am unable to build. I think it may be an issue with files that `ccls` is looking for in `llvm` and `clang`, but am not sure. I have tried on my own computer, and a clean VM that I spun up on a server, and neither work. I have tried using the build command given in the build section of the wiki, and am getting an error that `cmake` is unable to find `libclangBasic.a`. I have tried installing `llvm-7`, `llvm-8` and `llvm-9` and their `clang` counterparts. Neither work. I am currently building `llvm` from source and am going to install that and see if that works, but doubt it. Any help would be appreciated. 
![image](https://user-images.githubusercontent.com/19225089/73695817-e8a81100-46a8-11ea-89ad-f00a87484fc2.png)

### System information

* ccls version (`git describe --tags --long`): Attempting to install the current version at `master`
* clang version: 7, 8 and 9. Currently have `9.0.0-2~ubuntu18.04.1` installed
* OS: Ubuntu server 18.04

**Comment by SethGower** [comment]
Building llvm and clang from source fixed the problem. I guess it is probably an ubuntu packaging problem.

**Comment by phrxmd** [comment]
Ubuntu has separate packages `libclang-7-dev`, `libclang-8-dev`, `libclang-9-dev` that contain this file.

**Comment by fei4xu** [comment]
> Ubuntu has separate packages `libclang-7-dev`, `libclang-8-dev`, `libclang-9-dev` that contain this file.

what about `libclang-10-dev` ?

**Comment by homeassistant-hacs-m** [comment]
> what about `libclang-10-dev` ?

take a guess

**Comment by Zhenyu-Yao** [comment]
libclang-10-dev is useful for this problem.

**Comment by n-jay** [comment]
> what about libclang-10-dev ?

Rule of thumb is to install `libclang-<version-you-want>-dev`. Worked fine with 14 for me.
