### ISSUE TITLE
Unable to rename symbols in ALE/NeoVim

### ISSUE THREAD

**Issue by SethGower** [MaskRay/ccls#566]
### Observed behavior

I am using `ccls` with ALE in NeoVim. When I try and rename a symbol, it just says `No changes received from server`. I am not sure what is wrong. 
`main.c`:
```c
#include <stdio.h>

int main(int argc, char *argv[]) {
    int test = 69;
    printf("The number is %d\n", test);
    return 0;
}
```
`compile_commands.json`:
```json
[
    {
        "arguments": [
            "gcc",
            "-c",
            "-I./include",
            "-o",
            "output",
            "main.c"
        ],
        "directory": "/home/seth/Documents/Development/test/c",
        "file": "main.c"
    }
]
```

Entering rename:
![image](https://user-images.githubusercontent.com/19225089/73711369-a3013d80-46d4-11ea-8dd3-2e5d1321be78.png)
Result:
![image](https://user-images.githubusercontent.com/19225089/73711386-adbbd280-46d4-11ea-95b7-27e56c01a739.png)

### Steps to reproduce

1. use `ALERename` on a symbol

### System information

* ccls version: The version in the AUR
* clang version: 9.0.0
* OS: Arch linux
* Editor: Neovim
* Language client (and version): ALE (most up to date)

**Comment by MaskRay** [comment]
This seems like a client issue? coc.nvim and emacs-ccls work fine...
