### ISSUE TITLE
A fatal when building

### ISSUE THREAD

**Issue by BenSYZ** [MaskRay/ccls#567]
### System information
* Ubuntu 18.04
* cmake version 3.10.2
* gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
* GNU Make 4.1
* Clang+LLVM is used prebuilt binaries

* rapidjson-dev/bionic,bionic,now 1.1.0+dfsg2-3 all [installed]
* libstdc++-7-dev/bionic-updates,bionic-security,now 7.4.0-1ubuntu1~18.04.1 amd64 [installed,automatic]
* zlib1g-dev/bionic,now 1:1.2.11.dfsg-0ubuntu2 amd64 [installed]

### Command of build

```sh
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/ben/ccls/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04 -DCMAKE_INSTALL_PREFIX=/home/ben/cc
```

I want to install the ccls to a temporary directory at first. If it was successed, the install to standard path. So I add this parameter `-DCMAKE_INSTALL_PREFIX=/home/ben/cc`.

### Observed behavior

```sh
$ cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/ben/ccls/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04 -DCMAKE_INSTALL_PREFIX=/home/ben/cc
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- RapidJSON found. Headers: /usr/include
fatal: No names found, cannot describe anything.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ben/ccls/Release
```

### Expected behavior
There is a fatal, and I have no idea to solve it. However if I skip the fatal, and `cmake --build Release` directory. There are many warnings, but no error. Then the last line printed on screen is `[100%] Built target ccls`. But there is no ccls in `/home/ben/cc/`.

Please excuse me for my poor English. I'm a newcomer and this is my first time to install program from source.

Thanks a lot!

**Comment by findNextStep** [comment]
it show `[100%] Built target ccls` mean that ccls has compile over
may by you need go to Release dir and install it
```shell
cd Release
make install
```
or you can try `cmake --install build/Debug`(but what i never build by cmake
Please excuse me for my poor English hope you can enjoy ccls

**Comment by BenSYZ** [comment]
> it show `[100%] Built target ccls` mean that ccls has compile over
> may by you need go to Release dir and install it
> 
> ```shell
> cd Release
> make install
> ```
> 
> or you can try `cmake --install build/Debug`(but what i never build by cmake
> Please excuse me for my poor English hope you can enjoy ccls

Thanks a lot! I make it. It seems that I know where I was stuck. I just build it but not install it.

**Comment by exp2ipi** [comment]
So cmake throws a "Fatal" error, but in fact there's no error? 

**This. Is. Ridiculous.**

After a bunch of _actual_ errors due to woefully unclear build instructions, I am supposed to somehow know that this fatal error is ok and I should just ignore it and run make? I've added a note to that effect to the word salad that is the build instructions wiki, hopefully it will help the next poor soul.
