### ISSUE TITLE
ccls can't complete C++ system headers

### ISSUE THREAD

**Issue by CSRaghunandan** [MaskRay/ccls#57]
I remember them working on `cquery`,  but not so in `ccls`. I'm running on Mac OS High Sierra and I installed `ccls` with homebrew using the following command: `brew install ccls --HEAD`

**Comment by MaskRay** [comment]
Please read https://github.com/MaskRay/ccls/wiki/FAQ#some-cc-headers-are-not-recognized

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/issues/58 is more detailed. Mark this as a duplicate.
