### ISSUE TITLE
autocompletion with pointer correction does not replace the dot

### ISSUE THREAD

**Issue by ele828** [MaskRay/ccls#570]
### Expected behavior

When using ccls with coc.nvim in neovim, sometimes we may forget if a variable is a a pointer or not. I notice that ccls will show up auto-completions even if I use dot on a pointer type.

But unfortunately, when insert -> after select a auto-completion, the previous entered dot is still there. It behaves as follows:

```c++
#include <vector>

int main() {
    std::vector<int>* foo;
    foo.->push_back(0);    // extra dot
}
```

The expected behavior should be `foo->push_back()` without a dot.

### Steps to reproduce

1. type a dot after a pointer value
2. select a suggestion from auto-completion list
3. the dot you entered is still there

### System information

* ccls version (`git describe --tags --long`): 
* clang version:  9.0.0
* OS: macOS Mojave
* Editor: nvim
* Language client (and version): coc.nvim

**Comment by ele828** [comment]
A related issue in coc.nvim https://github.com/neoclide/coc.nvim/issues/1396

**Comment by ele828** [comment]
Go through the release note and found out this maybe an issue in coc.nvim.

> With clang>=7, completion items can replace . with -> or replace -> with . The client-side support of additionalTextEdits is required.

**Comment by findNextStep** [comment]
seem that it can be solve by set client.snippetSupport and install coc-snippets
see https://github.com/MaskRay/ccls/wiki/Customization#clientsnippetsupport

example configuration
```json
        "ccls": {
            "command": "ccls",
            "args": [
                "--log-file",
                "/tmp/ccls.log"
            ],
            "filetypes": [
                "c",
                "cpp",
                "objc",
                "objcpp"
            ],
            "rootPatterns": [
                ".ccls-cache",
                ".vim/",
                ".git/",
                "compile_commands.json"
            ],
            "initializationOptions": {
                "cache": {
                    "directory": "./.ccls-cache"
                },
                "compilationDatabaseDirectory": "./build/Debug",
                "client":{
                    "snippetSupport":true
                }
            }
        },

```

**Comment by ele828** [comment]
I've resolved it by writing a coc.nvim extensions. Close this issue for now.
