### ISSUE TITLE
High CPU and RAM Usage during sessions which include Google's fruit

### ISSUE THREAD

**Issue by alexzielenski** [MaskRay/ccls#573]
### Observed behavior

ccls uses consistently 90%+ CPU and climbing amounts of ram. I observed 20GB of ram used before I killed it. Running `ccls -index=<#dir>` on the directory finishes rather quickly, but when running the ccls helper alongside vscode it uses a lot of system resources.

### Expected behavior

Small CPU spike when opening file, eventually declining to nothing.

### Steps to reproduce

I was able to reproduce using one of the example files provided by fruit and included with the brew install:

1. `brew install fruit`
2. `code /usr/local/share/fruit`
3. Open `main.cpp` and make sure ccls is enabled

### System information

* ccls version (`0.20190823.5`): 
* clang version: `Apple clang version 11.0.0` 
* OS: macOS 10.15
* Editor: vscode
* Language client (and version): `vscode-ccls 0.1.28`

**Comment by MaskRay** [comment]
This is a project built with Bazel. `compile_commands.json` might be tricky to generated.

I use this `.ccls` and it seems to work:

```
% cat .ccls 
clang
-Iinclude
```

Indexing the project (`loaded project. Refresh semantic highlight for all working files`) took about 10 seconds on my machine.

I'd suggest attaching a debugger (https://github.com/MaskRay/ccls/wiki/Debugging) to see what ccls is doing if you can still reproduce the problem
