### ISSUE TITLE
Clang 11.0 `indexer.cc:687:51: error: only virtual member functions can be marked 'override'`

### ISSUE THREAD

**Issue by flekystyley** [MaskRay/ccls#575]
## Observed behavior
Happened when installing ccls from latest master branch. I think this problem is not a clang version.

### step
- `ghq get git@github.com:MaskRay/ccls.git`
- `git submodule update --init`
- `cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH= ${MY_LLVM_PATH}`
```
------- Log ---------
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/flekystyley/.ghq/github.com/MaskRay/ccls/Release
```
- `cmake --build Release`
```
------- Log ---------
/Users/flekystyley/.ghq/github.com/MaskRay/ccls/src/indexer.cc:687:51: error: only virtual member functions can be marked 'override'
                            ASTNodeInfo ast_node) override {
```

### resolve
- Change `handleDeclOccurrence` in lines 682 and 684 to`handleDeclOccurence`
- plz check `SS`

### SS
- Problem log
![スクリーンショット 2020-02-16 0 00 10](https://user-images.githubusercontent.com/25461250/74590179-5829e300-504f-11ea-94dd-0eee2430f2c3.png)

- Problem Code (after correction)
![スクリーンショット 2020-02-16 0 06 32](https://user-images.githubusercontent.com/25461250/74590297-82c86b80-5050-11ea-81d8-d54fa2924b8e.png)

- Problem Code (Before correction)
![スクリーンショット 2020-02-16 0 02 43](https://user-images.githubusercontent.com/25461250/74590198-b22aa880-504f-11ea-8e7b-d40627cfb82e.png)

## System information

* ccls version (`0.20190823.5-18-gd9cac2af`): 
* clang version(`Apple clang version 11.0.0 (clang-1100.0.33.12)`): 
* OS(macOS Catalina 10.15.3):

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/commit/86e340caf00b2d337ddb839e646085bf2222be3b

You are using an unreleased LLVM version that is older than llvmorg-10-init-12036-g3b9715cb219. You need to update your LLVM repository.

**Comment by flekystyley** [comment]
okay, thank you
