### ISSUE TITLE
I set `. ccls-cache` under the current project.The jump function will always jump to the file in the `ccls_cache`.

### ISSUE THREAD

**Issue by 3038922** [MaskRay/ccls#578]
I set `. ccls-cache` under the current project.The jump function will always jump to the file in the `ccls_cache`.
![image](https://user-images.githubusercontent.com/33926386/74948572-728d0380-5437-11ea-83fa-be51d27cf06a.png)

How can I ignore some folders?

**Comment by joelhock** [comment]
https://github.com/MaskRay/ccls/issues/184 should prevent this.

from the screenshot, it seems the directory does not have the period in it. and the title and comment has a space between the period and the rest of the directory name.  could that somehow be the issue?
