### ISSUE TITLE
go definition works , but code_complete can't give suggestions on vector. 

### ISSUE THREAD

**Issue by Abbyyan** [MaskRay/ccls#579]
I've create the `compile_commands.json` file. 

and write a `std::vector<int> vc;` and it can go definition to the file `bits/stl_vector.h` , but when i typed `vc.` it can't give code completion suggestions such as `vc.pop_back() ; vc.clear()` . Can you give me some suggestion on whether the problems may occur please? Thanks a lot.

**Comment by findNextStep** [comment]
can you show which OS you use and what you have write in `compile_commands.json`?

**Comment by Abbyyan** [comment]
I'm working on `linux` and the commands in `compile_commands.json` is like 
```shell

        usr/include/c++/4.8.2/x86_64-redhat-linux -I/usr/include/c++/4.8.2/backward -I/usr/local/include/c++/4.8.2 -I/usr/local/include/c++/4.8.2/x86_64-unknown-linux-gnu -I/usr/local/include/c++/4.8.2/backward -DMM_GCC_HIGH_VER -DLINUX -Dlinux -D__STDC_FORMAT_MACROS -D__BLADE_PROFILE_DEBUG -DUSE_COMM2 -iquote . -iquote /home/ww/workspace/local_linux-fastbuild/genfiles -Iantm/mmr/social  -DLINUX -D_PTHREADS -DTIXML_USE_STL -D_NEW_LIC -D_GNU_SOURCE -D_REENTRANT -DMM_BUILD_LOGIC_SVR -D__MMDEBUG__ -DNEED_XSS -DNEED_FILTER -std=c++11 -Wno-builtin-macro-redefined -D__DATE__=\\\"redacted\\\" -D__TIMESTAMP__=\\\"redacted\\\" -D__TIME__=\\\"redacted\\\" -c antm/mmr/social/main.cpp -o antm/mmr/social/main.pic.o 
```
I'm using coc-nvim and the settings  are as follows
```json
{
    "languageserver": {
        "ccls": {
            "command": "ccls",
            "args": ["--log-file=/tmp/ccls.log"],
            "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
            "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
            "initializationOptions": {
                "cache": {
                    "directory": ".ccls-cache"
                },
                "clang": {
                    "resourceDir": "$CODE_COMPLETE_CLANG_LIB_PATH"
                },
                "index": {
                    "threads": 40 ,
		    "trackDependency": 1 ,
		    "initialBlacklist": ["."]
                }
            }
        }
    },
    "suggest.triggerAfterInsertEnter": true,
    "suggest.noselect": false,
    "suggest.enablePreview": true,
    "suggest.minTriggerInputLength": 2,
    "suggest.acceptSuggestionOnCommitCharacter": true
}
```

I've find in some file that may be the setting `"ccls.clang.resourceDir"` may be the reason. When i delete this setting, the problem occurs( Can go definition to the std::vector file , but when input `std::vector<int> vec1; vec1. `, no code completion occurs.  Originally  there should be some functions like `pop ()  ` etc.). But only if i set the settings , there are still some files can't get the completion. It's weired and can you give me some suggestions please? Thanks a lot.

**Comment by Abbyyan** [comment]
I've tried it in vscode with the same settings, the editor can give suggestions that variable `vec` is a vector , but it can't give suggestions about the properties such as `push_back()`, `clear()` and so on. 
![image](https://user-images.githubusercontent.com/12140508/75234350-69b07f00-57f5-11ea-962e-eb076f0a36bc.png)
![image](https://user-images.githubusercontent.com/12140508/75234405-88af1100-57f5-11ea-9123-c4d4116eea6d.png)

**Comment by findNextStep** [comment]
I don`t know if set evnironment arg in there will work or not. may be you need to try write the answer of `echo $CODE_COMPLETE_CLANG_LIB_PATH ` in to the ccls.clang.resourceDir

**Comment by Abbyyan** [comment]
Oh, in my coc-settings.json, I've replace the `$CODE_COMPLETE_CLANG_LIB_PATH` with `/home/abby/tools/clang/lib/clang/11.0.0` where my clang lib locate. (Just a mock )

**Comment by Abbyyan** [comment]
It‘s really wired that i set `"ccls.clang.resourceDir": "/home/abbytan/clang/lib/clang/11.0.0", and `reopen the vscode. It works. it seems like just because i did't reopen the vscode-ssh extension totally. Thanks for your help .
