### ISSUE TITLE
ccls can't find subproject header

### ISSUE THREAD

**Issue by sleepyeye** [MaskRay/ccls#58]
Hi. I'm trying to configure ccls for my C++ project.
It works really smooths and it is really fast.
However ccls can't detect some header files and I can't figure out that this is caused by my cmake config 
or wrong behavior of ccls.

Problems

- ccls cannot complete header file location. (Only cannot find subporject's header files)
- ccls cannot complete class methods  which is defined in subproject(I guess this is related to previous issue)

The problem is that ccls failed to detect headers in external subporject in my project. I'm using two subproject currently (**fmt** and **eigen**). They are just git submodule from another github repo. 
For instance let's say I want to use include `fmt/core.h` in my project which is located in **fmt** project.
If I type `#include <fm` ccls does not suggest any header file candidates in **fmt** project.

Emacs config
```lisp
(use-package ccls
  :init
  (progn
    (spacemacs|add-company-backends :backends company-lsp :modes c-mode-common)
    (spacemacs/add-to-hooks #'lsp-ccls-enable '(c-mode-hook c++-mode-hook))
    (dolist (mode '(c-mode c++-mode))
      (spacemacs/declare-prefix-for-mode mode "ml" "lsp")
      (spacemacs/declare-prefix-for-mode mode "mh" "hierarchy")
      (evil-leader/set-key-for-mode mode
        "." #'lsp-ui-peek-find-definitions
        "," #'lsp-ui-peek-find-references
        "[" #'lsp-ui-peek-jump-backward
        "]" #'lsp-ui-peek-jump-forward))
    )
  :config
  (setq company-transformers nil
        company-lsp-async t
        company-lsp-cache-candidates nil)
  (setq ccls-executable "/usr/local/bin/ccls")
  )
```

Project setup
**PROJECT_ROOT/CMakeLists.txt**
```cmake

...

add_subdirectory(extern)

...

target_link_libraries(${PROJECT_NAME}
  PUBLIC
  fmt::fmt
  eigen::eigen
  )


```

**extern/CMakeLists.txt**
```cmake
set(EXTERN_MODULE_DIR "${PROJECT_SOURCE_DIR}/extern")

# Add fmt
add_subdirectory(fmt)

# Add Eigen
set(EIGEN_INCLUDE_DIR "${EXTERN_MODULE_DIR}/eigen")
add_library(eigen INTERFACE)
target_include_directories(eigen INTERFACE
  $<INSTALL_INTERFACE:include/Eigen>
  $<BUILD_INTERFACE:${EIGEN_INCLUDE_DIR}>
  )
add_library(eigen::eigen ALIAS eigen)
```

**Proejct structure**
```
.
├── build
├── cmake
├── extern
│   ├── eigen
│   │   ├── Eigen
│   │   ├── bench
│   │   ├── blas
│   │   ├── cmake
│   │   ├── debug
│   │   ├── demos
│   │   ├── doc
│   │   ├── failtest
│   │   ├── lapack
│   │   ├── scripts
│   │   ├── test
│   │   └── unsupported
│   └── fmt
│       ├── doc
│       ├── include
│       ├── src
│       ├── support
│       └── test
├── include
│   ├── rfwr
│   └── test
└── src

```

**Comment by MaskRay** [comment]
Please read https://github.com/MaskRay/ccls/wiki/FAQ#some-cc-headers-are-not-recognized

**Comment by MaskRay** [comment]
https://github.com/llvm-mirror/clang/tree/master/include/clang/Lex/HeaderSearchOptions.h#L31

* `-iquote` => `clang::frontend::Quoted` => `config->quote_dirs`
* `-I` => `clang::frontend::Angled` => `config->angle_dirs` & `config->quote_dirs
* `-isystem` => `clang::frontend::System` => `config->angle_dirs`

**Comment by sleepyeye** [comment]
Thanks for your advise. However it turns out there are no problems in both **ccls** and my **CMakeLists.txt** script.
The problem is in **compile_commands.json**. 
I couldn't realize the source of problem since I was writing header file.

In the json file, compile commands for **cpp** are set right. 
For instance, compile commands for **test.cpp** in my project looks like this.
```json
  "directory": "/home/workspace/rfwr/build",
  "command": "/usr/bin/c++   -I/home/workspace/rfwr/include -isystem /usr/include/OpenEXR -I/home/workspace/rfwr/extern/fmt/include -I/home/workspace/rfwr/extern/eigen    -std=gnu++14 -o CMakeFiles/rfwr-test.dir/src/test.cpp.o -c /home/workspace/rfwr/src/test.cpp",
  "file": "/home/workspace/rfwr/src/test.cpp"
```

However there are no compile commands for header files. For example, I expected something like this.
```json
  "directory": "/home/workspace/rfwr/build",
  "command": "/usr/bin/c++   -I/home/workspace/rfwr/include -isystem /usr/include/OpenEXR -I/home/workspace/rfwr/extern/fmt/include -I/home/workspace/rfwr/extern/eigen  ",
  "file": "/home/workspace/rfwr/include/rfwr/rfwr.h"
```
There is no compile commands section for header files which seems reasonable. Unfortunately it seems like CMake does not provide any option for these. (Compile command for headers? Pretty weird)

But if **ccls** can support me in header file, it would make me much easier to write my headers. Do you have any hints for this?

**Comment by MaskRay** [comment]
ccls indexes only one version for a file. A header files is usually intended for being included, not being compiled on its own. I have decided that a header should not be indexed standalone, it is only indexed when it has been included by a `compile_commands.json` entry.

This has a limitation. When you create a new header file, it will not be indexed. But I consider to be acceptable as indexing it may cause a worse effect: when the header is not side-by-side with the source, its compile command line will be difficult to decide if it is compiled on its own.

**Comment by amosbird** [comment]
> When you create a new header file, it will not be indexed. 

hmm it's indexed correctly here.

**Comment by nickenchev** [comment]
> ccls indexes only one version for a file. (Macros can have multiple versions, and I will explore multiple versions of templates. This is one part where ccls is superior to its alternative). A header file is usually intended for being included, not being compiled on its own. I have decided that a header should not be indexed standalone, it is only indexed when it has been included by a `compile_commands.json` entry.
> 
> This has a limitation. When you create a new header file, it will not be indexed. But I consider to be acceptable as indexing it may cause a worse effect: when the header is not side-by-side with the source, its compile command line will be difficult to decide if it is compiled on its own. A file can also be included only first but then gets its own `compile_commands.json` entry (`#include "bin_elf.c"`). I haven't done much experiment on this but @amosbird reported that this seems ok.

Why does it matter whether or not a header file is intended to be compiled or not? It is intended to be edited, and in order to get completions, code navigation and any other editing features, it needs just the same contextual information as a compilation unit. In the end, we're not talking about building the project, but providing tooling while editing. I don't use ccls to build my project, I use it to get some extra features inside my editor of choice. So using this reasoning, about half my project doesn't get indexed?

**Comment by MaskRay** [comment]
@nickenchev To get completion/diagnostics, you need to make sure the header file is compilable on its own, i.e. if you expect a macro to be defined before every instance of its inclusion, that is unacceptable. As a result, you may lose some completion/diagnostics.

```
#define FOO 1
#include "a.h"
```

There are heuristics compiling a header with flags similar to its nearby files.

**Comment by nickenchev** [comment]
@MaskRay to be clear since I did click reply on your last comment, I wasn't referring to a macro scenario, I avoid macros like the plague. Was strictly about headers not being indexed and other issues I've generally had working in my header files.
