### ISSUE TITLE
ccls is failing to store a file from a sibling directory to the current root

### ISSUE THREAD

**Issue by lanza** [MaskRay/ccls#580]
Given a project layout made via
```
git clone https://github.com/llvm/llvm-project
cd llvm-project
cmake -G Ninja -Sllvm -Bbuild/Debug -DLLVM_ENABLE_PROJECTS='clang'
cd clang
ln -s ../build/Debug/compile_commands.json .
```

and a rootPattern of `compile_commands.json` (thus ccls detects the root as `llvm-project/clang`) and a cache directory of `./.ccls-cache` (e.g. `llvm-project/llvm/.ccls-cache`) I consistently get this type of error:

```
utils.cc:173 E failed to write to /Users/lanza/Projects/llvm-project/clang/.ccls-cache/@Users@lanza@Projects@llvm-project@llvm/lib@Support@BlockFrequency.cpp No such file or directory
```

ccls is attempting to store files at `Users/lanza/Projects/llvm-project/clang/.ccls-cache/@Users@lanza@Projects@llvm-project@llvm/` though ccls has never made the directory. Simply `mkdir thedir`ing fixes the problem.

Also, while I'm at it, what's your personal set up for using ccls with llvm? I haven't found a configuration that doesn't surprise me with issues or necessary reindexing more often than I like.

**Comment by MaskRay** [comment]
I don't recommend using a root pattern of `compile_commands.json`, because the client may locate `Debug/compile_commands.json` when visiting `Debug/include/llvm/Config/config.h`.

```
cd llvm-project
cmake -Hllvm -BDebug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=on # other options
ln -s Debug/compile_commands.json .
touch .ccls-root
```

Configure the client to use `.ccls-root`.


(Slightly out of date: https://github.com/MaskRay/Config/wiki#llvm)

**Comment by lanza** [comment]
Thanks for the setup! However, this doesn't solve the above fundamental problem. With your setup I still can hit, e.g.,

`16:07:13                     utils.cc:173 E failed to write to /Users/lanza/Projects/llvm-project/clang/.ccls-cache/@@Users@lanza@Projects@llvm-project@clang/@Applications@Xcode.app@Contents@Developer@Platforms@MacOSX.platform@Developer@SDKs@MacOSX.sdk@usr@include@_types@_wctrans_t.h No such file or directory
`
