### ISSUE TITLE
Phantom Errors

### ISSUE THREAD

**Issue by genericlastname** [MaskRay/ccls#582]
### Observed behavior

In my file `large_math.cc` I have this function:
```cpp
// from large_math.h
#include <iostream>
#include <string>
using namespace std;
...
void reverse_str(string& s) {
    int n = s.length();

    for (int i = 0; i < n/2; i++) {
        char temp = s[i];
        s[i] = s[n-i-1];
        s[n-i-1] = temp;
    }
}
```

The lines inside the for loop show up as having errors. The error is:
`[ccls] type 'std::string' (aka 'basic_string<char>') does not provide a subscript operator`

In addition I get an error when calling `reverse_str`:
`[ccls] call to 'reverse_str' is ambiguous`

My `.ccls` file is empty.

None of these "errors" actually show up when the project is compiled.

### Expected behavior

For none of these false errors to show up.

### System information

* ccls version (`git describe --tags --long`): 0.20190823.5-1 (from Fedora 31 repos)
* clang version: 9.0.1
* OS: Fedora 31
* Editor: Neovim
* Language client (and version): coc.nvim v0.0.75-10-gbe83214

**Comment by MaskRay** [comment]
Can't reproduce at HEAD...

Mind testing at HEAD? :)
