### ISSUE TITLE
If the same file opened multiple times, the first close will close it

### ISSUE THREAD

**Issue by geza-herman** [MaskRay/ccls#584]
### Observed behavior

If the same file opened multiple times, the first close will close it. This can be reproduced for example, from emacs. If you use magit + ediff to diff a file, it will open the same file multiple times. After closing ediff, LSP will print this into the echo area:

```
LSP :: <filename> is not opened
```

### Expected behavior

I think that ccls should consider open/close as a pair, so it should really close the file if there are as many close calls as open calls.

(Note, I'm not sure whether this is a ccls or an emacs-lsp bug. I mean, this issue could be fixed in ccls like I described here, or in emacs-lsp so it doesn't open the same file multiple times. But, if multiple clients can use ccls, it makes sense to handle this case is ccls) 

### Steps to reproduce

Setup lsp + ccls and magit in emacs. Go into some git repository, open a file. Observe that lsp works. Now, to go magit log, and press e to ediff the file. Now quit from ediff, and observe that lsp doesn't work anymore.

Here's a screencast of the problem:
![output](https://user-images.githubusercontent.com/27892988/75762817-973c8180-5d3b-11ea-8a29-67c3bb9722f8.gif)

I could fix this issue by this patch:
```
diff -r /home/geza/tmp/ccls-0.20190823.5/src/working_files.cc /home/geza/source/ccls/ccls-0.20190823.5/src/working_files.cc
379a380
> 
387a389
>   wf->refCount++;
432c434,440
<   files.erase(path);
---
>   auto &wf = files[path];
>   if (wf) {
>     wf->refCount--;
>     if (wf->refCount<=0) {
>       files.erase(path);
>     }
>   }
diff -r /home/geza/tmp/ccls-0.20190823.5/src/working_files.hh /home/geza/source/ccls/ccls-0.20190823.5/src/working_files.hh
17a18
>   int refCount = 0;
```
### System information

* ccls version (`git describe --tags --long`):  0.20190823.5-10-g86e340ca
* clang version: 9 
* OS: Linux
* Editor: emacs
* Language client (and version): emacs-ccls

**Comment by MaskRay** [comment]
Thanks for reporting. While I am an Emacs user and use magit blame sometimes, I am far from a power user.
In any case, I think ccls does the correct thing here. It closes the working file upon `textDocument/didClose`.

If any reference counting is desired, I think the proper place is in the client side (lsp-mode).
