### ISSUE TITLE
Unrecognized Arguments in `compile_commands.json` by clang of Different Version

### ISSUE THREAD

**Issue by coppercash** [MaskRay/ccls#586]
#### A. ccls Refused to Work at All

Found this in log.

```
[Error  - 8:12:03 AM] Request textDocument/defination failed.
  Message: not indexed
  Code: -32600
```
#### B. `.ccls-cache` was Empty

After I ran `ccls --index="."`, there were only two empty folders in `.ccls-cache`.

#### C. No Error in Indexing Log

I saw only `pipeline.cc:340 I parse path/to/my/src/file.m`.
No `pipeline.cc:378 I store index for path/to/my/src/file.m`.

#### D. Could not Exclude Some Arguments with `excludArgs`

I tried  `ccls --index="." --init="{\"clang\": { \"excludeArgs\": [ \"-index-store-path\", \"-fmodules\", \"-gmodules\" ] } }"`.
It worked well for `-fmodules` and `-gmodules`, but not for `-index-store-path` (coz' of its suffixing value).

### Expected behavior

* More information if anything goes wrong when indexing.
* Capability to exclude arguments suffixed by values.

### Steps to reproduce

1. Generate `compile_commands.json` with Xcode 11+ & xcpretty.
2. Run `ccls --index="."` in the project root directory.

### System information

* ccls version: `ccls: stable 0.20190823.5 (bottled), HEAD` (from brew)
* clang version: `Apple clang version 11.0.0 (clang-1100.0.33.16)`
* OS: `macOS Catalina 10.15.3 (19D76)`
* Editor: nvim
* Language client (and version): `coc.nvim@0138243`

### Solution

After investigated following issues / posts:

* [Figuring out why indexing gives up](https://github.com/MaskRay/ccls/issues/154)
* [Receiving "code -32600" / message "not indexed"](https://github.com/MaskRay/ccls/issues/242)
* ["LLVM ERROR: unknown module format" error](https://github.com/MaskRay/ccls/issues/330)
* [included string.h but still see "implicitly declaring library function 'memcpy'"](https://github.com/MaskRay/ccls/issues/512#issuecomment-545575369)
* [Can ccls be compiled with Clang/LLVM shared libs instead of static?](https://github.com/MaskRay/ccls/issues/355)
* [ccls c++ header completion on osx](https://github.com/MaskRay/ccls/issues/191)
* [Remove unsupported `index-store-path` argument from clang commands](https://github.com/facebook/infer/commit/17cc5ec7bec1ef0d10fc3461f089384ee7e51c7f)

I found it was the argument `-index-store-path` causing the trouble.
The clang generated the `compile_commands.json` was of version 11, which is newer than the clang used by ccls.

I tried to exclude it, but failed.
By investigating the source code, I found arguments suffixed by values can not be excluded (correct me if I am wrong).
And the whole argument looks like `-index-store-path /path/to/some/store/xcode/uses`.

Then I tried to build ccls with clang 11, but failed
– I couldn't find llvm released with clang 11.

My current solution is to pass some arguments to `xcodebuild` so that it stops outputting arguments that clang 9 cannot recognize.

The makefile I am currently using:

```makefile
cmpl_cmds:
	xcodebuild build \
		-workspace MyAwsome.xcworkspace \
		-scheme MyAwsome \
		COMPILER_INDEX_STORE_ENABLE=NO \
		CLANG_INDEX_STORE_ENABLE=NO \
		SWIFT_INDEX_STORE_ENABLE=NO \
		MTL_ENABLE_INDEX_STORE=NO \
		CLANG_DEBUG_MODULES=NO \
		| tee xcodebuild.log \
		| bundle exec xcpretty \
		-r json-compilation-database \
		--output compile_commands.json

index:
	ccls \
		--index="." \
		-v=1
```

`*_INDEX_STORE_ENABLE=NO` are to get rid of `-index-store-path`.

`CLANG_DEBUG_MODULES=NO` is to get rid of `-gmodules`. BTW, the error caused by `-gmodules` could be seen in the indexing log.

Other articles may also help:

* [ccls 和 vscode 一种在vscode以外的c++方案](https://zhuanlan.zhihu.com/p/84876003)
* [Xcode Build Settings](https://xcodebuildsettings.com/)

**Comment by coppercash** [comment]
Cos' I have found the solution to my issue, there is no need to leave it open.
I just wanna post it here, so that it could help poeple who also encounter this.

**Comment by ingjieye** [comment]
Thanks you!!

**Comment by urev** [comment]
Thank you.

```
-mabi=lp64
```

This option can make `ccls` fail to index too.
