### ISSUE TITLE
`textDocument/signatureHelp` should not hint the underlying function for a function-like macro

### ISSUE THREAD

**Issue by aganm** [MaskRay/ccls#588]
I'm using coc-nvim with coc-ccls extension in vim.

Say I have a function
`void my_function(int x, const char *xstr);`
and a macro
`#define my_macro(x) my_function(x, #x)`

When I type my_macro, I expect the intellisense to show me the parameters for my_macro, but the intellisense shows me information about what is behind the macro rather than the macro itself which is not helpful. If I type `my_macro(` , ccls powered intellisense shows `my_function(int x, const char *xstr)`.

Does someone know what's wrong? Is that normal ccls behaviour?

**Comment by findNextStep** [comment]
in my vim it work fine
![image](https://user-images.githubusercontent.com/26270464/76693822-6991f980-66a6-11ea-8577-26b338d4c27d.png)
![image](https://user-images.githubusercontent.com/26270464/76693834-7adb0600-66a6-11ea-91a3-a554740f518e.png)

here is my config in coc, i have no install the coc-ccls
```json
{
            "command": "ccls",
            "args": [
                "--log-file",
                "/tmp/ccls.log"
            ],
            "filetypes": [
                "c",
                "cpp",
                "objc",
                "objcpp"
            ],
            "rootPatterns": [
                ".ccls-cache",
                ".vim/",
                ".git/",
                "compile_commands.json"
            ],
            "initializationOptions": {
                "cache": {
                    "directory": "./.ccls-cache"
                },
                "compilationDatabaseDirectory": "./build/Debug",
                "highlight": {
                    "lsRanges": true
                },
                "index": {
                    "thread": 12
                },
                "clang": {
                    "extraArgs": [
                        "-isystem",
                        "/usr/local/opt/llvm/include/c++/v1",
                        "-Wold-style-cast"
                    ],
                    "resourceDir": "/usr/local/opt/llvm/lib/clang/9.0.1"
                },
                "completion": {
                    "placeholder": true,
                    "caseSensitivity": 1
                },
                "client": {
                    "snippetSupport": true
                }
            }
        }
```
may be you can try `"client": { "snippetSupport": true}` in CocConfig

**Comment by aganm** [comment]
@findNextStep What if you keep typing that opening parentheses? I get the proper suggestion in my autocompletion list until I type that parentheses.
![GIF](https://user-images.githubusercontent.com/20380758/76695090-34a78780-6651-11ea-83c1-6adc86286c18.gif)

ccls config:
       ` "ccls": {                                                                                                                    "command": "ccls",                                                                                                   "filetypes": ["c", "cpp", "objc", "objcpp"],                                                                         "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],                                        "initializationOptions": {                                                                                                   "cache": {                                                                                                                   "directory": "/tmp/ccls"                                                   +                                 },                                                                                 +                                 "client": {                                                                        +                                         "snippetSupport": true                                                                                       }                                                                                                            }                                                                                                            }     
`

**Comment by findNextStep** [comment]
Oh...I misunderstanding you...
I not enable intellisense yet.... sorry for noisy

**Comment by aganm** [comment]
Hi! Just bumping to ask if someone would know anything about solving this issue.

**Comment by aganm** [comment]
Now I think this isn't an issue with ccls. Might be on clang's side.
