### ISSUE TITLE
Will ccls reindex the file after `compile_commands.json` regenerate? 

### ISSUE THREAD

**Issue by Abbyyan** [MaskRay/ccls#589]
I'm using ccls and because my dependency changed frequently , the `compile_commands.json` used in ccls was regenerated frequently. But i find ccls won't reread the `compile_commands.json` , so there usually has some dependencies can't be found. Is there any method that let ccls reread new `compile_commands.json` except reopen the file please? Thanks a lot.  @MaskRay

**Comment by findNextStep** [comment]
if you use vscode with ccls you can try ccls:reload index after you change compile_commands.json
![image](https://user-images.githubusercontent.com/26270464/76746471-8582c180-67b2-11ea-9d70-b824a318366f.png)

**Comment by Abbyyan** [comment]
Got it. Thanks a lot !
