### ISSUE TITLE
Can't find Clang::Clang with releases.llvm.org LLVM-6.0.1-win64.exe

### ISSUE THREAD

**Issue by dschaefer** [MaskRay/ccls#59]
I'm on Windows using g++ and tools from scoop. CMake fails finding the Clang library. I tried again with the MSVC tools and it failed there also.

$ cmake -H. -BRelease -G Ninja
-- The CXX compiler identification is GNU 8.1.0
-- Check for working CXX compiler: C:/QNX/scoop/apps/gcc/current/bin/c++.exe
-- Check for working CXX compiler: C:/QNX/scoop/apps/gcc/current/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Using downloaded Clang
-- Downloading Clang 6.0.1 (https://releases.llvm.org/6.0.1/LLVM-6.0.1-win64.exe) ...
-- 7-Zip found in PATH
-- Extracting downloaded Clang with 7-Zip ...
-- Could NOT find Clang (missing: Clang_LIBRARY LLVM_INCLUDE_DIR LLVM_BUILD_INCLUDE_DIR) (found suitable version "6.0.1", minimum required is "6.0.0")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Configuring done
CMake Error at CMakeLists.txt:18 (add_executable):
  Target "ccls" links to target "Clang::Clang" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

**Comment by innerout** [comment]
Do you have clang installed?

**Comment by dschaefer** [comment]
No. Why do I need clang?

**Comment by MaskRay** [comment]
* `Clang_LIBRARY` => `libclangIndex.{so,a}`
* `Clang_INCLUDE_DIR` => `llvm/tools/clang/include`
* `Clang_EXECUTABLE` => `clang`, `clang -print-resource-dir` is used to get the default `-resource-dir` path (e.g. `xxx/lib/clang/8.0.0`). You should be able to find `include/stddef.h` in it.

**Comment by dschaefer** [comment]
Ok, I do have the clang source since I also build my own clangd.

**Comment by MaskRay** [comment]
BTW, there are some screenshots/screencasts in the two wiki pages:

https://github.com/MaskRay/ccls/wiki/LanguageClient-neovim#custom-cross-references
https://github.com/MaskRay/ccls/wiki/Emacs

Would like to know how CDT handles these :)

**Comment by MaskRay** [comment]
Thanks to Riatre for contributing the msys2 build instruction

https://github.com/MaskRay/ccls/wiki/Build#windows
