### ISSUE TITLE
Issuing $ccls/reload manually in nvim w/ coc.nvim

### ISSUE THREAD

**Issue by randrej** [MaskRay/ccls#591]
This is not a bug per se, but I can't seem to find a way to manually reload ccls or otherwise force it to reindex. I'm using `neovim 0.4.3` with `coc.nvim`. While working on my C/C++ projects, I frequently check out other branches of code in git, and I need a way to reindex. Currently, I have to delete the `.ccls-cache` folder and restart neovim.

Coc should be able to send an arbitrary command to a language server like so:

```vim
:call CocAction('runCommand', '$ccls/reload')
```

But this only yields:

```
[coc.nvim] Command: $ccls/reload not found
```

It's mentioned that it's a notification in [the FAQ](https://github.com/MaskRay/ccls/wiki/FAQ#reload), and I can't find a way to issue it manually from neovim. I guess issuing `workspace/didChangeConfiguration` would work too, but I don't know how to do that either.

Does anyone here use coc.nvim with ccls? Do you know how to do this? Thanks!

**Comment by MaskRay** [comment]
`:call CocAction('runCommand', '$ccls/reload')` should work. It seems that coc.nvim does not allow a custom notification. Can you report an issue there?
