### ISSUE TITLE
The .gitignore does not match build instructions

### ISSUE THREAD

**Issue by php1ic** [MaskRay/ccls#594]
### Observed behavior

Following the [build instructions](https://github.com/MaskRay/ccls/wiki/Build) does not leave the repo in a clean state.

### Expected behavior

A build directory named the same as in the instructions should be ignored by git.

### Steps to reproduce

1. Follow the [build instructions](https://github.com/MaskRay/ccls/wiki/Build) to create a Release build.

### System information

* ccls version (`git describe --tags --long`): 0.20190823.5-19-g73e8a224
* clang version: Any 
* OS: Any
* Editor: n/a
* Language client (and version): n/a

**Comment by MaskRay** [comment]
Fixed by db12223081767fac2826512521bdeb61b6c01e88 (use a .gitignore whitelist)
