### ISSUE TITLE
ccls reindex every time when there are soft links.

### ISSUE THREAD

**Issue by xiaobinshe** [MaskRay/ccls#597]
### Observed behavior

I'm using ccls with coc.nvim, and I encountered a problem, ccls reindex some cpp files every time I open nvim. Those cpp files are generated by bazel (https://bazel.build), bazel will generated some symbolic  links in the root working directory, somethings like:

bazel-bin@  bazel-genfiles@  bazel-project_name@  bazel-out@  bazel-testlogs@

the actual directories are placed in the .cache/bazel directory in the home directory.

And it seems that ccls reindex these files every time I open nvim.

Below are the output in coc.nvim:

15:17:44 ccls initialize.cc:271 I initialize in directory /home/xxxxxxxx with uri file:///home/xxxxxx
15:17:44 ccls initialize.cc:294 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":"/home/ss/.cache/ccls" ,"format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldi ngRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":[],"pathMappings":[],"resourceDir":"" },"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completio n":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[" .h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100,"placeholder":true},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[] },"highlight":{"largeFileSize":2097152,"lsRanges":true,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initia lWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parameter sInDeclarations":true,"threads":4,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"so rt":true},"xref":{"maxNum":2000}}
15:17:44 ccls initialize.cc:326 I use -resource-dir=/home/ss/devel/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04/lib/clang/9.0.0
15:17:44 ccls initialize.cc:359 I workspace folder: /home/ss/devel/xxxxx
15:17:44 ccls project.cc:284 I use /home/ss/devel/xxxxx/.ccls: clang++ %cpp -std=c++11 %c %cpp -pthread -fPIC -Wall -I . -I /home/ss/devel/incl1 -I /home/ss/devel/incl2 -I /home/ss/.cache/bazel/_bazel_ss/f5a6ca0b670378ceeec0ae9e162cdaaf/execroot/xxxxx/bazel-out/k8-dbg/genfiles/ - I /home/ss/.cache/bazel/_bazel_ss/f5a6ca0b670378ceeec0ae9e162cdaaf/external/xxxx/src/ -I /home/ss/.cache/bazel/_bazel_ss/f5a6ca0b670378ceeec0ae9e162cdaaf/external/com_google_pro tobuf/src/ -I /home/ss/devel/incl3 -I /home/ss/devel/incl4 -I /home/ss/devel/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04/incl ude/ -I /usr/include/c++/5.4.0
15:17:44 ccls initialize.cc:384 I start 4 indexers
15:17:44 ccls initialize.cc:392 I dispatch initial index requests
15:17:44 preamble sema_manager.cc:735 I create session for /home/ss/devel/xxxx.cpp
15:17:44 indexer3 pipeline.cc:290 I load cache for /home/ss/devel/xxxx.cpp
15:17:44 indexer1 pipeline.cc:290 I load cache for /home/ss/devel/xxxx2.cpp
...
...
...
15:17:47 indexer2 pipeline.cc:340 I parse /home/ss/devel/prxxxxx.pb.cc
15:17:47 indexer2 pipeline.cc:378 I store index for /home/ss/.cache/bazel/_bazel_ss/f5a6ca0b670378ceeec0ae9e162cdaaf/external/xxxxxx.pb.cc (delta: 0)
...
...
lots of parse and store messages

please notice that there are some logs like

15:17:47 indexer2 pipeline.cc:340 I parse /home/ss/devel/bazel-xxxxx/external/prxxxxx.pb.cc
15:17:47 indexer2 pipeline.cc:378 I store index for /home/ss/.cache/bazel/_bazel_ss/f5a6ca0b670378ceeec0ae9e162cdaaf/external/xxxxxx.pb.cc (delta: 0)

The above two files are actually the same file.
These files are reindex every time.

Below is my coc config:

1 {                                                                                                                                                                            
2     "languageserver": {                                                                                                                                                      
3         "ccls": {                                                                                                                                                            
4             "command": "ccls",                                                                                                                                               
5             "filetypes": [                                                                                                                                                   
6                 "c",                                                                                                                                                         
7                 "cpp",                                                                                                                                                       
8                 "objc",                                                                                                                                                      
9                 "objcpp"                                                                                                                                                     
10 ],
11 "rootPatterns": [
12 ".ccls",
13 "compile_commands.json",
14 ".vim/",
15 ".git/",
16 ".hg/"
17 ],
18 "initializationOptions": {
19 "cache": {
20 "directory": "/home/ss/.cache/ccls"
21 },
22 "index": {"threads": 4},
23 "highlight": { "lsRanges" : true }
24 }
25 }
26 }
27 }

and the .ccls file

clang++
%cpp -std=c++11
%c %cpp -pthread
-fPIC
-Wall
-I
.
-I
/home/ss/devel/project1
-I
/home/ss/devel/project2
-I
/home/ss/.cache/bazel/_bazel_ss/f5a6ca0b670378ceeec0ae9e162cdaaf/execroot/project/bazel-out/k8-dbg/genfiles/
-I
/home/ss/.cache/bazel/_bazel_ss/f5a6ca0b670378ceeec0ae9e162cdaaf/external/3rdproject/src/
-I
/home/ss/.cache/bazel/_bazel_ss/f5a6ca0b670378ceeec0ae9e162cdaaf/external/com_google_protobuf/src/
-I
/home/ss/devel/project/3rd/etcd/
-I
/home/ss/devel/project/3rd/rocksdb/include/
-I
/home/ss/devel/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04/include/
-I
/usr/include/c++/5.4.0

The reindex will cost lots of cpu and time everytime I open nvim.

### Expected behavior

These files are not reindexed everytime I open nvim.

### Steps to reproduce

Using bazel to compile a project, and add using ccls to generate the index.

### System information

* ccls version (`git describe --tags --long`): 

 ~  ccls --version                                                                                                                                           
ccls version 0.20190314.1-0-ga41b976a
clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)

I installed ccls using snap in ubuntu.

* clang version: 
~  clang -v                                                                                                                                                 
clang version 9.0.0 (https://github.com/llvm-mirror/llvm c62b24f070c9a4bb1a76409e623042a740cac4cd)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/xiaobinshe/devel/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

* OS: 

Ubuntu 16.04

* Editor: 

 ~  vim -v                                                                                                                                                    
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info

* Language client (and version): 

coc.nvim version: 0.0.77-322876fe15

**Comment by xiaobinshe** [comment]
And one interesting thing is that that I have to add the .cache/bazel directory in the .ccls file, otherwise the symbols in those files can be used.

**Comment by MaskRay** [comment]
Bazel is quite complex. Please reduce to a minimal reproduce to make the issue easier to investigate.

I suspect https://github.com/MaskRay/ccls/pull/661 has fixed this.
