### ISSUE TITLE
a warning after I upgrade lsp-mode

### ISSUE THREAD

**Issue by zhuxyu** [MaskRay/ccls#599]
### warning
there is a warning after I upgrade lsp-mode.
![图片](https://user-images.githubusercontent.com/42087435/77431576-d7ad8d80-6e17-11ea-96f3-4bf80f1208c2.png)

### System information
* ccls version (`git describe --tags --long`): 
![图片](https://user-images.githubusercontent.com/42087435/77432565-33c4e180-6e19-11ea-9517-2bb9ce650de2.png)
* clang version: 
![图片](https://user-images.githubusercontent.com/42087435/77431779-25c29100-6e18-11ea-8486-1864980925a3.png)
* lsp-mode version: lsp-mode-6.0 
![图片](https://user-images.githubusercontent.com/42087435/77432535-27408900-6e19-11ea-88cb-e1ca957caf8b.png)

* OS: Linux
* Editor: Emacs
* Language client (and version): C++

### Steps to solve

1. Modified ccls-common.el( replace **(require 'lsp with require 'lsp-mode)**)
2. recompile ccls-common.el
3. restart emacs.

![Uploading 图片.png…]()
There is a warning in the 27 lines.

**Comment by MaskRay** [comment]
Forgot to close

0bf23a2c67a14200f4936defb001583acdc5ec23
