### ISSUE TITLE
How to do a basic run?

### ISSUE THREAD

**Issue by mehulmpt** [MaskRay/ccls#602]
Sorry, this question might be super lame, but I would really appreciate any help. I've been trying to set up this for a long time with docker and my custom solution, and now when it's done, when I run `ccls` in `alpine:edge` OS, nothing happens. It just stays there no matter what I enter. When I do enter two newlines (enter key), it terminates and returns back to the shell.

How do I get the ccls server to speak something?

**Comment by MaskRay** [comment]
ccls (language server) communicates with a language client via stdin/stdout. When you run ccls in a terminal, its stdin/stdout is connected to the terminal. You are expected to type JSON-RPC messages. This is probably not really an intended use case.

If you have a language client, you can trace the traffic via something like strace.

**Comment by mehulmpt** [comment]
Hi @MaskRay! Really appreciate your time. However, I'm talking about this:

<img width="1025" alt="Screenshot 2020-03-28 at 5 07 17 PM" src="https://user-images.githubusercontent.com/10388889/77822222-b8b04380-7116-11ea-8b68-f95931f38705.png">

How do I make the CCLS server speak for the given payload? The JSON RPC (https://www.jsonrpc.org/specification) specification says that it should respond with "Invalid Request" on this, but it doesn't respond with anything. Even with verbosity level set, it outputs no debug information.

I understand directly from CLI is not the intended use, and I don't expect to run it this way anyway, it's running inside a docker container whose stdin/stdout I attach using the docker engine API through webscokets, but right now, I'm just trying to test.

Thanks!

**Comment by mehulmpt** [comment]
Got it! I wasn't following the JSONRPC protocol correctly, the first message should be the `Content-Length` header followed by the JSON payload. Doing that, it works fine.
