### ISSUE TITLE
Standalone Binary/Reduced build size?

### ISSUE THREAD

**Issue by mehulmpt** [MaskRay/ccls#603]
This is not an issue, rather a request or suggestion from you. The ccls server works flawlessly, a big thank you for that.

I'm running this CCLS server inside an alpine docker container, and on following the instructions for alpine distribution in the wiki page, I added these packages to build: https://github.com/MaskRay/ccls/wiki/Build#alpine-linux

The thing is, after building the CCLS server, the size of alpine container shoots up to 1.3GB. I'm very sure after building, I could get rid of a lot of files not needed anymore, but I'm just not sure which files should I delete. I've tried removing some installed packages or deleting some `.a` archive files, but it breaks either CCLS or GCC in the container.

I'm running a LSP with Java as well, and with a standalone jar binary, the container size is ~330MB, this is why I thought it should be possible with C as well. What do you suggest in this case?

Thank you so much for your time and effort

**Comment by myrgy** [comment]
Hi,
on my host ccls binary is about 34M.
and it doesn't depend on any libs:
```
 ~/.o/bin  readelf -d ./ccls
Dynamic section at offset 0x1bddcf0 contains 33 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libtinfo.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```
Probably you need to remove some huge libs and remain only runtime dependencies.

**Comment by mehulmpt** [comment]
Yes, I found that there were a lot of archive files `.a` of these shared libraries. Removing them brought down the size.
