### ISSUE TITLE
Suggest update Build wiki for Debian 10

### ISSUE THREAD

**Issue by paraduxos** [MaskRay/ccls#609]
### Observed behavior
This is just a suggestions from newbie's view.

I have hard time install ccls on Debian 10.
I'm using Debian 10 (Stable)

From [Build wiki](https://github.com/MaskRay/ccls/wiki/Build) 

> Some distributions package a pre-built version of ccls. See the [system-specific](https://github.com/MaskRay/ccls/wiki/Build#system-specific-notes) sections below. If you build ccls from source, you will need:

So I go to [system-specific](https://github.com/MaskRay/ccls/wiki/Build#system-specific-notes) (I also try with [`backport`](https://backports.debian.org/Instructions/) but get same result.)
```bash
$ sudo apt-get install ccls
Unable to locate package ccls
```
So I get back to build from source.
This is what wiki suggest
> Download "Pre-Built Binaries" from https://releases.llvm.org/download.html
> and unpack to /path/to/clang+llvm-xxx.

But from [https://apt.llvm.org/](https://apt.llvm.org/) **Automatic installation script** said
> To install the latest stable version: 
> bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

So I run (This command installed `clang-10` and `llvm-config-10` successfully.)
```bash
$ sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
```
But in [Debian section](https://github.com/MaskRay/ccls/wiki/Build#debian) These commands will install `clang` or `llvm` version `7`.
>```
> # build from source
> sudo apt install clang cmake libclang-dev llvm-dev rapidjson-dev
> cmake -H. -BRelease
> cmake --build Release

Then build wiki said
> ```bash
> # See https://github.com/MaskRay/ccls/wiki/FAQ#verify-the-clang-resource-directory-is-correct
> cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/path/to/clang+llvm-xxx

So I run (And get error)
```bash
$ clang-10 -print-resource-dir
/usr/lib/llvm-10/lib/clang/10.0.0

# In ccls dir
$ cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-10/lib/clang/10.0.0
```
I end up install `snapd` and `snap install ccls` succesfully.

### Steps to reproduce

In conclusion. For Debian 10.

1. Install LLVM+Clang (Read more: [https://apt.llvm.org/](https://apt.llvm.org/))
```bash
# You need PPA before run llvm.sh
$ sudo apt-get install software-properties-common
$ sudo apt-get update

# Install with llvm.sh
$ sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
```

You can verified installation with
```bash
$ clang-{version} --version
$ llvm-config-{version} --version

# Press <TAB> once or twice to see your {version}
# For example: type clang then press TAB twice
$ clang
clang++-10    clang-10      clang-cpp-10  clangd-10

# Then run
$ clang-10 --version
clang version 10.0.0-++20200412072704+50d7e5d5e7d-1~exp1~20200412053303.133 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

# Do the same with llvm
```

2. Install snapd
```bash
# Install snapd
$ sudo apt install snapd

# Check status
$ systemctl status snapd.service
● snapd.service - Snappy daemon
   Loaded: loaded (/lib/systemd/system/snapd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-04-13 14:57:41 +07; 44min ago
 Main PID: 30133 (snapd)
    Tasks: 26 (limit: 4915)
   Memory: 128.2M
   CGroup: /system.slice/snapd.service
           └─30133 /usr/lib/snapd/snapd
```

3. Install ccls with snapd [https://snapcraft.io/install/ccls/debian](https://snapcraft.io/install/ccls/debian)
```bash
# Run snapd, if not yet active
$ systemctl start snapd.service

$ sudo snap install ccls --classic

# Add snap bin to $PATH
$ cd ~
$ nvim .bashrc

# add to last line
PATH="$PATH:/snap/bin/"
# save and run
$ source .bashrc

# Then check ccls version
$ ccls --version
ccls version 0.20190314.1-0-ga41b976a
clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
```
### System information

* ccls version  0.20190314.1-0-ga41b976a
* clang version: 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
* OS: Debian 10 stable
* Editor: neovim
* Language client (and version):

**Comment by findNextStep** [comment]
i have make a ci script for ubuntu, it may also work on debain 10

https://github.com/findNextStep/ccls/blob/master/.github/workflows/build_linux.yaml

it may more sample

```bash
sudo apt install clang libclang-9-dev
git submodule update --init --recursive
cmake -H. -Bbuild/Debug
make -C build/Debug -j
```

**Comment by zhsj** [comment]
I think you have confused with `apt` and `snap`. They two different ways to install softwares.

### snap
If you want to install with snap. You just need to follow the instructions on 
https://snapcraft.io

You don't need to install clang or llvm with `apt` from `https://apt.llvm.org`.

### build ccls from source.

You can either install clang from Debian official repo, which has clang-7. Or install from `https://apt.llvm.org`, which has latest clang, currently it's clang-10.

I think both clang-7 and clang-10 can build ccls. This way you don't need to use snap to install the prebuild ccls binary.

**Comment by MaskRay** [comment]
`wiki/Build.md` should be up-to-date now.
