### ISSUE TITLE
Autodetect the Clang resource directory?

### ISSUE THREAD

**Issue by D4N** [MaskRay/ccls#610]
### Observed behavior

According to https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory ccls hard codes the path to clang's resource directory at build time. That is a viable approach when building ccls locally, as one will rebuild it quite frequently.

This is however causing a surprising problem for the package shipped in Fedora: as the clang resource directory includes the full version clang, it would require a full rebuild of ccls on each minor version update of clang. However, as ccls only links against the various clang libs, we don't rebuild it on each minor clang version bump (as that does not cause a SONAME bump). This results in a problem: once the clang version changes from e.g. 9.0.0 to 9.0.1, and suppose ccls was built with 9.0.0, then it will no longer work with clang 9.0.1, because the path to the resource directory changed.

### Expected behavior

It would be nice if ccls could tolerate a clang update that does not result in a SONAME bump without needing a rebuild.

I think a potential approach would be to change `DEFAULT_RESOURCE_DIRECTORY` to `DEFAULT_RESOURCE_DIRECTORY_ROOT` that would point to the clang directory (e.g. `/usr/lib64/clang` and not `/usr/lib64/clang/9.0.1/`) and ccls would find the most recent resource directory in the by itself.

Does that sound reasonable? If yes, I'd prepare a patch as I'd prefer to have this functionality upstream and not to carry downstream patches in Fedora.

**Comment by MaskRay** [comment]
How about `cmake -DCLANG_RESOURCE_DIR=/usr/lib64/clang/9`?

`/usr/lib64/clang/9` can be a symlink to `/usr/lib64/clang/9.0.0` or 9.0.1

**Comment by findNextStep** [comment]
> How about `cmake -DCLANG_RESOURCE_DIR=/usr/lib64/clang/9`? It is already available.
> 
> `/usr/lib64/clang/9` can be a symlink to `/usr/lib64/clang/9.0.0` or 9.0.1

on mac every time when clang upgrade, it will change clang dir name and every time we upgrade xcode (or brew upgrade #llvm) , the dir will chang
maybe we can set CLANG_RESOURCE_DIR as /usr/lib64/clang for most use and set clang version for use that need use one of dir
if there is more than one dir in resource dir we should choose the biggest one

**Comment by Riatre** [comment]
AFAIK not all distributions have symlinks like `/usr/lib64/clang/9`. Debian does, at `/usr/lib/clang/9/`, Fedora does not: [9.0.1](https://rpmfind.net/linux/RPM/openmandriva/4.1/x86_64/main/release/clang-9.0.1-1.x86_64.html) [10.0.0](https://rpmfind.net/linux/RPM/fedora/devel/rawhide/x86_64/c/clang-libs-10.0.0-1.fc33.x86_64.html)

As for detecting resource dir during runtime, are there reliable way for pulling out `CLANG_VERSION_STRING` from .so?

**Comment by MaskRay** [comment]
> As for detecting resource dir during runtime, are there reliable way for pulling out CLANG_VERSION_STRING from .so?

No:/ `CLANG_VERSION_STRING` is not referenced by a dynamic symbol (`.dynsym`). The string exists somewhere in the `.rodata` section.

I believe this is a packaging problem. The distribution can add a symlink `/usr/lib64/clang/9` so that all out-of-tree tools can work with little host detection.

**Comment by D4N** [comment]
I assume that this being closed means that you don't want such a feature in ccls?

**Comment by MaskRay** [comment]
This feature does not seem suitable.

Create `/usr/lib64/clang/9` and configure ccls with `-DCLANG_RESOURCE_DIR=/usr/lib64/clang/9`
