### ISSUE TITLE
Incorrect indexing after llvm 10 release macOS 10.15.4

### ISSUE THREAD

**Issue by sunbubble** [MaskRay/ccls#611]
Recently I updated macOS to version 10.15.4 (from 10.15.3). This coincided with the release of llvm 10, which now also is on homebrew. Since then I couldn't get ccls to index my C++ projects correctly. I'm getting ccls diagnostics of the type
```
ccls: Type is not a class namespace or enumeration
```
I'm building with cmake and exporting the compile_commands.json directly.

I tried reinstalling everything, deleting the .ccls-cache folder, adding the C-style headers thing to the .ccls file. I tried building the HEAD version of ccls (through `brew install --HEAD ccls`). Alas nothing worked.

There might be something off with my setup, I'll continue looking. I'm just asking whether any of you tried ccls with the latest macOS version?

### System information

* ccls version (`git describe --tags --long`): latest homebrew version: "0.20190823.5"
* clang version: 10.0.0
* OS: macOS Catalina 10.15.4
* Editor: emacs-mac GNU Emacs 26.3 (mitsuharu port). (also tried with neovim and COC: same errors)
* Language client (and version): emacs lsp-mode

**Comment by findNextStep** [comment]
add  clang setting work for me    
```json
 "clang": {
                    "extraArgs": [
                        "-isystem",
                        "/usr/local/opt/llvm/include/c++/v1",
                        "-Wold-style-cast"
                    ],
                    "pathMappings": [],
                    "resourceDir": "/usr/local/opt/llvm/lib/clang/10.0.0"
                },
```

**Comment by sunbubble** [comment]
Where did add this setting? as an init parameter to ccls?

**Comment by findNextStep** [comment]
> Where did add this setting? as an init parameter to ccls?

yes, add the setting into ccls Initialization options
here is my setting for coc.nvim, in emacs can by see in https://github.com/MaskRay/ccls/wiki/lsp-mode

**Comment by sunbubble** [comment]
This fixed my problem:
`  (setq ccls-initialization-options '(:clang (:resourceDir "/usr/local/opt/llvm/lib/clang/10.0.0")))`

Thanks @findNextStep

**Comment by findNextStep** [comment]
> This fixed my problem:
> `(setq ccls-initialization-options '(:clang (:resourceDir "/usr/local/opt/llvm/lib/clang/10.0.0")))`
> 
> Thanks @findNextStep

It should know that every time you upgrade llvm you may need chang the dir for clang.resoureDir
about auto set, you can see https://github.com/MaskRay/ccls/issues/610

**Comment by findNextStep** [comment]
can we close it ?

**Comment by sunbubble** [comment]
We can, but it would be nice to have this explicit in the wiki.

**Comment by MaskRay** [comment]
Thanks findNextStep!

If `/usr/local/opt/llvm/lib/clang/10` exists as a symlink, you can try `cmake -DCLANG_RESOURCE_DIR=/usr/local/opt/llvm/lib/clang/10 ...` so that the built executable will work with 10.0.1 10.0.2 ...
