### ISSUE TITLE
ccls exited with code when i input the second letter

### ISSUE THREAD

**Issue by meziberry** [MaskRay/ccls#612]
### problem
ccls can start correctly,  function/var/type jump works normally. but, ccls exits when i input the second letter. sometimes the exit code is 5.
`LSP :: ccls has exited (exited abnormally with code 116)`
![image](https://user-images.githubusercontent.com/10571785/79238948-94888c80-7ea2-11ea-8bbc-9b5286102638.png)
### environment 
ccls:  `db12223`
os:  win10 msys2
clang: mingw-w64-x86_64-llvm 10.0.0  /  llvm git repo 11.0.0
emacs: 26.3/28.0.50
[my emacs config ](https://github.com/meziberry/zconfig/tree/master/.doom.d)

By the way , after updating the ccls compiled by llvm 10.0.0,  the problem is present. the v9.0.1 was seem like ok.

Thank you.

**Comment by MaskRay** [comment]
Apologies for my slow response. This can be a problem of 10.0.0. Probably wait for 10.0.1
clang bugs can be difficult to diagnose without further information. Tips on debugging clang: https://github.com/MaskRay/ccls/wiki/Debugging
