### ISSUE TITLE
Connection to server got closed. Server will restart.  | Request textDocument/completion failed. │   Connection got disposed.

### ISSUE THREAD

**Issue by thomaklee** [MaskRay/ccls#613]
**Basic Information**

- OS arch linux  linux 5.6.3   
-nvim NVIM v0.5.0-428-g46fdad255   
-ccls  ccls version 0.20190823.5-19-gdb122230   
-clang clang version 9.0.1   
-problem:I encountered an error when using coc.nvim + ccls to configure the c ++ development environment:     
|43 [Info  - 9:57:19 AM] Connection to server got closed. Server will restart.    
|44 [Error  - 9:57:19 AM] Request textDocument/completion failed.    
|45 Error: Connection got disposed.    
![Screenshot_20200414_063028](https://github.com/thomaklee/error/blob/master/Screenshot_20200414_063028.png)     
   
You can download the text.https://github.com/thomaklee/error/blob/master/error.txt<br>

My coc-settings.json ![Screenshot_20200414_063147](https://github.com/thomaklee/error/blob/master/Screenshot_20200414_063147.png)      
I use spdlog project https://github.com/gabime/spdlog and generate compile_commands.json for testing.   
   
Thank you！

**Comment by MaskRay** [comment]
See https://github.com/MaskRay/ccls/wiki/Debugging

Your build may be incorrect.

**Comment by thomaklee** [comment]
> See https://github.com/MaskRay/ccls/wiki/Debugging
> 
> Your build may be incorrect.

My ccls was installed using the command  'sudo pacman -S ccls-git'

**Comment by thomaklee** [comment]
> See https://github.com/MaskRay/ccls/wiki/Debugging
> 
> Your build may be incorrect.

I solved this problem by redeploying the system，thanks!
