### ISSUE TITLE
Arch Linux extra/clang 10.0.0 requires -DCLANG_LINK_CLANG_DYLIB=on -DLLVM_LINK_LLVM_DYLIB=on

### ISSUE THREAD

**Issue by codehz** [MaskRay/ccls#615]
### Observed behavior

Failed to build with clang 10.0.0 in linux
```
找不到 -lclangFormat
/usr/bin/ld: 找不到 -lclangTooling
/usr/bin/ld: 找不到 -lclangToolingInclusions
/usr/bin/ld: 找不到 -lclangToolingCore
/usr/bin/ld: 找不到 -lclangFrontend
/usr/bin/ld: 找不到 -lclangParse
/usr/bin/ld: 找不到 -lclangSerialization
/usr/bin/ld: 找不到 -lclangSema
/usr/bin/ld: 找不到 -lclangAST
/usr/bin/ld: 找不到 -lclangLex
/usr/bin/ld: 找不到 -lclangDriver
/usr/bin/ld: 找不到 -lclangBasic
```

### Expected behavior

Build success

### Steps to reproduce

1. Install clang 10.0.0
2. Download and build ccls

### System information

* ccls version (`git describe --tags --long`): 0.20190823.5-20-g24dd3bd4
* clang version: 10.0.0
* OS: ArchLinux
* Editor: (NONE)
* Language client (and version): (NONE)

PS:
clang /usr/lib/libclang-cpp.so
clang /usr/lib/libclang-cpp.so.10
clang /usr/lib/libclang.so
clang /usr/lib/libclang.so.10

**Comment by codehz** [comment]
temp fix for 10.0.0
need to add some detection code
related code
https://github.com/MaskRay/ccls/blob/dev/CMakeLists.txt#L73-L91
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 471f4a63..b9350c00 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -73,21 +73,7 @@ find_package(Clang REQUIRED)
 if(CLANG_LINK_CLANG_DYLIB)
   target_link_libraries(ccls PRIVATE clang-cpp)
 else()
-  target_link_libraries(ccls PRIVATE
-    clangIndex
-    clangFormat
-    clangTooling
-    clangToolingInclusions
-    clangToolingCore
-    clangFrontend
-    clangParse
-    clangSerialization
-    clangSema
-    clangAST
-    clangLex
-    clangDriver
-    clangBasic
-  )
+  target_link_libraries(ccls PRIVATE clang-cpp)
 endif()
 
 if(LLVM_LINK_LLVM_DYLIB)
```

**Comment by bastianbeischer** [comment]
The first branch of the if() should already do the right thing, but apparently CLANG_LINK_CLANG_DYLIB is not set after find_package(Clang) in case Clang was built with libclang-cpp.so. See also https://github.com/ziglang/zig/issues/4799, where someone observed the same and suggested to use LLVM_LINK_LLVM_DYLIB instead.

**Comment by MaskRay** [comment]
https://git.archlinux.org/svntogit/packages.git/log/trunk/PKGBUILD?h=packages/clang

Arch Linux switched to use `-DCLANG_LINK_CLANG_DYLIB=on -DLLVM_LINK_LLVM_DYLIB=on`

Downstream packages need to link to `libLLVM.so` and `libclang-cpp.so`. `ccls/CMakeLists.txt` already handles the case but the options must be explicitly specified by the user. Arguably the LLVM/Clang shipped CMake files should set the options so that no downstream package needs to explicitly set the options.
