### ISSUE TITLE
ubuntu 18.04 ccls issue report

### ISSUE THREAD

**Issue by ssh352** [MaskRay/ccls#618]
### Observed behavior

Describe what happened. Any aids you can include (that you think could be relevant) are a tremendous help.

* `compile_commands.json` or `.ccls` ([wiki/Project-Setup](https://github.com/MaskRay/ccls/wiki/Project-Setup))

* Reduce to A minimal set of `.c` `.cc` `.h` `.hh` files that can still demonstrate the issue.
* Consider a screencast gif.

<img width="988" alt="Screen Shot 2020-04-23 at 3 25 41 PM" src="https://user-images.githubusercontent.com/41779116/80071203-cbcbfd00-8576-11ea-96c7-bfa44155bd30.png">
<img width="512" alt="Screen Shot 2020-04-23 at 3 25 10 PM" src="https://user-images.githubusercontent.com/41779116/80071229-d5556500-8576-11ea-8f55-4d21a15c869d.png">
<img width="953" alt="Screen Shot 2020-04-23 at 3 24 52 PM" src="https://user-images.githubusercontent.com/41779116/80071232-d5edfb80-8576-11ea-9a8f-40dd1881f755.png">
<img width="541" alt="Screen Shot 2020-04-23 at 3 49 50 PM" src="https://user-images.githubusercontent.com/41779116/80073321-29ae1400-857a-11ea-8150-c449ce3aad4a.png">

### Expected behavior
I expected std::cout not be marked red.

### Steps to reproduce

as detailed in the 3 screenshots. I've also played with .ccls file per the wiki to no avail.

### System information

* ccls version (`git describe --tags --long`): 

```
ccls --version
ccls version <unknown>
clang version 9.0.0 (tags/RELEASE_900/final)
```

```
brew info ccls
ccls: stable 0.20190823.5 (bottled), HEAD
C/C++/ObjC language server
https://github.com/MaskRay/ccls
/home/linuxbrew/.linuxbrew/Cellar/ccls/0.20190823.5 (6 files, 28.1MB) *
  Poured from bottle on 2020-04-03 at 15:27:05
From: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/ccls.rb
==> Dependencies
Build: cmake ✘, rapidjson ✘
Required: llvm ✘, gcc@9 ✔
==> Requirements
Required: macOS is required ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 41 (30 days), 135 (90 days), 576 (365 days)
install-on-request: 41 (30 days), 135 (90 days), 578 (365 days)
build-error: 0 (30 days)
```

ccls is installed via brew on Linux.

* clang version: 

```
clang --version
clang version 10.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/linuxbrew/.linuxbrew/bin

```

* OS: 
ubuntu 18.04

* Editor: 
neovim 0.4.3

* Language client (and version): 
latest coc.nvim

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Build#macos

**Comment by ssh352** [comment]
> https://github.com/MaskRay/ccls/wiki/Build#macos

The issue is on ubuntu 18.04 not macOS...

**Comment by findNextStep** [comment]
> > https://github.com/MaskRay/ccls/wiki/Build#macos
> 
> The issue is on ubuntu 18.04 not macOS...

if you use clang from homebrew you may meet same issure in mac 
try set clang.resourceDir in coc
in macos , the resouceDir is like `/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0/`

here is my configuration in mac
```json
            "initializationOptions": {
                "cache": {
                    "directory": ".ccls-cache"
                },
                "clang": {
                    "extraArgs": [
                        "-isystem",
                        "/usr/local/opt/llvm/include/c++/v1",
                        "-Wold-style-cast"
                    ],
                    "resourceDir": "/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0/"  // change clang path to your brew, maybe  /home/linuxbrew/.linuxbrew/llvm/10.0.0_3/lib/clang/10.0.0/
                }, 
                "highlight": {
                    "lsRanges": true
                },
            }
```
