### ISSUE TITLE
Memory requirements.

### ISSUE THREAD

**Issue by shoorlyne** [MaskRay/ccls#62]
I am investigating various C/C++ language servers (LS), including ccls. As we are going to run the LS in a memory constrained environment, memory consumption is an important criteria for us when choosing from candidate LS'es.

Suppose I have a setup like this: I have installed standard g++/STL, along with Boost library. How much memory is consumed when ccls parses a simple C/Cpp/ObjC file handling LSP requests, consisting no more than a few hundred lines of code?

I assume indexed files derived from C standard library/STL/Boost are loaded when parsing the client's file, how much memory is required for the indexed files? What if I run multiple ccls instances on one single machine, are these files shared by all the instances, or each instance has to load a copy of these index files?

Thank you.

**Comment by MaskRay** [comment]
The memory consumption characteristics of indexers should be similar as that of `clang -fsyntax-only a.cc ...`


`diagnostics.onParse: false`
`diagnostics.onType: false`

**Comment by shoorlyne** [comment]
Good to know. Will try out later.

Thanks.

**Comment by MaskRay** [comment]
@shoorlyne I made that comment in a hurry. I have just updated it with some more details. If you compare ccls with other alternatives (cquery, clangd), I'd love to know the results!
