### ISSUE TITLE
build ccls in VS amd msys2 two ways test

### ISSUE THREAD

**Issue by WingDust** [MaskRay/ccls#624]
Here are some things you should try before filing a bug report:

+ For client issues related to [emacs-ccls](https://github.com/MaskRay/emacs-ccls) or [vscode-ccls](https://github.com/MaskRay/vscode-ccls), report in their own repository.
+ For build problems, check https://github.com/MaskRay/ccls/wiki/Build
+ Check https://github.com/MaskRay/ccls/wiki/Debugging
+ Check [the FAQ](https://github.com/MaskRay/ccls/wiki/FAQ) to see if your issue is mentioned.

If none of those help, remove this section and fill out the four sections in the template below.

---

### Observed behavior
i already try two way to build ccls 
first to  VS but in ninja -C Release
but i don't how to update llvm reporsitory 

![image](https://user-images.githubusercontent.com/45911286/80463163-6313c480-896a-11ea-9559-8ea44703cc3c.png)

second
follow the wiki  i use msys2 to complie the ccls
in step 2 

![image](https://user-images.githubusercontent.com/45911286/80463495-e9c8a180-896a-11ea-8e51-ea232e5725e8.png)
 

### Expected behavior

Describe what you expected to happen.

### Steps to reproduce
First way
1. i follow the (https://emacs-china.org/t/windows-vs2017-clang-ccls/8242) to install,

Second way
1.i follow the wiki to install package
i don't about `mingw-w64-x86_64-cmake 3.17.1-2`
when i install `mingw-w64-x86_64-cmake 3.17.1-2` i use cmake it't don't work
so  i also install cmake ninja
when build problem happen
### System information

* ccls version (`git describe --tags --long`): 0.20190823.6 
* clang version: mingw-w64-x86_64-clang 10.0.0-1
* OS: window10
* Editor: neovim
* Language client (and version):

**Comment by xubury** [comment]
make sure you install clang+llvm, these're packages you can installed in msys2. Also try use `MSYS Makefiles` i.e `-G "MSYS Makefiles"`

**Comment by MaskRay** [comment]
> but i don't how to update llvm reporsitory

ccls can be built with LLVM 7 ~ LLVM 10 and LLVM master. It seems that you are using an out-of-date snapshot of LLVM 11 (git). You need to update your llvm-project.
