### ISSUE TITLE
Modernize ccls

### ISSUE THREAD

**Issue by condy0919** [MaskRay/ccls#625]
At present, there are some pieces of code in ccls that are not modern enough, such as

- Inclusion of deprecated c++ header `stdio.h`, `stdlib.h`, etc...
- Using `NULL` instead of `nullptr`
- `return` statement isn't inside braces
- and other readability issues

**Comment by MaskRay** [comment]
> Inclusion of deprecated c++ header stdio.h, stdlib.h, etc...

Honestly don't know how useful this is. cstdio requires std:: which can make the program more verbose.

> Using NULL instead of nullptr

Only a few places where a system C function is called `NULL` is used. Don't find `nullptr` too useful, either.

> `return` statement isn't inside braces

Can you elaborate? If you mean `return (...);` I am not sure how this is going to be useful. This is a basic rule which every C++ programmer should understand.

> and other readability issues

Please elaborate.

**Comment by condy0919** [comment]
# prefer the c++ version file

```c++
// From cctype, the c++ version

// Get rid of those macros defined in <ctype.h> in lieu of real functions.
#undef isalnum
...
#undef toupper
```

It guarantees that `toupper` is a function defined in `std`.

`gcc` may optimize `toupper` to a macro, although it can't happen in c++-mode.

```c++
// From ctype.h

# if __GNUC__ >= 2 && defined __OPTIMIZE__ && !defined __cplusplus
#  define tolower(c)    __tobody (c, tolower, *__ctype_tolower_loc (), (c))
#  define toupper(c)    __tobody (c, toupper, *__ctype_toupper_loc (), (c))
# endif /* Optimizing gcc */
```

Defensive programming is actually healthy. :-)

# `nullptr` vs `NULL`

`nullptr_t` is an opaque type without implicit conversion to integral types,
etc... It's recommended to use to prevent accident mistakes.

While `NULL` is an **implementation-defined** pointer constant. If `NULL` is
defined with `#define NULL 0`, conversion from `0` to integral types is legal.
pitfall.

# The brace style

``` c++
if (cond) {
  return true;
}
```

Using `brace` is always worth the effort. Or consider linux kernel coding style?

# Nitpicking

- Prefer `!vec.empty()` over `vec.size()`. There is no implicit conversion.
- Add `[[nodiscard]]` for the functions return primitive types.

**Comment by MaskRay** [comment]
> prefer the c++ version file

Really this does not seem useful.

C11 7.1.4

> Any function declared in a header may be additionally implemented as a function-like macro defined in the header ... For the same syntactic reason, it is permitted to take the address of a library function even if it is also defined as a macro

The code base does not have any library function uses which may break with the C version header file.

> nullptr vs NULL

There are actually very few `NULL` and their uses are all about system C functions. I don't see how nullptr (requires a conversion from std::nullptr_t to a pointer) can be helpful. 

```
src/test.cc
200:    execlp("diff", "diff", "-U", "3", expected_file, actual_file, NULL)
```
This is actually a bug because an int might not be the same size as a `char *`, though I don't know of any psABI breaking this.

> The brace style

The braces are redundant with no benefits. It protects misleading indentations but GCC/clang -Wmisleading-indentation provides the same protection. It prevents clang-format from placing the code on one line `if (cond) return true;` for certain styles (Google). LLVM style does not have the problem.

> Nitpicking

> * Prefer !vec.empty() over vec.size(). There is no implicit conversion.

This replacement does not seem very useful. `size()` avoids a negation.

* Add [[nodiscard]] for the functions return primitive types.

This may be useful.

**Comment by condy0919** [comment]
After some investigation...

https://github.com/MaskRay/ccls/blob/master/src/utils.hh#L132

```c++
template <typename T> struct Vec {
  std::unique_ptr<T[]> a;
  int s = 0;
#if !(__clang__ || __GNUC__ > 7 || __GNUC__ == 7 && __GNUC_MINOR__ >= 4) ||    \
    defined(_WIN32)
  // Work around a bug in GCC<7.4 that optional<IndexUpdate> would not be
  // construtible.
  Vec() = default;
  Vec(const Vec &o) : a(std::make_unique<T[]>(o.s)), s(o.s) {
    std::copy(o.a.get(), o.a.get() + o.s, a.get());
  }
  Vec(Vec &&) = default;
  Vec &operator=(Vec &&) = default;
  Vec(std::unique_ptr<T[]> a, int s) : a(std::move(a)), s(s) {}
#endif
  const T *begin() const { return a.get(); }
  T *begin() { return a.get(); }
  const T *end() const { return a.get() + s; }
  T *end() { return a.get() + s; }
  int size() const { return s; }
  const T &operator[](size_t i) const { return a.get()[i]; }
  T &operator[](size_t i) { return a.get()[i]; }
};
```

Is `Vec` necessary?
