### ISSUE TITLE
C++ code completion suggests both private and public class members

### ISSUE THREAD

**Issue by jmdaly** [MaskRay/ccls#63]
When using code completion in neovim (through the LanguageClient-neovim plugin) with ccls, the completion suggestions on an object include both public and private members. For instance, given the class,

```
class A
{
  public:
    void myPublicFunction();

  private:
   void myPrivateFunction();
   int private_member_;
};
```

performing completion on an object `a` of class `A` shows `myPublicFunction()`, `myPrivateFunction()`, and `private_member_` as completion suggestions. In practice, we can't call private members on an object. Is there a way for ccls to only provide completion suggestions for public members, or to note whether a member is public or private? This would be a really helpful addition to code completion.

**Comment by MaskRay** [comment]
Thanks for reporting the issue.

`src/clang_complete.cc`
```diff
-      if (CCS->getAvailability() == CXAvailability_NotAvailable)
+      if (CCS->getAvailability() == CXAvailability_NotAccessible ||
+          CCS->getAvailability() == CXAvailability_NotAvailable)
```

Such private members are inaccessible

https://github.com/llvm-mirror/clang/tree/master/lib/Sema/SemaCodeComplete.cpp#L1307
```cpp
    void FoundDecl(NamedDecl *ND, NamedDecl *Hiding, DeclContext *Ctx,
                   bool InBaseClass) override {
      bool Accessible = true;
      if (Ctx)
        Accessible = Results.getSema().IsSimplyAccessible(ND, Ctx);
      ResultBuilder::Result Result(ND, Results.getBasePriority(ND), nullptr,
                                   false, Accessible, FixIts);
      Results.AddResult(Result, CurContext, Hiding, InBaseClass);
    }
```

Fixed in HEAD.

**Comment by jmdaly** [comment]
Wow, thank you for the quick fix! I'll re-build from HEAD as soon as I can :)

**Comment by simonjoylet** [comment]
In some case I'd like non-accessible member to be shown in the complete list. Is that ok to add an optional config for this feature?
