### ISSUE TITLE
not finding headers - coc.nvim on msys2 mingw64

### ISSUE THREAD

**Issue by rjl6789** [MaskRay/ccls#630]
### Observed behavior

any "custom" included header files end up with the error `[ccls 1] [E] 'a.h' file not found` 

### Steps to reproduce
- compile on msys2 (mingw64 shell) using wiki instructions
- follow coc.nvim config instructions (note I also added `.ccls` to `rootPatterns`)
- mkdir /tmp/c; cd /tmp/c; git init; touch .ccls create a.c and a.h
- in a.c add: `include "a.h"`
- open in vim and see the error `[ccls 1] [E] 'a.h' file not found` 

I've tied with a blank .ccls file and also having `clang` at the top, I've also tried adding `%h`

### Expected behavior

no error

### System information

* ccls version : latest commit c5acf62 
* clang version: 10.0.0 
* OS: Msys2 MINGW64
* Editor: vim
* Language client (and version): coc.nvim (v0.0.78)

**Comment by rjl6789** [comment]
I think I've made some progress.  I believe the version of vim shipped with msys2 is built in "native" msys (similar to cygwin) i.e. not mingw64.  So adding gvim to my path (installed outside of msys) and running this gets me further.  However I now see errors when I do `CocInfo` along the line of `ccls indexer.cc:1348 E clang crashed`  this is perhaps a separate issue - so think I should probably close this and open a new one?  As a side note, I'v also tried `coc-clang` which I believe uses `clangd` - this appears to work so I'm hopefull that the issues with ccls are configuration related.

**Comment by MaskRay** [comment]
Sorry for my late reply. Pretty sure this is a problem of the Clang installation which has nothing to do with ccls.
There are several alternative installations https://github.com/MaskRay/ccls/wiki/Build#windows

I'll ask a few folks who might use msys2 and hope they can update the wiki if necessary.
