### ISSUE TITLE
Cannot autocomplete in Mac OS

### ISSUE THREAD

**Issue by toptodown** [MaskRay/ccls#637]
![image](https://user-images.githubusercontent.com/28153666/81641711-3d031f80-9454-11ea-8202-beac4291e216.png)

### System information

* ccls version (`git describe --tags --long`): 
* clang version: Apple clang version 11.0.3 (clang-1103.0.32.59)
* OS: Mac OS 10.15.4
* Editor: neovim
* Language client (and version): 

cycles version:
ccls version <unknown>
clang version 10.0.0

**Comment by MaskRay** [comment]
See #622
