### ISSUE TITLE
Relative path in directory in compile_commands.json

### ISSUE THREAD

**Issue by rohit04saluja** [MaskRay/ccls#642]
### Observed behavior
ccls does not work when directory value in compile_commands.json is relative the root. ccls works with directory value in compile_commands.json is absolute.

### Expected behavior
If directory value in compile_commands.json is a relative path, then it should be resolved using the root.

### Steps to reproduce
Just give directory value in compile_commands.json as relative path from root.

### System information
* ccls version: 0.1.28
* OS: Linux
* Editor: vs-code

I was able to see in the code that when we are getting the directory information we don't check for relative path as we do for filename.

`      // If workspace folder is real/ but entries use symlink/, convert to
      // real/.
      entry.directory = realPath(cmd.Directory);
      normalizeFolder(entry.directory);
      doPathMapping(entry.directory);
      entry.filename =
          realPath(resolveIfRelative(entry.directory, cmd.Filename));
      normalizeFolder(entry.filename);
      doPathMapping(entry.filename);`

Just like we resolve if relative for filename with anchor as directory, we should resolve if relative for directory as well with anchor as root.

**Comment by findNextStep** [comment]
it may be same issues with https://github.com/MaskRay/ccls/issues/572
can you check if the compile_commands.json has any of `-I../*` or `-isystem../`?
i think it may be the option with path don`t work

**Comment by rohit04saluja** [comment]
I saw that in the code we ain't supporting it.

In #572 the submitter is trying to set `compilationDatabaseDirector` to a relative value. Where as here, I am wanting to set `directory` inside compile_commands.json to a relative value.

Like you pointed out `compilationDatabaseDirector` as a relative path is supported in the code but just check the code snippet I have attached. Seems that relative path for compile_commands.json is only support for filename and not directory.

Wanting to add support for relative path in directory if it's possible. root becomes the anchor here

**Comment by myrgy** [comment]
I use emacs-ccls and it's able to locate proper compile_commands.json in multiple projects
```
(setq ccls-executable "~/.opt/bin/ccls"
      ccls-initialization-options `(:cache (:directory ".cache"), :compilationDatabaseDirectory "build"))
```
but each project has `.ccls` in the root
```
%compile_commands.json
```

**Comment by rohit04saluja** [comment]
The problem is not being able to locate compile_commands.json.

We have a `directory` value per compile command inside compile_commands.json.

This `directory` value is the anchor for other values like `command`, `file`, etc.

This `directory` value should be defined as absolute path. If I am defining it as relative path then ccls execution does not index the files.

**Comment by MaskRay** [comment]
`Project::Entry::directory` is normalized, so this should work. Maybe an older commit did not work...

`src/project.cc`: `entry.directory = realPath(cmd.Directory);`

**Comment by rohit04saluja** [comment]
When can I see this in the binary file?

--
Regards
Rohit Saluja

**Comment by rohit04saluja** [comment]
@MaskRay It still doesn't work. I was talking about making _directory_ relative to the workspace path.

**Comment by mbaranchik** [comment]
@rohit04saluja I had the same issue, 
solved it by passing a compilationDatabaseCommand to a proxy script that adds sys.argv[1] which is root (among other things).

**Comment by myrgy** [comment]
Could you please share you solution?

**Comment by rohit04saluja** [comment]
@mbaranchik I have been doing the same. I just wanted to remove the dependency of running the script again and again.

**Comment by madscientist** [comment]
I recommend providing a more complete problem report.  It appears that maskray doesn't see the problem.  If you provide a minimal complete test case including an actual compile_commands.json file and instructions for how to install it and run ccls with it to see the issue then you'll have a better chance of getting a fix.

**Comment by rohit04saluja** [comment]
@MaskRay understood the problem and we had a discussion about it as part of #711 and #703 

My problem seems to be coming from using inside vscode client of ccls.

VSCode CCLS extension runs all child process at the home directory. This is because VSCode can have multiple workspace folders and thus the workspace folder can't be picked for the execution of the child process. This issue was fixed by @MaskRay but it didn't work with VSCode ccls extention. Thus he mentioned that a fix is needed in VSCode client as well.
