### ISSUE TITLE
QUESTION: Avoid absolute paths in .ccls file

### ISSUE THREAD

**Issue by kheaactua** [MaskRay/ccls#647]
How can I prepare a `.ccls` file that can be committed to git and shared with others (no absolute paths)

Following the [ccls file advice here](https://github.com/MaskRay/ccls/wiki/Project-Setup#ccls-file), I have ccls working with my Buildroot/QNX project with neovim, but I had to put absolute paths in my `.ccls` file, is there anyway around this?

I build my project with CMake using a toolchain file, it exports a `compile_commands.json` file, using the commands in that file I can compile my files in the shell, but in vim the std headers aren't found.

When I add a `.ccls` file with the `-system` paths to QNX in buildroot, re-index, ccls in vim them works great, however, I don't want to commit my `.ccls` file, nor do I want to risk loosing the file (and when helping other people set this up, I'd prefer to reduce the instructions required.)

Is there a better way to inject the cross piles paths?  Either somehow get them into my `compile_commands.json`, have my vimrc inject them in the ccls invocation, env vars, _etc_?

(if this is a bad place to ask this, where should I ask it?)

### System information

* ccls version (`git describe --tags --long`): c5acf62060f32 (built off master, git describe says no names found?)
* clang version: 10.0.1-++20200519095410+f79cd71e145-1~exp1~20200519200813.165
* OS: Ubuntu 18.04
* Editor: NVIM v0.5.0-433-g05fd64777
* Language client (and version): autozimu/LanguageClient-neovim, rev next, 4b35f5d6859

**Comment by Rayaray** [comment]
As I know at least the include path is supporting relative path like "-I./QNX".

**Comment by MaskRay** [comment]
The paths are relative to the workspace folder root.
