### ISSUE TITLE
Foundation/Foundation.h file not found for Objective-C.

### ISSUE THREAD

**Issue by shoorlyne** [MaskRay/ccls#65]
I am seeing "Foundation/Foundation.h file not found" error while trying to use ccls to parse an Objective-C file.

<img width="505" alt="screen shot 2018-08-30 at 9 22 40 pm" src="https://user-images.githubusercontent.com/20250340/44854387-f464fc00-ac9a-11e8-89fc-3b9c9766150d.png">

I guess I need to use ccls to index built-in Objective-C library source files so that this error goes away. Is it correct?

Thanks!

**Comment by shoorlyne** [comment]
Well, actually the language server runs on Ubuntu.

Am I supposed to collect the Objective-C system headers somewhere and feed them to ccls for indexing?

**Comment by MaskRay** [comment]
Then you may need something like `-isystem /usr/include/GNUstep`. But Objective-C may have its own convention.

**Comment by myrgy** [comment]
in case of OSX there are multiple parameters - `-framework OpenGL` to enable framework, `-F ./my-frameworks` to specify additional frameworks path.
Each framework is a directory with includes and libraries in it.
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Frameworks.html
