### ISSUE TITLE
Wrong/misleading syntax checker error message

### ISSUE THREAD

**Issue by exp2ipi** [MaskRay/ccls#655]
### Observed behavior

See attached gif for a repro of a problem that took hours to track down.  Flycheck was reporting "no matching function call" error despite the fact that the function in question was clearly defined and was indexed by ccls.

After isolating the problem, turned out that a header file, completely unrelated to the one defining the code with the purported error, was not being found by ccls.  The fix was adding `-I/path/to/header/directory` to `.ccls`.

This was extremely difficult to track down because the error message was very misleading. Furthermore, "project setup" documentation suggests that includes in `.ccls`  are recursively processed.  It is certainly NOT the case that the directories are included recursively.  Namely, `-I/foo/` does not mean that `-I/foo/bar/` will be included, which is unexpected.

Finally, the ccls::stderr output further masks the problem, because it indicated that the missing header file was indexed, but it was in fact not being found by my editor until `-I/path/to/header/directory` was added.  Here's the relevant line from `ccls::stderr`:

```
17:28:54 indexer2         pipeline.cc:378 I store index for /home/leo/projects/covent/VentilatorSoftware/common/third_party/nanopb/pb.h (delta: 0)
```

It would save many hours of users' time if CCLS could do at least one of the following:

- ensure that missing files do not result in complete misleading unrelated syntax error messages
- make it very clear in the "project setup" documentation that **all** subdirectories that may contain code should be placed in the `.ccls` file. This can be easy to do in an automated fashion, but the docs should indicate that this is necessary!  

![ccls-bad-error-message](https://user-images.githubusercontent.com/338250/85910662-fe8fad00-b7d4-11ea-9c7e-fbbc425df9ee.gif)
### System information

* ccls version: latest master 
* clang version: 10.0
* OS: Ubuntu
* Editor: Emacs

**Comment by MaskRay** [comment]
> It is certainly NOT the case that the directories are included recursively. Namely, -I/foo/ does not mean that -I/foo/bar/ will be included, which is unexpected.

wiki/Project-Setup does not say that "directories are included recursively"... It says "Recursively listed source files ... will be indexed".

`-I/foo/` not implying `-I/foo/bar/` should be an obvious fact. With `.ccls`, ccls does not add implicit `-I`.

> make it very clear in the "project setup" documentation that all subdirectories that may contain code should be placed in the .ccls file. This can be easy to do in an automated fashion, but the docs should indicate that this is necessary!

This really depends on what directories are included. Recursively adding all subdirectories is usually not the right thing.

I think the `store index for /home/leo/projects/covent/VentilatorSoftware/common/third_party/nanopb/pb.h` log can be improved to include the number of diagnostics.

**Comment by exp2ipi** [comment]
The bigger issue here is that the flycheck error message shown to the user was completely inappropriate. It suggested a problem with a concrete piece of  code, whereas the actual issue was something completely else entirely: a missing include in totally unrelated component.

Perhaps this is not unexpected because software is complex and failing to build in inscrutable ways is just what C++ does -- but in this case, it should be documented or added to the FAQ.

Please try to see this from a perspective of someone new to C++ tooling, who just joined an unfamiliar project. Yes, we'll try to figure out what compiler flags and includes are being used by the build system and put them in `.ccls`. But if at that point CCLS is misconfigured, but shows misleading error messages, the only way to track down the problem is spending hours bisecting the project. It's very frustrating.
