### ISSUE TITLE
Clang::Clang not found on Gentoo x64

### ISSUE THREAD

**Issue by DarkMonad** [MaskRay/ccls#66]
I am trying to compile ccls with `-DSYSTEM_CLANG=on`
When I execute the following command:
```
cmake -H. -BRelease -DSYSTEM_CLANG=on -DUSE_SHARED_LLVM=on -DCMAKE_CXX_COMPILER=clang++
```
I get the following error:
```
-- The CXX compiler identification is Clang 6.0.1
-- Check for working CXX compiler: /usr/lib/llvm/6/bin/clang++
-- Check for working CXX compiler: /usr/lib/llvm/6/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Using system Clang
-- Could NOT find Clang (missing: Clang_LIBRARY Clang_INCLUDE_DIR LLVM_INCLUDE_DIR LLVM_BUILD_INCLUDE_DIR) (found suitable version "6.0.1", minimum required is "6.0.0")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
CMake Error at CMakeLists.txt:18 (add_executable):
  Target "ccls" links to target "Clang::Clang" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/DarkMonad/ccls/Release
```
My cmake version is:
```
cmake --version                                                                        
cmake version 3.9.6
```
And I am using the following clang version:
```
clang --version
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/6/bin
```
If I am not using  `-DSYSTEM_CLANG=on` and use the downloaded clang version, everything works fine.
Am I doing something wrong or is this a bug?

**Comment by MaskRay** [comment]
If gentoo does not provide libLLVM.so  , canyou remove -DUSE_SHARED_LLVM=on

**Comment by DarkMonad** [comment]
I tried without `-DUSE_SHARED_LLVM=on` such that the command was only
```
cmake -H. -BRelease -DSYSTEM_CLANG=on -DCMAKE_CXX_COMPILER=clang++
```
Output was the same:
```
-- The CXX compiler identification is Clang 6.0.1
-- Check for working CXX compiler: /usr/lib/llvm/6/bin/clang++
-- Check for working CXX compiler: /usr/lib/llvm/6/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Using system Clang
-- Could NOT find Clang (missing: Clang_LIBRARY Clang_INCLUDE_DIR LLVM_INCLUDE_DIR LLVM_BUILD_INCLUDE_DIR) (found suitable version "6.0.1", minimum required is "6.0.0")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
CMake Error at CMakeLists.txt:18 (add_executable):
  Target "ccls" links to target "Clang::Clang" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/DarkMonad/ccls/Release
```
Btw I was able to compile everything with the following command:
```
cmake -H. -BRelease -DUSE_SHARED_LLVM=on -DCMAKE_CXX_COMPILER=clang++
```
So using `-DUSE_SHARED_LLVM=on` doesnt seem to cause a problem

**Comment by MaskRay** [comment]
Also pay attention if `-DLLVM_ENABLE_RTTI=on` is used for Gentoo clang. If it does, you also need to pass this option when building ccls. Can you put a simple description to https://github.com/MaskRay/ccls/wiki/Getting-started ?

**Comment by DarkMonad** [comment]
I am sorry I dont quite understand what you mean with putting a simple description to [https://github.com/MaskRay/ccls/wiki/Getting-started](https://github.com/MaskRay/ccls/wiki/Getting-started).
Passing  `-DLLVM_ENABLE_RTTI=on` as argument does not help. Still getting the same error.

**Comment by MaskRay** [comment]
If you use `-DSYSTEM_CLANG=on`, `/usr/lib/llvm/6/lib/libLLVM*` will be linked.
Otherwise, an archive rclang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04 will be downloaded from releases.llvm.org and `libLLVM*.a` there will be used.

By using `-DUSE_SHARED_LLVM=on`, you instruct cmake to link `libLLVM.so`, instead of many `libLLVM*.a`.

`-DLLVM_ENABLE_RTTI=off` is for releases.llvm.org archives because they do not enable RTTI.

But if you use `-DSYSTEM_CLANG=on`, you should consider it. Some systems provide llvm libraries with RTTI. The mismatch of llvm libraries and the flags building ccls can cause SIGSEGV https://github.com/MaskRay/ccls/issues/30

**Comment by MaskRay** [comment]
`cmake -H. -BRelease -DSYSTEM_CLANG=on -DCMAKE_PREFIX_PATH=/usr/lib/llvm/6 -DLLVM_ENABLE_RTTI=on` solved the issue.
