### ISSUE TITLE
Failed to build on the latest commit

### ISSUE THREAD

**Issue by nikuolive** [MaskRay/ccls#663]
### Observed behavior

Building ccls on a new arch installation. Got hit by an error after running `cmake --build build`

the error log
```
/home/treadster/Programs/ccls/src/clang_tu.cc:27:15: error: no matching constructor for initialization of 'std::string' (aka 'basic_string<char>')
std::string ret(path);
```

### Steps to reproduce

```
git clone --depth=1 --recursive https://github.com/MaskRay/ccls
cd ccls
cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_CXX_COMPILER=clang++ -DCLANG_LINK_CLANG_DYLIB=on -DUSE_SYSTEM_RAPIDJSON=off
cmake --build build
```

### System information

* ccls latest 
* clang version: 10
* OS: Arch linux

### Solution
changing `std::string ret(path)` to `std::string ret(path.str())` seems to fixed it.

**Comment by MaskRay** [comment]
Thanks. Fixed. The explicit conversion function is newer than LLVM 10 (https://reviews.llvm.org/D73640 )
