### ISSUE TITLE
How to make ccls index current workspace

### ISSUE THREAD

**Issue by ampatzid** [MaskRay/ccls#667]
### Observed behavior

The project that I work has multiple branches. I use git worktree for these different branches. When I open nvim in both workspaces and I do get references I get results from both workspaces.
### Expected behavior

I would like to get results only from the current workspace that I have my nvim open

### Steps to reproduce

1) cd at ws1 and open nvim : 
    cd /home/ws1; nvim
2) cd at ws2 and open nvim:
   cd /home/ws2; nvim
3) call get reference at any function in the code.

### System information

* ccls version (`git describe --tags --long`):  ccls version c5acf62
* clang version: clang version 10.0.1 (/tmp/llvm-project/clang f79cd71e145c6fd005ba4dd1238128dfa0dc2cb6)
* OS: linux 
* Editor: nvim
* Language client (and version): coc.nvim version: 0.0.78

**Comment by MaskRay** [comment]
This is entirely decided by the client setup. The ccls server has implemented workspace folders.

LSP 3.6.0 workspace folders (interface InitializeParams):

> If a client workspace consists of multiple roots then a server typically needs to know about this. The protocol up to now assumes one root folder which is announced to the server by the rootUri property of the InitializeParams. If the client supports workspace folders and announces them via the corresponding workspaceFolders client capability, the InitializeParams contain an additional property workspaceFolders with the configured workspace folders when the server starts.

If your client configures `/home/ws2` as the project root, and the code does not reference `/home/ws1`, you will not seen references in `/home/ws1`

If your client configures both `/home/ws1` and `/home/ws2` as workspaceFolders, then you will naturally get both in your cross reference requests.
