### ISSUE TITLE
HOWTO:  Programmatically pre-index?

### ISSUE THREAD

**Issue by dakami** [MaskRay/ccls#67]
I have large codebases to index, I am happy this is supported at runtime but I'd like to precompile.  Also I'm not sure how dereferencing would work adhoc.  How should I do this?

**Comment by MaskRay** [comment]
ccls starts indexing the whole project (with `compile_commands.json` or hierarchical `.ccls`) after it received the `initialize` request telling it where the project resides. When you open the first file in your editor, the indexer threads are working in the background, while the main thread is serving requests from the language client plugin.

If you want to have headless indexing, you may use some specialized language client to just send an `initialize` request then wait.

**Comment by dakami** [comment]
I had thought dereferencing type definitions required a global view of the codebase in order to be accurate.  Is that not the case?

Will initialize return when indexing is complete?

**Comment by MaskRay** [comment]
`initialize` spawns several indexer threads abd returns. The main thread
does not wait for completion.

Yes, many operations require global view if the code base.

**Comment by MaskRay** [comment]
I have added some description to `README.md`

> It starts indexing the whole project (including subprojects if exist) parallelly when you open the first file, while the main thread can serve requests before the indexing is complete.
> Saving files will incrementally update the index.

**Comment by MaskRay** [comment]
Also check out https://github.com/MaskRay/ccls/issues/98 for the standalone indexing mode `-index`
