### ISSUE TITLE
Completion overwriting word

### ISSUE THREAD

**Issue by nickenchev** [MaskRay/ccls#678]
### Observed behavior
I'm not quite sure where this is configured or what it stems from, but if I switch to ```clangd``` the behavior is as expected. Also not sure if this is something people generally want and I'm weird for reporting it, but here goes:
When selecting a completion, the selected completion overwrites the current word my cursor is on.
![Screenshot_20200725_100912](https://user-images.githubusercontent.com/8262271/88458902-397e1280-ce5f-11ea-89c4-8f9864ba5a9f.png)
![Screenshot_20200725_100935](https://user-images.githubusercontent.com/8262271/88458905-3daa3000-ce5f-11ea-89c0-72f7f7f7c1bf.png)
![Screenshot_20200725_100951](https://user-images.githubusercontent.com/8262271/88458906-3f73f380-ce5f-11ea-94a6-49a56fe8e182.png)

### Expected behavior

Insert the completion candidate, rather than overwriting the word at the cursor.

### Steps to reproduce

1. Go to any word
2. Type and select a completion option

### System information
ccls version 0.20190823.6-22-gcb08df44
clang version 10.0.0 
* OS: Arch Linux (Linux Office-Arch 5.7.9-arch1-1 #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64 GNU/Linux)
* Editor: Emacs
* Language client (and version): lsp-mode (Not sure where the version is, I use straight.el, so here's the last commit in the repo)
```
lsp-mode: git log
commit 41ba941797f5c0cb9b251af5ea37922595d772bc (HEAD -> master, origin/master, origin/HEAD)
Author: kiennq <kien.n.quang@gmail.com>
Date:   Fri Jul 24 18:42:10 2020 +0900

    type-formatting: do best effort async text edits applying (#1959)
```

**Comment by MaskRay** [comment]
Apologies for my late reply. While I see you reported the issue and sh-zam added a +1, this is actually intended and appears to be favored by many other users.

The logic is in `src/messages/textDocument_completion.cc`, related to `end_pos`.

**Comment by nickenchev** [comment]
@MaskRay Thanks for the reply. What is your reply based on, was this polled at some point? Why would ccls assume that every time I get a completion, I want to overwrite whatever is at my cursor, that doesn't seem weird to you?

It seems ridiculous to force this behaviour, I don't even think I've seen any other tools do this. I regularly work with Android Studio, Xcode, IntelliJ/Eclipse, and every time I use ccls within Emacs this "feature" stands out like a sore thumb. Is there no way to disable this?

**Comment by nickenchev** [comment]
@MaskRay you said this is intended, is there no way to control this "feature"? I find it very frustrating, here's an example:

1) I create a method in my class' (VulkanRenderer) ```.h``` file:
```void updateMaterials(const std::vector<Material> &materials) const override;```

2) I copy the method declaration, so that I can paste it in the cpp file. I do this because ccls doesn't refresh the cache quickly enough after I've saved the .h file, so I can't rely on it to complete the method for me in the cpp file.

3) Switch to my ```.cpp``` file, paste the declaration from above.
```void [#]updateMaterials(const std::vector<Material> &materials) const override;```
I place the cursor in the [#] so that I can put the class name and scope operator "VulkanRenderer::". Company starts compeling, I select "VulkanRenderer::" and I'm left with this:
```void VulkanRenderer::(const std::vector<Material> &materials) const override;```

Why in the world would anybody find this useful? This happens all the time in different situations. If you simply don't want to change it because of time constraints, say the word and I'll look for other solutions.

**Comment by madscientist** [comment]
I have to agree with others here: this is frustrating behavior for me.  I suppose it might  be the case that I'm trying to replace an existing symbol with some other symbol, but >90% of the time I'm trying to add a new symbol at point, not trying to replace the already-existing symbol at point.

And, if I want to delete the existing symbol Emacs (and other editors) provide simple keystrokes so I can do that easily myself without assistance from an LSP server.

**Comment by AraragiHokuto** [comment]
Given that there is requirement for both behaviour, how about a new initialization option to allow customization for this?

@MaskRay I can try putting together a PR later if you are OK with my proposal.

**Comment by AraragiHokuto** [comment]
https://github.com/MaskRay/ccls/pull/745

Anyone interested trying that?

For now I'm keeping the original behaviour by default. Use --init={"completion": { "overwriteFollowingIdentifier": false }} to disable overwriting.

**Comment by nickenchev** [comment]
I've just cloned your code

> #745
> 
> Anyone interested trying that?
> 
> For now I'm keeping the original behaviour by default. Use --init={"completion": { "overwriteFollowingIdentifier": false }} to disable overwriting.

Hey, thanks for updating that. How should I go about testing this?

**Comment by AraragiHokuto** [comment]
> I've just cloned your code
> 
> > #745
> > Anyone interested trying that?
> > For now I'm keeping the original behaviour by default. Use --init={"completion": { "overwriteFollowingIdentifier": false }} to disable overwriting.
> 
> Hey, thanks for updating that. How should I go about testing this?

Given that it's literally only a few lines of changes, I would say probably not much to test here. :)  Maybe just use it for a while and check if it behaves as you wish, and see if it introduces some weird behaviour in unexcepted places?

**Comment by nickenchev** [comment]
> > I've just cloned your code
> > > #745
> > > Anyone interested trying that?
> > > For now I'm keeping the original behaviour by default. Use --init={"completion": { "overwriteFollowingIdentifier": false }} to disable overwriting.
> > 
> > 
> > Hey, thanks for updating that. How should I go about testing this?
> 
> Given that it's literally only a few lines of changes, I would say probably not much to test here. :) Maybe just use it for a while and check if it behaves as you wish, and see if it introduces some weird behaviour in unexcepted places?

Your previous comment asked someone to try it, so that's what I'm offering. I think you misunderstood my question btw, I'm asking how to go about running your version of ccls along with setting overwriteFollowingIdentifier. I'm not a ccls developer and currently have it installed directly from the arch AUR repo. My emacs config also doesn't specify how to initialize ccls.

Should I clone your "dev" branch with this latest change?
Do I need to specify the ```--init=...``` inside my ```.emacs``` for the ccls package?

**Comment by AraragiHokuto** [comment]
> > > I've just cloned your code
> > > > #745
> > > > Anyone interested trying that?
> > > > For now I'm keeping the original behaviour by default. Use --init={"completion": { "overwriteFollowingIdentifier": false }} to disable overwriting.
> > > 
> > > 
> > > Hey, thanks for updating that. How should I go about testing this?
> > 
> > 
> > Given that it's literally only a few lines of changes, I would say probably not much to test here. :) Maybe just use it for a while and check if it behaves as you wish, and see if it introduces some weird behaviour in unexcepted places?
> 
> Your previous comment asked someone to try it, so that's what I'm offering. I think you misunderstood my question btw, I'm asking how to go about running your version of ccls along with setting overwriteFollowingIdentifier. I'm not a ccls developer and currently have it installed directly from the arch AUR repo. My emacs config also doesn't specify how to initialize ccls.
> 
> Should I clone your "dev" branch with this latest change?
> Do I need to specify the `--init=...` inside my `.emacs` for the ccls package?

I see. You need to clone the dev branch and build ccls from it by yourself, following the instructions in wiki (https://github.com/MaskRay/ccls/wiki/Build).

After that you need to configure your editor to use the ccls binary you've just build, instead of the one you installed into system, and ask your editor to run it with the init option.

For emacs, use something like this:
```
(setq ccls-executable "/path/to/ccls/Release/ccls")
(setq ccls-args '("--init={\"completion\": {\"overwriteFollowingIdentifier\": false}}"))
```

**Comment by nickenchev** [comment]
@AraragiHokuto Thanks, I've built it ccls from source before so should be good. The issue I'm running into is not being able to checkout your ```dev``` branch.

```git clone --depth=1 --recursive git@github.com:AraragiHokuto/ccls.git```
```
ccls: git branch -r
  origin/HEAD -> origin/master
  origin/master
```

**Comment by AraragiHokuto** [comment]
> git clone --depth=1 --recursive git@github.com:AraragiHokuto/ccls.git

Append `--branch=dev` to your clone command line, or if you don't want to clone again, cd into your cloned repo and type `git checkout -b dev && git pull origin dev`.

**Comment by nickenchev** [comment]
Odd, thats the only method of pulling the remote branch I didn't try. Thanks.
Successfully built the branch, configured emacs and it seems to be working great!

**Comment by AraragiHokuto** [comment]
> Odd, thats the only method of pulling the remote branch I didn't try. Thanks.
> Successfully built the branch, configured emacs and it seems to be working great!

Nice to hear that, thanks for testing! :)

**Comment by nickenchev** [comment]
> > Odd, thats the only method of pulling the remote branch I didn't try. Thanks.
> > Successfully built the branch, configured emacs and it seems to be working great!
> 
> Nice to hear that, thanks for testing! :)

My please, thank you for making the change. :)

**Comment by MaskRay** [comment]
I asked some other users and it seems that most people think the following identifier should not be overwritten. I think not overwriting the identifier is an option the client can provide instead. So #749 just switched the default behavior.
