### ISSUE TITLE
Support #include "project_root/some_path/something.h"

### ISSUE THREAD

**Issue by kkweon** [MaskRay/ccls#679]
Hello. Thank you for creating the ccls. It's super helpful.

### Observed behavior

Bazel based project needs to use the path relative to the project root.
I cannot include the headers by the project root based path.

```
❯ tree
.
├── BUILD
├── WORKSPACE
└── temp
    ├── BUILD
    ├── temp.c
    └── temp.h

1 directory, 5 files
```

For example, I cannot do the following in any source files.

```C
#include "temp/temp.h"
```

The error message says 

```
[ccls] cannot open file '/private/tmp/ccls_test/temp/temp/temp.h': No such file or directory [E]
```

The GIF is

![ccls_screencast](https://user-images.githubusercontent.com/2981167/88470507-f9944b00-ceb1-11ea-85b2-abfcfe1358af.gif)

### Expected behavior

Support for being able to include based on the project root.

### Steps to reproduce

```bash
mkdir temp
echo '#include "temp/temp.h"' > temp/temp.c
touch temp/temp.h
```

Now the tree should look like this 

```shell
❯ tree .
.
└── temp
    ├── temp.c
    └── temp.h
```

Open at the current project directory and then open `temp/temp.c` and find the message.

### System information

* ccls version (`git describe --tags --long`): 0.20190823.6 (built from Homebrew)
* clang version: clang version 10.0.0
* OS: MacOS
* Editor: vim
* Language client (and version): coc.nvim (version: 0.0.78-2407993395)

**Comment by rhcher** [comment]
https://github.com/MaskRay/ccls/wiki/Project-Setup

**Comment by kkweon** [comment]
Thank you. I should have mentioned. 
Regardless how I create `.ccls` (whether I put the absolute path -I or put nothing or put relative path), the error happens.


![image](https://user-images.githubusercontent.com/2981167/89115588-df70e480-d43e-11ea-966a-828b5213ec19.png)

**Comment by rhcher** [comment]
It works in my here
tree : 
![image](https://user-images.githubusercontent.com/50723480/89147754-2ddeca00-d58a-11ea-81d7-5196ba706c21.png)
my .ccls
![image](https://user-images.githubusercontent.com/50723480/89147788-549d0080-d58a-11ea-983c-a41834573020.png)
and the completion working fine
![image](https://user-images.githubusercontent.com/50723480/89148088-59ae7f80-d58b-11ea-9a1f-1657480b5523.png)

**Comment by kkweon** [comment]
You are not using temp/temp.h
Bazel requires the project root based path.

**Comment by rhcher** [comment]
sorry,but it still works in my here
tree
![image](https://user-images.githubusercontent.com/50723480/89154235-11965980-d599-11ea-84b9-43efb8127d8e.png)
my .ccls
![image](https://user-images.githubusercontent.com/50723480/89154150-ec095000-d598-11ea-9190-13aec6ae6c3e.png)
code completion
![image](https://user-images.githubusercontent.com/50723480/89154103-d6942600-d598-11ea-9d6a-1ab27575168c.png)

**Comment by kkweon** [comment]
Hmm. how can i debug this? 

You can see in the following screen that ccls is reading based on the location of a file.
My PWD = `/Users/kkweon/tmp/ccls-bug` and `temp.c` is trying to load $PWD/temp/**temp/temp.h**

```
❯ tree -a
.
├── .ccls
├── build
└── temp
    ├── temp.c
    └── temp.h

2 directories, 3 files
```

![image](https://user-images.githubusercontent.com/2981167/89239365-d0f50b00-d5ad-11ea-96f5-fa361b02721e.png)


```
❯ cat .ccls
clang
%c -std=c11
-I.

❯ ccls --version
ccls version <unknown>
clang version 10.0.0

❯ screenfetch

                 -/+:.          
                :++++.          OS: 64bit Mac OS X 10.15.6 19G73
               /+++/.           Kernel: x86_64 Darwin 19.6.0
       .:-::- .+/:-``.::-       Uptime: 8d 4h 57m
    .:/++++++/::::/++++++/:`    Packages: 400
  .:///////////////////////:`   Shell: zsh 5.8
  ////////////////////////`     Resolution: 2880x1800
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue (Dark)
 :ssssssssssssssssssssssss-     Disk: 11G / 500G (7%)
  osssssssssssssssssssssssso/`  CPU: Intel Core i9-8950HK @ 2.90GHz
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  GPU: Intel UHD Graphics 630 / Radeon Pro 560X
   `ossssssssssssssssssssss/    RAM: 15805MiB / 32768MiB
     :ooooooooooooooooooo+.
      `:+oo+/:-..-:/+o+/-

```

**Comment by ekmecic** [comment]
Looks like it only happens on macOS as I'm seeing the same issue. I assume @rhcher is running on Linux, where the bug isn't reproducible.

**Comment by MaskRay** [comment]
Tested again. This works. If you use compile_commands.json, the paths are relative to `"directory"`. If you use `.ccls` or hierarchical `.ccls`, the paths are relative to the project root. There might be a problem before `#639` was fixed.

**Comment by kkweon** [comment]
It still doesn't work. Did you test on macOS?
