### ISSUE TITLE
Only headers in the same directory are being indexed

### ISSUE THREAD

**Issue by WiseMaestro** [MaskRay/ccls#68]
I have just set ccls up with emacs. I've generated compile_commands, and when I run lsp-ccls-enable from a cc file, caches are created for system headers and the corresponding headers. They are not created for all the other headers from the project that are pulled in.

For example, in foo.cc (lets say it's in the projectroot/base directory), the following headers might exist.

# include <memory>

#include "foo.h"

#include "base/bar.h"

After lsp-ccls-enable, .ccls-cache has 
@usr@include@c++@7@memory and @usr@include@c++@7@memory.blob

as well as 
base@foo.h, base@foo.h.blob, base@foo.cc, and base@foo.cc.blob

I don't get any headers for base@bar.h or base@bar.cc even though these are in the compile commands database.

Can you help me troubleshoot this? Finding references is not very useful with only a fraction of the project indexed and it's even worse for files that fully qualify their own header. If foo.cc had

#include "base/foo.h" 

then the header is not indexed at all.

**Comment by WiseMaestro** [comment]
The formatted include above is for the memory system header. Markdown had its way with the line.

**Comment by MaskRay** [comment]
Suppose `/tmp/d` is the project root.

// compile_commands.json
```javascript
[
    {
        "arguments": [ "c++", "-c", "-I.", "-o", "base/a", "base/a.cc" ], 
        "directory": "/tmp/d", 
        "file": "base/a.cc"
    }
]
```

```cpp
// base/a.cc
#include "base/foo.h"
```

This example works. You'll need `-I/tmp/d` or `-I.`, otherwise `clang -fsyntax-only base/a.cc` cannot find `base/foo.h`

**Comment by WiseMaestro** [comment]
Thanks. That helped. I'm trying to work around some issues because the project uses bazel, so compilation occurs in a sandbox of symlinks. With a change to add the project root to the include path, my hacky workflow seems to be working OK.

**Comment by MaskRay** [comment]
The directory containing the source file is an implicit search path. So `#include "base.h"` works without any `-I`.

Are you using https://github.com/grailbio/bazel-compilation-database ?

**Comment by WiseMaestro** [comment]
No. I'm using an attached listener to get a compilation database. It's based on https://github.com/google/kythe/blob/72169bc0c2025e6e5a2e12f81de7e5d4a1981f19/tools/cpp/generate_compilation_database.sh

**Comment by WiseMaestro** [comment]
Another problem I'm having is that our headers are name ".h" and this seems to be confusing ccls, which wants to treat them as c headers.

This is causing error: invalid argument '-std=c++14' not allowed with 'C' statements.

**Comment by MaskRay** [comment]
`.h` files are not indexed by themselves, but rather though other files that include them.

If you have `-std=c++14` in your `.ccls`, it will also apply to `.c` files. Use `%cpp -std=c++14`.

This is documented at https://github.com/MaskRay/ccls/wiki/Getting-started#ccls

**Comment by WiseMaestro** [comment]
Thank you for the help. This is useful info and the tool works well overall.
