### ISSUE TITLE
Progress never reset to zero

### ISSUE THREAD

**Issue by reporter123** [MaskRay/ccls#681]
### Observed behavior

Job count never drops even after all jobs are completed.

### Expected behavior

Reset job count on completion of all pending jobs 

### Steps to reproduce

1. Open project with vscode-ccls. Having it re-index on typing will be helpful
2. Wait for a jobs to complete.
3. Start new job by typing

### System information

* ccls version (`git describe --tags --long`): 0.20190823.6-23-g26add896
* clang version: 10.0.1-++20200708122807+ef32c611aa2-1~exp1~20200707223407.61
* OS:  Kubuntu 20.04
* Editor: vscode 1.47.2
* Language client (and version): vscode-ccls 0.1.29

**Comment by MaskRay** [comment]
This was immediately fixed after the bug was introduced.

**Comment by reporter123** [comment]
What ever you did the issue is still present in latest master.

**Comment by reporter123** [comment]
This is still reproducible either tell me what I doing wrong or reopen this. I can no longer use ccls with current behavior combine your apparent inability to investigate this further.
