### ISSUE TITLE
add Semicolon(；) in the end of a statement automatically

### ISSUE THREAD

**Issue by cybaol** [MaskRay/ccls#684]
### Observed behavior

When I want to complete an option
I found that there is no Semicolon(；) in the end of a statement
I suspect that if it can complete the Semicolon(；) in the end of a line or a atatement, there will be great!!!
And then I don't need to add it manually.

### Expected behavior
let's assume that
if I press <tab> to complete a statement such as printf
the Origin is printf("......")
the expected behavior is printf("......")；   //there is a Semicolon in the end of statement

### System information

* ccls version (`git describe --tags --long`): 20190823
* clang version: 10.0.0
* OS: Arch Linux
* Editor: neovim 0.5
* Language client (and version): coc.nvim v0.0.78

**Comment by findNextStep** [comment]
enable clientsnippetsupport may work https://github.com/MaskRay/ccls/wiki/Customization#clientsnippetsupport

**Comment by findNextStep** [comment]
I don`t think add (;) work in every case , for example when we write
```cpp
printf("XXX" , add$,);
```
and point is in $,we expect no (;) insert.clientsnippetsupport work and use tab (C-J in coc) to function end

**Comment by MaskRay** [comment]
Thanks to findNextStep!

I agree that auto semicolon insertion is only suitable in few cases where a function call is a statement. This functionality should probably be provided by a snippet extension or a keyboard shortcut.
