### ISSUE TITLE
The issue for the file .ccls and compile_commands.json which compiler is tricore-gcc

### ISSUE THREAD

**Issue by jiangjianshan** [MaskRay/ccls#686]
**Hello,

### System information
* ccls version (`git describe --tags --long`):  0.20190823.6-22-gcb08df44
* clang version: 10.0.0 (Target: i686-pc-windows-msvc)
* OS: Windows 10
* Editor:  Vim 8.2.1328
* Language client (and version):  coc.nvim

 I have several embedded software project and its C compiler for TriCore which is GNU GCC cross-toolchain but it triple is 'tricore'.
![image](https://user-images.githubusercontent.com/20179047/89499569-d1321800-d7f2-11ea-8370-00646fe61110.png)

the .ccls file I written is here:
![image](https://user-images.githubusercontent.com/20179047/89499540-c5deec80-d7f2-11ea-9a69-408dd7fbd049.png)

the piece of compile_commands.json is here:
![image](https://user-images.githubusercontent.com/20179047/89500590-8c0ee580-d7f4-11ea-8051-41d2a7e838da.png)

the piece of coc-settings.json is here:
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": [
        "c",
        "cpp",
        "objc",
        "objcpp"
      ],
      "rootPatterns": [
        ".ccls",
        "compile_commands.json",
        ".git/",
        ".svn/",
        ".hg/"
      ],
      "initializationOptions": {
        "cache": {
          "directory": ".ccls-cache"
        },
        "cacheFormat": "json",
        "clang": {
          "extraArgs": [
            "-nostdinc++"
          ],
          "excludeArgs": []
        },
        "client": {
          "snippetSupport": true
        },
        "completion": {
          "placeholder": false,
          "detailedLabel": false,
          "filterAndSort": false
        },
        "index": {
          "onChange": true,
          "trackDependency": 1
        }
      }
    }
  }

I have put .ccls and compile_commands.json into the project root directory,  they can't work because if I want to jump to one of definition, it will throw out such kind of error:
![image](https://user-images.githubusercontent.com/20179047/89503395-0d687700-d7f9-11ea-826c-9c530ff99aaf.png)

I think there should be something wrong with my .ccls and compile_commands.json which is using C compiler which name is 'tricore-gcc.exe'. What is the correct setting for these two files? I have look through the wiki inside ccls github but can't find the answer.

**Comment by MaskRay** [comment]
Hello. The first line of `.ccls` should be `%compile_commands.json`, instead of `%compile_commands.json%`

**Comment by jiangjianshan** [comment]
@MaskRay , sorry for late reply. Why the issue has been closed? I write the issue a long time ago and take some times to see whether there are some reply but don't have them for a long days. I have actually use "%compile_commands.json%" as the picture showing there.

**Comment by madscientist** [comment]
Please re-read MaskRay's comment.  You wrote `%compile_commands.json%`.  That's wrong.  It should be `%compile_commands.json` (no trailing percent sign).

Please check the docs more carefully and you'll see that they do not use a trailing percent (if you find some docs that are wrong please provide a link to said docs).

**Comment by jiangjianshan** [comment]
@madscientist , thanks for your hint.
