### ISSUE TITLE
c++ warning flag is applied to c and gave false warnings

### ISSUE THREAD

**Issue by laoshaw** [MaskRay/ccls#687]
Newest ccls with newest vim on ubuntu 20.04. I just noticed in my c code I had the typical type casting such as (char *) malloc(100); then ccls warns: [W] use of old-style cast.

I have -Wold-cast-style in extraArgs, that flag(along with a few others) is only applicable to c++ not c, can ccls separate extraArgs for c and c++?

ale linter can tell c from c++ and do not issue warning like this.

**Comment by laoshaw** [comment]
I just disabled coc.nvim / ccls from sending diagnostic messages, I will let ALE deal with them alone, they're pretty much duplicated anyways.

**Comment by xerrni** [comment]
create compilation database `compile_commands.json`, rather than using `.ccls` file

**Comment by laoshaw** [comment]
Thanks.
