### ISSUE TITLE
Why generate .ccls-cache both at project root and %HOME% folder?

### ISSUE THREAD

**Issue by jiangjianshan** [MaskRay/ccls#689]
Hello,

I'm using Vim 8.2.1328 and ccls which version is 0.20190823.6-23-g4cf16a7e. here is piece of my coc-settings.json:
  
"languageserver": {
        "ccls": {
            "command": "ccls",
            "filetypes": ["c", "cpp", "objc", "objcpp"],
            "rootPatterns": ["compile_commands.json", ".prettierrc.json", ".ccls", ".git/", ".svn/", ".hg/"],
            "initializationOptions": {
                "cache": {"directory": "F:/SPB_Data/.ccls-cache"},
                "cacheFormat": "json",
                "clang": {
                    "extraArgs": ["-fms-extensions", "-fms-compatibility", "-fdelayed-template-parsing"],
                    "excludeArgs": []
                },
                "client": {"snippetSupport": false},
                "completion": {
                    "placeholder": false,
                    "detailedLabel": false,
                    "filterAndSort": false
                 },
                 "index": {
                     "onChange": false,
                     "trackDependency": 1
                 }
            }
        }

I have already configured the cache directory to 'F:/SPB_Data/.ccls-cache' but the cache will be generated at project root and F:\SPB_Data\.ccls-cache'. How to make the cache only generate into the folder where is the setting of coc-settings.json, e.g. "F:/SPB_Data/.ccls-cache'?

**Comment by MaskRay** [comment]
Hello, I cannot reproduce the issue. Can you check whether does `ccls -index . --init='{"cache": {"directory": "F:/SPB_Data/.ccls-cache"}}'` store the cache files? Worth checking the log file as well.

**Comment by jiangjianshan** [comment]
@MaskRay , sorry for later reply. I have try your suggestion but failed to run the command.
![image](https://user-images.githubusercontent.com/20179047/92349477-cbd52f80-f108-11ea-8827-5364808084fe.png)

**Comment by madscientist** [comment]
You are running in a Windows command shell.  The command line MaskRay provided you was intended to be run in a POSIX shell.  If you want to run this in a Windows command shell you'll have to figure out the quoting to make it work properly...

**Comment by jiangjianshan** [comment]
Hello,

I have changed the command as below picutre showing:
![image](https://user-images.githubusercontent.com/20179047/92422652-b9aecc00-f1b0-11ea-8bd1-71beb0f28aa1.png)

The .ccls-cache can be exactly generated at the F:/SPB_Data/.ccls-cache now. For this moment it seems like I can't reproduce the issues.
