### ISSUE TITLE
spacemacs使用ccls无法自动补全QT的QDebug, QString, QFile等等没有后缀的文件, 但是iostream是可以的

### ISSUE THREAD

**Issue by wutianjun5858** [MaskRay/ccls#696]
但是自己写QDebug, QString, QFile....并不会报错
在使用qDebug()打印信息也是能够自动补全的, 只是这个#include <QDebug>之类的无法补全

**Comment by MaskRay** [comment]
This is a client issue, unrelated to ccls (language server). Your client does not consider the system header as part of the project so cross reference/completion requests are not sent to ccls. On the Emacs side, lsp-ui@2300e94a9a1d953b2f5c436c5f915da31ca2fb8b changed the new buffer to be associated with the current workspace. Your client may need a similar change.
