### ISSUE TITLE
Incomplete cross references hint

### ISSUE THREAD

**Issue by wwm0609** [MaskRay/ccls#697]
Please check the following two pics, vscode-cquery can show the cross ref count properly but vscode-ccls doesn't.
1. cquery-cross-ref-count
![cquery-crosss-ref-count](https://user-images.githubusercontent.com/35440923/92342495-97a34400-f0f3-11ea-8ed6-e4757f9a626a.png)
2. ccls-cross-ref-count
![ccls-cross-ref-count](https://user-images.githubusercontent.com/35440923/92342497-9a059e00-f0f3-11ea-9be2-1a267a2e0841.png)

The caller code is really identical, it looks like this:
```c++
void MessageQueue::Handler::handleMessage(const Message& message) {
    switch (message.what) {
        case INVALIDATE:
            android_atomic_and(~eventMaskInvalidate, &mEventMask);
            mQueue.mFlinger->onMessageReceived(message.what, mExpectedVSyncTime);
            break;
        case REFRESH:
            android_atomic_and(~eventMaskRefresh, &mEventMask);
            mQueue.mFlinger->onMessageReceived(message.what, mExpectedVSyncTime);
            break;
    }
}
```
You can find the project source code at https://android.googlesource.com/platform/frameworks/native.
The compile_commands.json is too big to upload in here, so I put it in google drive, check https://drive.google.com/file/d/1hMBmtf-Gf6m1bkHv7iSqrh5Yt1rnAQ1Y/view?usp=sharing

**Comment by wwm0609** [comment]
![Screenshot from 2020-09-07 10-34-25](https://user-images.githubusercontent.com/35440923/92343236-c91d0f00-f0f5-11ea-925c-e248f4606139.png)
And this one too, If you looked at SurfaceFlinger.cpp， you would find dispatchDisplayHotplugEvent() was called by SurfaceFlinger::processDisplayChangesLocked twice.

BTW, the 'ccls: 0/0 jobs' in bottom-right corner in also kind of weird

**Comment by MaskRay** [comment]
Does closing and reopening the file help?

**Comment by wwm0609** [comment]
Closing and reopening the file helped!
