### ISSUE TITLE
[performance] can we index all serialize cache in one file

### ISSUE THREAD

**Issue by findNextStep** [MaskRay/ccls#698]
current ccls will cache `IndexFile ` for every file in independent blob/json file, it may slow when read so many file and i think write all `IndexFile` in one file may faster.
现在的ccls为每一个文件的`IndexFile`对象保存到唯一的文件中，这可能会导致读取所有文件的速度很慢（尤其是较大的工程中），我认为我们或许可以将cache写在同一个文件里，这可能会更快。

**Comment by MaskRay** [comment]
There is a serious issue with concurrent cache update. Another problem is that incremental changes are more difficult. This requires a database design which will significantly complicate the server.

> it may slow when read so many file and i think write all IndexFile in one file may faster.

And this claim should be benchmarked as well.
