### ISSUE TITLE
designated initializers are a C99 feature

### ISSUE THREAD

**Issue by Luis-Hebendanz** [MaskRay/ccls#699]
In c++20 designated initializers have been added.
So this error should be removed.

### Reproduce
```
struct kvm_userspace_memory_region memory {
      .slot = 0,
      .flags = 0,
      .guest_phys_addr = 0,
      .memory_size = 0x1000,
      .userspace_addr = (unsigned long)mem,
}
```

### System information

* ccls version: clang version 8.0.1 (tags/RELEASE_801/final)
* clang version: 10.0.0 
* OS: NixOS
* Editor: vim 
* Language client (and version):

**Comment by myrgy** [comment]
Hi @Luis-Hebendanz , I assume that error was removed in clang 11

**Comment by Luis-Hebendanz** [comment]
I see!
