### ISSUE TITLE
Does the diagnostic can be disabled?

### ISSUE THREAD

**Issue by Abbyyan** [MaskRay/ccls#701]
There are a lot of repos in my project, and i just clone part of them on my own PC. When i open with a repo on my PC, it will show a lot of diagnostic errors which i don't care about them. I just want to use the `go definition` and `go reference`  function of ccls. Is there any method i can use to disable the diagnostic sometime please? Thanks a lot.

**Comment by MaskRay** [comment]
You can probably use a client side suppression mechanism...
