### ISSUE TITLE
Relative "directory" in compile_commands.json does not work if CWD != project root

### ISSUE THREAD

**Issue by rohit04saluja** [MaskRay/ccls#703]
**Observed behavior**
ccls does not work when directory value in compile_commands.json is relative to the root (workspace). ccls works with directory value in compile_commands.json as absolute.

**Expected behavior**
If directory value in compile_commands.json is a relative to root (workspace) path, then it should be resolved using the root.

**Steps to reproduce**
Just give directory a relative value w.r.t root in compile_commands.json.

System information
ccls version: 0.1.28
OS: Linux
Editor: vs-code

I was able to see in the code that when we are getting the directory information we don't check for the relative path as we do for _filename_.

// If workspace folder is real/ but entries use symlink/, convert to // real/. entry.directory = realPath(cmd.Directory); normalizeFolder(entry.directory); doPathMapping(entry.directory); entry.filename = realPath(resolveIfRelative(entry.directory, cmd.Filename)); normalizeFolder(entry.filename); doPathMapping(entry.filename);

Just like we resolve value if it is relative, for filename with the anchor as directory, we should resolve if relative for directory as well with the anchor as root.

**Comment by MaskRay** [comment]
```json
% cat compile_commands.json 
[
    {
        "arguments": [
            "g++",
            "-DA",
            "-c",
            "-o",
            "a",
            "a.cc"
        ],
        "directory": ".",
        "file": "a.cc"
    }
]
```

This works fine.

**Comment by rohit04saluja** [comment]
Hey @MaskRay I am using a similar compile_commands.json with the "command" key in place of the "arguments" key in vscode, but it's not working. Any leads on how I can debug it?

**Comment by MaskRay** [comment]
`"command"` should work as well. https://github.com/MaskRay/ccls/wiki/Debugging has some tips for debugging. In particular, you can set up a breakpoint on `Project::findEntry` before opening a file.

**Comment by rohit04saluja** [comment]
The issue is that VSCode does not chdir to the project root. Thus directory path relative to users directory works fine as  mentioned above

**Comment by MaskRay** [comment]
Thanks for confirmation. #711

**Comment by rohit04saluja** [comment]
@MaskRay should we fix the change directory bug in the VSCode client as well?
