### ISSUE TITLE
add goto 'parent'

### ISSUE THREAD

**Issue by Frydac** [MaskRay/ccls#706]
This is a feature request, or it is already possible but I haven't found it.

I used to use rtags some time ago, and I sometimes miss some functionality it had, it had the notion of goto 'parent', meaning:
* if the cursor is inside a function -> goto the function signature->function name
* if on a function signature/name -> goto surrounding class name if member function, goto namespace name if free function
* if on a class name -> goto surrounding class/namespace
* if on a namespace name -> goto surrounding namespace

maybe there are more of these that I don't know about.

My usecase for it is to find a possible callstack some functionality could be part of, going up a callstack, for example:
* I am on a function, I goto references, choose one, then I would goto parent function name (with confidence with one key combo), goto references, and so on.
Also when exploring unknown code with big/long functions/classes/files, it can be handy to get your bearings from time to time.

Maybe a feature request that is related is to be able to print the current fully expanded type of the symbol the cursor is on, meaning with all the namespaces, classes(, templates). Which can also be very handy when exploring unknown code.

If these usecases are covered by existing functionality, then please enlighten me :)

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/LSP-Extensions#cclsnavigate `$ccls/navigate` with `"directory": "U"` is what you need.

**Comment by Frydac** [comment]
Indeed, thanks!
