### ISSUE TITLE
index also system include files?

### ISSUE THREAD

**Issue by xwl** [MaskRay/ccls#707]
### Observed behavior

When following the types defined in  some system include files, for example, <vector>, inside the vector file, one can't look up definitions of objects defined (e.g., __vector_base) there, the file seems simply not indexed. 

This is one feature that i missed a lot from rtags (where rtags supports it quite well)

### Expected behavior

Able to find definitions inside system include files

### Steps to reproduce

1. open your project, follow definition of std::vector
2. inside the <vector> file, try to follow definition of its base class "__vector_base"

You will get, file not indexed error.

### System information

* ccls version (`git describe --tags --long`): 0.20190823.6-26-g141aea8a
 (git commit: 141aea8ae61a960ce6243dca2a17ef587888ce3e)
* clang version: 10.0.0
* OS: Linux
* Editor: Emacs
* Language client (and version): eglot

**Comment by MaskRay** [comment]
This is a client issue, unrelated to ccls (language server). Your client does not consider the system header as part of the project so cross reference requests are not sent to ccls. On the Emacs side, lsp-ui@2300e94a9a1d953b2f5c436c5f915da31ca2fb8b changed the new buffer to be associated with the current workspace. Your client may need a similar change.
