### ISSUE TITLE
In specific scenario, indexing performance degrades extremely when .ccls file is present

### ISSUE THREAD

**Issue by summer-tt** [MaskRay/ccls#710]
### Observed behavior

* I use vim + coc.nvim + latest ccls + clang 11.0.0

* My project tree is like:
		SDK_ROOT/
		├── makefile.top
		├── apps
		│   ├── **A**
		│   ├── B
		│   ├── **C**
		│   └── D
		│   └── ....
		├── drivers
		│   ├── ....
		│   ├── X
		│   ├── **Y**
		│   └── Z
		├── kernel_ver1
		├── kernel_ver2
		├── kernel_ver3
		└── kernel_ver4

it is a full-fledged Linux SDK for some embedded system, which contains dozons of apps, dozeon of drivers and 4 different versions of Linux kernel code, and the files I feed to ccls is just a very small subset of that SDK (dirs marked as **bold font** as above).

* The compile_commands.json file (generated by  [compile_db](https://github.com/nickdiego/compiledb), and exists under **_SDK_ROOT_**) is about 301K lines long, which consistss of about 900 files' compile option info, and each file entry contains lots of -Dxxx and -Ixxx options.

I inspected the following different cases:

1. If there is **no .ccls file under the _SDK_ROOT_**, ccls **takes seconds** to finish indexing. 

1. If I add **under _SDK_ROOT_ dir** a .ccls file **which only contains one line: %compile_commands.json**, it takes **more than 4 minutes** for ccls to finish indexing. And during these 4 minuts, the CPU time taken by ccls process is mostly below 10%.

1. If I **move the .ccls file from SDK_ROOT into _apps_ folder**, the indexing again takes seconds to finish. But after reviewing the log file I believe **SDK_ROOT/apps/.ccls** file is not loaded by ccls.

Below is the log, abtained by appending `--log-file=/tmp/ccls.log -v=1` to ccls command.

1. ccls log when .ccls is not present at all:
![image](https://user-images.githubusercontent.com/656838/97174875-a510ac80-17cd-11eb-9fa9-691b0f55fe86.png)
![image](https://user-images.githubusercontent.com/656838/97175257-2ff1a700-17ce-11eb-95e9-d41a0e8e3cf2.png)

1. ccls log when .ccls file is present in **_SDK_ROOT_** folder:
![image](https://user-images.githubusercontent.com/656838/97173080-f7040300-17ca-11eb-9c88-c863e7bdc8e0.png)

1. ccls log when .ccls file is present in **_apps_** folder:
![image](https://user-images.githubusercontent.com/656838/97184065-7e587300-17d9-11eb-97a9-620d76ea0168.png)

### Expected behavior

With or without .ccls file present in the project root dir, the indexing time taken by ccls should be nearly the same.

### Steps to reproduce

1. Create a compile_commands.json file with [compile_db](https://github.com/nickdiego/compiledb), commands is like: make -B -n targetA targetB ... | compiledb
2. Open vim project ([Obsession ](https://github.com/tpope/vim-obsession)saved) and see how long it takes ccls to finishing indexing.
3. Create one .ccls file under project root which only contains one line: %compile_commands.json
4. Re-open vim project and observe the indexing time again.
5. Move the .ccls file to **_apps_** subfolder of the project, the subfolder contains a subset of the source code files listed in compile_command.json.
6. Re-open vim project and observe the indexing time again.

### System information
* I use vim + coc.nvim + ccls, and my project is a Linux SDK for an embedded system, which uses make + gcc cross compiler.

* My OS info:
![image](https://user-images.githubusercontent.com/656838/97173264-3c283500-17cb-11eb-9894-ee226b3987da.png)

* Vim version:
![image](https://user-images.githubusercontent.com/656838/97174141-a392b480-17cc-11eb-9579-648d8cf7cb37.png)

* ccls version (`git describe --tags --long`): 
0.20201025-0-g1fec76c
![image](https://user-images.githubusercontent.com/656838/97172782-7e04ab80-17ca-11eb-9e04-9041d732ae21.png)

* CocInfo command in Vim shows:
![image](https://user-images.githubusercontent.com/656838/97172405-f3bc4780-17c9-11eb-997c-58d9e1e9ed96.png)

* coc.nvim config for ccls:
![image](https://user-images.githubusercontent.com/656838/97174002-69c1ae00-17cc-11eb-88f1-19980b8c9859.png)

**Comment by MaskRay** [comment]
Can you compare the output of `/tmp/ccls.log` when .ccls is present or absent. The file should also say whether there are more indexed files.

You can also use the standalone mode: `rm -r .ccls-cache; ccls --index=path/to/project --log-file/tmp/ccls.log -v=1`

**Comment by summer-tt** [comment]
> Can you compare the output of `/tmp/ccls.log` when .ccls is present or absent. The file should also say whether there are more indexed files.
> 
> You can also use the standalone mode: `rm -r .ccls-cache; ccls --index=path/to/project --log-file/tmp/ccls.log -v=1` to exclude the external factors.

@MaskRay , I tried adding `--index=path/to/SDK_ROOT` arg, but after reviewing the log, it turns out that it will try to index the whole SDK, which is not what I wanted.

Actually, I only want to index a subset of the SDK, and since the subset source code files resides in different sub-folders (SDK_ROOT/apps/A, SDK_ROOT/apps/B, SDK_ROOT/drivers/Y) , I cannot use a single `--index` arg to include all the files I need while not including irrelavant files.

But to exclude as much external factors as possible, I tried a different repeat method:

1. Remove all .ccls files in my project
2. Execute `rm -rf /tmp/.ccls-cache/*`
3. Open vim with an empty buffer, and working dir is SDK_ROOT
4. Load one file udner SDK_ROOT/apps/A dir to trigger coc.nvim to invoke ccls
5. Review /tmp/ccls.log in vim
6. Add .ccls file under SDK_ROOT dir, the file contains only one line: `%compile_commands.json`, and repeat step 2~5

In vim, I use `:%s/indexer.* store index for .*\.c//gn` command to count all the indexed *.c files, and:
1. Without .ccls file
   * the count number is 916, **same as number of files listed in SDK_ROOT/compile_commands.json.**
   * indexing took **1 min 43s**
2. With .ccls file
   * the count number is 916, **same as number of files listed in SDK_ROOT/compile_commands.json.**
   * indexing totally took **8 min 35s**
   * log shows that at the line: **_project.cc:284 I use /path/to/SDK_ROOT/.ccls: %compile_commands.json_**, ccls stuck here for **6 min 38s**, and the reset indexing took **1min 55s** 

After I view the project.cc file, I wonder if it is slow becasue **`getFilesInFolder`** function traverse all files in SDK_ROOT ? If that's so, it explains. And if it is so, is there a way to fix it?
![image](https://user-images.githubusercontent.com/656838/97253579-c7dfa700-1847-11eb-9c89-1caaefb3657f.png)

**Comment by summer-tt** [comment]
I found a work-around for my use case.

To be specific, I just want to feed some project/module specific options to ccls for the files I want  to parse, e.g., ignore some warnings, add cross compiler specific system header file search path, exclude some compiler options.....

I found [`clang.extraArgs`](https://github.com/MaskRay/ccls/wiki/Customization#clangextraargs--clangexcludeargs) in `initializationOptions` can mostly do what I want. And I found the discussion in [#138 ](https://github.com/MaskRay/ccls/issues/138) very helpful.

Since I use [coc.nvim](https://github.com/neoclide/coc.nvim), I add a project specific coc-settings.json file, which looks like this:

![image](https://user-images.githubusercontent.com/656838/99958031-94028d80-2dc3-11eb-9a84-0a17a85d1c41.png)

It solves most of my current problem, however, I still haven't figured out how to do a module specific config, since my project contains source code from many modules. If .ccls can work as I expected, I can add a different .ccls files at different modules' dir. So, I wish to keep this issue open,  hoping there is a good way to do module specific config.

But still, thanks very much for your project @MaskRay , I think ccls is really usefully for lots of people!!

PS: Before I found this work-around, I took a detour to try clangd, and to be very honest, clangd's **current** indexing performance is **really** awfully!!! When I was edting some source file from one of my Linux driver module, it takes tens of seconds to give completion info back to coc.nvim....... But @MaskRay I also need to say this: maybe 'cquery' option is not so bad? Since it's very straight forward, I'd say it's kinda user-friendly.

**Comment by MaskRay** [comment]
> After I viewed the project.cc file, I wonder if it is slow becasue getFilesInFolder function traverses all folders in SDK_ROOT ? If that's so, it explains, and is there a way to fix it?

Yes.

> And it seems that for clangd .clangd file can work as I expected without sufferring performance degrade, if .ccls file could do the same, that would be terrific!!

`.clangd` does not traverse all files IIUC. `.ccls` is different: it traverses all source files. https://github.com/MaskRay/ccls/wiki/Project-Setup Empirically for larger projects `compile_commands.json` should be used to avoid the directory traversal.

The initialization option `index.initialBlacklist` may be useful if you have to use `.ccls`: https://github.com/MaskRay/ccls/wiki/Customization#indexinitialblacklist
