### ISSUE TITLE
Parallelize initial loading phase of ccls in VS code

### ISSUE THREAD

**Issue by betasheet** [MaskRay/ccls#719]
AFAICT, when using the VS code extension for ccls, the extension seems to send the list of opened files to ccls, and ccls then immediately starts to (re)index those files (if necessary?). That's probably a good idea - however, this seems to happen on a single thread (htop shows one core at 100% and the others idle). As a result, when opening VS code with half a dozen or more files opened, the extension shows "loading" for a rather long time. Is there a way to parallelize more of the loading phase?

**Comment by MaskRay** [comment]
> send the list of opened files to ccls, and ccls then immediately starts to (re)index those files (if necessary?).

for textDocument/didOpen files, ccls do check whether they need to be re-indexed.

>  That's probably a good idea - however, this seems to happen on a single thread (htop shows one core at 100% and the others idle).

It is parallelized. Please see `index.threads` (https://github.com/MaskRay/ccls/wiki/Customization#indexthreads)
