### ISSUE TITLE
ccls complaints cannot found file

### ISSUE THREAD

**Issue by xeechou** [MaskRay/ccls#72]
I am using the ccls-git from **AUR**. This weekend I just updated it and from then I keep receiving the error.

    16:11:05 comp-preload clang_complete.cc:546 I create completion session for path_to_the_header_file
    16:11:05 ccls         message_handler.cc:169 I unable to find file "path_to_the_header_file.", 

This header is generated from XML, after this I keep receiving the same error and completion is broken. 

And do you know here what went wrong? Thanks.

**Comment by MaskRay** [comment]
Your `.ccls` is incorrect. `path_to_the_header_file` is supposed to be a placeholder, not to let you just type it verbatim...

**Comment by xeechou** [comment]
`the_path_to_the_header_file` is not the one in the error message. I masked
it because it is not related to the problem.

Le lun. 3 sept. 2018 21 h 28, Fangrui Song <notifications@github.com> a
écrit :

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/blob/master/src/messages/textDocument_didOpen.cc#L71

```c++
    // Submit new index request if it is not a header file.
    if (SourceFileLanguage(path) != LanguageId::Unknown) {
      Project::Entry entry = project->FindCompilationEntryForFile(path);
      pipeline::Index(entry.filename,
                      params.args.size() ? params.args : entry.args, true);

      clang_complete->FlushSession(entry.filename);
    }
```

A `.h` file will not be indexed by itself. There should be some `.c` `.cc` `.cpp` files including it.

**Comment by MaskRay** [comment]
With recent improvement to the pipeline, I revisited this just now and pushed a commit to support indexing new `.h` in `textDocument/didOpen`

```cpp
    // Submit new index request if it is not a header file or there is no
    // pending index request.
    if (SourceFileLanguage(path) != LanguageId::Unknown ||
        !pipeline::pending_index_requests)
      pipeline::Index(path, args, IndexMode::Normal);
```
