### ISSUE TITLE
Failed to initialize server "'ccls'".

### ISSUE THREAD

**Issue by bloody82** [MaskRay/ccls#722]
Hello.
I can't get vim-lsc to work with ccls. When I open a .cpp file in vim (equipped with vim-lsc) I can see the following set of messages:

    Error detected while processing function <SNR>13_OnOpen[4]..lsc#file#onOpen[3]..lsc#server#start[3...<SNR>27_Start[41]..4[2]..7[4]..10[2]..12[2]..13[2]..14:

    E631: ch_sendraw(): write failed

    [lsc:Error] StdErr from 'ccls': executing job failed: No such file or directory
    [lsc:Error] Failed to initialize server "'ccls'".

My .vimrc (a part relevant to vim-lsc setup):

    ...
    if empty(glob('~/.vim/autoload/plug.vim'))
      silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-    plug/master/plug.vim
      autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif

    call plug#begin()
    Plug 'natebosch/vim-lsc'
    call plug#end()

    "run PlugInstall if there are missing plugins
    if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
      autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif

    let g:lsc_server_commands = {
    \  'cpp': {
    \    'command': 'ccls',
    \    'message_hooks': {
    \        'initialize': {
    \            'initializationOptions': {'cache': {'directory': '/tmp/ccls/cache'}},
    \        },
    \    },
    \  },
    \}
    let g:lsc_auto_map = v:true

I have also tried different permutations of 'lsc_server_command' section (found in some arbitrary web sources) but none did work.

My .ccls (it is of course located in the project root - above the open source file):
    clang
    %cpp -std=c++14
    %cpp -stdlib=libc++

ccls is successfully built, added to the PATH and invokable from CLI. I'm not equipped with compile_commands.json.
My project folder is pure sources - a bunch of .cpp classes. No way all headers from #includes are available and there is no way it can be built. I hope it doesn't prevent available tools like ccls/clangd from parsing existing scope and providing proper LSP features (look: vs code) - please correct me if I'm wrong. I know this is more like a question to ccls itself but first I'am trying to seek a lead regarding what's going on on the lsc <-> ccls border or perhaps you're able to suggest me anything relevant on the topic.  I've been struggling with it, I appreciate any help.
 
vim 8.1
vim-lsc (no idea how to check its version but it's freshly loaded with the vim-plug as shown)
ccls version (`git describe --tags --long`): "no names, nothing to describe"
ccls --version: ccls version <unknown> clang version 10.0.0-4ubuntu1
Ubuntu 20.04 LTS (WSL - Windows Subsystem for Linux)

**Comment by Waqar144** [comment]
You might wanna make your post a bit more readable by using stuff like formatting and code blocks.

**Q**: What's the output of running `ccls --index=.` in the project root directory? Does the directory afterwards contain a `.ccls-cache`?

**Q**: Is `/tmp/ccls/cache` accessible and writable?

You can try `coc.nvim` plugin, it usually works and is much better than everything out there.

**Comment by bloody82** [comment]
Hello. I have edited my answer to apply better formatting (thanks for the suggestion:)

`/tmp/ccls/cache` did not indeed exist (I thought it is perhaps auto-generated). I created this and now all preceding errors are gone but this one still shows up:
`[lsc:Error] Failed to initialize server "'ccls'".`

`ccls --index=.` output:

    15:34:37 ccls           initialize.cc:274 I initialize in directory /home/user/foolsmate/foolsmate with uri file:///home/user/foolsmate/foolsmate/.
    15:34:37 ccls           initialize.cc:297 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":".ccls-cache","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":[],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100,"placeholder":true},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":false,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
    15:34:37 ccls           initialize.cc:329 I use -resource-dir=/home/user/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04/lib/clang/11.0.0
    15:34:37 ccls           initialize.cc:361 I workspace folder: /home/user/foolsmate/foolsmate/
    15:34:37 ccls              project.cc:284 I use /home/user/foolsmate/foolsmate/.ccls: clang %cpp -std=c++14 %cpp -stdlib=libc++
    15:34:37 ccls           initialize.cc:386 I start 8 indexers
    15:34:37 ccls           initialize.cc:394 I dispatch initial index requests
    entries:	8
    completed:	0/8
    15:34:37 indexer6         pipeline.cc:298 I load cache for /home/user/foolsmate/foolsmate/CGameHistory.cpp
    15:34:37 indexer3         pipeline.cc:298 I load cache for /home/user/foolsmate/foolsmate/CMoveArray.cpp
    15:34:37 indexer0         pipeline.cc:298 I load cache for /home/user/foolsmate/foolsmate/CLookupData.cpp
    15:34:37 indexer4         pipeline.cc:298 I load cache for /home/user/foolsmate/foolsmate/CTranspositionTable.cpp
    15:34:37 indexer7         pipeline.cc:298 I load cache for /home/user/foolsmate/foolsmate/CAISearchAgent.cpp
    15:34:37 indexer2         pipeline.cc:298 I load cache for /home/user/foolsmate/foolsmate/CEngineIO.cpp
    15:34:37 indexer1         pipeline.cc:298 I load cache for /home/user/foolsmate/foolsmate/CMoveGenerator.cpp
    15:34:37 indexer5         pipeline.cc:298 I load cache for /home/user/foolsmate/foolsmate/CGameState.cpp
    completed:	8/8

Yes - `ccls --index=.` command generated folder `.ccls/cache`. I'm presenting its content:

    .ccls-cache/
    ├── @@home@user@foolsmate@foolsmate
    │   ├── @home@user@clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04@lib@clang@11.0.0@include@intrin.h
    │   └── @home@user@clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04@lib@clang@11.0.0@include@intrin.h.blob
    └── @home@user@foolsmate@foolsmate
        ├── CAISearchAgent.cpp
        ├── CAISearchAgent.cpp.blob
        ├── CAISearchAgent.h
        ├── CAISearchAgent.h.blob
        ├── CEngineIO.cpp
        ├── CEngineIO.cpp.blob
        ├── CEngineIO.h
        ├── CEngineIO.h.blob
    ... and all remaining source files equivalents.

This indexing part seems to look not bad (??) Any idea what error `vim-lsc` might be talking about?

**Comment by Waqar144** [comment]
**`vim-lsc` is saying**: `E631: ch_sendraw(): write failed`. That probably means that `/tmp/ccls/cache` is not writable unless you `sudo`.

Anyways, to make this work you just need to use `.ccls-cache` as your cache path:

```viml
let g:lsc_server_commands = {
\  'cpp': {
\    'command': 'ccls',
\    'message_hooks': {
\        'initialize': {
\            'initializationOptions': {'cache': {'directory': '.ccls-cache'}},
\        },
\    },
\  },
\}
```

That should make it work

**Comment by bloody82** [comment]
It's working. I had also wrong PATH content, this is why lsc couldn't find `ccls`. I added `~/` to the PATH instead of the explicit path (I thought it should work with `~` either).

Thank you very much! I have learnt something.
