### ISSUE TITLE
[new]c/c++ Header file macro definition define/undefine recognition error

### ISSUE THREAD

**Issue by HarmonyAngel** [MaskRay/ccls#723]
Hi,
I have a problem with C/C++ header file macro definition.
For example, there are two header files a.h b.h and a source code file src.c. If a macro "#define TEST 1" is defined in b.h, the macro is used in a.h for code isolation, but there is no "include b.h" displayed. Then After make is compiled, vscode will do inactive processing of the isolated code in a.h based ccls, alse causing to be unable to search for this code.
This is very common in some open source products such as postgres.
Because the macro definition is displayed and defined in b.h, compile_command.json cannot recognized it to a.h, so in the final vscode processing, ccls gives inactive processing in a.h.
If I use the c_cpp plug-in and define global macros in c_cpp_properties.json, I can make up for this problem. But based on ccls, I still don't know how to deal with it, so please help me solve it.
Note, some project compile is base on some more complex makefile, like postgres(database). And There are so many such cases.
Thank you very much.

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/FAQ#diagnostics-in-headers
