### ISSUE TITLE
Reindexing each time I quit the editor (nvim)

### ISSUE THREAD

**Issue by ranjithshegde** [MaskRay/ccls#724]
---

### Observed behavior

Each time the text editor is launched, ccls reindexes. On projects with 50+ lines of code it takes about 3-9 minutes
Recent error (roughly 10-15 days)

### Expected behavior

Describe what you expected to happen.

### Steps to reproduce

1. created ctags file with "ctags -R ~/project"
2. run compiledb
3. open a project and code
4. reopen the file - reindexes
### System information

* clang version: 11.0.0
* OS: Arch, 5.8.14-zen kernel
* Editor: NVIM v0.4.4
* Language client (and version): (LanguageServerProtocol) LanguageClient-neovim 0.1.160

**Comment by torokati44** [comment]
Is this a duplicate of #718?
Could you verify using the comments on that issue - for example, by reverting cb08df4 from master?

**Comment by ranjithshegde** [comment]
Thank you. I reverted the head you mentioned

Now it only reindexes on reboot (which I guess is related to /tmp being cleared?)

**Comment by MaskRay** [comment]
Fixed https://github.com/MaskRay/ccls/issues/718#issuecomment-748558171
