### ISSUE TITLE
Hint nvim-lspconfig configuration in wiki

### ISSUE THREAD

**Issue by matu3ba** [MaskRay/ccls#727]
Instructions for [nvim-lsp](https://github.com/neovim/nvim-lspconfig#ccls) could be added to wiki. The [editor table](https://github.com/MaskRay/ccls/wiki/Editor-Configuration) is also missing nvim-lspconfig.

**Comment by MaskRay** [comment]
Added a stub https://github.com/MaskRay/ccls/wiki/nvim-lspconfig. Hope users can contribute to the  wiki...
