### ISSUE TITLE
Question: Can .ccls allow flags are applied for files both list or not list in compile_commands.json

### ISSUE THREAD

**Issue by xaljer** [MaskRay/ccls#732]
As description in Wiki:
> By default .ccls compiler flags are applied only to files not listed in compile_commands.json. If this directive appears first in .ccls, the compiler driver must be omitted. After compile_commands.json is parsed, the rest of the .ccls arguments will be appended to the compiler flags for files found in compile_commands.json.

In some big projects, my own build target may not cover all files. But when I view those files, I want to at least avoid errors on bool/size_t/NULL stuffs. So I want to add extra include path to all files in cross-compile project.

**Comment by MaskRay** [comment]
Use `%compile_commands.json`: https://github.com/MaskRay/ccls/wiki/Project-Setup#compile_commandsjson-1

Uncovered files are not a problem. `src/project.cc` infers their compiler options from nearby source files.

**Comment by xaljer** [comment]
How to define "nearby"? I indeed got errors because of some std header files not found on uncovered files.
Specify it explicitly is better than do "infer"?
