### ISSUE TITLE
Does cache.retainInMemory: 0 require index.threads: 1?

### ISSUE THREAD

**Issue by Manouchehri** [MaskRay/ccls#733]
Just reading the docs and wasn't quite sure, is it safe to use multiple threads (e.g. `"ccls.index.threads": 8`) with `"ccls.cache.retainInMemory": 0` (never retain)?

I'm using VS Code on Linux, not sure if that makes a difference at all.

**Comment by MaskRay** [comment]
Yes, it is safe to use `"ccls.cache.retainInMemory": 0` with multi-threading.

**Comment by Manouchehri** [comment]
Thank you! 🙂
