### ISSUE TITLE
mainLoop(): variable `last_completed` is never updated, resulting in many identical progress updates

### ISSUE THREAD

**Issue by joelhock** [MaskRay/ccls#734]
### Observed behavior
When processing a file, many identical progress reports are sent back.  I believe this is because `mainLoop()` never updates the `last_completed`, variable, so this condition is always true:
```
    int64_t completed = stats.completed.load(std::memory_order_relaxed);
    if (completed != last_completed) {
```
i'd do a pull request, but it's not clear to me what the right fix is.

### Expected behavior
only progress reports that differ from the last state are sent.

### Steps to reproduce

1. run with -v 2
2. open a long-to-compile file that has lots of headers that is cached
3. see lots of identical progress reports being sent

### System information

* ccls version `0.20201025-2-g2ad71f10` 
* clang version: `clang version 11.0.0 (https://github.com/llvm/llvm-project.git 176249bd6732a8044d457092ed932768724a6f06)`
* OS: linux
* Editor: vscode
* Language client (and version): ccls extension 0.29

**Comment by MaskRay** [comment]
Thanks! `last_completed` should be set to `completed`. Fixed by 5108cfafcb709f42f86d8f6e445323c24ee4fc35 (amended that commit)
