### ISSUE TITLE
ccls on OSX 10.11 

### ISSUE THREAD

**Issue by C2vsh2nk2** [MaskRay/ccls#735]
Hey,

i am not able to install llvm via homebrew due to the lack of support for older verisons on mac (i am on macbook mid 2009). I would like to know which installation method i should follow? and if yes, which minimum llvm version will work, do i use the on shipped from Xcode 8? 

thank you.

**Comment by findNextStep** [comment]
the minimum version of llvm should be llvm8, it work for me
you can try the way build with llvm tar
```shell
wget -c https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
tar xf clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$PWD/clang+llvm-8.0.0-x86_64-apple-darwin
cmake --build Release
```
may be work for you(i don`t test yet :(
