### ISSUE TITLE
`normalizePath` removing `/usr/` from include path

### ISSUE THREAD

**Issue by miguelsaldivar** [MaskRay/ccls#737]
Here are some things you should try before filing a bug report:
### Observed behavior
When using ccls on a project, it would jump to paths that did not exist.

Describe what happened. Any aids you can include (that you think could be relevant) are a tremendous help.

* `compile_commands.json` or `.ccls` ([wiki/Project-Setup](https://github.com/MaskRay/ccls/wiki/Project-Setup))
* Reduce to A minimal set of `.c` `.cc` `.h` `.hh` files that can still demonstrate the issue.
* Consider a screencast gif.

### Expected behavior
The issue stems from `normalizePath at platform_posix.cc:44`. 
When the path is something like: `/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/x86_64-pc-linux-gnu/bits/cpu_defines.h`. The `usr` directory seems to be a part of those dots, which is what gets removed, leaving the
the path to be: `/include/c++/10.2.0/x86_64-pc-linux-gnu/bits/cpu_defines.h`. So in reality it should be: `/usr/include/c++/10.2.0/x86_64-pc-linux-gnu/bits/cpu_defines.h`, which is what `file.RealPathName` seems to be in `pathFromFileEntry at clang_tu.cc:33`. The code before [this commit](https://github.com/MaskRay/ccls/commit/cb08df44aa552d3120e2e1d317f9aaafdf2cfd65) seems to solve that issue for me.

### System information

* ccls version (`git describe --tags --long`): 0.20201025-2-g2ad71f10
* clang version: 11.0.0
* OS: Manjaro
* Editor: neovim
* Language client (and version): coc.vim

**Comment by MaskRay** [comment]
Thanks for the analysis.

Fixed by amended ca95f48a53b91be9646b6ab4943f4af3db8367f7 `Support workspaces as symlinks and symlinks within a workspace`

**Comment by miguelsaldivar** [comment]
@MaskRay thanks for fixing so fast, and awesome work with this project :)
