### ISSUE TITLE
How to configure multiple compile_commands.json

### ISSUE THREAD

**Issue by marumuga** [MaskRay/ccls#738]
Hi There:

I'm new to using the CCLS plugin on VScode. I'm mainly using it for getting my source tagging work better. I'm new to this forum, so please advise, how to handle the problems I'm facing. Also, if I missed any posting guideline, please let me know.  

**Question-1:** How do I know, if CCLS took the compile_commands.json, and ran successfully ? 

For example, these are some generic traces I noticed (I removed file path and repetitive traces)
These are some common trace I see from the "Output" window:
15:38:41                initialize.cc:386 I start 6 indexers
15:38:41                initialize.cc:394 I dispatch initial index requests
15:38:42                pipeline.cc:386 I parse < file name >
15:38:42                pipeline.cc:397 I store index for < file name >
15:38:42                pipeline.cc:298 I load cache for < file name >
... 
More "I parse", "I store" and "I load cache" traces for the various files in my project
...
15:38:43                pipeline.cc:493 I loaded project. Refresh semantic highlight for all working file.
15:38:43                pipeline.cc:397 I store index for < file name >
...
15:38:43                pipeline.cc:397 I store index for < file name >
...

**Question-2:** Also, I noticed that CCLS doesn't process (because I don't see parse/load/store trace for those files) every single file specified in the compile_commands.json, is this expected ?

**Question-3:** When I have two sub components inside my project from the same repo, but each subcomponent has its own cmake build commands, how can I configure CCLS to use the respective compile_commands.json ? One option I thought was to merge these two compile commands, and place it in the root directory, but with this approach, I din't notice a big difference, it seemed as if though only one of those subcomponents got processed. How to approach this situation ?

### System information
* ccls version (`git describe --tags --long`):  Unknown
* clang version: 11.0.0
* OS: MacOS Catalina
* Editor: VScode
* Language client (and version): 

Thanks you for your time, and help!

**Comment by MaskRay** [comment]
> **Question-1:** How do I know, if CCLS took the compile_commands.json, and ran successfully ?

`Project::loadDirectory`

Something like `project.cc:426 I loaded /tmp/d/compile_commands.json` in the log file.

> **Question-2:** Also, I noticed that CCLS doesn't process (because I don't see parse/load/store trace for those files) every single file specified in the compile_commands.json, is this expected ?

From you uploaded load, `compile_commands.json` is not loaded. By default a `compile_commands.json` is found in each workspace folder root.

> **Question-3:** When I have two sub components inside my project from the same repo, but each subcomponent has its own cmake build commands, how can I configure CCLS to use the respective compile_commands.json ? One option I thought was to merge these two compile commands, and place it in the root directory, but with this approach, I din't notice a big difference, it seemed as if though only one of those subcomponents got processed. How to approach this situation ?

One option is to use multiple workspace folders. Another choice is to manually merge `compile_commands.json`.

You can also use https://github.com/MaskRay/ccls/wiki/Project-Setup#stdout-of-an-external-command
