### ISSUE TITLE
Indexing fails on compilation database using 'arguments:' for command line

### ISSUE THREAD

**Issue by jmataraz** [MaskRay/ccls#74]
New user here, could be something I'm doing wrong.  I'm using ccls with Emacs on macOS. I built ccls from github clone and installed it in /usr/local/bin. I installed emacs-ccls and lsp-mode packages for Emacs.

When I call M-x lsp-ccls-enable on a project file, it picks up the compilation database fine. The database was generated from clang -MJ option, and it uses "arguments:" key instead of "command:" for the compile command. When the indexer attempts to run on the visited file, it fails reporting a bunch of Error lines in \*Messages\*. Checking \*lsp-ccls stderr\* it's reporting an error from clang:
```
error: unable to handle compilation, expected exactly one compiler job in ' "/path/to/clang" "-cc1" <rest of compile args> ; '
```
where \<rest of compile args\> is the rather long set of compile options I've used, omitted for brevity.

Maybe clang is expecting the arguments to be joined into a single command? This would look more like the "command:" key that is the alternative option for the compile db.

**Comment by jmataraz** [comment]
Hm, I didn't fully parse the stderr output earlier - it's putting 2 clang invocations on a single line. Looks like they're for i386 (32-bit) and x86_64 (64-bit) invocations. Obviously that's the problem. I removed the -arch options from the dB but it's still failing. The ccsl.log output still says clang crashed, but the lsp stderr buffer in Emacs doesn't show any problems.

**Comment by MaskRay** [comment]
What ccls indexer does is similar to:

`c-index-test -index-file <other options> a.cc -resource-dir=/path/to/clang/lib/7.0.0`

It (`clang::createInvocationFromCommandLine`) does not support **two or more filenames**. You should make sure every `compile_commands.json` entry has exactly one main source filename.
