### ISSUE TITLE
ccls stuck at the last job: completed: 16779/16780

### ISSUE THREAD

**Issue by tchiang-ml** [MaskRay/ccls#744]
Here are some things you should try before filing a bug report:

This is for running the command line debug version of ccls:
ccls --index=. -log-file=/tmp/ccls.log -v=1

+ Checked [the FAQ] and there is a mention about long waiting time for huge codebase, not sure if this is one of the known issue.

---

### Observed behavior

when parsing codebase, everything went well until the last job and stuck there forever. It will crash later when system memory is exhausted. I have 64G RAM and 64G Swap. Both are fully used up by ccls in the last task . Not sure is it normal. The codebase is AOSP, but I have removed 2/3 of the files that I don't use.

I used `compile_commands.json` 

### System information

* ccls version (`git describe --tags --long`):  0.20201219-0-g4c66fdf
* clang version: clang version 12.0.0
* OS: Ubuntu 16.04
* Editor: VSCode, but also tested using command line
* Language client (and version): clang+llvm 7.01

**Comment by MaskRay** [comment]
This report is not actionable for others. (Detailed reproduce instructions are required.) If you don't mind investigating it by yourself, you can check the variables introduced in 5108cfafcb709f42f86d8f6e445323c24ee4fc35 and see where they change.

**Comment by tchiang-ml** [comment]
Thanks, Will check the progress of index variable.

**Comment by tchiang-ml** [comment]
This is what the messages look like. It just stuck at 16779 and never go
finish to 16780.
[image: ccls_message_widow.jpg]

**Comment by tchiang-ml** [comment]
![ccls_message_widow](https://user-images.githubusercontent.com/70732451/103316678-10e5e000-49de-11eb-98e8-c2c715f44e2d.jpg)

**Comment by tchiang-ml** [comment]
problem seems gone after I removed all the .vscode and .ccls-cache dirs from home dir and workspace. something might be corrupted in those configure and cache data. Thanks for making such wonderful tool for software engineers.!
