### ISSUE TITLE
How to use local ccls with docker?

### ISSUE THREAD

**Issue by arwtyxouymz** [MaskRay/ccls#75]
Hi
I use ccls with [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) in local environment.
I wonder how to use this with docker container, so I post here.

# Details
I usually use this with `compile_commands.json` in my local environment, and my code is linked to some libraries like opencv in local.

When I develop with docker container, I mount my code, which is in local, to docker container, and I edit it with my local editor like vim.

Because I build my code in container, the include paths of libraries written in `compile_commands.json` are in docker container.

My local ccls reads that `compile_commands.json` but completion does not work because the paths don’t exist in local.

I can solve this problem by creating editor environment with libraries in my container and I edit my code in my container.
But if I do that, container size becomes so big and I have to create editor env every time when I create new container.

How to use local ccls with docker container?
Please help me!

# My environment
OS X: 10.13.6
Neovim: v0.3.2
LanguageClient-neovim: 0.1.93

**Comment by MaskRay** [comment]
Suppose your local source directory is `/host`, the mount point in the container is `/container` and the build directory is `/container/Debug`.

After getting `/container/Debug/compile_commands.json`, you should change the `arguments/command/filename` a bit to `/host` and put it in `/host/compile_commands.json`.

Open a source file in `/host` and `/host/compile_commands.json` will be picked the ccls server. Stale `compile_commands.json` usually does not matter because ccls can infer compile command line for new files from existing entries.

**Comment by MaskRay** [comment]
I am considering addting an initialization option `index.pathMapping: [string]`, which translates absolute paths in `compile_commands.json` entries and `IndexFile.dependencies`.

This will allow a cache file with `/container/` paths encoded to be reused by host with `/host/` source paths. Will that be useful? What do you think?

**Comment by MaskRay** [comment]
Added `clang.pathMappings`

**Comment by arwtyxouymz** [comment]
@MaskRay 

Sorry for late to reply.
I don't know how to use that `clang.pathMappings` option.
My acknowledgement is the value of `clang.pathMappings` is 
```
[container's ccls's cache path : host's cache path]
```

To generate ccls's cache file, we need to execute ccls in docker container, don't we?
Therefore we need to mount ccls binary to docker container or install ccls in container.
Then, the container's ccls cache file rsync to host cache file, and local ccls use the host cache file.
As a result, ccls can detect the right path of `compile_commands.json`.

If i was wrong, please tell me right usage.
Thank you.

**Comment by MaskRay** [comment]
@arwtyxouymz It is not directly related to containers. It is for reusing cache files indexed with a different project root. 

https://github.com/MaskRay/ccls/wiki/Initialization-options#clangpathmappings

**Comment by arwtyxouymz** [comment]
@MaskRay 

You mean this option is not for docker container?

Because if ccls didn't exist in docker container, cache file is not generated in container.
So we can't reuse container cache file to host project, right?

**Comment by MaskRay** [comment]
This describes how pathMappings work. It does not understand what a
container is.  If you merely copy cache files from the container to the
host, you can use this option.
