### ISSUE TITLE
How to use ccls in qt creator?

### ISSUE THREAD

**Issue by 93Alliance** [MaskRay/ccls#752]
How to use ccls in qt creator?
![image](https://user-images.githubusercontent.com/33192459/104688028-507d2d80-573b-11eb-818b-cc6113782a18.png)

---

### Observed behavior

Describe what happened. Any aids you can include (that you think could be relevant) are a tremendous help.

* `compile_commands.json` or `.ccls` ([wiki/Project-Setup](https://github.com/MaskRay/ccls/wiki/Project-Setup))
* Reduce to A minimal set of `.c` `.cc` `.h` `.hh` files that can still demonstrate the issue.
* Consider a screencast gif.

### Expected behavior

Describe what you expected to happen.

### Steps to reproduce

1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.

### System information

* ccls version (`git describe --tags --long`): 20201219
* clang version: 11
* OS: linux
* Editor: qt creator
* Language client (and version):

**Comment by MaskRay** [comment]
```cpp
// a.cc
#include <QGuiApplication>
#include <QQmlApplicationEngine>

int main(int argc, char *argv[]) {
  QGuiApplication app(argc, argv);
  QQmlApplicationEngine engine;
  const QUrl url(QStringLiteral("qrc:/main.qml"));

  QObject::connect(&engine, &QQmlApplicationEngine::objectCreated, &app,
                   [url](QObject *obj, const QUrl &objUrl) {
                   }, Qt::QueuedConnection);
  engine.load(url);
  return app.exec();
}
```

```zsh
# Debian: sudo apt install qtbase5-dev qtdeclarative5-dev

git init
qmake -project
qmake
# Append QT += qml

bear -- make
nvim a.cc  # :CocStart, works fine
```
