### ISSUE TITLE
ccls and qt (QObject::connect) has some issue

### ISSUE THREAD

**Issue by jjpark78** [MaskRay/ccls#753]
### Observed behavior

when using ccls load a project generated from qt-creator, ccls report error where is not 

![image](https://user-images.githubusercontent.com/20697443/104806841-c063e480-581d-11eb-899f-1649f2c6219e.png)

ccls report QObject::connect is no matching function for call. but other vscode or qt-creator don't report such thing. 

### Expected behavior

do not report error

### Steps to reproduce

1. using qt-creator generate some boilerplate project from template
2. load that project with ccls configured vim or emacs
3. at main.cpp QObject::connect function has a error from lsp

### System information

* ccls version: (installed with brew) stable 0.20201219 (bottled), HEAD
* clang version: 11.0.0 
* OS: MacOS Big Sur 11.1
* Editor: Doom Emacs
* Language client (and version): LSP

**Comment by MaskRay** [comment]
You need to specify some `-I`. Please include the textual program.

```cpp
// a.cc
#include <QGuiApplication>
#include <QQmlApplicationEngine>

int main(int argc, char *argv[]) {
  QGuiApplication app(argc, argv);
  QQmlApplicationEngine engine;
  const QUrl url(QStringLiteral("qrc:/main.qml"));

  QObject::connect(&engine, &QQmlApplicationEngine::objectCreated, &app,
                   [url](QObject *obj, const QUrl &objUrl) {
                   }, Qt::QueuedConnection);
  engine.load(url);
  return app.exec();
}
```

```zsh
git init
qmake -project
qmake
bear -- make
nvim a.cc  # :CocStart, works fine
```

**Comment by jjpark78** [comment]
yes. in linux no problem. 

macos  and ccls + clang looks like have some issue but i think it can be solved with some additional configuration which is i dont know. 
(vscode on macos has no issue like this)

**Comment by MJAS1** [comment]
I have this same exact problem. Running the example above did not work in my Fedora 34 with `ccls-0.20201219`. After some digging, I found this related problem: #750. I tried building ccls from source and it fixed the problem. Probably related to ccls and clang version mismatch.
