### ISSUE TITLE
Manjaro系统下无法正常解析C++标准库

### ISSUE THREAD

**Issue by chenyidao110** [MaskRay/ccls#755]
编译过程：
操作系统：WSL2 Manjaro
gcc: 10.2.0
clang: 11.0.1
1、pacman安装依赖，如git curl cmake clang llvm等，克隆代码
    git clone --depth=1 --recursive https://github.com/MaskRay/ccls
2、在ccls目录下cmake -H. -Bbuild/Release    
	-DCMAKE_EXPORT_COMPILE_COMMANDS=ON           
	-DCMAKE_CXX_COMPILER=clang++           
	-DClang_DIR=/usr/lib/cmake/clang           
	-DLLVM_DIR=/usr/lib/cmake/llvm
3、在vim8.2中正常使用生成的compile_commands.json文件和ccls有如下问题：
     像std::之后能解析出string和其他的方法，但是在定义一个对象比如说std::string str = "Hello,world!"，正常的输入str.会解析出string下的各个方法，但是没有按期望弹出。
4、直接用pacman -S ccls安装的ccls问题和上面一样

**Comment by l1nxy** [comment]
What vim plugin do  you use? coc.vim or any else?

**Comment by l1nxy** [comment]
I was tested on archlinux on wsl1,and use `pacman -Sy ccls`,it work correctly.
The enviroment is neovim and coc.vim.
![20210119133958](https://user-images.githubusercontent.com/12152770/104992539-38b7e900-5a5c-11eb-9348-9b7933fb8125.png)

**Comment by chenyidao110** [comment]
> 
> 
> I was tested on archlinux on wsl1,and use `pacman -Sy ccls`,it work correctly.
> The enviroment is neovim and coc.vim.
> ![20210119133958](https://user-images.githubusercontent.com/12152770/104992539-38b7e900-5a5c-11eb-9348-9b7933fb8125.png)

wait,I'm testing..

**Comment by chenyidao110** [comment]
> 
> 
> I was tested on archlinux on wsl1,and use `pacman -Sy ccls`,it work correctly.
> The enviroment is neovim and coc.vim.
> ![20210119133958](https://user-images.githubusercontent.com/12152770/104992539-38b7e900-5a5c-11eb-9348-9b7933fb8125.png)

It's still working incorrectly
![ccls](https://user-images.githubusercontent.com/14362421/104994959-7159c180-5a60-11eb-9231-015d04cfc616.gif)
