### ISSUE TITLE
ccls 支持 google c++ style 进行代码 format 吗？

### ISSUE THREAD

**Issue by weihongkai2008** [MaskRay/ccls#757]

**Comment by findNextStep** [comment]
ccls的格式化使用clang-format，直接在工程根目录或者使用google风格的目录添加对应的.clang-format即可
谷歌风格的.clang-format文件的编写可以参照webrtc中的 https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/.clang-format

**Comment by weihongkai2008** [comment]
thx
