### ISSUE TITLE
Local header files is missing

### ISSUE THREAD

**Issue by olamohey** [MaskRay/ccls#766]
Hello, Experts 

I'm newbie. I try lsp & ccls for first time. and Vim complain it's not found local files
this is my .ccls:
```
%c
-isystem./htop

-isystem/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10
-isystem/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/x86_64-redhat-linux
-isystem/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/backward
-isystem/usr/lib/gcc/x86_64-redhat-linux/10/include
-isystem/usr/local/include
-isystem/usr/include
```
Project structure:
`

```
├── .ccls
├── htop
│   ├── aclocal.m4
│   ├── Action.c
│   ├── Action.h
│   ├── Action.o
│   ├── Affinity.c
│   ├── Affinity.h

```

If I opened `Aciton.c` for example. I get error that Affinity.h & Action.h not found.
Thanks alot 

### System information
* ccls version (`git describe --tags --long`):  clang version 10.0.1 (Fedora 10.0.1-3.fc32)
* clang version: 10.0.1
* OS: Linux (fedora)
* Editor: vim
* Language client (and version): c language

**Comment by MaskRay** [comment]
The first line needs to be clang. See https://github.com/MaskRay/ccls/wiki/Project-Setup
