### ISSUE TITLE
Wierd error linting

### ISSUE THREAD

**Issue by Alvaroalloc** [MaskRay/ccls#767]
I started using neovim to finally replace my workflow from vscode, but in c++ i got some weird errors , at first header were not included, i solved it, but i start a file with this contents:

```
#include <iostream>

int main() {
  std::cout << "helloworld" << std::endl;
  return 0;
}
```
and i get this error while hovering in the first "<<"
![Screen Shot 2021-02-07 at 0 38 50](https://user-images.githubusercontent.com/71088454/107138874-daed2300-68dc-11eb-9f7a-0199477859f5.png)

this is my coc-settings.json: 
```
{
    "languageserver": {
        "ccls": {
            "command": "ccls",
            "filetypes": ["c", "cpp", "h", "cc", "hpp"],
            "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
            "initializationOptions": {
                "cache": {
                    "directory": "/tmp/ccls"
                },
		"client": {
		    "snippetSupport": true
		},
                // see https://github.com/MaskRay/ccls/issues/191
                "clang": {
                    // from clang -v -fsyntax-only -x c++ /dev/null
                    "extraArgs": [
			"-nostdinc",
                        "-isystem",
			"/Library/Developer/CommandLineTools/usr/include/c++/v1"
                    ],
                    //From clang -print-resource-dir
                    "resourceDir": "/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0"
                }
            }
        }
    }
}
```

**Comment by Nimrod0901** [comment]
Do you find the solution?

**Comment by Nimrod0901** [comment]
https://github.com/MaskRay/ccls/issues/191#issuecomment-577129941 solved.

**Comment by Alvaroalloc** [comment]
yes it was solved by adding all the clang include paths, but i want just to show completion for the standard library headers, how can i do that?.
here what happens:
![Screen Shot 2021-02-07 at 16 40 23](https://user-images.githubusercontent.com/71088454/107161572-2e09b900-6963-11eb-9f7e-4c7bb340e993.png)
