### ISSUE TITLE
How do I load a header from my own project?

### ISSUE THREAD

**Issue by 1m-N00b** [MaskRay/ccls#770]
### Observed behavior
For example, in the following configuration, #include <A.hpp> is written in A.cpp.
However, an error message "[ccls 1] [E] 'A.hpp' file not  found" will be printed.
```
/
├── include
│   └── A.hpp
└── src
    └── A.cpp
```

### System information

* ccls version (`git describe --tags --long`): [latest](https://archlinux.org/packages/community/x86_64/ccls/)
* clang version: clang version 11.1.0
* OS: Arch linux x86_64
* Editor: nvim
* Language client (and version): coc(latest)

**Comment by findNextStep** [comment]
check https://github.com/MaskRay/ccls/wiki/Project-Setup and generator compile_commands.json and set
or make a .ccls file like below
```
clang
%c -std=c11
%cpp -std=c++2a
-I ./inlcude
```

**Comment by vastus** [comment]
My setup (very similar to OPs if not the same) was unable to find the local headers as well. Looks like ccls still found 'em at least what I could tell by reading the log. I suspect I have something misconfigured.

[Example project w/ version info and ccls log](https://gist.github.com/vastus/56e18d838d7a4aec4c0ed87ee509f15d).

![scrot-0](https://user-images.githubusercontent.com/199064/108941474-09bc0680-760a-11eb-9a4c-5aa7e8fa947d.png)

**Comment by vastus** [comment]
I also tried the .ccls example @findNextStep posted but I still get the same `file not found`.

**Comment by findNextStep** [comment]
> I also tried the .ccls example @findNextStep posted but I still get the same `file not found`.

try use bear generator compile_commands.json and set 
```
            "initializationOptions": {
                "compilationDatabaseDirectory": "./",
}
```
in coc

**Comment by 1m-N00b** [comment]
i can fixed thank u

**Comment by vastus** [comment]
I figured out my problem as well. I had coc-clangd installed which was showing the errors, not ccls. Fixed my issue by uninstall coc-clangd w/

```
:CocUninstall coc-clangd
```

Thanks!

**Comment by teutat3s** [comment]
I struggled with this as well and for anybody stumbling across this, this is the `.ccls` example I needed to make it work (typo and space removed from first example above):
```
clang
%c -std=c11
%cpp -std=c++2a
-I./include
```
