### ISSUE TITLE
throttle $/progress

### ISSUE THREAD

**Issue by prabirshrestha** [MaskRay/ccls#772]
Issue was originally reported at https://github.com/prabirshrestha/vim-lsp/issues/1073. On digging further it seems that ccls is sending too many $/progress notifications. VimScript being slow and running in the same UI thread it causes vim to be very slow. It would be good if $/progress notifications can be throttled.

Here is the log. https://github.com/prabirshrestha/vim-lsp/files/6055035/vim-lsp-with-issue.log

Percentage doesn't change so the client is unnecessarily parsing the message, decoding and updating the ui status bar causing it to be very slow.

```
Sat 27 Feb 2021 11:04:41 PM IST:["<---", 5, "ccls", {"response": {"method": "$/progress", "jsonrpc": "2.0", "params": {"token": "index", "value": {"percentage": 0.011531, "message": "1/8672", "kind": "report"}}}}]
Sat 27 Feb 2021 11:04:41 PM IST:["<---", 5, "ccls", {"response": {"method": "$/progress", "jsonrpc": "2.0", "params": {"token": "index", "value": {"percentage": 0.011531, "message": "1/8672", "kind": "report"}}}}]
Sat 27 Feb 2021 11:04:41 PM IST:["<---", 5, "ccls", {"response": {"method": "$/progress", "jsonrpc": "2.0", "params": {"token": "index", "value": {"percentage": 0.011531, "message": "1/8672", "kind": "report"}}}}]
```

I reported something similar to rust-analyzer. https://github.com/rust-analyzer/rust-analyzer/issues/7590

**Comment by joelhock** [comment]
this should already be fixed by https://github.com/MaskRay/ccls/issues/734#issuecomment-748554062
