### ISSUE TITLE
How to specify a default .ccls file for all projects?

### ISSUE THREAD

**Issue by dcordb** [MaskRay/ccls#782]
I want to have some default configuration for C++ projects, is there a way to do this, I know I could have one .ccls file and in every new project just copy it but is there a better way to do this?

Also, how do I specify the formatting settings for the formatter?

**Comment by MaskRay** [comment]
ccls respects `.clang-format` for formatting.

> I know I could have one .ccls file and in every new project just copy it but is there a better way to do this?

It is very unlikely that a `.ccls` file can be used everywhere.

If you are happy with the default -std=gnu++14 and don't need any `-I`, the default (i.e. no `compile_commands.json`, no `.ccls`) works pretty well.
