### ISSUE TITLE
Help wanted: If there are more than one compile_commands.json, how to make ccls resolve them?

### ISSUE THREAD

**Issue by stark-zhang** [MaskRay/ccls#783]
I have a project, it is cross-compiled. And its binary file is divided to RT(real-time) and NRT(non-RT). compilation of them is separate and two compiling db files were generated by ninja. How to make ccls to read all of compile_commands.json and run as a language server?

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Project-Setup

(a) Concatenate `compile_commands.json` files.
(b) Or use `stdout of an external command`
