### ISSUE TITLE
Compile without ltinfo?

### ISSUE THREAD

**Issue by rickyelopez** [MaskRay/ccls#785]
Is there any way to compile this without `ltinfo`? I am trying to compile this on a system where I do not have the privileges to install the `libtinfo-dev` package.

Forgive me if this is stupid, but is it possible to download this library separately and link it in at compile time with a static reference?

**Comment by Ristovski** [comment]
Mega hack, but you could download the `libtinfo-dev` package, unpack it and then manually add the path to `LIBRARY_PATH` or link it yourself.

**Comment by MaskRay** [comment]
ccls itself dowsn't use libtinfo. However, the Clang and LLVM packages ccls depends on may use libtinfo, you'll need libtinfo-dev to link the ccls executable. Yes, unpacking a `.deb` and then manually adding the path to `LIBRARY_PATH` should work.
