### ISSUE TITLE
Status of latest tag?

### ISSUE THREAD

**Issue by carlocab** [MaskRay/ccls#786]
I can see that you've tagged `0.20210330`, but [`0.20201219`](https://github.com/MaskRay/ccls/releases/tag/0.20201219) is still showing up as the latest release on GitHub.

Is `0.20210330` a pre-release, or is it your latest stable one?

This is relevant for https://github.com/Homebrew/homebrew-core/pull/74589, as we only merge the latest stable releases to homebrew/core.

Thanks!

**Comment by MaskRay** [comment]
Thanks. Added a short description.

**Comment by carlocab** [comment]
Thanks, @MaskRay.
