### ISSUE TITLE
Method's name doesn't display properly in Vscode's breadcrumbs

### ISSUE THREAD

**Issue by fiddleyuan** [MaskRay/ccls#789]
Description:
When cursor is inside a ClassName::FunctionName, the function name doesn't display properly. It only shows namespace rather than **namespace > ClassName > FunctionName**

Take CCLS's own code for example, in src/lsp.cc file, if I put cursor at DocumentUri::fromPath, Vscode's breadcrumb will display like below:
![2](https://user-images.githubusercontent.com/524369/115686535-de486480-a38b-11eb-8290-82d55c8e2d53.jpg)

However, if I put cursor at a function without ClassName, Vscode's breadcrumb will display as expected. Take another function in the same file as example:
![1](https://user-images.githubusercontent.com/524369/115686811-2c5d6800-a38c-11eb-8960-343d74af3817.jpg)

I'm not sure if this is CCLS's issue or Vscode's issue. But I moved from cquery, I remember it will display properly for both cases.
I would be appreciated if someone can point out where the problem is, or even provide a solution, thanks!

**Comment by FederAndInk** [comment]
I made a PR for that: https://github.com/MaskRay/ccls/pull/674

if you want you can test it and compile ccls from my branch including the changes: https://github.com/FederAndInk/ccls/tree/fix/document_symbol_range_based

**Comment by fiddleyuan** [comment]
> I made a PR for that: #674
> 
> if you want you can test it and compile ccls from my branch including the changes: https://github.com/FederAndInk/ccls/tree/fix/document_symbol_range_based

Thank you, FederAndInk, I tried you PR, it works well.

**Comment by fiddleyuan** [comment]
By the way, can we mainline this change? @MaskRay

**Comment by MaskRay** [comment]
Fixed by a modified https://github.com/MaskRay/ccls/pull/674
