### ISSUE TITLE
Just to remind there is a typo in the Customization page

### ISSUE THREAD

**Issue by tchiang-ml** [MaskRay/ccls#792]
While I read the Customization page, I noticed a small typo regarding the whitelist :

Example: {"index": {"initialBlacklist": ["."]}} (matches all files)

Isn't the "." should be ".*".?

Thanks for all you efforts to make the community work better!

**Comment by tchiang-ml** [comment]
sorry, it's the blacklist, not whitelist. 
So easy to make typo my own, haha.

**Comment by MaskRay** [comment]
`"."` is correct. `"."` matches if there is at least one character.
