### ISSUE TITLE
bool type did not supported for c in osx

### ISSUE THREAD

**Issue by arthurkiller** [MaskRay/ccls#803]
I can build my code without any change (eg. add include <stdbool.h>)

but ccls prompt me with this

```
[Error] [ccls] 2: unknown type name 'bool'
```

Q： how to fix this or hide this?

OSX 10.16

BTW,  ccls was installed with brew, do I need to compile and buil mysely locally?

**Comment by MaskRay** [comment]
`bool` is not a keyword in C. You need `#include <stdbool.h>`

**Comment by arthurkiller** [comment]
@MaskRay thx for reply

> `bool` is not a keyword in C. You need `#include <stdbool.h>`

but I can build without importing `stdbool.h`, seems bool has been an internal type since c99,
is there any way I can config ccls to disable this prompt?

**Comment by arthurkiller** [comment]
and after I added `stdbool.h` 

ccls still got this
> [Error] [ccls] 2: unknown type name 'bool'
