### ISSUE TITLE
Tilde character not expanded for cacheDirectory

### ISSUE THREAD

**Issue by whatacold** [MaskRay/ccls#81]
Hi,

I specify cache directory via `eglot` like this:

    (eval-after-load 'eglot
      '(progn
         (add-to-list 'eglot-server-programs '((c-mode c++-mode) "ccls"
                                               "-log-file=/tmp/ccls.log"
                                               "-init={\"cacheDirectory\": \"~/ccls-cache-dir/\"}"))))

but ccls take `~` character literally, and generate that directory under the project root.

**Comment by MaskRay** [comment]
Tilde should be expanded by a shell. It is also tricky to expand them. There is `wordexp.h` but they can be dangerous. VSCode as I know, expanded `~` but not `~user`. I am not sure if that has been fixed or not.

Since you are using Emacs, use `expand-file-name`
