### ISSUE TITLE
.ccls-cache file configuration

### ISSUE THREAD

**Issue by basicfunc** [MaskRay/ccls#816]
Hey there,
How to configure ccls to cache files in specific directory either by commandline or in emacs.
I tried a lot using ccls --init option but no success yet.

`
~ ❯ ccls --init={"initializationOptions":{"cache":{"directory":"/tmp/ccls-cache"}}}
`
`
Failed to parse --init as JSON: Missing a name for object member. (1)
`

Maybe I'm doing something wrong, please help!

**Comment by MaskRay** [comment]
shell quoting issue.

Use `'--init={"initializationOptions":{"cache":{"directory":"/tmp/ccls-cache"}}}'` or `--init='{"initializationOptions":{"cache":{"directory":"/tmp/ccls-cache"}}}'`

**Comment by basicfunc** [comment]
Problem persists!!
![image](https://user-images.githubusercontent.com/84739019/126866351-ed0f76da-98f8-4048-b12d-f6cbe968b37e.png)
![image](https://user-images.githubusercontent.com/84739019/126866380-ae5c91e5-24fb-438b-9fce-f13a4100adf2.png)

**Comment by basicfunc** [comment]
And if I puts it in a script and then run script by Eglot, ccls works but cache dir setting doesn't work.
![image](https://user-images.githubusercontent.com/84739019/126866442-b0747dca-a3c5-413e-a848-4934c521fe9d.png)
This is what I've putted in my Config, a script named cemacs which looks like this,
![image](https://user-images.githubusercontent.com/84739019/126866463-2043cfae-789a-4595-9ed8-ca7a5e215dad.png)
This time server works, but cache dir is still in Project Dir not where supposed to be,
![image](https://user-images.githubusercontent.com/84739019/126866504-12db0f51-bb24-45eb-8b75-17ef0a0b5790.png)
What can be possible reasons?

`[client-request] (id:1) Sat Jul 24 16:35:14 2021:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
		  (:processId 4179 :rootPath "/home/rahul/" :rootUri "file:///home/rahul" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
																													   ())
					  :capabilities
					  (:workspace
					   (:applyEdit t :executeCommand
								   (:dynamicRegistration :json-false)
								   :workspaceEdit
								   (:documentChanges :json-false)
								   :didChangeWatchedFiles
								   (:dynamicRegistration t)
								   :symbol
								   (:dynamicRegistration :json-false)
								   :configuration t)
					   :textDocument
					   (:synchronization
						(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
						:completion
						(:dynamicRegistration :json-false :completionItem
											  (:snippetSupport :json-false)
											  :contextSupport t)
						:hover
						(:dynamicRegistration :json-false :contentFormat
											  ["markdown" "plaintext"])
						:signatureHelp
						(:dynamicRegistration :json-false :signatureInformation
											  (:parameterInformation
											   (:labelOffsetSupport t)
											   :activeParameterSupport t))
						:references
						(:dynamicRegistration :json-false)
						:definition
						(:dynamicRegistration :json-false)
						:declaration
						(:dynamicRegistration :json-false)
						:implementation
						(:dynamicRegistration :json-false)
						:typeDefinition
						(:dynamicRegistration :json-false)
						:documentSymbol
						(:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
											  (:valueSet
											   [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
						:documentHighlight
						(:dynamicRegistration :json-false)
						:codeAction
						(:dynamicRegistration :json-false :codeActionLiteralSupport
											  (:codeActionKind
											   (:valueSet
												["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
											  :isPreferredSupport t)
						:formatting
						(:dynamicRegistration :json-false)
						:rangeFormatting
						(:dynamicRegistration :json-false)
						:rename
						(:dynamicRegistration :json-false)
						:publishDiagnostics
						(:relatedInformation :json-false))
					   :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
												   ()))))
[stderr] 16:35:15 ccls           initialize.cc:274 I initialize in directory /home/rahul with uri file:///home/rahul
[stderr] 16:35:15 ccls           initialize.cc:297 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":".ccls-cache","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":[],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100,"placeholder":true},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":false,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
[stderr] 16:35:15 ccls           initialize.cc:329 I use -resource-dir=/usr/lib/clang/12.0.0
[stderr] 16:35:15 ccls           initialize.cc:361 I workspace folder: /home/rahul/
[stderr] 16:35:15 ccls           initialize.cc:386 I start 4 indexers
[server-reply] (id:1) Sat Jul 24 16:35:15 2021:
(:jsonrpc "2.0" :id 1 :result
		  (:capabilities
		   (:textDocumentSync
			(:openClose t :change 2 :willSave :json-false :willSaveWaitUntil :json-false :save
						(:includeText :json-false))
			:hoverProvider t :completionProvider
			(:resolveProvider :json-false :triggerCharacters
							  ["." ":" ">" "#" "<" "\"" "/"])
			:signatureHelpProvider
			(:triggerCharacters
			 ["(" ","])
			:declarationProvider t :definitionProvider t :implementationProvider t :typeDefinitionProvider t :referencesProvider t :documentHighlightProvider t :documentSymbolProvider t :workspaceSymbolProvider t :codeActionProvider
			(:codeActionKinds
			 ["quickfix"])
			:codeLensProvider
			(:resolveProvider :json-false)
			:documentFormattingProvider t :documentRangeFormattingProvider t :documentOnTypeFormattingProvider
			(:firstTriggerCharacter "}" :moreTriggerCharacter
									[])
			:renameProvider t :documentLinkProvider
			(:resolveProvider t)
			:foldingRangeProvider t :executeCommandProvider
			(:commands
			 ["ccls.xref"])
			:workspace
			(:workspaceFolders
			 (:supported t :changeNotifications t)))
		   :serverInfo
		   (:name "ccls" :version "<unknown>")))
[client-notification] Sat Jul 24 16:35:15 2021:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
															()))
[client-notification] Sat Jul 24 16:35:15 2021:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
		  (:textDocument
		   (:uri "file:///home/rahul/main.c" :version 0 :languageId "c" :text "#include <stdio.h>\n\nvoid main(){\n  int a:2 = 123;\n  printf(\"%d\", a);\n}\n")))
[client-notification] Sat Jul 24 16:35:15 2021:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
		  (:settings nil))
[stderr] 16:35:15 ccls           initialize.cc:394 I dispatch initial index requests
[stderr] 16:35:15 ccls             pipeline.cc:493 I loaded project. Refresh semantic highlight for all working file.
[stderr] 16:35:15 preamble     sema_manager.cc:763 I create session for /home/rahul/main.c
[stderr] 16:35:15 indexer1         pipeline.cc:298 I load cache for /home/rahul/main.c
[stderr] 16:35:15 ccls         sema_manager.cc:772 I clear all sessions
[stderr] 16:35:15 ccls             pipeline.cc:493 I loaded project. Refresh semantic highlight for all working file.
[stderr] 16:35:15 diag         sema_manager.cc:763 I create session for /home/rahul/main.c
[server-request] (id:0) Sat Jul 24 16:35:15 2021:
(:jsonrpc "2.0" :method "client/registerCapability" :id 0 :params
		  (:registrations
		   [(:id "didChangeWatchedFiles" :method "workspace/didChangeWatchedFiles" :registerOptions
				 (:watchers
				  [(:globPattern "**/*")]))]))
[client-reply] (id:0) Sat Jul 24 16:35:18 2021:
(:jsonrpc "2.0" :id 0 :result nil)
[server-notification] Sat Jul 24 16:35:18 2021:
(:jsonrpc "2.0" :method "$ccls/publishSkippedRanges" :params
		  (:uri "file:///home/rahul/main.c" :skippedRanges
				[]))
[server-notification] Sat Jul 24 16:35:18 2021:
(:jsonrpc "2.0" :method "$ccls/publishSemanticHighlight" :params
		  (:uri "file:///home/rahul/main.c" :symbols
				[(:id 0 :parentKind 1 :kind 12 :storage 0 :ranges
					  [(:L 25 :R 29)]
					  :lsRanges
					  [])
				 (:id 1 :parentKind 0 :kind 12 :storage 0 :ranges
					  [(:L 52 :R 58)]
					  :lsRanges
					  [])
				 (:id 0 :parentKind 12 :kind 13 :storage 0 :ranges
					  [(:L 39 :R 40)
					   (:L 65 :R 66)]
					  :lsRanges
					  [])]))
[server-notification] Sat Jul 24 16:35:18 2021:
(:jsonrpc "2.0" :method "$ccls/publishSemanticHighlight" :params
		  (:uri "file:///home/rahul/main.c" :symbols
				[(:id 0 :parentKind 1 :kind 12 :storage 0 :ranges
					  [(:L 25 :R 29)]
					  :lsRanges
					  [])
				 (:id 1 :parentKind 0 :kind 12 :storage 0 :ranges
					  [(:L 52 :R 58)]
					  :lsRanges
					  [])
				 (:id 0 :parentKind 12 :kind 13 :storage 0 :ranges
					  [(:L 39 :R 40)
					   (:L 65 :R 66)]
					  :lsRanges
					  [])]))
[server-notification] Sat Jul 24 16:35:18 2021:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
		  (:uri "file:///home/rahul/main.c" :diagnostics
				[(:range
				  (:start
				   (:line 2 :character 0)
				   :end
				   (:line 2 :character 4))
				  :severity 2 :code 2 :source "ccls" :message "return type of 'main' is not 'int'" :relatedInformation
				  [])
				 (:range
				  (:start
				   (:line 3 :character 7)
				   :end
				   (:line 3 :character 8))
				  :severity 1 :code 4 :source "ccls" :message "expected ';' at end of declaration" :relatedInformation
				  [])
				 (:range
				  (:start
				   (:line 3 :character 10)
				   :end
				   (:line 3 :character 11))
				  :severity 1 :code 2 :source "ccls" :message "expression is not assignable" :relatedInformation
				  [])]))
[client-notification] Sat Jul 24 16:35:20 2021:
(:jsonrpc "2.0" :method "workspace/didChangeWatchedFiles" :params
		  (:changes
		   [(:uri "file:///home/rahul/.mozilla/firefox/z7mfvkfm.default-default/sessionstore-backups/recovery.jsonlz4.tmp" :type 1)]))
[server-request] (id:1) Sat Jul 24 16:35:20 2021:
(:jsonrpc "2.0" :method "window/workDoneProgress/create" :id 1 :params
		  (:token "index"))
[client-reply] (id:1) Sat Jul 24 16:35:20 2021:
(:jsonrpc "2.0" :id 1 :result nil)
[client-notification] Sat Jul 24 16:35:20 2021:
(:jsonrpc "2.0" :method "workspace/didChangeWatchedFiles" :params
		  (:changes
		   [(:uri "file:///home/rahul/.mozilla/firefox/z7mfvkfm.default-default/sessionstore-backups/recovery.jsonlz4.tmp" :type 2)]))
`
This is output from Eglot!

It's output from terminal.
`~ ❯ ccls --version
ccls version <unknown>
clang version 12.0.0
`
I'm using Void Linux and Emacs 27.2

**Comment by basicfunc** [comment]
@MaskRay Please have a look.
