### ISSUE TITLE
ccls shows errors in c++ standard library

### ISSUE THREAD

**Issue by qumusabel** [MaskRay/ccls#817]
### Observed behavior
ccls finds errors in standard library, but the code compiles correctly (g++). 
![image](https://user-images.githubusercontent.com/18624304/126665985-624c0a9d-133b-41c6-acfc-bbe906f8aa39.png)

### Expected behavior
No errors

### Steps to reproduce

C++ source to reproduce:
```cpp
#include <iostream>

int main() {
  std::string s;
  std::string s2;
}
```

![image](https://user-images.githubusercontent.com/18624304/126665517-3fe46639-cb92-463f-8c1f-c9a75a33847b.png)

But if I comment the second declaration the errors disappear:
![image](https://user-images.githubusercontent.com/18624304/126665573-cefd1f85-c7f9-48d9-b968-2d71b94b8a7f.png)

### System information

* ccls version (`git describe --tags --long`): 0.20210330-4-gf21fd7e5
* clang version: 12.0.1
* OS: Arch Linux (upgraded 22.07)
* Editor: NeoVim
* Language client (and version): coc.nvim with ccls defined in coc-config.json

**Comment by qumusabel** [comment]
It keeps getting worse. Now this gives me an error that actually shows up:
![image](https://user-images.githubusercontent.com/18624304/126676946-38ba2891-d429-4788-a4cb-573d01de5b90.png)

**Comment by qumusabel** [comment]
Downgrading clang to 12.0.0 seems to fix this issue completely.

**Comment by FederAndInk** [comment]
Are you using ccls from the community repo? or ccls-git?

You should recompile ccls-git when there is an update to clang

**Comment by qumusabel** [comment]
Rebuilt ccls-git, this fixed it! Thanks.
(I don't remember ever rebuilding ccls-git after clang upgrades though... and it was still working until now)
