### ISSUE TITLE
 [Enhancement] Global options

### ISSUE THREAD

**Issue by jay-tux** [MaskRay/ccls#842]
Just an idea, but would it be possible to add some global configuration? Like a `.ccls` in (for example) `.config/ccls/` or the likes?

(Asking because the Atom plugin doesn't seem to work well with project-wide `.ccls` or `compile_commands.json` and I'd really like to have it include the `inc/` directory of my project when indexing)

**Comment by MaskRay** [comment]
A global `.ccls` file is not suitable. `.ccls` is an indicator that you want to index the whole project. In the absence of this file, ccls doesn't index every file. https://github.com/MaskRay/ccls/wiki/Project-Setup

For configurations, use initialization options (https://github.com/MaskRay/ccls/wiki/Customization#initialization-options).
