### ISSUE TITLE
Use SYSTEM ENVIRONMENT in .ccls file

### ISSUE THREAD

**Issue by GinShio** [MaskRay/ccls#846]
I download a lib and I want to use it, export it path in shell, this `env var` is found in emacs (getenv),

so i want to include it, add line to `.ccls` file like
```
-I${env:ENVPATH}
```

then i delete `.ccls-cache` and restart lsp in workspace, but it isn't work

could i can include system environment path or use `absolute path` in .ccls 

### System information

* ccls version (`git describe --tags --long`): 0.20210330 (from openSUSE package)
* clang version: 11.0.1
* OS: openSUSE 15.3 (Linux 5.3.18-59.24-preempt)
* Editor: DOOM Emacs
* Language client (and version): lsp-mode

**Comment by MaskRay** [comment]
This looks like a client feature request to me. The client may have some way to use a template to generate customized initialization-options (https://github.com/MaskRay/ccls/wiki/Customization#initialization-options). Imagine that if the server is not spawned by the client, its environment variables may not be expected, so only the client has the information.
