### ISSUE TITLE
open .h at first, can't generate full index file

### ISSUE THREAD

**Issue by fcying** [MaskRay/ccls#852]
### Observed behavior
when I open .h at first(have not .ccls-cache), it can generate index file also, but can't use jump to definition.
if I open .c at first, and then open .h, jump to definition can be used.

I compare two .ccls-cache, open .h at first not generate full index file(On the right side of the picture)
![image](https://user-images.githubusercontent.com/106934/146636719-505e8663-f965-4303-a4e1-447518b7ae22.png)

### Expected behavior
 I open .h at first generate full index file also.

### Steps to reproduce
`test 1`
1. rm -rf ./ccls-cache
2. nvim a.h +12
3. wait 5s for generate index
4. jump to definition on `b_t`  #can't work, a.h.blob have not struct info.
5. cp -rf ./ccls-cache ./err
6. :e main.c
7. :e a.h
8. jump to definition on `b_t`  #can work, a.h.blob have struct info.  

`test 2`
1. rm -rf ./ccls-cache
2. nvim main.c   #a.h.blob have struct info.

### System information

* ccls version (`dce86b1362acbabb8f997869fdaa27adc67f9a55`): 
* clang version: 12.0.1
* OS: debian
* Editor: neovim
* Language client (and version): nvim-lsp

### Test Code
`main.c`
```
#include "a.h"

int main(void)
{
    return 0;
}
```
`a.h`
```
#ifndef A_H
#define A_H

typedef struct b
{
    int aa;
} b_t;


typedef struct a
{
    b_t aa;
} a_t;

#endif

```
`compile_commands.json`
```
[
  {
    "arguments": [
      "/usr/bin/gcc",
      "-c",
      "-std=c11",
      "-I.",
      "main.c"
    ],
    "directory": "/home/fcying/test/ccls",
    "file": "/home/fcying/test/ccls/main.c"
  }
]
```

**Comment by MaskRay** [comment]
Not reproducible.

If you use `-v=1` (https://github.com/MaskRay/ccls/wiki/Debugging), there should be a `parse .*main.c` line and it will index `a.h`

**Comment by fcying** [comment]
use cmd { 'ccls', '-v=1', '-log-file=/tmp/ccls.log' } for test. 
when i open `.c` at first, get more information below
```
14:27:32 indexer0         pipeline.cc:386 I parse /home/fcying/test/ccls/main.c
  /usr/bin/gcc -c -std=c11 -I. main.c -working-directory=/home/fcying/test/ccls
14:27:39 preamble     sema_manager.cc:771 I create session for /home/fcying/test
/ccls/a.h
  /usr/bin/gcc -c -std=c11 -I. main.c -working-directory=/home/fcying/test/ccls
```
![image](https://user-images.githubusercontent.com/106934/149076110-aeef29f2-043c-4efe-8692-0d69c079ce92.png)
