### ISSUE TITLE
Document offset counting method or(and?) implement clangd's LSP extension.

### ISSUE THREAD

**Issue by black-desk** [MaskRay/ccls#858]
I think we should document the offset encoding ccls use. So far this information can only be found in commit message.

https://github.com/neovim/nvim-lspconfig/pull/1649#issuecomment-1010539697

And should we implement clangd's LSP extension?

check https://clangd.llvm.org/extensions#utf-8-offsets

ccls can avoid the code point counting process when the client-side accepts utf-8 byte offset.

**Comment by MaskRay** [comment]
Does https://github.com/MaskRay/ccls/pull/859 work?

**Comment by black-desk** [comment]
work!

**Comment by MaskRay** [comment]
Merged #859
