### ISSUE TITLE
Reference usage count in code behind auto wraps

### ISSUE THREAD

**Issue by Meigumikato** [MaskRay/ccls#871]
### System information

* ccls version 0.20210330-5
* clang version: 13
* OS: arch linux
* Editor: nvim coc LSP
* Language client (and version): 
### preview 
![image](https://user-images.githubusercontent.com/49133741/155687406-3257bf63-ff31-4539-9f9e-caa7ad5f4c8b.png)

**Comment by findNextStep** [comment]
能补充下预期的行为吗

**Comment by Meigumikato** [comment]
在之前使用当中这个代码引用计数的tag是在同一行的，更新现在是换行的，看着很别扭

**Comment by findNextStep** [comment]
> 在之前使用当中这个代码引用计数的tag是在同一行的，更新现在是换行的，看着很别扭

感觉像是coc-ccls的问题，如果回退ccls的版本没有作用的话，可能问下coc-ccls是否有更新？

**Comment by Meigumikato** [comment]
coc 使用ccls只是在coc 的config文件中启动了ccls的LSP server，我更新了coc但是没有效果
<img width="668" alt="image" src="https://user-images.githubusercontent.com/49133741/155945614-24340cdc-fbe8-4ba6-8ceb-efed2c15d088.png">
