### ISSUE TITLE
[Request]: New tagged release for distributions packaging LLVM 14

### ISSUE THREAD

**Issue by thunder-coding** [MaskRay/ccls#878]
Hey there, I'm one of the maintainers of [Termux project](https://github.com/termux/) which maintains ports for common UNIX utilities and also much of widely needed Linux software for Android platform. We have recently updated LLVM to 14.0.0, and as a part of our LLVM 14 transition, we are rebuilding packages depending on llvm.

The latest tagged version of ccls (0.20210330) doesn't build with LLVM 14, I was however able to build locally ccls from the master branch. It would be great if a new release can be made available so that distributions which package ccls can update it with ease!

**Comment by mattst88** [comment]
Gentoo is likely to switch to llvm-14/clang-14 soon. Could we get a new tag?

**Comment by MaskRay** [comment]
Fixed by https://github.com/MaskRay/ccls/releases/tag/0.20220729
