### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [MaskRay/ccls#895]
👋  it looks like the current release (`0.20220729`) is marked as `pre-release`, raising this issue to confirm if that is intended (as [we did before](https://github.com/MaskRay/ccls/issues/786) :) ).

A bit context is that we [only merge the stable latest release update PR](https://github.com/Homebrew/homebrew-core/pull/106939). Thanks!!

**Comment by chenrui333** [comment]
Bump this issue

**Comment by MaskRay** [comment]
"pre-release" state was removed long ago :)
