### ISSUE TITLE
vscode 插件

### ISSUE THREAD

**Issue by maosuyun2009** [MaskRay/ccls#9]
请问这个有vscode的插件吗？

**Comment by Riatre** [comment]
You may also need to `sed -i 's/$cquery/$ccls/g'` and repackage.

**Comment by scturtle** [comment]
[ccls.vsix.zip](https://github.com/MaskRay/ccls/files/2106056/ccls.vsix.zip)

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Visual-Studio-Code

But I have very little time to maintain it.
