### ISSUE TITLE
Compilation is not supported when using CUDA

### ISSUE THREAD

**Issue by sleepyeye** [MaskRay/ccls#90]
Hello,
Currently I'm working with cuda proejct and  **ONLY** completion is not working. Other features works well.

This is the output of **\*lsp-ccls stderr\*** looks like this
```
error: unknown argument: '-ptx'
errorerror: : unknown argument: '-ptx'unknown argument: '-ptx'

errorerror: : language not recognized: 'cu'language not recognized: 'cu'

error: language not recognized: 'cu'
warningwarning: : /workspace/myKernel.cu: 'linker' input unused
/workspace/myKernel2.cu: 'linker' input unusedwarning
: /workspace/myKernel3.cu: 'linker' input unusederror
error: : unable to handle compilation, expected exactly one compiler job in ''unable to handle compilation, expected exactly one compiler job in ''error
```

Because of my CUDA codes, I had to use two compilers at the same time. (NVCC and GCC)
For my cuda codes I convert them into PTX files using nvcc and later, my excutable which is compiled with GCC reads them in runtime.

I think because of this, `ccls` cannot generate completion candidates for `company`.
If this kind of situation is not supported properly with `ccls`, I would want to disable completion for CUDA codes.
In this case, is there any way to ignore cuda files?

**Comment by MaskRay** [comment]
I'm not familiar with cuda. Can you provide a reduced source file and your compiler command line? [Clang has CUDA support](https://llvm.org/docs/CompileCudaWithLLVM.html), but you may need to tweak your command line a bit to make it compile.

You may add `.cu` to https://github.com/maskray/ccls/blob/master/src/language.cc#L23 locally, do some experiment with `c-index-test -index-file a.cu -resource-dir=$DEFAULT_RESOURCE_DIRECTORY [options]` (read wiki how to get `DEFAULT_RESOURCE_DIRECTORY`)

**Comment by MaskRay** [comment]
Pushed a commit to use `types::lookupTypeForExtension`
https://github.com/llvm-mirror/clang/tree/master/lib/Driver/Types.cpp#L195

`.cu` `.cui`  are now recognized as `LanguageId::Cpp` and they can be indexed

Note, before this change, `.cu` can be indexed when you send a `textDocument/didOpen` request. After the change, they will be indexed in background if they have `compile_commands.json` entries.

https://github.com/maskray/ccls/blob/master/src/messages/textDocument_did.cc#L128
```cpp
    // Submit new index request if it is not a header file or there is no
    // pending index request.
    std::pair<LanguageId, bool> lang = lookupExtension(path);
    if ((lang.first != LanguageId::Unknown && !lang.second) ||
        !pipeline::pending_index_requests)
      pipeline::Index(path, args, IndexMode::Normal);
```

**Comment by Maswor** [comment]
I believed ccls has stopped working with cuda, despite the compile_commands.json successful generated by Cmake. Can you take another look, thank you!

**Comment by MaskRay** [comment]
@Maswor clang and nvcc have different sets of command line options. You'll have to tweak your nvcc command line a bit to be compatible with `clang a.cu`.

I have little experience with CUDA but I just checked a simple `a.cu` and it works.

**Comment by Maswor** [comment]
I delete the compile_commands.json and it work, but with it ccls throw -32600, not indexed error.

**Comment by MaskRay** [comment]
Commit 796c75794e2b524aec3bc7af2ce01b806c651b74 added support for the `%cu` directive for CUDA files. See wiki/Project-Setup for more details.
