### ISSUE TITLE
New tag for LLVM 16 support?

### ISSUE THREAD

**Issue by thesamesam** [MaskRay/ccls#937]
Would it be possible to have a new tag for LLVM 16 support? Thank you!

**Comment by mattst88** [comment]
@MaskRay: this would help Gentoo a lot.

**Comment by MaskRay** [comment]
Sorry:) Done: https://github.com/MaskRay/ccls/releases/tag/0.20230717

**Comment by mattst88** [comment]
Thanks very much!

**Comment by MaskRay** [comment]
> Do that again for LLVM-18?

Done! https://github.com/MaskRay/ccls/releases/tag/0.20240202
