### ISSUE TITLE
how to set ccls to search c++ standard headers automatically

### ISSUE THREAD

**Issue by FH0** [MaskRay/ccls#945]
`compile_commands.json` does not contains `-I/usr/include/x86_64-linux-gnu/c++/11` and `-I/usr/include/c++/11`. This error will be emitted `'shared_mutex' file not found`.

If I add `-I/usr/include/x86_64-linux-gnu/c++/11` and `-I/usr/include/c++/11` to `compile_commands.json`, there is no error.

It seems my `ccls` can't find c++ standard headers automatically. I don't know which settings I changed. `ccls` was able to work properly yesterday.

Headers and sources are no problem because I can use `cmake` to compile my project without an error.

### System information

* ccls version (`git describe --tags --long`): 8bc3959537adae26b470c8223845555ea26693cc
* clang version: `16.0.6 (++20230710042046+7cbf1a259152-1~exp1~20230710162136.105)`
* OS: `WSL2 Ubuntu-22.04`
* Editor: `VSCode`
* Language client (and version): `VSCode ccls v0.1.29`

**Comment by hikycool** [comment]
The same problem that I also met.
And Ccls only include standard header file but miss project header file while setting "-I/usr/include/c++/11" in ".ccls" file.

**Comment by FH0** [comment]
Finally solved by `apt purge libgcc-12-dev -y`

**Comment by hikycool** [comment]
My way is "apt install gcc-12 g++-12” on Ubuntu-22.04.
