### ISSUE TITLE
warning: multiple different client offset_encodings detected for buffer

### ISSUE THREAD

**Issue by 66RING** [MaskRay/ccls#951]
Maybe we need the ability to modify the offsetEncode in ccls as clangd did.like:

![image](https://github.com/MaskRay/ccls/assets/49358576/8a9c497b-bfb4-4fa3-88f1-7cd5a294a4ec)

which is hard code in ccls.

![image](https://github.com/MaskRay/ccls/assets/49358576/8a09d52d-ab6e-4b3c-8746-516cdc288149)

document from neovim lsp file:

![image](https://github.com/MaskRay/ccls/assets/49358576/bbd587a3-72bb-4072-8034-cb185f465fe4)

### Observed behavior

 I got "warning: multiple different client offset_encodings detected for buffer" when use the copilot plugin and ccls.

![image](https://github.com/MaskRay/ccls/assets/49358576/ee84584f-d017-4944-9ccc-bbc7ba0d0a83)

the offsetEncoding of ccls and copilot is conflict .

### Expected behavior

Decode as user parameter specify.

### Steps to reproduce

1. enable ccls as lsp
2. install copilot.vim plugin

**Comment by MaskRay** [comment]
UTF-16 is a perennial pain point from LSP :( I think copilot should probably support UTF-32.
