### ISSUE TITLE
is ccls supported clang 7?

### ISSUE THREAD

**Issue by losper** [MaskRay/ccls#97]
run ccls after build ccls with clang7,i got a error : 
>CommandLine Error: Option 'help-list' registered more than once!  
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by MaskRay** [comment]
It support clang 6, 7 and trunk.

Please give detailed description and read https://github.com/MaskRay/ccls/wiki/Getting-started first.

On Arch Linux, you need `-DUSE_SHARED_LLVM=on` to use `extra/clang`
