### ISSUE TITLE
Standalone running mode

### ISSUE THREAD

**Issue by sergei-dyshel** [MaskRay/ccls#98]
It would be nice if `ccls` could run in "standalone" mode without a client connected to it. The most meaningful action in this mode is to update index on the whole project or individual files. One can use this, for example, to build index on some (faster server) machine and then transfer it to another (workstation/laptop) machine which won't need to build index by itself.

`cquery` has an option `--check` which just parses given file and shows diagnostics, just to test whether `compile_commands.json` works. I propose to take this one step further and allow reading/writing database in this mode.

**Comment by MaskRay** [comment]
Close via commit e101e4782def4c406d26ab9d542bfeba224720c0

`ccls -index .` => index PWD without starting a language server. The cache will be written at `.ccls-cache` (`cacheDirectory` in `src/config.h`). The initialization option can be customized via `-init={...}` thought a bit clumsy.

**Comment by sergei-dyshel** [comment]
Thanks for quick followup! Will check it out ASAP.
