### ISSUE TITLE
Overloaded operator-> issue

### ISSUE THREAD

**Issue by mpajkowski** [MaskRay/ccls#99]
Hi @MaskRay,

It seems that ccls doesn't take operator-> into consideration - it can be easy spotted when using smart pointers. 

"|" indicates current cursor position.

```
#include <memory>

struct Dummy
{
  int a = 10;
};

auto main(int argc, char** argv) -> int
{
   auto pointer = std::make_unique<Dummy>();
   pointer->| 

   return 0;
}
```

Currently langserver provides completions for:
* underlying type (aka Dummy) - which is good
* std::unique_ptr<Dummy> class members - which is semantically incorrect.

Version:
Installed from AUR, ccls-git 1758.e101e478-1

Anyway, thanks for great tool, it improved my C++ development experience quite a lot :)

**Comment by MaskRay** [comment]
If you use clang >= 7, `FixIts` are available in completion items (`clang::CodeCompleteOptions::IncludeFixIts`). I pushed a commit to deprioritize completion items with such `AccessOpFixIt` (`.` to `->` and its converse)

I'm thinking if an initialization option is necessary.

**Comment by MaskRay** [comment]
Fixed by https://github.com/MaskRay/ccls/pull/210
